### Etymology Cross Check

In [1]:
import pandas as pd
import numpy as np
import glob
import re
import nltk
from nltk import word_tokenize

#### Etymologeek Result

In [2]:
lang_1 = "Turkish"  # English, Turkish, German, French, Spanish, Arabic, Russian, Portuguese, Dutch, Italian 
lang_2 = "Dutch"  # English, Turkish, German, French, Spanish, Arabic, Russian, Portuguese, Dutch, Italian

if lang_2 == "English":
    lang_3 = "English (eng)"
elif lang_2 == "Turkish":
    lang_3 = "Turkish (tur)"
elif lang_2 == "German":
    lang_3 = "German (deu)"
elif lang_2 == "French":
    lang_3 = "French (fra)"
elif lang_2 == "Spanish":
    lang_3 = "Spanish (spa)"
elif lang_2 == "Arabic":
    lang_3 = "Arabic (ara)"
elif lang_2 == "Russian":
    lang_3 = "Russian (rus)"
elif lang_2 == "Portuguese":
    lang_3 = "Portuguese (por)"
elif lang_2 == "Dutch":
    lang_3 = "Dutch (nld)"
elif lang_2 == "Italian":
    lang_3 = "Italian (ita)"
else:
    pass
#lang_3 = "English (eng)"  # English (eng), Turkish (tur), German (deu), French (fra), Spanish (spa), Arabic (ara), Russian (rus), 
                          # Portuguese (por), Dutch (nld), Italian (ita)
print(f"{lang_1}\n{lang_2}\n{lang_3}")

Turkish
Dutch
Dutch (nld)

In [3]:
#Path(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/{lang_1.capitalize()}").mkdir(parents=True, exist_ok=True)

In [4]:
lang_1_file = glob.glob(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/*/{lang_1.capitalize()}_And_*_Etymologeek_Result1.xlsx")
lang_1_file

['/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Turkish/Turkish_And_Dutch (nld)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Turkish/Turkish_And_Arabic (ara)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Turkish/Turkish_And_English (eng)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Turkish/Turkish_And_French (fra)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Turkish/Turkish_And_Italian (ita)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Turkish/Turkish_And_Portuguese (por)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Turkish/Turkish_And_Spanish (spa)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Turkish/Turkish_And_German (deu)_Etymologeek_Result1.xlsx']

In [5]:
df_lang_1 = pd.DataFrame()
for i in lang_1_file:
    df_var = pd.read_excel(f"{i}")
    df_lang_1 = pd.concat([df_lang_1,df_var], axis=0)
    df_lang_1.reset_index(drop=True, inplace=True)
df_lang_1

,search_word,dict_entry_main,language_main,definition_main,dict_entry,language,definition
0,şans,şans,Turkish,(Noun) Fortune. Luck.Fortune. Luck.,dice,Dutch (nld),NaN
1,loca,loca,Turkish,(Noun) (masonic) lodge. Box (in theaters).(mas...,laubja,Dutch (nld),NaN
2,mı,mıknatıs,Turkish,(Noun) Magnet.Magnet.,مِغْنَاطِيس,Arabic (ara),NaN
3,mı,mısdak,Turkish,(Noun) (obsolete) criterion.(obsolete) criterion.,مِصْدَاق,Arabic (ara),NaN
4,şey,şey,Turkish,(Noun Interjection) (slang) genital organ. Thi...,شَيْئاً,Arabic (ara),NaN
...,...,...,...,...,...,...,...
732,vermut,vermut,Turkish,(Noun),wermut,German (deu),"Vermouth is an aromatized fortified wine, flav..."
733,panzer,panzer,Turkish,(Noun),panzer,German (deu),A tank is an armoured fighting vehicle intende...
734,tonymayster,tonymayster,Turkish,(Noun),tonmeister,German (deu),Tonmeister
735,filinta,filinta,Turkish,(Noun),flinte,German (deu),Flinte
736,kuvars,kuvars,Turkish,(Noun),quarz,German (deu),"Quartz is a hard, crystalline mineral composed..."

In [6]:
lang_2_file = glob.glob(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/*/{lang_2.capitalize()}_And_*_Etymologeek_Result1.xlsx")
lang_2_file

['/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Dutch/Dutch_And_Arabic (ara)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Dutch/Dutch_And_English (eng)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Dutch/Dutch_And_French (fra)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Dutch/Dutch_And_German (deu)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Dutch/Dutch_And_Italian (ita)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Dutch/Dutch_And_Portuguese (por)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Dutch/Dutch_And_Russian (rus)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Dutch/Dutch_And_Spanish (spa)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Dutch/Dutch_And_Turkish (tur)_Etymologeek_Result1.xlsx']

In [7]:
df_lang_2 = pd.DataFrame()
for i in lang_2_file:
    df_var2 = pd.read_excel(f"{i}")
    df_lang_2 = pd.concat([df_lang_2,df_var2], axis=0)
    df_lang_2.reset_index(drop=True, inplace=True)
df_lang_2

,search_word,dict_entry_main,language_main,definition_main,dict_entry,language,definition
0,emir,emir,Dutch,(Noun) Emir (Islamic prince or leader).Emir (I...,أَمِير الْبَحْر,Arabic (ara),NaN
1,fakir,fakir,Dutch,"(Noun) (Islam, Hinduism) fakir.(Islam, Hinduis...",فَقِير,Arabic (ara),NaN
2,koffie,koffie,Dutch,(Noun) Coffee.Coffee.,قهوة,Arabic (ara),"(colloquial) coffee shop, café (colloquial use..."
3,genie,genie,Dutch,(Noun Noun) Genius Military engineers (unit).G...,جِنّ,Arabic (ara),NaN
4,suiker,suiker,Dutch,(Noun) Sugar.Sugar.,سُكَّر,Arabic (ara),NaN
...,...,...,...,...,...,...,...
897,prise,prise,Dutch,(Noun) (Belgium) electrical plug.(Belgium) ele...,prehensus,Spanish (spa),NaN
898,pape,papegaai,Dutch,(Noun) Parrot.Parrot.,papagayo,Spanish (spa),"Any wrasse, (Labridae). Elephant ear (Caladium..."
899,beg,beg,Dutch,(Noun) (historical) .(historical) .,beg,Turkish (tur),NaN
900,sultan,sultan,Dutch,"(Noun) A certain pastry. Sultan, a Muslim rule...",sultan,Turkish (tur),"A breed of chicken originating in Turkey, kept..."
901,bei,bei,Dutch,"(Noun) (historical) bey, beg (historical Turki...",bey,Turkish (tur),"Gentleman, mister. Husband. Lord, master."

In [8]:
set_lang_11 = set(df_lang_1["dict_entry"])

In [9]:
set_lang_12 = set(df_lang_2["dict_entry"])

In [10]:
df_cross = pd.DataFrame(set_lang_11.intersection(set_lang_12), columns=["dict_entry"])
df_cross

   dict_entry
0        rail
1      condom
2       poser
3      cancer
4     whiskey
..        ...
77     vision
78  garçonnet
79  chocolate
80      panda
81     madame

[82 rows x 1 columns]

In [11]:
df_lang_1_cross = pd.merge(df_cross,df_lang_1,how="inner", on="dict_entry")
df_lang_1_cross.drop_duplicates(inplace=True)
df_lang_1_cross = df_lang_1_cross[["language_main","dict_entry_main","dict_entry"]]
df_lang_1_cross.rename(columns={"language_main":"lang_master","dict_entry_main":"term_master"}, inplace=True)
df_lang_1_cross

   lang_master term_master dict_entry
0      Turkish         ray       rail
1      Turkish      kondom     condom
2      Turkish        depo      poser
3      Turkish      kanser     cancer
4      Turkish       viski    whiskey
..         ...         ...        ...
83     Turkish  televizyon     vision
84     Turkish      garson  garçonnet
85     Turkish    çikolata  chocolate
86     Turkish       panda      panda
87     Turkish       madam     madame

[88 rows x 3 columns]

In [12]:
df_lang_2_cross = pd.merge(df_cross,df_lang_2,how="inner", on="dict_entry")
df_lang_2_cross.drop_duplicates(inplace=True)
df_lang_2_cross = df_lang_2_cross[["language_main","dict_entry_main","dict_entry"]]
df_lang_2_cross.rename(columns={"language_main":"lang_sleeve","dict_entry_main":"term_sleeve"}, inplace=True)
df_lang_2_cross

   lang_sleeve term_sleeve dict_entry
0        Dutch        rail       rail
1        Dutch     condoom     condom
2        Dutch        pose      poser
3        Dutch       depot      poser
4        Dutch      kanker     cancer
..         ...         ...        ...
92       Dutch   televisie     vision
93       Dutch      garçon  garçonnet
94       Dutch   chocolade  chocolate
95       Dutch       panda      panda
96       Dutch       madam     madame

[97 rows x 3 columns]

In [13]:
df_lang_1_lang_2_cross = pd.merge(df_lang_1_cross,df_lang_2_cross, how="inner", on="dict_entry")
df_lang_1_lang_2_cross.drop_duplicates(inplace=True)
df_lang_1_lang_2_cross = df_lang_1_lang_2_cross[["lang_master","term_master","lang_sleeve","term_sleeve"]]
df_lang_1_lang_2_cross

    lang_master term_master lang_sleeve term_sleeve
0       Turkish         ray       Dutch        rail
1       Turkish      kondom       Dutch     condoom
2       Turkish        depo       Dutch        pose
3       Turkish        depo       Dutch       depot
4       Turkish      kanser       Dutch      kanker
..          ...         ...         ...         ...
102     Turkish  televizyon       Dutch   televisie
103     Turkish      garson       Dutch      garçon
104     Turkish    çikolata       Dutch   chocolade
105     Turkish       panda       Dutch       panda
106     Turkish       madam       Dutch       madam

[97 rows x 4 columns]

In [14]:
lang_3_file = glob.glob(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/*/*_And_{lang_3.capitalize()}_Etymologeek_Result1.xlsx")
lang_3_file

['/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Turkish/Turkish_And_Dutch (nld)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/English/English_And_Dutch (nld)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/German/German_And_Dutch (nld)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/French/French_And_Dutch (nld)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Spanish/Spanish_And_Dutch (nld)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Arabic/Arabic_And_Dutch (nld)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Russian/Russian_And_Dutch (nld)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Portuguese/Portuguese_And_Dutch (nld)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Italian/Italian_And_Dutch (nld)_Etymologeek_Result1.xlsx']

In [15]:
df_lang_3 = pd.DataFrame()
for i in lang_3_file:
    df_var3 = pd.read_excel(f"{i}")
    df_lang_3 = pd.concat([df_lang_3,df_var3], axis=0)
    df_lang_3.reset_index(drop=True, inplace=True)
df_lang_3

,search_word,dict_entry_main,language_main,definition_main,dict_entry,language,definition
0,şans,şans,Turkish,(Noun) Fortune. Luck.Fortune. Luck.,dice,Dutch (nld),NaN
1,loca,loca,Turkish,(Noun) (masonic) lodge. Box (in theaters).(mas...,laubja,Dutch (nld),NaN
2,porno,pornoaction,English,"(Noun) (Indonesia, legal) Any actions, behavio...",spiegelstraf,Dutch (nld),NaN
3,kast,kast,English,(Noun) A type of traditional cupboard produced...,kast,Dutch (nld),"Cupboard, closet."
4,toen,toenadering,English,(Noun) (South Africa) A rapprochement.(South A...,toenadering,Dutch (nld),Approach; the process of coming closer.
...,...,...,...,...,...,...,...
272,capra,capra,Italian,(Noun) Goat (mammal). Nanny goat. Trestle.Goat...,bok,Dutch (nld),(gymnastics) vaulting horse. (pejorative) chur...
273,capra,caprareccia,Italian,(Noun) A shed used to keep goats indoors durin...,bok,Dutch (nld),(gymnastics) vaulting horse. (pejorative) chur...
274,alloggi,alloggiare,Italian,(Verb) (intransitive) To stay or lodge (at). (...,laubja,Dutch (nld),NaN
275,sigillo,sigillo,Italian,(Noun Verb) Seal (that seals something).Seal (...,sein,Dutch (nld),Signal.
276,cogliere,cogliere,Italian,"(Verb) (transitive) to grasp, seize, take. (tr...",legere,Dutch (nld),NaN

In [16]:
set_lang_21 = set(df_lang_1["dict_entry_main"])

In [17]:
set_lang_23 = set(df_lang_3["dict_entry_main"])

In [18]:
df_cross_2 = pd.DataFrame(set_lang_21.intersection(set_lang_23), columns=["dict_entry_main"])
df_cross_2

  dict_entry_main
0            şans
1            loca

In [19]:
df_lang_1_lang_3_cross = pd.merge(df_cross_2,df_lang_3,how="inner", on="dict_entry_main")
df_lang_1_lang_3_cross.drop_duplicates(inplace=True)
df_lang_1_lang_3_cross = df_lang_1_lang_3_cross[["language_main","dict_entry_main","language","dict_entry"]]
df_lang_1_lang_3_cross.rename(columns={"language_main":"lang_master","dict_entry_main":"term_master","language":"lang_sleeve","dict_entry":"term_sleeve"}, inplace=True)
df_lang_1_lang_3_cross

  lang_master term_master  lang_sleeve term_sleeve
0     Turkish        şans  Dutch (nld)        dice
1     Turkish        loca  Dutch (nld)      laubja

In [20]:
df_lang_1_lang_2_lang_3 = pd.concat([df_lang_1_lang_2_cross,df_lang_1_lang_3_cross], axis=0)
df_lang_1_lang_2_lang_3.reset_index(drop=True, inplace=True)
df_lang_1_lang_2_lang_3["term_master"] = df_lang_1_lang_2_lang_3["term_master"].apply(lambda x: x.lower())
df_lang_1_lang_2_lang_3["term_sleeve"] = df_lang_1_lang_2_lang_3["term_sleeve"].apply(lambda x: x.lower())
df_lang_1_lang_2_lang_3

   lang_master term_master  lang_sleeve term_sleeve
0      Turkish         ray        Dutch        rail
1      Turkish      kondom        Dutch     condoom
2      Turkish        depo        Dutch        pose
3      Turkish        depo        Dutch       depot
4      Turkish      kanser        Dutch      kanker
..         ...         ...          ...         ...
94     Turkish    çikolata        Dutch   chocolade
95     Turkish       panda        Dutch       panda
96     Turkish       madam        Dutch       madam
97     Turkish        şans  Dutch (nld)        dice
98     Turkish        loca  Dutch (nld)      laubja

[99 rows x 4 columns]

In [21]:
#df_word = pd.read_excel(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/{lang_2.capitalize()}/Result/Word/Merge/Word_Merge2.xlsx")
#df_word = df_word.head(40000)
#df_word = df_word.loc[:,["word"]]
#df_word.rename(columns={"word":"term_sleeve"}, inplace=True)
#df_word

In [22]:
#df_lang_1_lang_2_lang_3 = pd.merge(df_lang_1_lang_2_lang_3,df_word, how="inner", on="term_sleeve")
#df_lang_1_lang_2_lang_3

In [23]:
df_lang_1_lang_2_lang_3.to_excel(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/{lang_1.capitalize()}/{lang_1.capitalize()} {lang_2.capitalize()}/{lang_1.capitalize()}_And_{lang_3.capitalize()}_Etymologeek_Result5.xlsx", index=False)