### Etymology TVS File

In [1]:
import pandas as pd
import numpy as np
import glob
import re
import nltk
from nltk import word_tokenize
from pathlib import Path
import shutil

#### Read TVS And Convert CSV

In [2]:
#df_tvs = pd.read_csv("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Data/All/etymwn.tsv", sep="\t")
#df_tvs.rename(columns={"aaq: Pawanobskewi":"column_1","rel:etymological_origin_of":"column_2","eng: Penobscot":"column_3"}, inplace=True)
#df_tvs

In [3]:
#def low_func(x):
#    try:
#        var_out = x.lower()
#    except:
#        var_out = x
#    return var_out

In [4]:
#def strip_func(x):
#    try:
#        var_out = x.strip()
#    except:
#        var_out = x
#    return var_out

In [5]:
#df_col_1 = df_tvs["column_1"].str.split(":", n=-1, expand=True)
#df_col_1 = df_col_1.iloc[:,[0,1]]
#df_col_1.rename(columns={0:"lang",1:"term"}, inplace=True)
#df_col_2 = df_tvs["column_2"].str.split(":", n=-1, expand=True)
#df_col_2 = df_col_2.iloc[:,[1]]
#df_col_2.rename(columns={1:"reltype"}, inplace=True)
#df_col_3 = df_tvs["column_3"].str.split(":", n=-1, expand=True)
#df_col_3 = df_col_3.iloc[:,[0,1]]
#df_col_3.rename(columns={0:"related_lang",1:"related_term"}, inplace=True)

In [6]:
#df_tvs_expand =  pd.concat([df_col_1,df_col_2,df_col_3], axis=1)
#df_tvs_expand

In [7]:
#df_tvs_expand["lang"] = df_tvs_expand["lang"].apply(lambda x: low_func(x))
#df_tvs_expand["lang"] = df_tvs_expand["lang"].apply(lambda x: strip_func(x))
#df_tvs_expand["term"] = df_tvs_expand["term"].apply(lambda x: low_func(x))
#df_tvs_expand["term"] = df_tvs_expand["term"].apply(lambda x: strip_func(x))
#df_tvs_expand["reltype"] = df_tvs_expand["reltype"].apply(lambda x: low_func(x))
#df_tvs_expand["reltype"] = df_tvs_expand["reltype"].apply(lambda x: strip_func(x))
#df_tvs_expand["related_lang"] = df_tvs_expand["related_lang"].apply(lambda x: low_func(x))
#df_tvs_expand["related_lang"] = df_tvs_expand["related_lang"].apply(lambda x: strip_func(x))
#df_tvs_expand["related_term"] = df_tvs_expand["related_term"].apply(lambda x: low_func(x))
#df_tvs_expand["related_term"] = df_tvs_expand["related_term"].apply(lambda x: strip_func(x))

In [8]:
#df_tvs_expand.to_csv("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Data/All/etymwn.csv", index=False)

#### Read CSV File

##### Part 1

In [9]:
df_etymology = pd.read_csv("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Data/All/etymwn.csv")
df_etymology

        lang      term                 reltype related_lang   related_term
0        aaq    senabe  etymological_origin_of          eng         sannup
1        abe  waniigan  etymological_origin_of          eng         wangan
2        abe  waniigan  etymological_origin_of          eng       wannigan
3        abs      beta  etymological_origin_of          zsm           beta
4        adt      yuru  etymological_origin_of          eng           euro
...      ...       ...                     ...          ...            ...
6031425  zul       ya-  etymological_origin_of          zul  inhlamvu yeso
6031426  zul       ya-  etymological_origin_of          zul  inja yasendle
6031427  zul       zi-         is_derived_from          zul           izi-
6031428  zul      zim-         is_derived_from          zul          izim-
6031429  zul      zin-         is_derived_from          zul          izin-

[6031430 rows x 5 columns]

In [10]:
lang_1 = "tur"  # tur, eng, fra, deu, por, spa, ita, nld, ara, rus
lang_2 = "deu"  # tur, eng, fra, deu, por, spa, ita, nld, ara, rus

if lang_1 == "tur":
    lang_3 = "Turkish"
elif lang_1 == "eng":
    lang_3 = "English"
elif lang_1 == "fra":
    lang_3 = "French"
elif lang_1 == "deu":
    lang_3 = "German"
elif lang_1 == "por":
    lang_3 = "Portuguese"
elif lang_1 == "spa":
    lang_3 = "Spanish"
elif lang_1 == "ita":
    lang_3 = "Italian"
elif lang_1 == "nld":
    lang_3 = "Dutch"
elif lang_1 == "ara":
    lang_3 = "Arabic"
elif lang_1 == "rus":
    lang_3 = "Russian"
else:
    pass

if lang_2 == "tur":
    lang_4 = "Turkish"
elif lang_2 == "eng":
    lang_4 = "English"
elif lang_2 == "fra":
    lang_4 = "French"
elif lang_2 == "deu":
    lang_4 = "German"
elif lang_2 == "por":
    lang_4 = "Portuguese"
elif lang_2 == "spa":
    lang_4 = "Spanish"
elif lang_2 == "ita":
    lang_4 = "Italian"
elif lang_2 == "nld":
    lang_4 = "Dutch"
elif lang_2 == "ara":
    lang_4 = "Arabic"
elif lang_2 == "rus":
    lang_4 = "Russian"
else:
    pass

print(f"{lang_1}\n{lang_2}\n{lang_3}\n{lang_4}")

tur
deu
Turkish
German

In [11]:
#Path(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/{lang_3.capitalize()}").mkdir(parents=True, exist_ok=True)

In [12]:
df_lang1 = df_etymology[df_etymology.lang == f"{lang_1.lower()}"]
df_lang1.reset_index(drop=True, inplace=True)
df_lang1 = df_lang1[~(df_lang1["related_lang"] == f"{lang_1.lower()}")]
df_lang1 = df_lang1[~(df_lang1["related_lang"] == f"{lang_2.lower()}")]
df_lang1

,lang,term,reltype,related_lang,related_term
118,tur,-cı,etymological_origin_of,lad,-djí
457,tur,-luk,etymological_origin_of,hbs,-luk
996,tur,-çi,etymological_origin_of,hye,-չի
1053,tur,afyonkarahisar,etymological_origin_of,eng,afyonkarahisar
1066,tur,allah,etymological_origin_of,rus,аллах
...,...,...,...,...,...
22642,tur,نجار,etymological_origin_of,hye,նաջարյան
22643,tur,نجار,etymological_origin_of,hye,նաջար
22644,tur,‏پاشا‎,etymological_origin_of,hun,pasa
22645,tur,ﮔﺎﻭﺭ,etymological_origin_of,hun,gyaur
22646,tur,ﮔﺎﻭﺭ,etymology,fas,گبر

In [13]:
df_lang2 = df_etymology[df_etymology.lang == f"{lang_2.lower()}"]
df_lang2.reset_index(drop=True, inplace=True)
df_lang2 = df_lang2[~(df_lang2["related_lang"] == f"{lang_1.lower()}")]
df_lang2 = df_lang2[~(df_lang2["related_lang"] == f"{lang_2.lower()}")]
df_lang2

,lang,term,reltype,related_lang,related_term
1,deu,''[[imperial]] [[parliament]]'',etymological_origin_of,eng,reichstag
2,deu,''[[mixed]] [[metal]]'',etymological_origin_of,eng,mischmetal
3,deu,''[[world]] [[sight]] or [[view]]'',etymological_origin_of,eng,weltansicht
21,deu,-al,etymological_origin_of,fra,instrumental
22,deu,-al,etymological_origin_of,lat,fundamentalis
...,...,...,...,...,...
177514,deu,über,etymological_origin_of,eng,uber-
177530,deu,über,etymology,goh,ubiri
177731,deu,überhaupt,etymological_origin_of,nob,overhodet
177897,deu,übermorgen,etymological_origin_of,dan,overmorgen
178015,deu,überraschen,etymological_origin_of,dan,overraske

In [14]:
df_lang1_lang2 = pd.merge(df_lang1,df_lang2,how="inner",on=["related_lang","related_term"])
df_lang1_lang2.drop_duplicates(inplace=True)
df_lang1_lang2.reset_index(drop=True, inplace=True)
df_lang1_lang2

,lang_x,term_x,reltype_x,related_lang,related_term,lang_y,term_y,reltype_y
0,tur,aristo,etymology,grc,ἀριστοτέλης,deu,aristoteles,etymology
1,tur,pandora,etymology,grc,πανδώρα,deu,pandora,etymology
2,tur,adres,etymology,fra,adresse,deu,adresse,etymology
3,tur,akor,etymology,fra,accord,deu,akkord,etymology
4,tur,ambi-,etymology,lat,ambi-,deu,ambi-,etymology
...,...,...,...,...,...,...,...,...
78,tur,şah,etymological_origin_of,ron,șah,deu,schach,etymological_origin_of
79,tur,şampanya,etymology,fra,champagne,deu,champagner,etymology
80,tur,şef,etymology,fra,chef,deu,chef,etymology
81,tur,şerif,etymology,eng,sheriff,deu,sheriff,etymology
82,tur,اوطه‌لق,etymological_origin_of,fra,odalisque,deu,odaliske,etymology

In [15]:
df_lang1_lang2_result1 = df_lang1_lang2.loc[:,["term_x","term_y"]]
df_lang1_lang2_result1.rename(columns={"term_x":"dict_entry_main","term_y":f"{lang_4.lower()}_word"}, inplace=True)
df_lang1_lang2_result1.reset_index(drop=True, inplace=True)
df_lang1_lang2_result1

   dict_entry_main  german_word
0           aristo  aristoteles
1          pandora      pandora
2            adres      adresse
3             akor       akkord
4            ambi-        ambi-
..             ...          ...
78             şah       schach
79        şampanya   champagner
80             şef         chef
81           şerif      sheriff
82         اوطه‌لق     odaliske

[83 rows x 2 columns]

##### Part 2

In [16]:
df_lang1_lang2_result2 = df_etymology[(df_etymology["lang"] == f"{lang_1.lower()}") & (df_etymology["related_lang"] == f"{lang_2.lower()}")]
df_lang1_lang2_result2

        lang       term                 reltype related_lang related_term
5902684  tur    element               etymology          deu      element
5904852  tur  hamburger               etymology          deu    hamburger
5905076  tur  haymatlos               etymology          deu    heimatlos
5905141  tur      helde               etymology          deu       heiden
5908012  tur      kuruş               etymology          deu     groschen
5908013  tur      kuruş               etymology          deu     groschen
5908052  tur     kuvars               etymology          deu        quarz
5913939  tur    tülbent  etymological_origin_of          deu       turban
5914527  tur    volfram               etymology          deu      wolfram
5915751  tur      çakal  etymological_origin_of          deu      schakal
5917351  tur     şablon               etymology          deu    schablone

In [17]:
df_lang1_lang2_result2 = df_lang1_lang2_result2.loc[:,["term","related_term"]]
df_lang1_lang2_result2.rename(columns={"term":"dict_entry_main","related_term":f"{lang_4.lower()}_word"}, inplace=True)
df_lang1_lang2_result2.reset_index(drop=True, inplace=True)
df_lang1_lang2_result2

   dict_entry_main german_word
0          element     element
1        hamburger   hamburger
2        haymatlos   heimatlos
3            helde      heiden
4            kuruş    groschen
5            kuruş    groschen
6           kuvars       quarz
7          tülbent      turban
8          volfram     wolfram
9            çakal     schakal
10          şablon   schablone

##### Concat Part 1 And Part 2

In [18]:
#df_part1_part2_concat = pd.concat([df_lang1_lang2_word_check,df_lang1_lang2_word_check2], axis=0)
df_part1_part2_concat = pd.concat([df_lang1_lang2_result1,df_lang1_lang2_result2], axis=0)
df_part1_part2_concat.drop_duplicates(inplace=True)
df_part1_part2_concat.reset_index(drop=True, inplace=True)
df_part1_part2_concat

   dict_entry_main  german_word
0           aristo  aristoteles
1          pandora      pandora
2            adres      adresse
3             akor       akkord
4            ambi-        ambi-
..             ...          ...
88          kuvars        quarz
89         tülbent       turban
90         volfram      wolfram
91           çakal      schakal
92          şablon    schablone

[93 rows x 2 columns]

In [19]:
df_part1_part2_concat.to_excel(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/{lang_3.capitalize()}/{lang_3.capitalize()} {lang_4.capitalize()}/{lang_3.capitalize()}_And_{lang_4.capitalize()}_Etymologeek_Concat_Result2.xlsx", index=False)