### Quaran N Gram

In [1]:
#!pip install lang-trans

In [1]:
import pandas as pd
import numpy as np
import re
from camel_tools.utils.charmap import CharMapper
from lang_trans.arabic import buckwalter
import nltk
from nltk import word_tokenize
from nltk import ngrams

##### NLTK N Gram From Text

In [2]:
df_word = pd.read_excel("Arabic_Buckwalter_Word_And_Simple_Morphology.xlsx")

In [3]:
df_word

,num_1,num_2,num_3,arabic_simple,buckwalter_simple,arabic,buckwalter
0,1,1,1,بسم,bsm,بِسْمِ,bisomi
1,1,1,2,ٱلله,{llh,ٱللَّهِ,{ll~ahi
2,1,1,3,ٱلرحمن,{lrHmn,ٱلرَّحْمَٰنِ,{lr~aHoma`ni
3,1,1,4,ٱلرحيم,{lrHym,ٱلرَّحِيمِ,{lr~aHiymi
4,1,2,1,ٱلحمد,{lHmd,ٱلْحَمْدُ,{loHamodu
...,...,...,...,...,...,...,...
77424,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri
77425,114,5,5,ٱلناس,{lnAs,ٱلنَّاسِ,{ln~aAsi
77426,114,6,1,من,mn,مِنَ,mina
77427,114,6,2,ٱلجنة,{ljnp,ٱلْجِنَّةِ,{lojin~api
77428,114,6,3,وٱلناس,w{lnAs,وَٱلنَّاسِ,wa{ln~aAsi

In [4]:
arabic_list =  df_word.iloc[:,5].to_list() # arabic extended

In [5]:
arabic_concat = " ".join(arabic_list) # arabic text
#arabic_concat

In [2]:
# N gram from text data and DataFrame output
#ngram_type = "twogram"
def text_ngram(text, ngram_num, ngram_type): # text_ngram(arabic_concat, 2, "twogram") ...
    n_gram = ngrams(text.split(), ngram_num)
    n_gram_list = []
    for i in n_gram:
        n_gram_group = " ".join(i)
        n_gram_list.append(n_gram_group)
    df_ngram = pd.DataFrame(n_gram_list, columns=[f"{ngram_type.lower()}"])
    df_ngram = pd.DataFrame(df_ngram.iloc[:,0].value_counts(ascending=False))
    df_ngram.reset_index(inplace=True)
    df_ngram.rename(columns={"index":f"{ngram_type.lower()}", f"{ngram_type.lower()}":"frequency"}, inplace=True)
    return df_ngram

In [7]:
n = 2
n_gram = ngrams(arabic_concat.split(), n)
n_gram_list = []
for i in n_gram:
    n_gram_group = " ".join(i)
    n_gram_list.append(n_gram_group)

In [8]:
df_extend_ngram = pd.DataFrame(n_gram_list, columns=["twogram"])
df_extend_ngram

                       twogram
0               بِسْمِ ٱللَّهِ
1         ٱللَّهِ ٱلرَّحْمَٰنِ
2      ٱلرَّحْمَٰنِ ٱلرَّحِيمِ
3         ٱلرَّحِيمِ ٱلْحَمْدُ
4            ٱلْحَمْدُ لِلَّهِ
...                        ...
77424              فِى صُدُورِ
77425         صُدُورِ ٱلنَّاسِ
77426            ٱلنَّاسِ مِنَ
77427          مِنَ ٱلْجِنَّةِ
77428    ٱلْجِنَّةِ وَٱلنَّاسِ

[77429 rows x 1 columns]

In [9]:
df_extend_ngram = pd.DataFrame(df_extend_ngram.iloc[:,0].value_counts(ascending=False))
df_extend_ngram.reset_index(inplace=True)
df_extend_ngram.rename(columns={"index":"twogram", "twogram":"frequency"}, inplace=True)
df_extend_ngram

                         twogram  frequency
0                  إِنَّ ٱللَّهَ        205
1                  فِى ٱلْأَرْضِ        176
2           ٱلَّذِينَ ءَامَنُوا۟        148
3            ٱلَّذِينَ كَفَرُوا۟        115
4      ٱلسَّمَٰوَٰتِ وَٱلْأَرْضِ         95
...                          ...        ...
52610            ٱلرَّأْىِ وَمَا          1
52611              نَرَىٰ لَكُمْ          1
52612                مِن فَضْلٍۭ          1
52613               فَضْلٍۭ بَلْ          1
52614              ٱلنَّاسِ مِنَ          1

[52615 rows x 2 columns]

In [11]:
# 2 way from def func
#df_extend_ngram = text_ngram(arabic_concat, 2, "twogram")
#df_extend_ngram

In [12]:
#df_extend_ngram.to_excel("Arabic_Twogram_Frequency_Morphology.xlsx", sheet_name="Arabic_Twogram", index=False)

In [10]:
arabic_simple_word_list =  df_word.iloc[:,3].to_list() # arabic_simple

In [11]:
arabic_simple_word_concat = " ".join(arabic_simple_word_list)
#arabic_simple_word_concat

In [12]:
df_simple_ngram = text_ngram(arabic_simple_word_concat, 2, "twogram")
df_simple_ngram

             twogram  frequency
0            إن ٱلله        205
1           فى ٱلأرض        176
2       ٱلذين ءامنوا        148
3             ي أيها        142
4      ٱلسموت وٱلأرض        133
...              ...        ...
49820   ٱلأمر وٱستوت          1
49821     وٱستوت على          1
49822     على ٱلجودى          1
49823    ٱلجودى وقيل          1
49824     صدور ٱلناس          1

[49825 rows x 2 columns]

In [16]:
#df_simple_ngram.to_excel("Arabic_Simple_Twogram_Frequency_Morphology.xlsx", sheet_name="Arabic_Simple_Twogram", index=False)

##### NLTK N Gram From DataFrame

In [17]:
#df_word = pd.read_excel("Arabic_Buckwalter_Word_And_Simple_Morphology.xlsx")

In [13]:
df_buckwalter = df_word.iloc[:,[0,1,2,6]]
df_buckwalter

       num_1  num_2  num_3    buckwalter
0          1      1      1        bisomi
1          1      1      2       {ll~ahi
2          1      1      3  {lr~aHoma`ni
3          1      1      4    {lr~aHiymi
4          1      2      1     {loHamodu
...      ...    ...    ...           ...
77424    114      5      4       Suduwri
77425    114      5      5      {ln~aAsi
77426    114      6      1          mina
77427    114      6      2    {lojin~api
77428    114      6      3    wa{ln~aAsi

[77429 rows x 4 columns]

In [14]:
df_buckwalter_concat = df_buckwalter.groupby(["num_1","num_2"])["buckwalter"].apply(" ".join).reset_index()
df_buckwalter_concat

      num_1  num_2                                buckwalter
0         1      1    bisomi {ll~ahi {lr~aHoma`ni {lr~aHiymi
1         1      2     {loHamodu lil~ahi rab~i {loEa`lamiyna
2         1      3                   {lr~aHoma`ni {lr~aHiymi
3         1      4                   ma`liki yawomi {ld~iyni
4         1      5  <iy~aAka naEobudu wa<iy~aAka nasotaEiynu
...     ...    ...                                       ...
6231    114      2                           maliki {ln~aAsi
6232    114      3                          <ila`hi {ln~aAsi
6233    114      4        min $ar~i {lowasowaAsi {loxan~aAsi
6234    114      5   {l~a*iY yuwasowisu fiY Suduwri {ln~aAsi
6235    114      6                mina {lojin~api wa{ln~aAsi

[6236 rows x 3 columns]

In [2]:
# buckwalter text clean for simple before transString
def clean_ex(text):
    buckwalter_out = re.sub(r'''([PJVG\.:;,!\+\^\]\[@#FNKauio`~"%-])''', "", text) # difference from clean
    return buckwalter_out

In [3]:
# Arabic Encoding Extended
# -*- coding: utf-8 -*-

# Arabic Transliteration based on Buckwalter
# dictionary source is buckwalter2unicode.py http://www.redhat.com/archives/fedora-extras-commits/2007-June/msg03617.html 

buck2uni = {"'": u"\u0621", # hamza-on-the-line
            "|": u"\u0622", # madda
            ">": u"\u0623", # hamza-on-'alif
            "&": u"\u0624", # hamza-on-waaw
            "<": u"\u0625", # hamza-under-'alif
            "}": u"\u0626", # hamza-on-yaa'
            "A": u"\u0627", # bare 'alif
            "b": u"\u0628", # baa'
            "p": u"\u0629", # taa' marbuuTa
            "t": u"\u062A", # taa'
            "v": u"\u062B", # thaa'
            "j": u"\u062C", # jiim
            "H": u"\u062D", # Haa'
            "x": u"\u062E", # khaa'
            "d": u"\u062F", # daal
            "*": u"\u0630", # dhaal
            "r": u"\u0631", # raa'
            "z": u"\u0632", # zaay
            "s": u"\u0633", # siin
            "$": u"\u0634", # shiin
            "S": u"\u0635", # Saad
            "D": u"\u0636", # Daad
            "T": u"\u0637", # Taa'
            "Z": u"\u0638", # Zaa' (DHaa')
            "E": u"\u0639", # cayn
            "g": u"\u063A", # ghayn
            "_": u"\u0640", # taTwiil
            "f": u"\u0641", # faa'
            "q": u"\u0642", # qaaf
            "k": u"\u0643", # kaaf
            "l": u"\u0644", # laam
            "m": u"\u0645", # miim
            "n": u"\u0646", # nuun
            "h": u"\u0647", # haa'
            "w": u"\u0648", # waaw
            "Y": u"\u0649", # 'alif maqSuura
            "y": u"\u064A", # yaa'
            "F": u"\u064B", # fatHatayn
            "N": u"\u064C", # Dammatayn
            "K": u"\u064D", # kasratayn
            "a": u"\u064E", # fatHa
            "u": u"\u064F", # Damma
            "i": u"\u0650", # kasra
            "~": u"\u0651", # shaddah
            "o": u"\u0652", # sukuun
            "^": u"\u0653", # maddah
            "#": u"\u0654", # hamzaabove            
            "`": u"\u0670", # dagger 'alif
            "{": u"\u0671", # waSla
            "P": u"\u067E", # arabicletterpeh
            "J": u"\u0686", 
            "V": u"\u06A4", # arabicletterveh
            "G": u"\u06AF", # arabiclettergaf
            ":": u"\u06DC", # smallhighseen
            "@": u"\u06DF", # smallhighroundedzero
            "\"": u"\u06E0", # smallhighuprightrectangularzero
            "[": u"\u06E2", # smallhighmeemisolatedform
            ";": u"\u06E3", # smalllowseen
            ",": u"\u06E5", # smallwaw
            ".": u"\u06E6", # smallya
            "!": u"\u06E8", # smallhighnoon
            "-": u"\u06EA", # emptycentrelowstop
            "+": u"\u06EB", # emptycentrehighstop
            "%": u"\u06EC", # roundedhighstopwithfilledcentre
            "]": u"\u06ED", # smalllowmeem           
}

def transString(string, reverse=0):
    '''Given a Unicode string, transliterate into Buckwalter. To go from
    Buckwalter back to Unicode, set reverse=1'''

    for k, v in buck2uni.items():
      if not reverse:
            string = string.replace(v, k)
      else:
            string = string.replace(k, v)

    return string

In [4]:
# Simple Technique
# -*- coding: utf-8 -*-

# Arabic Transliteration based on Buckwalter
# dictionary source is buckwalter2unicode.py http://www.redhat.com/archives/fedora-extras-commits/2007-June/msg03617.html 

buck2unisimple = {"'": u"\u0621", # hamza-on-the-line
            "|": u"\u0622", # madda
            ">": u"\u0623", # hamza-on-'alif
            "&": u"\u0624", # hamza-on-waaw
            "<": u"\u0625", # hamza-under-'alif
            "A": u"\u0627", # bare 'alif
            "b": u"\u0628", # baa'
            "p": u"\u0629", # taa' marbuuTa
            "t": u"\u062A", # taa'
            "v": u"\u062B", # thaa'
            "j": u"\u062C", # jiim
            "H": u"\u062D", # Haa'
            "x": u"\u062E", # khaa'
            "d": u"\u062F", # daal
            "*": u"\u0630", # dhaal
            "r": u"\u0631", # raa'
            "z": u"\u0632", # zaay
            "s": u"\u0633", # siin
            "$": u"\u0634", # shiin
            "S": u"\u0635", # Saad
            "D": u"\u0636", # Daad
            "T": u"\u0637", # Taa'
            "Z": u"\u0638", # Zaa' (DHaa')
            "E": u"\u0639", # cayn
            "g": u"\u063A", # ghayn
            "_": u"\u0640", # taTwiil
            "f": u"\u0641", # faa'
            "q": u"\u0642", # qaaf
            "k": u"\u0643", # kaaf
            "l": u"\u0644", # laam
            "m": u"\u0645", # miim
            "n": u"\u0646", # nuun
            "h": u"\u0647", # haa'
            "w": u"\u0648", # waaw
            "Y": u"\u0649", # 'alif maqSuura
            "y": u"\u064A", # yaa'
            "{": u"\u0671", # waSla         
}

def transStringSimple(string, reverse=0):
    '''Given a Unicode string, transliterate into Buckwalter. To go from
    Buckwalter back to Unicode, set reverse=1'''

    for k, v in buck2unisimple.items():
      if not reverse:
            string = string.replace(v, k)
      else:
            string = string.replace(k, v)

    return string

In [5]:
# character clean for simple after transStringSimple 
def clean(text):
    arabic_out = re.sub(r'''([PJVG\.:;,!\+\]\[@#FNKauio`~"%-])''', "", text) # .$^*+
    arabic_out2 = re.sub(r"\^", " ", arabic_out)
    return arabic_out2

In [17]:
# Fail
#def clean(text):
#    arabic_text2 = re.sub(r"\[", "", text)
#    arabic_text3 = re.sub(r"\]", "", arabic_text2)
#    arabic_text4 = re.sub(r'''([@#:;,.!-+%"FNKaui~o`}PJVG])''', "", arabic_text3)
#    arabic_text5 = re.sub(r"\^", " ", arabic_text4)
#    return arabic_text5

In [18]:
df_buckwalter_concat["arabic"] = df_buckwalter_concat.iloc[:,2].apply(lambda x: transString(x, 1)) # Convert Arabic Extended

In [19]:
df_buckwalter_concat["arabic_simple"] = df_buckwalter_concat.iloc[:,2].apply(lambda x : transStringSimple(x, 1)) # Convert Arabic Simple
df_buckwalter_concat["arabic_simple"] = df_buckwalter_concat.iloc[:,4].apply(lambda x : clean(x))
df_buckwalter_concat

,num_1,num_2,buckwalter,arabic,arabic_simple
0,1,1,bisomi {ll~ahi {lr~aHoma`ni {lr~aHiymi,بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ,بسم ٱلله ٱلرحمن ٱلرحيم
1,1,2,{loHamodu lil~ahi rab~i {loEa`lamiyna,ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَٰلَمِينَ,ٱلحمد لله رب ٱلعلمين
2,1,3,{lr~aHoma`ni {lr~aHiymi,ٱلرَّحْمَٰنِ ٱلرَّحِيمِ,ٱلرحمن ٱلرحيم
3,1,4,ma`liki yawomi {ld~iyni,مَٰلِكِ يَوْمِ ٱلدِّينِ,ملك يوم ٱلدين
4,1,5,<iy~aAka naEobudu wa<iy~aAka nasotaEiynu,إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ,إياك نعبد وإياك نستعين
...,...,...,...,...,...
6231,114,2,maliki {ln~aAsi,مَلِكِ ٱلنَّاسِ,ملك ٱلناس
6232,114,3,<ila`hi {ln~aAsi,إِلَٰهِ ٱلنَّاسِ,إله ٱلناس
6233,114,4,min $ar~i {lowasowaAsi {loxan~aAsi,مِن شَرِّ ٱلْوَسْوَاسِ ٱلْخَنَّاسِ,من شر ٱلوسواس ٱلخناس
6234,114,5,{l~a*iY yuwasowisu fiY Suduwri {ln~aAsi,ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ,ٱلذى يوسوس فى صدور ٱلناس
6235,114,6,mina {lojin~api wa{ln~aAsi,مِنَ ٱلْجِنَّةِ وَٱلنَّاسِ,من ٱلجنة وٱلناس

In [20]:
df_buckwalter_concat = df_buckwalter_concat[["num_1","num_2","arabic","buckwalter","arabic_simple"]]
df_buckwalter_concat

,num_1,num_2,arabic,buckwalter,arabic_simple
0,1,1,بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ,bisomi {ll~ahi {lr~aHoma`ni {lr~aHiymi,بسم ٱلله ٱلرحمن ٱلرحيم
1,1,2,ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَٰلَمِينَ,{loHamodu lil~ahi rab~i {loEa`lamiyna,ٱلحمد لله رب ٱلعلمين
2,1,3,ٱلرَّحْمَٰنِ ٱلرَّحِيمِ,{lr~aHoma`ni {lr~aHiymi,ٱلرحمن ٱلرحيم
3,1,4,مَٰلِكِ يَوْمِ ٱلدِّينِ,ma`liki yawomi {ld~iyni,ملك يوم ٱلدين
4,1,5,إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ,<iy~aAka naEobudu wa<iy~aAka nasotaEiynu,إياك نعبد وإياك نستعين
...,...,...,...,...,...
6231,114,2,مَلِكِ ٱلنَّاسِ,maliki {ln~aAsi,ملك ٱلناس
6232,114,3,إِلَٰهِ ٱلنَّاسِ,<ila`hi {ln~aAsi,إله ٱلناس
6233,114,4,مِن شَرِّ ٱلْوَسْوَاسِ ٱلْخَنَّاسِ,min $ar~i {lowasowaAsi {loxan~aAsi,من شر ٱلوسواس ٱلخناس
6234,114,5,ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ,{l~a*iY yuwasowisu fiY Suduwri {ln~aAsi,ٱلذى يوسوس فى صدور ٱلناس
6235,114,6,مِنَ ٱلْجِنَّةِ وَٱلنَّاسِ,mina {lojin~api wa{ln~aAsi,من ٱلجنة وٱلناس

In [21]:
#df_buckwalter_concat["buckwalter_simple"] = df_buckwalter_concat.iloc[:,4].apply(lambda x : transString(x, 0))
df_buckwalter_concat["buckwalter_simple"] = df_buckwalter_concat.iloc[:,4].apply(lambda x : transStringSimple(x, 0)) # Convert Arabic Simple
df_buckwalter_concat["buckwalter_simple"] = df_buckwalter_concat.iloc[:,5].apply(lambda x : clean(x))
df_buckwalter_concat

,num_1,num_2,arabic,buckwalter,arabic_simple,buckwalter_simple
0,1,1,بِسْمِ ٱللَّهِ ٱلرَّحْمَٰنِ ٱلرَّحِيمِ,bisomi {ll~ahi {lr~aHoma`ni {lr~aHiymi,بسم ٱلله ٱلرحمن ٱلرحيم,bsm {llh {lrHmn {lrHym
1,1,2,ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَٰلَمِينَ,{loHamodu lil~ahi rab~i {loEa`lamiyna,ٱلحمد لله رب ٱلعلمين,{lHmd llh rb {lElmyn
2,1,3,ٱلرَّحْمَٰنِ ٱلرَّحِيمِ,{lr~aHoma`ni {lr~aHiymi,ٱلرحمن ٱلرحيم,{lrHmn {lrHym
3,1,4,مَٰلِكِ يَوْمِ ٱلدِّينِ,ma`liki yawomi {ld~iyni,ملك يوم ٱلدين,mlk ywm {ldyn
4,1,5,إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ,<iy~aAka naEobudu wa<iy~aAka nasotaEiynu,إياك نعبد وإياك نستعين,<yAk nEbd w<yAk nstEyn
...,...,...,...,...,...,...
6231,114,2,مَلِكِ ٱلنَّاسِ,maliki {ln~aAsi,ملك ٱلناس,mlk {lnAs
6232,114,3,إِلَٰهِ ٱلنَّاسِ,<ila`hi {ln~aAsi,إله ٱلناس,<lh {lnAs
6233,114,4,مِن شَرِّ ٱلْوَسْوَاسِ ٱلْخَنَّاسِ,min $ar~i {lowasowaAsi {loxan~aAsi,من شر ٱلوسواس ٱلخناس,mn r {lwswAs {lxnAs
6234,114,5,ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ,{l~a*iY yuwasowisu fiY Suduwri {ln~aAsi,ٱلذى يوسوس فى صدور ٱلناس,{lY ywsws fY Sdwr {lnAs
6235,114,6,مِنَ ٱلْجِنَّةِ وَٱلنَّاسِ,mina {lojin~api wa{ln~aAsi,من ٱلجنة وٱلناس,mn {ljnp w{lnAs

In [6]:
# N gram from DataFrame text and DataFrame output
def df_ngram(df_column, ngram_num, ngram_type): # df_ngram(df_buckwalter_concat.iloc[:,2], 2, "twogram") ...
    n_gram_not_list = []
    n_gram_list = []
    for i in df_column:
        try:
            n_gram = ngrams(i.split(), ngram_num)
            for j in n_gram:
                j = " ".join(j)
                n_gram_list.append(j)
        except:
            n_gram_not_list.append(i) 
    df_ngram = pd.DataFrame(n_gram_list,columns=[f"{ngram_type}"])
    df_ngram = df_ngram.iloc[:,0].value_counts(ascending=False).reset_index()
    df_ngram.rename(columns={"index":f"{ngram_type.lower()}", f"{ngram_type.lower()}":"frequency"}, inplace=True)
    return df_ngram

In [28]:
# Arabic_Extended
#n = 2
#n_gram_not_list = []
#n_gram_list = [] 
#for i in df_buckwalter_concat.iloc[:,2]:
#    try:
#        n_gram = ngrams(i.split(), n)
#        for j in n_gram:
#            j = " ".join(j)
#            n_gram_list.append(j)
#    except:
#        n_gram_not_list.append(i)#

In [29]:
#pd.DataFrame(n_gram_not_list,columns=["not_proper"])

In [30]:
#df_arabic_ngram = pd.DataFrame(n_gram_list,columns=["twogram"])
#df_arabic_ngram

In [31]:
#df_arabic_ngram = df_arabic_ngram.iloc[:,0].value_counts(ascending=False).reset_index()
#df_arabic_ngram.rename(columns={"index":"twogram", "twogram":"frequency"}, inplace=True)
#df_arabic_ngram

In [23]:
# Arabic
ngram_num = 5
ngram_type = "fivegram"
df_arabic_ngram = df_ngram(df_buckwalter_concat.iloc[:,2], ngram_num, f"{ngram_type}")
df_arabic_ngram

                                                fivegram  frequency
0                  فِى ٱلسَّمَٰوَٰتِ وَمَا فِى ٱلْأَرْضِ         28
1                        مَا فِى ٱلسَّمَٰوَٰتِ وَمَا فِى         26
2            جَنَّٰتٍ تَجْرِى مِن تَحْتِهَا ٱلْأَنْهَٰرُ         21
3          تَجْرِى مِن تَحْتِهَا ٱلْأَنْهَٰرُ خَٰلِدِينَ         19
4                 إِنَّ فِى ذَٰلِكَ لَءَايَٰتٍ لِّقَوْمٍ         14
...                                                  ...        ...
50214      رَبُّكَ إِلَى ٱلْمَلَٰٓئِكَةِ أَنِّى مَعَكُمْ          1
50215  إِلَى ٱلْمَلَٰٓئِكَةِ أَنِّى مَعَكُمْ فَثَبِّت...          1
50216  ٱلْمَلَٰٓئِكَةِ أَنِّى مَعَكُمْ فَثَبِّتُوا۟ ٱ...          1
50217  أَنِّى مَعَكُمْ فَثَبِّتُوا۟ ٱلَّذِينَ ءَامَنُوا۟          1
50218            ٱلَّذِى يُوَسْوِسُ فِى صُدُورِ ٱلنَّاسِ          1

[50219 rows x 2 columns]

In [33]:
df_arabic_ngram.to_excel(f"Arabic_{ngram_type.capitalize()}_Frequency_From_DataFrame_Morphology.xlsx", sheet_name=f"Arabic_{ngram_type.capitalize()}", index=False)

In [24]:
# Arabic_Simple
ngram_num = 5
ngram_type = "fivegram"
df_arabic_simple_ngram = df_ngram(df_buckwalter_concat.iloc[:,4], ngram_num, f"{ngram_type}")
df_arabic_simple_ngram

                       fivegram  frequency
0      فبأى ءالا ء ربكما تكذبان         31
1        فى ٱلسموت وما فى ٱلأرض         28
2           ما فى ٱلسموت وما فى         28
3          ي أيها ٱلذين ءامنو ا         27
4        ي أيها ٱلذين ءامنوا لا         27
...                         ...        ...
52219        بلا ء حسنا إن ٱلله          1
52220       ء حسنا إن ٱلله سميع          1
52221    حسنا إن ٱلله سميع عليم          1
52222    ذلكم وأن ٱلله موهن كيد          1
52223  ٱلذى يوسوس فى صدور ٱلناس          1

[52224 rows x 2 columns]

In [35]:
df_arabic_simple_ngram.to_excel(f"Arabic_Simple_{ngram_type.capitalize()}_Frequency_From_DataFrame_Morphology.xlsx", sheet_name=f"Arabic_Simple_{ngram_type.capitalize()}", index=False)

#### Tanzil N Gram

In [7]:
ar2bw = CharMapper.builtin_mapper('ar2bw')

In [8]:
type_file = "clean" # plain, minimal, clean

In [9]:
with open(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Data/Quran Simple {type_file.lower().capitalize()}.txt", "r", encoding="utf8") as file: # Quran Simple Clean.txt from Tanzil website
    arabic_text_simple =file.readlines()

In [10]:
df_tanzil_sent = pd.DataFrame(arabic_text_simple)
#df_tanzil_sent = df_tanzil_sent.iloc[0:6236,]
df_tanzil_sent

                                     0
0         1|1|بسم الله الرحمن الرحيم\n
1          1|2|الحمد لله رب العالمين\n
2                  1|3|الرحمن الرحيم\n
3                 1|4|مالك يوم الدين\n
4         1|5|إياك نعبد وإياك نستعين\n
...                                ...
6231                 114|2|ملك الناس\n
6232                 114|3|إله الناس\n
6233      114|4|من شر الوسواس الخناس\n
6234  114|5|الذي يوسوس في صدور الناس\n
6235           114|6|من الجنة والناس\n

[6236 rows x 1 columns]

In [11]:
df_tanzil_sent = pd.DataFrame(df_tanzil_sent.iloc[:,0].apply(lambda x: x.strip("\n")))
df_tanzil_sent

                                   0
0         1|1|بسم الله الرحمن الرحيم
1          1|2|الحمد لله رب العالمين
2                  1|3|الرحمن الرحيم
3                 1|4|مالك يوم الدين
4         1|5|إياك نعبد وإياك نستعين
...                              ...
6231                 114|2|ملك الناس
6232                 114|3|إله الناس
6233      114|4|من شر الوسواس الخناس
6234  114|5|الذي يوسوس في صدور الناس
6235           114|6|من الجنة والناس

[6236 rows x 1 columns]

In [12]:
df_tanzil_sent_nav = df_tanzil_sent.iloc[:,0].str.split("|", n=-1, expand=True)
df_tanzil_sent_nav.rename(columns={0:"num_1",1:"num_2",2:f"arabic_sent_tanzil_{type_file.lower()}"}, inplace=True)
df_tanzil_sent_nav

     num_1 num_2  arabic_sent_tanzil_clean
0        1     1    بسم الله الرحمن الرحيم
1        1     2     الحمد لله رب العالمين
2        1     3             الرحمن الرحيم
3        1     4            مالك يوم الدين
4        1     5    إياك نعبد وإياك نستعين
...    ...   ...                       ...
6231   114     2                 ملك الناس
6232   114     3                 إله الناس
6233   114     4      من شر الوسواس الخناس
6234   114     5  الذي يوسوس في صدور الناس
6235   114     6           من الجنة والناس

[6236 rows x 3 columns]

In [31]:
ngram_num = 5
ngram_type = "fivegram"
df_arabic_ngram = df_ngram(df_tanzil_sent_nav.iloc[:,2], ngram_num, f"{ngram_type}")
df_arabic_ngram

                           fivegram  frequency
0             ما في السماوات وما في         28
1          في السماوات وما في الأرض         28
2            يا أيها الذين آمنوا لا         27
3        جنات تجري من تحتها الأنهار         26
4      تجري من تحتها الأنهار خالدين         19
...                             ...        ...
50479  أطيعوا الله ورسوله ولا تولوا          1
50480     الله ورسوله ولا تولوا عنه          1
50481    ورسوله ولا تولوا عنه وأنتم          1
50482    ولا تولوا عنه وأنتم تسمعون          1
50483      الذي يوسوس في صدور الناس          1

[50484 rows x 2 columns]

In [32]:
df_arabic_ngram[f"buckwalter_{ngram_type.lower()}"] = df_arabic_ngram.iloc[:,0].apply(lambda x: transString(x, 0))
df_arabic_ngram = df_arabic_ngram.iloc[:,[0,2,1]]
df_arabic_ngram

                           fivegram           buckwalter_fivegram  frequency
0             ما في السماوات وما في         mA fy AlsmAwAt wmA fy         28
1          في السماوات وما في الأرض      fy AlsmAwAt wmA fy Al>rD         28
2            يا أيها الذين آمنوا لا        yA >yhA Al*yn |mnwA lA         27
3        جنات تجري من تحتها الأنهار    jnAt tjry mn tHthA Al>nhAr         26
4      تجري من تحتها الأنهار خالدين  tjry mn tHthA Al>nhAr xAldyn         19
...                             ...                           ...        ...
50479  أطيعوا الله ورسوله ولا تولوا  >TyEwA Allh wrswlh wlA twlwA          1
50480     الله ورسوله ولا تولوا عنه     Allh wrswlh wlA twlwA Enh          1
50481    ورسوله ولا تولوا عنه وأنتم    wrswlh wlA twlwA Enh w>ntm          1
50482    ولا تولوا عنه وأنتم تسمعون    wlA twlwA Enh w>ntm tsmEwn          1
50483      الذي يوسوس في صدور الناس      Al*y ywsws fy Sdwr AlnAs          1

[50484 rows x 3 columns]

In [33]:
#df_arabic_ngram[f"buckwalter_{ngram_type.lower()}"] = df_arabic_ngram.iloc[:,0].apply(lambda x: ar2bw(x))
#df_arabic_ngram = df_arabic_ngram.iloc[:,[0,2,1]]
#df_arabic_ngram

In [34]:
df_arabic_ngram.to_excel(f"Arabic_{type_file.lower().capitalize()}_{ngram_type.lower().capitalize()}_Frequency_From_DataFrame_Tanzil.xlsx", sheet_name=f"Arabic_{type_file.lower().capitalize()}_{ngram_type.lower().capitalize()}", index=False)