### Language Pair N Gram

In [1]:
import pandas as pd
import numpy as np
import os
import nltk
from nltk import word_tokenize
#import multiprocessing
##import multiprocessing as mp
#from multiprocessing import Process, Manager, Pool, Queue
from itertools import islice
import re
import glob

In [2]:
lang_folder = "Turkish"
lang_pair = "Arabic"
ngram_type = "Twogram"

In [3]:
word_num = 300
df_word = pd.read_excel(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/{lang_folder.lower().capitalize()}/Deployment/Data/Word/Word_Merge_Preprocess.xlsx")
#df_word = pd.read_csv(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/{lang_folder.lower().capitalize()}/Deployment/Data/Word/Word_Merge_Preprocess.csv")
df_word = df_word.head(word_num)
df_word

       word  frequency
0       bir   18835735
1        bu   11062659
2        ne    8025880
3        ve    7766036
4      için    5484109
..      ...        ...
295  eminim     252546
296   insan     252056
297  gördüm     251150
298    bazı     249261
299   polis     247969

[300 rows x 2 columns]

In [7]:
#df_ngram = pd.read_csv(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/{lang_folder.capitalize()}/Result/N Gram/Merge/{ngram_type.capitalize()}_Merge.csv")
df_ngram = pd.read_csv(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/{lang_folder.capitalize()}/Result/N Gram/N Gram And Sentence/Two_Gram_And_Sentence_All.csv")  # ext. sentence and ngram
df_ngram.rename(columns={"two_gram":"twogram"}, inplace=True)  # ext.
df_ngram

                      twogram  frequency
0             teşekkür ederim     244149
1                     öyle mi     209900
2                     ne oldu     195799
3                 aman tanrım     189521
4                özür dilerim     153784
...                       ...        ...
1036515         güzeldi tommy          3
1036516  durumu tuhaflaştırma          3
1036517         güzeldi canım          3
1036518        güzeldi daniel          3
1036519      güzelce vurdular          3

[1036520 rows x 2 columns]

In [8]:
lang_pair_list = glob.glob(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/{lang_folder.capitalize()}/{lang_folder.capitalize()}_And_{lang_pair.lower().capitalize()}*.xlsx")
lang_pair_list

['/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Turkish/Turkish_And_Arabic (ara)_Etymologeek_Result.xlsx']

In [9]:
df_pair = pd.read_excel(f"{lang_pair_list[0]}")
df_pair

,search_word,dict_entry_main,language_main,definition_main,dict_entry,language,definition
0,mı,mıknatıs,Turkish,(Noun) Magnet.Magnet.,مِغْنَاطِيس,Arabic (ara),NaN
1,mı,mısdak,Turkish,(Noun) (obsolete) criterion.(obsolete) criterion.,مِصْدَاق,Arabic (ara),NaN
2,şey,şey,Turkish,(Noun Interjection) (slang) genital organ. Thi...,شَيْئاً,Arabic (ara),NaN
3,şey,şeytan,Turkish,(Noun) Devil.Devil.,شَيَّطَ,Arabic (ara),NaN
4,şey,şeytanî,Turkish,(Adjective) Devilish.Devilish.,شَيْطَانِيّ,Arabic (ara),NaN
...,...,...,...,...,...,...,...
334,cumhuriyet,cumhuriyet,Turkish,(Noun) Republic.Republic.,جمهور,Arabic (ara),"Multitude, crowd, throng. Public, general public."
335,barut,barut,Turkish,(Noun) Gunpowder.Gunpowder.,بَارُود,Arabic (ara),NaN
336,emlak,emlak,Turkish,"(Noun) Estate, property.Estate, property.",أملاك,Arabic (ara),NaN
337,ebeveyn,ebeveyn,Turkish,(Noun) Parent (person from whom one is descend...,أَبَوَيْن,Arabic (ara),NaN
338,şah,şahıs,Turkish,(Noun) Person.Person.,شخص,Arabic (ara),"Figure, character. Person, individual. Someone..."

In [10]:
ngram_list = []
for i in df_pair["dict_entry_main"]:
    for j in word_tokenize(i):
        for k in df_word["word"]:
            twogram_1_2 = f"{j} {k}"
            ngram_list.append(twogram_1_2)
            twogram_2_1 = f"{k} {j}"
            ngram_list.append(twogram_2_1)
df_pair_ngram = pd.DataFrame(ngram_list)
df_pair_ngram.rename(columns={0:"twogram"}, inplace=True)
df_pair_ngram.drop_duplicates(inplace=True)
df_pair_ngram

             twogram
0       mıknatıs bir
1       bir mıknatıs
2        mıknatıs bu
3        bu mıknatıs
4        mıknatıs ne
...              ...
206395  gördüm şahıs
206396    şahıs bazı
206397    bazı şahıs
206398   şahıs polis
206399   polis şahıs

[203375 rows x 1 columns]

In [11]:
df_lang_pair_ngram = pd.merge(df_ngram, df_pair_ngram, how="inner", on="twogram")
df_lang_pair_ngram.drop_duplicates(inplace=True)
df_lang_pair_ngram

            twogram  frequency
0       aman tanrım     189521
1      özür dilerim     153784
2          tamam mı     134129
3       hayır hayır     114120
4        emin misin      56835
...             ...        ...
8655        cuma ha          3
8656     cuma yarın          3
8657     resim onun          3
8658   resim gerçek          3
8659  resim geliyor          3

[8660 rows x 2 columns]

In [12]:
df_lang_pair_ngram.to_excel(f"{lang_folder.capitalize()}_And_{lang_pair.capitalize()}_Word_Pair_{ngram_type.capitalize()}.xlsx", index=False)

In [10]:
#df_word.to_excel(f"{lang_folder.capitalize()}_{word_num}_Words.xlsx", index=False)

In [11]:
#df_pair[["dict_entry_main"]].to_excel(f"{lang_pair.capitalize()}_To_{lang_folder.capitalize()}_Words.xlsx", index=False)