### Level Results

In [1]:
import pandas as pd
import numpy as np
import re
import glob
import nltk
from nltk import word_tokenize

In [2]:
word_num = 28

In [3]:
df_word = pd.read_excel(f"Word_{word_num}.xlsx")
df_word = pd.DataFrame(df_word.iloc[:,0])
df_word

     word
0     bir
1      bu
2      ne
3      ve
4    için
5      mi
6     ben
7      de
8     çok
9     ama
10    var
11   evet
12     mı
13  değil
14     da
15    şey
16  hayır
17   daha
18    sen
19  kadar
20   bana
21    yok
22    onu
23   seni
24   beni
25   bunu
26   gibi
27    iyi

In [4]:
twogram_file = glob.glob(f"Twogram_And*")
twogram_file

['Twogram_And_Sentence_123_With_28_Word.xlsx']

In [48]:
df_twogram = pd.read_excel(f"{twogram_file[0]}")
df_twogram.sort_values(by="frequency", ascending=True, inplace=True)
df_twogram.reset_index(drop=True, inplace=True)
df_twogram = pd.DataFrame(df_twogram.iloc[:,0])
df_twogram

         twogram
0        ama var
1      hayır şey
2       ne değil
3     hayır evet
4        ama şey
..           ...
118  hayır hayır
119       var mı
120       ben de
121     değil mi
122      bir şey

[123 rows x 1 columns]

In [6]:
threegram_file = glob.glob(f"Threegram_And*")
threegram_file

['Threegram_And_Sentence_92_With_28_Word.xlsx']

In [49]:
df_threegram = pd.read_excel(f"{threegram_file[0]}")
df_threegram.sort_values(by="frequency", ascending=True, inplace=True)
df_threegram.reset_index(drop=True, inplace=True)
df_threegram = pd.DataFrame(df_threegram.iloc[:,0])
df_threegram

            threegram
0           ne var mı
1       yok yok hayır
2     hayır iyi değil
3           ne ben mi
4          ne için mi
..                ...
87      bir şey değil
88  hayır hayır hayır
89           bu da ne
90        bir şey var
91        bir şey yok

[92 rows x 1 columns]

In [8]:
fourgram_file = glob.glob(f"Fourgram_And*")
fourgram_file

['Fourgram_And_Sentence_61_With_28_Word.xlsx']

In [50]:
df_fourgram = pd.read_excel(f"{fourgram_file[0]}")
df_fourgram.sort_values(by="frequency", ascending=True, inplace=True)
df_fourgram.reset_index(drop=True, inplace=True)
df_fourgram = pd.DataFrame(df_fourgram.iloc[:,0])
df_fourgram

                   fourgram
0         ne kadar daha var
1             ben mi sen mi
2             bu iyi bu iyi
3        hayır bu iyi değil
4          evet bir şey yok
..                      ...
56            ne var ne yok
57           bir şey mi var
58  hayır hayır hayır hayır
59         bir şey daha var
60           bir şey var mı

[61 rows x 1 columns]

In [10]:
fivegram_file = glob.glob(f"Fivegram_And*")
fivegram_file

['Fivegram_And_Sentence_28_With_28_Word.xlsx']

In [51]:
df_fivegram = pd.read_excel(f"{fivegram_file[0]}")
df_fivegram.sort_values(by="frequency", ascending=True, inplace=True)
df_fivegram.reset_index(drop=True, inplace=True)
df_fivegram = pd.DataFrame(df_fivegram.iloc[:,0])
df_fivegram

                         fivegram
0           daha iyi çok daha iyi
1             bu bir şey değil mi
2           bu iyi değil değil mi
3           evet bir şey daha var
4             bu evet mi hayır mı
5           ne kadar iyi değil mi
6         hayır hayır bir şey yok
7              bu çok iyi bir şey
8              sen sen sen ve sen
9                ve bir de bu var
10            bu çok iyi değil mi
11            bana bir şey var mı
12           hayır bu iyi bir şey
13               ne sen ne de ben
14          bu daha bir şey değil
15               bu da bir şey mi
16           bu daha iyi değil mi
17              ve bu iyi bir şey
18             ama bu iyi bir şey
19                 da da da da da
20              bu da iyi bir şey
21            ve bir şey daha var
22           ama bir şey daha var
23       evet evet evet evet evet
24           bir şey yok değil mi
25              bu iyi bir şey mi
26           bu iyi bir şey değil
27  hayır hayır hayır hayır hayır

In [12]:
twogram_other_file = glob.glob(f"Twogram_*_Include*")
twogram_other_file

['Twogram_193_Include_Arabic_With_28_Word.xlsx']

In [52]:
df_twogram_other = pd.read_excel(f"{twogram_other_file[0]}")
df_twogram_other.sort_values(by="frequency", ascending=True, inplace=True)
df_twogram_other.reset_index(drop=True, inplace=True)
df_twogram_other = pd.DataFrame(df_twogram_other.iloc[:,0])
df_twogram_other

        twogram
0     yok kadar
1     bir kadar
2        şey da
3    gibi kadar
4    evet kadar
..          ...
188     şey var
189     şey yok
190    bu kadar
191    ne kadar
192     bir şey

[193 rows x 1 columns]

In [53]:
def word_count(df, bigger_than): # df is a dataframe, bigger_than is an integer
    list_all = []
    for i in df.columns:
        var_list = df[f"{i}"].dropna().tolist()
        for j in var_list:
            list_all.append(j)
    text = " ".join(list_all)
    word_list = re.findall(r"\w+",text, re.UNICODE)
    df_word_list = pd.DataFrame(word_list)
    df_word_list.rename(columns={0:"word"}, inplace=True)
    df_word_count = pd.DataFrame(df_word_list.value_counts())
    df_word_count.reset_index(inplace=True)
    df_word_count.rename(columns={0:"count"}, inplace=True)
    
    return  df_word_count["count"][df_word_count.loc[:,"count"] > bigger_than].any()

In [54]:
twogram_num = 30
threegram_num = 30
fourgram_num = 30
fivegram_num = 30
twogram_other_num = 30

In [55]:
df_lesson_result = pd.DataFrame(columns=["twogram","twogram_other","threegram","fourgram","fivegram"])
word_thresh_num = 8
a = 0
b = 0
c = 0
d = 0
e = 0
for i in range(len(df_word)):
    try:
        var1 = df_twogram.iloc[a,0]
        if (len(df_lesson_result["twogram"]) < twogram_num): # and (not(word_count(df_lesson_result, word_thresh_num))):
            df_lesson_result.loc[i,"twogram"] = var1
            while word_count(df_lesson_result, word_thresh_num): # word count result                
                a += 1
                var1 = df_twogram.iloc[a,0]
                df_lesson_result.loc[i,"twogram"] = var1
            else:
                pass
        else:
            pass
    except:
        pass
    a += 1

    try:
        var2 = df_twogram_other.iloc[b,0]
        if (len(df_lesson_result["twogram_other"]) < twogram_other_num): # and (not(word_count(df_lesson_result, word_thresh_num))):
            df_lesson_result.loc[i,"twogram_other"] = var2
            while word_count(df_lesson_result, word_thresh_num): # word count result                
                b += 1
                var2 = df_twogram_other.iloc[b,0]
                df_lesson_result.loc[i,"twogram_other"] = var2
            else:
                pass
        else:
            pass
    except:
        pass
    b += 1

    try:
        var3 = df_threegram.iloc[c,0]
        if (len(df_lesson_result["threegram"]) < threegram_num): # and (not(word_count(df_lesson_result, word_thresh_num))):
            df_lesson_result.loc[i,"threegram"] = var3
            while word_count(df_lesson_result, word_thresh_num): # word count result                
                c += 1
                var3 = df_threegram.iloc[c,0]
                df_lesson_result.loc[i,"threegram"] = var3
            else:
                pass
        else:
            pass
    except:
        pass
    c += 1

    try:
        var4 = df_fourgram.iloc[d,0]
        if (len(df_lesson_result["fourgram"]) < fourgram_num): # and (not(word_count(df_lesson_result, word_thresh_num))):
            df_lesson_result.loc[i,"fourgram"] = var4
            while word_count(df_lesson_result, word_thresh_num): # word count result                
                d += 1
                var4 = df_fourgram.iloc[d,0]
                df_lesson_result.loc[i,"fourgram"] = var4
            else:
                pass
        else:
            pass
    except:
        pass
    d += 1

    try:
        var5 = df_fivegram.iloc[e,0]
        if (len(df_lesson_result["fivegram"]) < fivegram_num): # and (not(word_count(df_lesson_result, word_thresh_num))):
            df_lesson_result.loc[i,"fivegram"] = var5
            while word_count(df_lesson_result, word_thresh_num):                
                e += 1
                var5 = df_fivegram.iloc[e,0]
                df_lesson_result.loc[i,"fivegram"] = var5
            else:
                pass
        else:
            pass
    except:
        pass
    e += 1

In [56]:
print(f'twogram: {a} \ntwogram_other: {b} \nthreegram_other: {c} \nfourgram_other: {d} \nfivegram_other: {e}')

twogram: 142
twogram_other: 212
threegram_other: 111
fourgram_other: 80
fivegram_other: 48

In [57]:
df_lesson_result

,twogram,twogram_other,threegram,fourgram,fivegram
0,ama var,yok kadar,ne var mı,ne kadar daha var,daha iyi çok daha iyi
1,hayır şey,bir kadar,yok yok hayır,ben mi sen mi,bu bir şey değil mi
2,ne değil,şey da,hayır iyi değil,bu iyi bu iyi,bu iyi değil değil mi
3,hayır evet,gibi kadar,ne ben mi,hayır bu iyi değil,evet bir şey daha var
4,ama şey,evet kadar,ne için mi,evet bir şey yok,bu evet mi hayır mı
5,ve şey,ama mı,bu şey mi,bu bir hayır mı,sen sen sen ve sen
6,evet yok,da kadar,ama ben değil,sen de ne var,ne sen ne de ben
7,ben hayır,ama de,evet beni de,daha çok daha çok,da da da da da
8,onu değil,kadar de,evet seni de,sen de var mı,hayır hayır hayır hayır hayır
9,bir şey,bir şey,bir şey yok,bir şey var mı,NaN

In [58]:
def word_count_result(df): # df is dataframe, bigger_than is integer
    list_all = []
    for i in df.columns:
        var_list = df[f"{i}"].dropna().tolist()
        for j in var_list:
            list_all.append(j)
    text = " ".join(list_all)
    word_list = re.findall(r"\w+",text, re.UNICODE)
    df_word_list = pd.DataFrame(word_list)
    df_word_list.rename(columns={0:"word"}, inplace=True)
    df_word_count = pd.DataFrame(df_word_list.value_counts())
    df_word_count.reset_index(inplace=True)
    df_word_count.rename(columns={0:"count"}, inplace=True)
    
    return  df_word_count

In [60]:
df_word_count_result = word_count_result(df_lesson_result)
df_word_count_result

     word  count
0   hayır     13
1     şey     12
2     bir      9
3      ne      8
4      mi      8
5     sen      8
6    evet      8
7   değil      8
8      bu      8
9      de      7
10    var      7
11     da      7
12    iyi      7
13  kadar      7
14   daha      6
15    yok      6
16     mı      6
17    ama      5
18    ben      5
19    çok      3
20     ve      2
21    onu      1
22   seni      1
23   gibi      1
24   beni      1
25   için      1

In [61]:
df_lesson_result["word"] = df_word_count_result["word"]
df_lesson_result["count"] = df_word_count_result["count"]

In [62]:
df_lesson_result

,twogram,twogram_other,threegram,fourgram,fivegram,word,count
0,ama var,yok kadar,ne var mı,ne kadar daha var,daha iyi çok daha iyi,hayır,13
1,hayır şey,bir kadar,yok yok hayır,ben mi sen mi,bu bir şey değil mi,şey,12
2,ne değil,şey da,hayır iyi değil,bu iyi bu iyi,bu iyi değil değil mi,bir,9
3,hayır evet,gibi kadar,ne ben mi,hayır bu iyi değil,evet bir şey daha var,ne,8
4,ama şey,evet kadar,ne için mi,evet bir şey yok,bu evet mi hayır mı,mi,8
5,ve şey,ama mı,bu şey mi,bu bir hayır mı,sen sen sen ve sen,sen,8
6,evet yok,da kadar,ama ben değil,sen de ne var,ne sen ne de ben,evet,8
7,ben hayır,ama de,evet beni de,daha çok daha çok,da da da da da,değil,8
8,onu değil,kadar de,evet seni de,sen de var mı,hayır hayır hayır hayır hayır,bu,8
9,bir şey,bir şey,bir şey yok,bir şey var mı,NaN,de,7

In [63]:
df_lesson_result.to_excel("Lesson_Result_28_Words.xlsx", index=False)

In [33]:
word_count_result(df_twogram)

     word  count
0    evet     22
1   hayır     20
2      ne     19
3     ben     18
4      bu     16
5     şey     15
6   değil     14
7     ama     14
8     sen     13
9      ve     10
10     mi      9
11    çok      9
12    bir      9
13    yok      7
14    iyi      6
15    var      6
16     de      6
17   daha      4
18   bana      4
19     da      4
20   beni      3
21    onu      3
22   seni      3
23   bunu      3
24     mı      3
25  kadar      2
26   için      2
27   gibi      2

In [36]:
word_count_result(df_twogram_other)

     word  count
0     şey     60
1     ama     58
2      ve     57
3   kadar     42
4     ben      8
5     bir      8
6      bu      8
7     yok      8
8    evet      8
9    bana      8
10     mi      7
11    çok      7
12    var      7
13   seni      7
14    sen      7
15    onu      7
16     ne      7
17   için      7
18   beni      7
19  hayır      7
20     de      7
21   daha      7
22     da      7
23   bunu      7
24    iyi      7
25     mı      6
26   gibi      5
27  değil      5

In [34]:
word_count_result(df_threegram)

     word  count
0      bu     25
1      ne     20
2   hayır     19
3     iyi     17
4   değil     17
5     ben     16
6    evet     16
7     sen     13
8      mi     13
9    daha     13
10     de     12
11    çok     10
12  kadar     10
13    yok      9
14     ve      9
15    bir      9
16    var      8
17    ama      8
18    şey      8
19     mı      7
20     da      6
21   için      5
22   seni      2
23   beni      2
24   bana      1
25   gibi      1

In [37]:
word_count_result(df_fourgram)

     word  count
0     bir     22
1     şey     19
2      bu     19
3     iyi     17
4   hayır     15
5    daha     15
6      mi     13
7    evet     13
8     var     12
9     çok     12
10    ben     12
11    yok     12
12     ne     11
13  değil     10
14    sen     10
15     de      8
16     mı      7
17     ve      6
18     da      4
19  kadar      4
20   seni      1
21   gibi      1
22    ama      1

In [38]:
word_count_result(df_fivegram)

     word  count
0     bir     17
1     şey     16
2      bu     15
3     iyi     13
4      mi      9
5   değil      9
6   hayır      9
7    daha      7
8    evet      7
9      da      7
10    sen      5
11    var      5
12     ve      4
13    çok      3
14     ne      3
15    yok      2
16    ama      2
17     mı      2
18     de      2
19  kadar      1
20   bana      1
21    ben      1