#### Language Pair Word Equality

In [1]:
#!pip uninstall googletrans

In [2]:
import pandas as pd
import numpy as np
import glob
import re
import nltk
from nltk import word_tokenize
#import googletrans
#from googletrans import Translator

In [3]:
lang_1 = "Turkish"  # English, Turkish, German, French, Spanish, Arabic, Russian, Portuguese, Dutch, Italian 
lang_2 = "Italian"  # English, Turkish, German, French, Spanish, Arabic, Russian, Portuguese, Dutch, Italian

if lang_2 == "English":
    lang_3 = "English (eng)"
elif lang_2 == "Turkish":
    lang_3 = "Turkish (tur)"
elif lang_2 == "German":
    lang_3 = "German (deu)"
elif lang_2 == "French":
    lang_3 = "French (fra)"
elif lang_2 == "Spanish":
    lang_3 = "Spanish (spa)"
elif lang_2 == "Arabic":
    lang_3 = "Arabic (ara)"
elif lang_2 == "Russian":
    lang_3 = "Russian (rus)"
elif lang_2 == "Portuguese":
    lang_3 = "Portuguese (por)"
elif lang_2 == "Dutch":
    lang_3 = "Dutch (nld)"
elif lang_2 == "Italian":
    lang_3 = "Italian (ita)"
else:
    pass

print(f"{lang_1}\n{lang_2}\n{lang_3}")

Turkish
Italian
Italian (ita)

In [4]:
df_lang11 = pd.read_excel(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/{lang_1.capitalize()}/{lang_1.capitalize()}_And_{lang_3.capitalize()}_Etymologeek_Result1.xlsx")
df_lang11 = df_lang11.loc[:,["language_main","dict_entry_main","language","dict_entry"]]
df_lang11.rename(columns={"language_main":"lang_master","dict_entry_main":"term_master","language":"lang_sleeve","dict_entry":"term_sleeve"}, inplace=True)
df_lang11["term_master"] = df_lang11["term_master"].apply(lambda x: x.lower())
df_lang11["term_sleeve"] = df_lang11["term_sleeve"].apply(lambda x: x.lower())
df_lang11

   lang_master   term_master    lang_sleeve term_sleeve
0      Turkish         polis  Italian (ita)     polizia
1      Turkish        kaptan  Italian (ita)     capitan
2      Turkish          bira  Italian (ita)       birra
3      Turkish          grup  Italian (ita)      groppo
4      Turkish         banka  Italian (ita)       banca
5      Turkish         çinko  Italian (ita)       zinco
6      Turkish          onur  Italian (ita)       onore
7      Turkish         banyo  Italian (ita)       bagno
8      Turkish       fırtına  Italian (ita)     fortuna
9      Turkish         bilet  Italian (ita)   biglietto
10     Turkish           duş  Italian (ita)      doccia
11     Turkish        makine  Italian (ita)    macchina
12     Turkish       sigorta  Italian (ita)     sicurtà
13     Turkish      çikolata  Italian (ita)  cioccolata
14     Turkish        gazete  Italian (ita)      gazeta
15     Turkish          moda  Italian (ita)        moda
16     Turkish      politika  Italian (ita)    politica
17     Turkish        korsan  Italian (ita)     corsaro
18     Turkish          kasa  Italian (ita)       cassa
19     Turkish        düzine  Italian (ita)     dozzina
20     Turkish      pantolon  Italian (ita)   pantalone
21     Turkish      kamuflaj  Italian (ita)         ca-
22     Turkish       tiyatro  Italian (ita)      teatro
23     Turkish       senaryo  Italian (ita)    scenario
24     Turkish       palyaço  Italian (ita)      paglia
25     Turkish         roket  Italian (ita)        ruca
26     Turkish         mafya  Italian (ita)       mafia
27     Turkish  mafya babası  Italian (ita)       mafia
28     Turkish       kariyer  Italian (ita)    carriera
29     Turkish        antika  Italian (ita)      antico
30     Turkish        konser  Italian (ita)    concerto
31     Turkish       madalya  Italian (ita)    medaglia
32     Turkish        salata  Italian (ita)    insalare
33     Turkish        balina  Italian (ita)      balena
34     Turkish       fabrika  Italian (ita)    fabbrica
35     Turkish       makarna  Italian (ita)     maccare
36     Turkish         balon  Italian (ita)       balla
37     Turkish          kare  Italian (ita)    quadrato
38     Turkish      protesto  Italian (ita)  protestare
39     Turkish        fatura  Italian (ita)     fattura
40     Turkish         firma  Italian (ita)     firmare
41     Turkish         salon  Italian (ita)        sala
42     Turkish         conta  Italian (ita)      giunta
43     Turkish         borda  Italian (ita)       bordo
44     Turkish        makina  Italian (ita)    macchina
45     Turkish        kabine  Italian (ita)   gabinetto
46     Turkish          loca  Italian (ita)      loggia
47     Turkish          mayo  Italian (ita)      maglia
48     Turkish       entrika  Italian (ita)   intricare

In [5]:
df_lang12 = pd.read_excel(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/{lang_1.capitalize()}/{lang_1.capitalize()}_And_{lang_2.capitalize()}_Etymologeek_Result2.xlsx")
df_lang12 = df_lang12.loc[:,["lang","term","related_term_id"]]
df_lang12["term"] = df_lang12["term"].apply(lambda x: x.lower())
df_lang12

        lang            term         related_term_id
0    Turkish         palavra  JHVmHqAPXEq-YaIbd0B5Jg
1    Turkish         parabol  JHVmHqAPXEq-YaIbd0B5Jg
2    Turkish      alternatif  ZSxxztTSVm6V_6rNEGaKhQ
3    Turkish             çek  crVVT9teU8aDKQjnHlsDQw
4    Turkish            broş  EdLnt58rWpWxL_UbjnY8aw
..       ...             ...                     ...
351  Turkish          pijama  ksheUv1HXryKq1kAYr6yMQ
352  Turkish         traktör  gdUU9jUWV3-ZVOGB-hnD7A
353  Turkish       sigortacı  AsCOIxVkWxuDILpsZwg1ug
354  Turkish  afyonkarahisar  GtqsFdsRXcqWOmtsk8k7RA
355  Turkish          bikini  oqwJif0MXBegenMOx5b9bw

[356 rows x 3 columns]

In [6]:
df_lang13 = pd.read_excel(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/{lang_1.capitalize()}/{lang_1.capitalize()}_And_{lang_2.capitalize()}_Etymologeek_Result3.xlsx")
df_lang13.rename(columns={"lang":"lang_master","term":"term_master","related_lang":"lang_sleeve","related_term":"term_sleeve"}, inplace=True)
df_lang13["term_master"] = df_lang13["term_master"].apply(lambda x: x.lower())
df_lang13["term_sleeve"] = df_lang13["term_sleeve"].apply(lambda x: x.lower())
df_lang13

    lang_master term_master        reltype lang_sleeve term_sleeve
0       Turkish       zebra  borrowed_from     Italian       zebra
1       Turkish        papa  borrowed_from     Italian        papa
2       Turkish        lira   derived_from     Italian        lira
3       Turkish      napoli  borrowed_from     Italian      napoli
4       Turkish        tema  borrowed_from     Italian        tema
..          ...         ...            ...         ...         ...
161     Turkish      sinyor   derived_from     Italian      signor
162     Turkish     kasadar   derived_from     Italian       cassa
163     Turkish     kasiyer   derived_from     Italian    cassiere
164     Turkish     bilanço   derived_from     Italian    bilancio
165     Turkish       balya   derived_from     Italian       balla

[166 rows x 5 columns]

In [7]:
df_lang22 = pd.read_excel(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/{lang_2.capitalize()}/{lang_2.capitalize()}_And_{lang_1.capitalize()}_Etymologeek_Result2.xlsx")
df_lang22 = df_lang22.loc[:,["lang","term","related_term_id"]]
df_lang22["term"] = df_lang22["term"].apply(lambda x: x.lower())
df_lang22

         lang         term         related_term_id
0     Italian   parlamento  uXGtk5g-W8G_TlTxSHImpg
1     Italian    parlabile  uXGtk5g-W8G_TlTxSHImpg
2     Italian     sparlare  uXGtk5g-W8G_TlTxSHImpg
3     Italian  straparlare  uXGtk5g-W8G_TlTxSHImpg
4     Italian   parolaccia  JHVmHqAPXEq-YaIbd0B5Jg
...       ...          ...                     ...
1642  Italian    infardare  17eUGISEVL6eeN4TNB38kQ
1643  Italian       bikini  oqwJif0MXBegenMOx5b9bw
1644  Italian    anticrisi  tteyoQ6GUpKst94SvVVRUA
1645  Italian     precrisi  tteyoQ6GUpKst94SvVVRUA
1646  Italian       civita  h8LKnZUkUkinIpCMnKKSHw

[1647 rows x 3 columns]

In [8]:
df_same_ety = pd.merge(df_lang12,df_lang22, how="inner", on="related_term_id", suffixes=["_master","_sleeve"])
df_same_ety.drop_duplicates(inplace=True)
df_same_ety

    lang_master term_master         related_term_id lang_sleeve   term_sleeve
0       Turkish     palavra  JHVmHqAPXEq-YaIbd0B5Jg     Italian    parolaccia
1       Turkish     palavra  JHVmHqAPXEq-YaIbd0B5Jg     Italian      parolina
2       Turkish     palavra  JHVmHqAPXEq-YaIbd0B5Jg     Italian      parabola
3       Turkish     palavra  JHVmHqAPXEq-YaIbd0B5Jg     Italian        parola
4       Turkish     palavra  JHVmHqAPXEq-YaIbd0B5Jg     Italian   paraboloide
..          ...         ...                     ...         ...           ...
927     Turkish    silindir  EuWYJQS3XUmwMvKT5rPZdw     Italian    cilindrare
928     Turkish    silindir  EuWYJQS3XUmwMvKT5rPZdw     Italian  semicilindro
929     Turkish      pijama  ksheUv1HXryKq1kAYr6yMQ     Italian       pigiama
930     Turkish     traktör  gdUU9jUWV3-ZVOGB-hnD7A     Italian      trattore
931     Turkish      bikini  oqwJif0MXBegenMOx5b9bw     Italian        bikini

[932 rows x 5 columns]

In [9]:
df_ety_concat = pd.concat([df_same_ety,df_lang11,df_lang13], axis=0)
df_ety_concat.reset_index(drop=True, inplace=True)
df_ety_concat

,lang_master,term_master,related_term_id,lang_sleeve,term_sleeve,reltype
0,Turkish,palavra,JHVmHqAPXEq-YaIbd0B5Jg,Italian,parolaccia,NaN
1,Turkish,palavra,JHVmHqAPXEq-YaIbd0B5Jg,Italian,parolina,NaN
2,Turkish,palavra,JHVmHqAPXEq-YaIbd0B5Jg,Italian,parabola,NaN
3,Turkish,palavra,JHVmHqAPXEq-YaIbd0B5Jg,Italian,parola,NaN
4,Turkish,palavra,JHVmHqAPXEq-YaIbd0B5Jg,Italian,paraboloide,NaN
...,...,...,...,...,...,...
1142,Turkish,sinyor,NaN,Italian,signor,derived_from
1143,Turkish,kasadar,NaN,Italian,cassa,derived_from
1144,Turkish,kasiyer,NaN,Italian,cassiere,derived_from
1145,Turkish,bilanço,NaN,Italian,bilancio,derived_from
1146,Turkish,balya,NaN,Italian,balla,derived_from

In [10]:
df_master_unique = pd.DataFrame()
df_master_unique["term_master"] = df_ety_concat["term_master"].unique()
df_master_unique.rename(columns={"term_master":"term"}, inplace=True)
df_master_unique

           term
0       palavra
1       parabol
2    alternatif
3         sıfır
4     sıfırıncı
..          ...
305      sinyor
306     kasadar
307     kasiyer
308     bilanço
309       balya

[310 rows x 1 columns]

In [11]:
df_word = pd.read_excel(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/{lang_1.capitalize()}/Result/Word/Merge/Word_Merge2.xlsx")
df_word = df_word.head(40000)
#df_word = df_word.loc[:,["word"]]
df_word.rename(columns={"word":"term"}, inplace=True)
df_word

               term  frequency
0               bir   18835735
1            fikret   12101580
2                bu   11062659
3                ne    8025880
4                ve    7766036
...             ...        ...
39995    ekipmanlar        974
39996     şanslılar        974
39997     aksanıyla        974
39998  yargılanacak        974
39999     tepkisini        974

[40000 rows x 2 columns]

In [12]:
df_master_unique_word_merge = pd.merge(df_word,df_master_unique, how="inner", on="term")
df_master_unique_word_merge.sort_values(by="frequency", inplace=True, ascending=False)
df_master_unique_word_merge.reset_index(drop=True, inplace=True)
df_master_unique_word_merge

         term  frequency
0     kontrol     272328
1       polis     247969
2     telefon     134485
3      kaptan     112895
4      numara      85695
..        ...        ...
218      klip       1072
219   fırıncı       1058
220  patlıcan       1016
221      düet        994
222  versiyon        984

[223 rows x 2 columns]

In [13]:
df_master_unique_word_merge = df_master_unique_word_merge.loc[:,["term"]]
df_master_unique_word_merge.rename(columns={"term":f"{lang_1.lower()}_word"}, inplace=True)
df_master_unique_word_merge

    turkish_word
0        kontrol
1          polis
2        telefon
3         kaptan
4         numara
..           ...
218         klip
219      fırıncı
220     patlıcan
221         düet
222     versiyon

[223 rows x 1 columns]

In [15]:
df_master_unique_word_merge.to_excel(f"{lang_1.capitalize()}_Unique_Word_From_{lang_2.capitalize()}_Etymology.xlsx", index=False)

#### Read Translate File

In [16]:
df_pair_translate = pd.read_excel(f"{lang_1.capitalize()} {lang_2.capitalize()} Language Pair Translate.xlsx")
df_pair_translate[f"{lang_2.lower()}_word"] = df_pair_translate[f"{lang_2.lower()}_word"].apply(lambda x: x.lower())
df_pair_translate

    turkish_word      italian_word
0        kontrol         controllo
1          polis  polizia stradale
2        telefon          telefono
3         kaptan          capitano
4         numara            numero
..           ...               ...
218         klip              clip
219      fırıncı        panettiere
220     patlıcan         melanzana
221         düet            duetto
222     versiyon          versione

[223 rows x 2 columns]

In [17]:
df_sleeve_unique = pd.DataFrame()
df_sleeve_unique["term_sleeve"] = df_ety_concat["term_sleeve"].unique()
df_sleeve_unique.rename(columns={"term_sleeve":f"{lang_2.lower()}_word"}, inplace=True)
df_sleeve_unique[f"{lang_2.lower()}_word"] = df_sleeve_unique[f"{lang_2.lower()}_word"].apply(lambda x: x.lower())
df_sleeve_unique.drop_duplicates(inplace=True)
df_sleeve_unique.reset_index(drop=True, inplace=True)
df_sleeve_unique

    italian_word
0     parolaccia
1       parolina
2       parabola
3         parola
4    paraboloide
..           ...
895       poggia
896     poggiare
897       signor
898     cassiere
899     bilancio

[900 rows x 1 columns]

In [18]:
df_translate_sleeve_merge = pd.merge(df_pair_translate,df_sleeve_unique,how="inner",on=f"{lang_2.lower()}_word")
df_translate_sleeve_merge

    turkish_word italian_word
0        kontrol    controllo
1        telefon     telefono
2         numara       numero
3          müzik       musica
4           okul       scuola
..           ...          ...
111      karamel    caramello
112      stadyum       stadio
113         klip         clip
114     patlıcan    melanzana
115         düet       duetto

[116 rows x 2 columns]

In [19]:
df_translate_sleeve_merge.to_excel(f"{lang_1.capitalize()}_{lang_2.capitalize()}_Etymology_Translate_Result.xlsx", index=False)

In [ ]:
from googletrans import Translator

In [ ]:
translator = Translator()

In [ ]:
result = translator.translate('Mitä sinä teet')

In [ ]:
print(googletrans.LANGUAGES)