In [39]:
import pandas as pd
import numpy as np
import glob
import re
import nltk
from nltk import word_tokenize

In [67]:
df_clean = pd.read_csv("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Data/All/etymology_clean.csv")
df_clean = df_clean.head(150000)
df_clean

,lang,term,reltype,related_lang,related_term
0,English,thesaurus,borrowed_from,Latin,thēsaurus
1,English,thesaurus,derived_from,Ancient Greek,θησαυρός
2,English,thesaurus,doublet_with,English,treasure
3,Latin,thesaurus,derived_from,Ancient Greek,θησαυρός
4,English,portmanteau,has_root,Proto-Indo-European,*per- (fare)
...,...,...,...,...,...
149995,English,architect,etymologically_related_to,Ancient Greek,ἀρχι-
149996,English,architect,etymologically_related_to,Ancient Greek,τέκτων
149997,Dutch,architect,borrowed_from,Middle French,architecte
149998,Dutch,architect,derived_from,Latin,architectus
149999,Dutch,architect,derived_from,Ancient Greek,ἀρχιτέκτων

In [58]:
result_list = []
for i in range(len(df_clean)):
    lang_11 = df_clean.loc[i,"lang"]
    term_11 = df_clean.loc[i,"term"]
    reltype_11	= df_clean.loc[i,"reltype"]
    lang_12 = df_clean.loc[i,"related_lang"]
    term_12 = df_clean.loc[i,"related_term"]
    
    try:
        df_var = df_clean[(df_clean["term"] == f"{term_12}")]
        df_var.reset_index(drop=True, inplace=True)
        j = 0
        while j < len(df_var):                    
            lang_21 = df_var.loc[j,"lang"]
            term_21 = df_var.loc[j,"term"]
            #reltype_21	= df_var.loc[j,"reltype"]
            lang_22 = df_var.loc[j,"related_lang"]
            term_22 = df_var.loc[j,"related_term"]
            if ((f"{lang_21}" == f"{lang_12}") & (f"{term_21}" == f"{term_12}")):
                #lang_12 = lang_22
                #term_12 = term_22
                #result_list.append([lang_11,term_11,reltype_11,lang_12,term_12])
                result_list.append([lang_11,term_11,reltype_11,lang_22,term_22])
            else:
                #lang_12 = lang_12
                #term_12 = term_12
                result_list.append([lang_11,term_11,reltype_11,lang_12,term_12])
            
            j+=1
    except:
        result_list.append([lang_11,term_11,reltype_11,lang_12,term_12])

In [65]:
result_list = []
for i in range(len(df_clean)):
    lang_11 = df_clean.loc[i,"lang"]
    term_11 = df_clean.loc[i,"term"]
    reltype_11	= df_clean.loc[i,"reltype"]
    lang_12 = df_clean.loc[i,"related_lang"]
    term_12 = df_clean.loc[i,"related_term"]
    
    
    df_var = df_clean[(df_clean["term"] == f"{term_12}")]
    df_var.reset_index(drop=True, inplace=True)
    j = 0
    while j < len(df_var):                    
        lang_21 = df_var.loc[j,"lang"]
        term_21 = df_var.loc[j,"term"]
        #reltype_21	= df_var.loc[j,"reltype"]
        lang_22 = df_var.loc[j,"related_lang"]
        term_22 = df_var.loc[j,"related_term"]
        if ((f"{lang_21}" == f"{lang_12}") & (f"{term_21}" == f"{term_12}")):
            #lang_12 = lang_22
            #term_12 = term_22
            #result_list.append([lang_11,term_11,reltype_11,lang_12,term_12])
            result_list.append([lang_11,term_11,reltype_11,lang_22,term_22])
        else:
            #lang_12 = lang_12
            #term_12 = term_12
            result_list.append([lang_11,term_11,reltype_11,lang_12,term_12])
        
        j+=1

In [66]:
df_test = pd.DataFrame(result_list, columns=["lang","term","reltype","related_lang","related_term"])
df_test

            lang       term       reltype    related_lang related_term
0        English  thesaurus  doublet_with  Middle English      tresour
1        English  thesaurus  doublet_with      Old French       tresor
2        English  thesaurus  doublet_with           Latin    thēsaurus
3        English  thesaurus  doublet_with   Ancient Greek     θησαυρός
4        English  thesaurus  doublet_with  Middle English        schat
...          ...        ...           ...             ...          ...
1143700  English   wordbook    cognate_of          Danish          ord
1143701  English   wordbook    cognate_of          Danish          bog
1143702  English   wordbook    cognate_of         Swedish       ordbok
1143703  English   wordbook    cognate_of         English     wordbook
1143704  English   wordbook    cognate_of          German   Wörterbuch

[1143705 rows x 5 columns]

In [56]:
df_var2 = df_test[(df_test["term"] == "chat")]
df_var2

,lang,term,reltype,related_lang,related_term
32718,English,chat,etymologically_related_to,English,chatter
32719,English,chat,etymologically_related_to,English,chit
32720,English,chat,etymologically_related_to,English,chad
32721,Antillean Creole,chat,derived_from,French,chat
32722,Dutch,chat,borrowed_from,English,chat
32723,French,chat,inherited_from,Middle French,chat
32724,French,chat,inherited_from,Old French,chat
32725,French,chat,inherited_from,Late Latin,cattus
32726,French,chat,borrowed_from,English,chat
32727,Iban,chat,derived_from,Min Nan,漆
32728,Italian,chat,borrowed_from,English,chat
32729,Middle French,chat,inherited_from,Old French,chat
32730,Middle French,chat,inherited_from,Late Latin,cattus
32731,Norwegian Nynorsk,chat,borrowed_from,English,chat
32732,Old French,chat,inherited_from,Late Latin,cattus
32733,Portuguese,chat,borrowed_from,English,chat
32734,Spanish,chat,borrowed_from,English,chat
32735,Tagalog,chat,borrowed_from,English,chat

In [ ]:
df_var2 = df_test[(df_test["related_term"] == "chat")]
df_var2

In [61]:
term_11 = df_clean.loc[15,"term"]
term_11

'encyclopaedia'

In [63]:
df_var2 = df_test[(df_test["related_term"] == f"{term_11}")]
df_var2

,lang,term,reltype,related_lang,related_term
9,English,encyclopedia,borrowed_from,New Latin,encyclopaedia
53004,Indonesian,ensiklopedia,learned_borrowing_from,New Latin,encyclopaedia
53009,Malay,ensiklopedia,learned_borrowing_from,New Latin,encyclopaedia

In [ ]:
lang_11 = df_clean.loc[i,"lang"]
term_11 = df_clean.loc[i,"term"]
reltype_11	= df_clean.loc[i,"reltype"]
lang_12 = df_clean.loc[i,"related_lang"]
term_12 = df_clean.loc[i,"related_term"]

In [51]:
df_var = df_clean[(df_clean["term"] == "chat")]
df_var

,lang,term,reltype,related_lang,related_term
32718,English,chat,etymologically_related_to,English,chatter
32719,English,chat,etymologically_related_to,English,chit
32720,English,chat,etymologically_related_to,English,chad
32721,Antillean Creole,chat,derived_from,French,chat
32722,Dutch,chat,borrowed_from,English,chat
32723,French,chat,inherited_from,Middle French,chat
32724,French,chat,inherited_from,Old French,chat
32725,French,chat,inherited_from,Late Latin,cattus
32726,French,chat,borrowed_from,English,chat
32727,Iban,chat,derived_from,Min Nan,漆
32728,Italian,chat,borrowed_from,English,chat
32729,Middle French,chat,inherited_from,Old French,chat
32730,Middle French,chat,inherited_from,Late Latin,cattus
32731,Norwegian Nynorsk,chat,borrowed_from,English,chat
32732,Old French,chat,inherited_from,Late Latin,cattus
32733,Portuguese,chat,borrowed_from,English,chat
32734,Spanish,chat,borrowed_from,English,chat
32735,Tagalog,chat,borrowed_from,English,chat

In [52]:
df_var = df_clean[(df_clean["related_term"] == "chat")]
df_var

,lang,term,reltype,related_lang,related_term
128,English,cat,cognate_of,French,chat
167,Norman,cat,inherited_from,Old French,chat
32721,Antillean Creole,chat,derived_from,French,chat
32722,Dutch,chat,borrowed_from,English,chat
32723,French,chat,inherited_from,Middle French,chat
32724,French,chat,inherited_from,Old French,chat
32726,French,chat,borrowed_from,English,chat
32728,Italian,chat,borrowed_from,English,chat
32729,Middle French,chat,inherited_from,Old French,chat
32731,Norwegian Nynorsk,chat,borrowed_from,English,chat
32733,Portuguese,chat,borrowed_from,English,chat
32734,Spanish,chat,borrowed_from,English,chat
32735,Tagalog,chat,borrowed_from,English,chat
43831,Mauritian Creole,sat,derived_from,French,chat
43847,Seychellois Creole,sat,derived_from,French,chat
107112,English,kitten,etymologically_related_to,Old French,chat
135860,Spanish,gato,cognate_of,French,chat

In [28]:
df_var = df_clean[(df_clean["term"] == "abacus")]
df_var.reset_index(drop=True, inplace=True)
df_var

,lang,term,reltype,related_lang,related_term
0,English,abacus,inherited_from,Middle English,abacus
1,English,abacus,etymologically_related_to,Middle English,abagus
2,English,abacus,etymologically_related_to,Middle English,agabus
3,English,abacus,derived_from,Latin,abacus
4,English,abacus,etymologically_related_to,Latin,abax
5,English,abacus,cognate_of,Late Latin,abacus
6,English,abacus,derived_from,Ancient Greek,ἄβαξ
7,English,abacus,cognate_of,Hebrew,אבק
8,English,abacus,cognate_of,Phoenician,-𐤀‬𐤁𐤀‬𐤒
9,English,abacus,cognate_of,Catalan,àbac
10,English,abacus,cognate_of,Old French,abac
11,English,abacus,cognate_of,Middle French,abaque
12,English,abacus,cognate_of,French,abaque
13,English,abacus,cognate_of,Italian,abaco
14,English,abacus,cognate_of,Portuguese,ábaco
15,English,abacus,cognate_of,Spanish,ábaco
16,English,abacus,doublet_with,English,abaque
17,English,abacus,etymologically_related_to,English,abaci
18,English,abacus,derived_from,Latin,abacī
19,Dutch,abacus,borrowed_from,Latin,abacus
20,Dutch,abacus,derived_from,Ancient Greek,ἄβαξ
21,Latin,abacus,derived_from,Ancient Greek,ἄβαξ
22,Middle English,abacus,derived_from,Latin,abacus
23,Middle English,abacus,derived_from,Ancient Greek,ἄβαξ

In [22]:
df_var.loc[1724,"lang"]

'Middle English'

In [ ]:
j = 0
while j < range(len(df_var)):                    
    lang_21 = df_var.loc[j,"lang"]
    term_21 = df_var.loc[j,"term"]
    #reltype_21	= df_var.loc[j,"reltype"]
    lang_22 = df_var.loc[j,"related_lang"]
    term_22 = df_var.loc[j,"related_term"]
    if (lang_21 == lang_12) & (term_21 == term_12):
        lang_12 = lang_22
        term_12 = term_22
        result_list.append([lang_11,term_11,reltype_11,lang_12,term_12])
    else:
        lang_12 = lang_12
        term_12 = term_12
        result_list.append([lang_11,term_11,reltype_11,lang_12,term_12])
    
    j+=1