### Etymology Cross Check

In [67]:
import pandas as pd
import numpy as np
import glob
import re
import nltk
from nltk import word_tokenize

#### Etymologeek Result

In [68]:
lang_1 = "Turkish"  # English, Turkish, German, French, Spanish, Arabic, Russian, Portuguese, Dutch, Italian 
lang_2 = "English"  # English, Turkish, German, French, Spanish, Arabic, Russian, Portuguese, Dutch, Italian
if lang_2 == "English":
    lang_3 = "English (eng)"
elif lang_2 == "Turkish":
    lang_3 = "Turkish (tur)"
elif lang_2 == "German":
    lang_3 = "German (deu)"
elif lang_2 == "French":
    lang_3 = "French (fra)"
elif lang_2 == "Spanish":
    lang_3 = "Spanish (spa)"
elif lang_2 == "Arabic":
    lang_3 = "Arabic (ara)"
elif lang_2 == "Russian":
    lang_3 = "Russian (rus)"
elif lang_2 == "Portuguese":
    lang_3 = "Portuguese (por)"
elif lang_2 == "Dutch":
    lang_3 = "Dutch (nld)"
elif lang_2 == "Italian":
    lang_3 = "Italian (ita)"
else:
    pass
#lang_3 = "English (eng)"  # English (eng), Turkish (tur), German (deu), French (fra), Spanish (spa), Arabic (ara), Russian (rus), 
                          # Portuguese (por), Dutch (nld), Italian (ita)
print(f"{lang_1}\n{lang_2}\n{lang_3}")

Turkish
English
English (eng)

In [69]:
lang_1_file = glob.glob(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/*/{lang_1.capitalize()}_And_*_Etymologeek_Result1.xlsx")
lang_1_file

['/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Turkish/Turkish_And_Dutch (nld)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Turkish/Turkish_And_Arabic (ara)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Turkish/Turkish_And_English (eng)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Turkish/Turkish_And_French (fra)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Turkish/Turkish_And_Italian (ita)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Turkish/Turkish_And_Portuguese (por)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Turkish/Turkish_And_Spanish (spa)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Turkish/Turkish_And_German (deu)_Etymologeek_Result1.xlsx']

In [70]:
df_lang_1 = pd.DataFrame()
for i in lang_1_file:
    df_var = pd.read_excel(f"{i}")
    df_lang_1 = pd.concat([df_lang_1,df_var], axis=0)
    df_lang_1.reset_index(drop=True, inplace=True)
df_lang_1

,search_word,dict_entry_main,language_main,definition_main,dict_entry,language,definition
0,şans,şans,Turkish,(Noun) Fortune. Luck.Fortune. Luck.,dice,Dutch (nld),NaN
1,loca,loca,Turkish,(Noun) (masonic) lodge. Box (in theaters).(mas...,laubja,Dutch (nld),NaN
2,mı,mıknatıs,Turkish,(Noun) Magnet.Magnet.,مِغْنَاطِيس,Arabic (ara),NaN
3,mı,mısdak,Turkish,(Noun) (obsolete) criterion.(obsolete) criterion.,مِصْدَاق,Arabic (ara),NaN
4,şey,şey,Turkish,(Noun Interjection) (slang) genital organ. Thi...,شَيْئاً,Arabic (ara),NaN
...,...,...,...,...,...,...,...
732,vermut,vermut,Turkish,(Noun),wermut,German (deu),"Vermouth is an aromatized fortified wine, flav..."
733,panzer,panzer,Turkish,(Noun),panzer,German (deu),A tank is an armoured fighting vehicle intende...
734,tonymayster,tonymayster,Turkish,(Noun),tonmeister,German (deu),Tonmeister
735,filinta,filinta,Turkish,(Noun),flinte,German (deu),Flinte
736,kuvars,kuvars,Turkish,(Noun),quarz,German (deu),"Quartz is a hard, crystalline mineral composed..."

In [71]:
lang_2_file = glob.glob(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/*/{lang_2.capitalize()}_And_*_Etymologeek_Result1.xlsx")
lang_2_file

['/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/English/English_And_Arabic (ara)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/English/English_And_Dutch (nld)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/English/English_And_French (fra)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/English/English_And_German (deu)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/English/English_And_Italian (ita)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/English/English_And_Portuguese (por)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/English/English_And_Russian (rus)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/English/English_And_Spanish (spa)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/English/English_And_Turkish (tur)_Etymologeek_Result1.xlsx']

In [72]:
df_lang_2 = pd.DataFrame()
for i in lang_2_file:
    df_var2 = pd.read_excel(f"{i}")
    df_lang_2 = pd.concat([df_lang_2,df_var2], axis=0)
    df_lang_2.reset_index(drop=True, inplace=True)
df_lang_2

,search_word,dict_entry_main,language_main,definition_main,dict_entry,language,definition
0,aman,amanaty,English,(Noun) (historical) Native American hostages t...,أَمَانَة,Arabic (ara),NaN
1,sakin,sakina,English,(Noun) (Islam) the divine tranquility obtained...,سَكِينَة,Arabic (ara),NaN
2,cevap,cevapi,English,(Noun) A Balkan food dish of minced meat.A Bal...,كَبَاب,Arabic (ara),NaN
3,hale,haleem,English,(Noun) A stew-like dish traditionally consisti...,حَلِيم,Arabic (ara),NaN
4,dua,dua,English,(Noun) (Islam) An Islamic invocation.(Islam) A...,دَعَا,Arabic (ara),NaN
...,...,...,...,...,...,...,...
3033,marta,martagon,English,(Noun) A Eurasian lily.A Eurasian lily.,martagan,Turkish (tur),NaN
3034,lahm,lahmacun,English,(Noun) A dish of Arab origin consisting of a r...,lahmacun,Turkish (tur),Lahmacun.
3035,caza,caza,English,(Noun) A Turkish provincial subdivision.A Turk...,kaza,Turkish (tur),Accident.
3036,chagrin,chagrin,English,(Verb Noun) (intransitive) To be vexed or anno...,sağrı,Turkish (tur),The chubby and round part of a mammal's body b...
3037,gilet,gilet,English,(Noun) A sleeveless jacket similar to a waistc...,yelek,Turkish (tur),"Jelick. Waistcoat, vest."

In [73]:
set_lang_11 = set(df_lang_1["dict_entry"])

In [74]:
set_lang_12 = set(df_lang_2["dict_entry"])

In [75]:
df_cross = pd.DataFrame(set_lang_11.intersection(set_lang_12), columns=["dict_entry"])
df_cross

     dict_entry
0        avocat
1    maquillage
2         poser
3         super
4      clinique
..          ...
114    saucisse
115      قَضَاء
116  bicyclette
117     amateur
118       salon

[119 rows x 1 columns]

In [76]:
df_lang_1_cross = pd.merge(df_cross,df_lang_1,how="inner", on="dict_entry")
df_lang_1_cross.drop_duplicates(inplace=True)
df_lang_1_cross = df_lang_1_cross[["language_main","dict_entry_main","dict_entry"]]
df_lang_1_cross.rename(columns={"language_main":"lang_master","dict_entry_main":"term_master"}, inplace=True)
df_lang_1_cross

    lang_master term_master  dict_entry
0       Turkish      avukat      avocat
1       Turkish      makyaj  maquillage
2       Turkish        depo       poser
3       Turkish       süper       super
4       Turkish      klinik    clinique
..          ...         ...         ...
123     Turkish       sosis    saucisse
124     Turkish        kaza      قَضَاء
125     Turkish    bisiklet  bicyclette
126     Turkish      amatör     amateur
127     Turkish       salon       salon

[128 rows x 3 columns]

In [77]:
df_lang_2_cross = pd.merge(df_cross,df_lang_2,how="inner", on="dict_entry")
df_lang_2_cross.drop_duplicates(inplace=True)
df_lang_2_cross = df_lang_2_cross[["language_main","dict_entry_main","dict_entry"]]
df_lang_2_cross.rename(columns={"language_main":"lang_sleeve","dict_entry_main":"term_sleeve"}, inplace=True)
df_lang_2_cross

    lang_sleeve   term_sleeve  dict_entry
0       English        avocat      avocat
1       English    maquillage  maquillage
2       English       deposit       poser
3       English        expose       poser
4       English   proposition       poser
..          ...           ...         ...
172     English      saucisse    saucisse
173     English          caza      قَضَاء
174     English  town bicycle  bicyclette
175     English       amateur     amateur
176     English         salon       salon

[177 rows x 3 columns]

In [78]:
df_lang_1_lang_2_cross = pd.merge(df_lang_1_cross,df_lang_2_cross, how="inner", on="dict_entry")
df_lang_1_lang_2_cross.drop_duplicates(inplace=True)
df_lang_1_lang_2_cross = df_lang_1_lang_2_cross[["lang_master","term_master","lang_sleeve","term_sleeve"]]
df_lang_1_lang_2_cross

    lang_master term_master lang_sleeve   term_sleeve
0       Turkish      avukat     English        avocat
1       Turkish      makyaj     English    maquillage
2       Turkish        depo     English       deposit
3       Turkish        depo     English        expose
4       Turkish        depo     English   proposition
..          ...         ...         ...           ...
189     Turkish       sosis     English      saucisse
190     Turkish        kaza     English          caza
191     Turkish    bisiklet     English  town bicycle
192     Turkish      amatör     English       amateur
193     Turkish       salon     English         salon

[189 rows x 4 columns]

In [79]:
lang_3_file = glob.glob(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/*/*_And_{lang_3.capitalize()}_Etymologeek_Result1.xlsx")
lang_3_file

['/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Turkish/Turkish_And_English (eng)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/German/German_And_English (eng)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/French/French_And_English (eng)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Spanish/Spanish_And_English (eng)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Arabic/Arabic_And_English (eng)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Russian/Russian_And_English (eng)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Portuguese/Portuguese_And_English (eng)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Dutch/Dutch_And_English (eng)_Etymologeek_Result1.xlsx',
 '/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/Italian/Italian_And_English (eng)_Etymologeek_Result1.xlsx']

In [80]:
df_lang_3 = pd.DataFrame()
for i in lang_3_file:
    df_var3 = pd.read_excel(f"{i}")
    df_lang_3 = pd.concat([df_lang_3,df_var3], axis=0)
    df_lang_3.reset_index(drop=True, inplace=True)
df_lang_3

,search_word,dict_entry_main,language_main,definition_main,dict_entry,language,definition
0,şu,şut,Turkish,(Noun) (football) shoot.(football) shoot.,shoot,English (eng),(mining) A vein of ore running in the same gen...
1,alo,alo,Turkish,(Interjection) Hello (only when picking up the...,heaven,English (eng),"(Christianity, Islam) The afterlife of the sou..."
2,tür,türban,Turkish,(Noun) Turban (man’s and women’s head-dress).T...,turban,English (eng),A man's headdress made by winding a length of ...
3,çek,çek,Turkish,"(Noun) Check, cheque.Check, cheque.",cheque,English (eng),"(Australia, Canada, India, New Zealand, UK) A ..."
4,film,film,Turkish,(Noun) A medium used to capture images in a ca...,film,English (eng),"(cinema, uncountable) Film or movies as a grou..."
...,...,...,...,...,...,...,...
1543,sanguigno,sanguigno,Italian,(Adjective) Blood (attributive). Hot-tempered....,blood,English (eng),(historical) One of the four humours in the hu...
1544,brunch,brunch,Italian,(Noun) Brunch.Brunch.,brunch,English (eng),A meal eaten later in the day than breakfast a...
1545,elezione,elezione,Italian,(Noun) Choice. Election.Choice. Election.,choosy,English (eng),Taking care when choosing that what is chosen ...
1546,salsiccia,salsiccia,Italian,(Noun) Sausage.Sausage.,salt mine,English (eng),"(by extension) Any laborious work situation, e..."
1547,tribù,tribù,Italian,(Noun) Tribe.Tribe.,three,English (eng),(basketball). A person who is three years old....

In [81]:
set_lang_21 = set(df_lang_1["dict_entry_main"])

In [82]:
set_lang_23 = set(df_lang_3["dict_entry_main"])

In [83]:
df_cross_2 = pd.DataFrame(set_lang_21.intersection(set_lang_23), columns=["dict_entry_main"])
df_cross_2

           dict_entry_main
0                    model
1                      çek
2                   bikini
3                   basket
4                      maç
5                      şov
6                basketbol
7                     test
8                 festival
9                destroyer
10                 sandviç
11                  kovboy
12                  salata
13                   papel
14                 dijital
15                    jüri
16                     şut
17                   radyo
18                    boks
19                   taksi
20                     alo
21                romantik
22                    film
23  bağımlılık enjeksiyonu
24                     dok
25                  futbol
26                striptiz
27                     kek
28                     gey
29                     sos
30                   viski
31               biftekkek
32                 beyzbol
33                  pijama
34               hamburger
35                   seksi
36                     gül
37                    site
38                  türban
39                   lider
40                  biftek
41                    vals
42               fransiyum
43                   sosis
44                   tenis
45                    lord
46                     kok

In [84]:
df_lang_1_lang_3_cross = pd.merge(df_cross_2,df_lang_3,how="inner", on="dict_entry_main")
df_lang_1_lang_3_cross.drop_duplicates(inplace=True)
df_lang_1_lang_3_cross = df_lang_1_lang_3_cross[["language_main","dict_entry_main","language","dict_entry"]]
df_lang_1_lang_3_cross.rename(columns={"language_main":"lang_master","dict_entry_main":"term_master","language":"lang_sleeve","dict_entry":"term_sleeve"}, inplace=True)
df_lang_1_lang_3_cross

   lang_master term_master    lang_sleeve term_sleeve
0      Spanish       model  English (eng)        mode
1      Turkish         çek  English (eng)      cheque
2      Turkish      bikini  English (eng)      Bikini
3       French      bikini  English (eng)      Bikini
4      Spanish      bikini  English (eng)      Bikini
..         ...         ...            ...         ...
57     Turkish       tenis  English (eng)      tennis
58     Turkish        lord  English (eng)        lord
59     Spanish        lord  English (eng)        lord
60     Italian        lord  English (eng)        lord
61     Turkish         kok  English (eng)     cocaine

[62 rows x 4 columns]

In [85]:
df_lang_1_lang_2_lang_3 = pd.concat([df_lang_1_lang_2_cross,df_lang_1_lang_3_cross], axis=0)
df_lang_1_lang_2_lang_3.reset_index(drop=True, inplace=True)
df_lang_1_lang_2_lang_3["term_master"] = df_lang_1_lang_2_lang_3["term_master"].apply(lambda x: x.lower())
df_lang_1_lang_2_lang_3["term_sleeve"] = df_lang_1_lang_2_lang_3["term_sleeve"].apply(lambda x: x.lower())
df_lang_1_lang_2_lang_3

    lang_master term_master    lang_sleeve  term_sleeve
0       Turkish      avukat        English       avocat
1       Turkish      makyaj        English   maquillage
2       Turkish        depo        English      deposit
3       Turkish        depo        English       expose
4       Turkish        depo        English  proposition
..          ...         ...            ...          ...
246     Turkish       tenis  English (eng)       tennis
247     Turkish        lord  English (eng)         lord
248     Spanish        lord  English (eng)         lord
249     Italian        lord  English (eng)         lord
250     Turkish         kok  English (eng)      cocaine

[251 rows x 4 columns]

In [86]:
#df_word = pd.read_excel(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/{lang_2.capitalize()}/Result/Word/Merge/Word_Merge2.xlsx")
#df_word = df_word.head(40000)
#df_word = df_word.loc[:,["word"]]
#df_word.rename(columns={"word":"term_sleeve"}, inplace=True)
#df_word

In [87]:
#df_lang_1_lang_2_lang_3 = pd.merge(df_lang_1_lang_2_lang_3,df_word, how="inner", on="term_sleeve")
#df_lang_1_lang_2_lang_3

In [88]:
df_lang_1_lang_2_lang_3.to_excel(f"{lang_1.capitalize()}_And_{lang_3.capitalize()}_Etymologeek_Result5.xlsx", index=False)