In [1]:
import pandas as pd
import numpy as np
import glob
import re
import nltk
from nltk import word_tokenize

In [24]:
df_clean = pd.read_csv("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Data/All/etymology_clean.csv")
#df_clean = df_clean.head(150000)
df_clean

,lang,term,reltype,related_lang,related_term
0,English,thesaurus,borrowed_from,Latin,thēsaurus
1,English,thesaurus,derived_from,Ancient Greek,θησαυρός
2,English,thesaurus,doublet_with,English,treasure
3,Latin,thesaurus,derived_from,Ancient Greek,θησαυρός
4,English,portmanteau,has_root,Proto-Indo-European,*per- (fare)
...,...,...,...,...,...
3484911,English,Boell,borrowed_from,Danish,Bøll
3484912,English,Boell,borrowed_from,German,Böll
3484913,South Levantine Arabic,بالمية,has_affix,South Levantine Arabic,بـ
3484914,South Levantine Arabic,بالمية,has_affix,South Levantine Arabic,الميّة
3484915,English,Cooler,derived_from,German,Kühler

In [25]:
df_clean["lang"] = df_clean["lang"].apply(lambda x: x.capitalize())
df_clean["lang"] = df_clean["lang"].apply(lambda x: x.strip())
df_clean["term"] = df_clean["term"].apply(lambda x: x.lower())
df_clean["term"] = df_clean["term"].apply(lambda x: x.strip())
df_clean["related_lang"] = df_clean["related_lang"].apply(lambda x: x.capitalize())
df_clean["related_lang"] = df_clean["related_lang"].apply(lambda x: x.strip())
df_clean["related_term"] = df_clean["related_term"].apply(lambda x: x.lower())
df_clean["related_term"] = df_clean["related_term"].apply(lambda x: x.strip())

In [26]:
lang_1 = "Turkish"  # English, Turkish, German, French, Spanish, Arabic, Russian, Portuguese, Dutch, Italian
lang_2 = "Portuguese"  # English, Turkish, German, French, Spanish, Arabic, Russian, Portuguese, Dutch, Italian

In [27]:
df_lang_pair = df_clean[(df_clean["lang"] == f"{lang_1.capitalize()}") & (df_clean["related_lang"] == f"{lang_2.capitalize()}")]
df_lang_pair

            lang      term        reltype related_lang related_term
154597   Turkish     kobra  borrowed_from   Portuguese        cobra
224989   Turkish    ananas   derived_from   Portuguese       ananás
259603   Turkish     japon   derived_from   Portuguese        japão
1174281  Turkish  kapibara   derived_from   Portuguese     capivara

In [28]:
df_lang_pair = df_lang_pair.drop_duplicates(subset="term")
df_lang_pair.reset_index(drop=True, inplace=True)
df_lang_pair

      lang      term        reltype related_lang related_term
0  Turkish     kobra  borrowed_from   Portuguese        cobra
1  Turkish    ananas   derived_from   Portuguese       ananás
2  Turkish     japon   derived_from   Portuguese        japão
3  Turkish  kapibara   derived_from   Portuguese     capivara

In [29]:
df_lang_pair.to_excel(f"{lang_1.capitalize()}_And_{lang_2.capitalize()}_Etymologeek_Result_Test.xlsx", index=False)

#### Compare Result

In [30]:
df_github_cross_result = pd.read_excel(f"{lang_1.capitalize()}_And_{lang_2.capitalize()}_Etymologeek_Result2.xlsx")
df_github_cross_result

       lang          term related_lang related_term
0   Turkish        kambur   Portuguese      cambiar
1   Turkish      portakal   Portuguese     portugal
2   Turkish         piyon   Portuguese         peão
3   Turkish        ananas   Portuguese       ananás
4   Turkish          port   Portuguese        porto
5   Turkish         japon   Portuguese        japão
6   Turkish       japonca   Portuguese        japão
7   Turkish       bisküvi   Portuguese     biscoito
8   Turkish       almanya   Portuguese     alemanha
9   Turkish      şampanya   Portuguese     campanha
10  Turkish          plaj   Portuguese        praia
11  Turkish         banka   Portuguese        banco
12  Turkish         tente   Portuguese        tenda
13  Turkish         fetiş   Portuguese      feitiço
14  Turkish        tayfun   Portuguese        tufão
15  Turkish         yarın   Portuguese        manhã
16  Turkish       kaşalot   Portuguese    cachalote
17  Turkish  japon balığı   Portuguese        japão
18  Turkish     mandalina   Portuguese     mandarim
19  Turkish      karamela   Portuguese     caramelo
20  Turkish       karamel   Portuguese     caramelo
21  Turkish      marmelat   Portuguese    marmelada
22  Turkish          şato   Portuguese      castelo
23  Turkish          jöle   Portuguese        geada
24  Turkish  akselerasyon   Portuguese   aceleração
25  Turkish     i̇spanyol   Portuguese     espanhol
26  Turkish       komando   Portuguese      comando
27  Turkish      kampanya   Portuguese     campanha
28  Turkish          staj   Portuguese      estágio
29  Turkish        peyzaj   Portuguese     paisagem
30  Turkish     bocalamak   Portuguese        pojar
31  Turkish       bandıra   Portuguese     bandeira

In [31]:
df_github_clean_result = pd.read_excel(f"{lang_1.capitalize()}_And_{lang_2.capitalize()}_Etymologeek_Result_Test.xlsx")
df_github_clean_result

      lang      term        reltype related_lang related_term
0  Turkish     kobra  borrowed_from   Portuguese        cobra
1  Turkish    ananas   derived_from   Portuguese       ananás
2  Turkish     japon   derived_from   Portuguese        japão
3  Turkish  kapibara   derived_from   Portuguese     capivara

In [32]:
set_github_cross = set(df_github_cross_result["term"])

In [33]:
set_github_clean = set(df_github_clean_result["term"])

In [34]:
len(set_github_cross.difference(set_github_clean))

30

In [47]:
set_github_clean.difference(set_github_cross)

{'kapibara', 'kobra'}

In [35]:
len(set_github_clean.difference(set_github_cross))

2

In [36]:
len(set_github_clean.union(set_github_cross))

34

In [53]:
pd.DataFrame(set_github_clean.union(set_github_cross), columns=["df_cross"])

        df_cross
0          kobra
1       karamela
2           plaj
3      bocalamak
4        komando
5       şampanya
6       kapibara
7        japonca
8        kaşalot
9        almanya
10       bisküvi
11         banka
12         yarın
13          port
14        tayfun
15      portakal
16          jöle
17  japon balığı
18  akselerasyon
19      marmelat
20         japon
21         fetiş
22       karamel
23      kampanya
24          staj
25        kambur
26       bandıra
27         piyon
28          şato
29     mandalina
30        ananas
31        peyzaj
32     i̇spanyol
33         tente

In [38]:
df_lang = df_clean[(df_clean["lang"] == f"{lang_1.capitalize()}")]
df_lang

,lang,term,reltype,related_lang,related_term
1651,Turkish,ab,has_root,Proto-indo-european,*h₂ep-
1652,Turkish,ab,inherited_from,Ottoman turkish,آب
1653,Turkish,ab,derived_from,Persian,آب
2080,Turkish,abdest,has_root,Proto-indo-european,*h₂ep-
2081,Turkish,abdest,has_root,Proto-indo-european,*ǵʰes-
...,...,...,...,...,...
3484459,Turkish,münakalat,inherited_from,Ottoman turkish,مناقلات
3484460,Turkish,münakalat,etymologically_related_to,Ottoman turkish,مناقله
3484461,Turkish,münakalat,derived_from,Arabic,مُنَاقَلَة‎
3484462,Turkish,münakalat,has_root,Arabic,ن ق ل
3484706,Turkish,sızı,inherited_from,Ottoman turkish,صیزی

In [39]:
df_related_lang = df_clean[(df_clean["related_lang"] == f"{lang_2.capitalize()}")]
df_related_lang

,lang,term,reltype,related_lang,related_term
131,English,cat,cognate_of,Portuguese,gato
1055,Galician,trade,cognate_of,Portuguese,trado
1570,English,abada,borrowed_from,Portuguese,abada
1577,Italian,abada,borrowed_from,Portuguese,abada
1578,Italian,abada,etymologically_related_to,Portuguese,
...,...,...,...,...,...
3483875,Portuguese,laborador,doublet_with,Portuguese,lavrador
3483876,Portuguese,laborador,doublet_with,Portuguese,labrador
3483878,Portuguese,verecúndia,doublet_with,Portuguese,vergonha
3483879,Portuguese,verecúndia,doublet_with,Portuguese,vergonça
3484699,Esperanto,penalo,cognate_of,Portuguese,penalidade

In [43]:
set_lang = set(df_lang["term"])

In [44]:
set_related_lang = set(df_related_lang["term"])

In [45]:
set_lang.intersection(set_related_lang)

{'-er',
 'aba',
 'abril',
 'aga',
 'agora',
 'ala',
 'albatros',
 'alma',
 'ama',
 'ananas',
 'ani',
 'anka',
 'asa',
 'aya',
 'aza',
 'bale',
 'bar',
 'baston',
 'ben',
 'bende',
 'bermuda',
 'bibi',
 'bin',
 'bira',
 'bomba',
 'boy',
 'boya',
 'bu',
 'can',
 'cima',
 'cuma',
 'dede',
 'dobra',
 'ego',
 'el',
 'en',
 'fatura',
 'faz',
 'feride',
 'firma',
 'flor',
 'foto',
 'funda',
 'hala',
 'hasta',
 'in',
 'internet',
 'jaguar',
 'japon',
 'kaba',
 'kama',
 'kantin',
 'kanton',
 'kapibara',
 'kasa',
 'katil',
 'kaza',
 'kel',
 'ki',
 'kil',
 'kobra',
 'kuma',
 'kuru',
 'madem',
 'maestro',
 'mal',
 'malta',
 'masa',
 'maça',
 'maço',
 'mor',
 'net',
 'nevi',
 'not',
 'o',
 'ora',
 'ova',
 'palavra',
 'papa',
 'para',
 'parlamento',
 'parti',
 'pas',
 'pasta',
 'pena',
 'pera',
 'peru',
 'pis',
 'plato',
 'polis',
 'port',
 'protesto',
 'risk',
 'sabun',
 'sal',
 'san',
 'sen',
 'ser',
 'sin',
 'sol',
 'som',
 'son',
 'tava',
 'tema',
 'ten',
 'tente',
 'tuna',
 'un',
 'ya',
 'yama',
 'yaya',
 'zebra',
 'zona'}

In [52]:
pd.DataFrame(set_lang.intersection(set_related_lang), columns=["df_clean"])

     df_clean
0      feride
1         som
2        foto
3        bale
4        kasa
..        ...
108   palavra
109      anka
110     sabun
111  albatros
112    ananas

[113 rows x 1 columns]

In [46]:
len(set_lang.intersection(set_related_lang))

113

In [48]:
set_github_cross.intersection(set_lang.intersection(set_related_lang))

{'ananas', 'japon', 'port', 'tente'}

In [49]:
set_github_cross.difference(set_lang.intersection(set_related_lang))

{'akselerasyon',
 'almanya',
 'bandıra',
 'banka',
 'bisküvi',
 'bocalamak',
 'fetiş',
 'i̇spanyol',
 'japon balığı',
 'japonca',
 'jöle',
 'kambur',
 'kampanya',
 'karamel',
 'karamela',
 'kaşalot',
 'komando',
 'mandalina',
 'marmelat',
 'peyzaj',
 'piyon',
 'plaj',
 'portakal',
 'staj',
 'tayfun',
 'yarın',
 'şampanya',
 'şato'}

In [50]:
(set_lang.intersection(set_related_lang)).difference(set_github_cross)

{'-er',
 'aba',
 'abril',
 'aga',
 'agora',
 'ala',
 'albatros',
 'alma',
 'ama',
 'ani',
 'anka',
 'asa',
 'aya',
 'aza',
 'bale',
 'bar',
 'baston',
 'ben',
 'bende',
 'bermuda',
 'bibi',
 'bin',
 'bira',
 'bomba',
 'boy',
 'boya',
 'bu',
 'can',
 'cima',
 'cuma',
 'dede',
 'dobra',
 'ego',
 'el',
 'en',
 'fatura',
 'faz',
 'feride',
 'firma',
 'flor',
 'foto',
 'funda',
 'hala',
 'hasta',
 'in',
 'internet',
 'jaguar',
 'kaba',
 'kama',
 'kantin',
 'kanton',
 'kapibara',
 'kasa',
 'katil',
 'kaza',
 'kel',
 'ki',
 'kil',
 'kobra',
 'kuma',
 'kuru',
 'madem',
 'maestro',
 'mal',
 'malta',
 'masa',
 'maça',
 'maço',
 'mor',
 'net',
 'nevi',
 'not',
 'o',
 'ora',
 'ova',
 'palavra',
 'papa',
 'para',
 'parlamento',
 'parti',
 'pas',
 'pasta',
 'pena',
 'pera',
 'peru',
 'pis',
 'plato',
 'polis',
 'protesto',
 'risk',
 'sabun',
 'sal',
 'san',
 'sen',
 'ser',
 'sin',
 'sol',
 'som',
 'son',
 'tava',
 'tema',
 'ten',
 'tuna',
 'un',
 'ya',
 'yama',
 'yaya',
 'zebra',
 'zona'}

#### Main Work

In [72]:
df_github_cross = pd.read_csv("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Data/All/etymology_cross_check2.csv")
#df_github_cross = df_github_cross.head(150000)
#df_github_cross = df_github_cross.loc[:,["lang","term","related_lang","related_term"]]
df_github_cross

,term_id,lang,term,reltype,related_term_id,related_lang,related_term
0,LHuH1RvcUjWNUTR6QQF8fg,Spanish,palabra,inherited_from,9w90qvZDUH-2OHPVZEGJSQ,Middle english,parlai
1,LHuH1RvcUjWNUTR6QQF8fg,Spanish,palabra,derived_from,Uy6v5wWuW6KGH4aTqGWnmA,Old french,parler
2,LHuH1RvcUjWNUTR6QQF8fg,Spanish,palabra,derived_from,HY24XyCcUZCYSa1Q6y2kPA,Late latin,parabolō
3,LHuH1RvcUjWNUTR6QQF8fg,Spanish,palabra,derived_from,uXGtk5g-W8G_TlTxSHImpg,Latin,parabola
4,LHuH1RvcUjWNUTR6QQF8fg,Spanish,palabra,derived_from,JHVmHqAPXEq-YaIbd0B5Jg,Ancient greek,παραβολή
...,...,...,...,...,...,...,...
8854119,3q28WGgPWs2K_SSglCAWvQ,Catalan,petitesa,inherited_from,TUnsO83vXXC1Us5rJgGyUg,Vulgar latin,*pittitus
8854120,3q28WGgPWs2K_SSglCAWvQ,Catalan,petitesa,etymologically_related_to,oUnwLLsHVymmwwiRXgrRow,Latin,pitinnus
8854121,3q28WGgPWs2K_SSglCAWvQ,Catalan,petitesa,etymologically_related_to,IGRZaHQ-VU-vpxMjdxSTlA,Latin,pitulus
8854122,3q28WGgPWs2K_SSglCAWvQ,Catalan,petitesa,etymologically_related_to,MDRrWciZWXGEj1KR9MUWtg,Latin,piccinus
8854123,3q28WGgPWs2K_SSglCAWvQ,Catalan,petitesa,cognate_of,SUJISOECWc6fDH00I_cTRQ,French,petit

In [93]:
lang_1 = "Turkish"  # English, Turkish, German, French, Spanish, Arabic, Russian, Portuguese, Dutch, Italian
lang_2 = "English"  # English, Turkish, German, French, Spanish, Arabic, Russian, Portuguese, Dutch, Italian

In [94]:
df_lang1 = df_github_cross[(df_github_cross["lang"] == f"{lang_1.capitalize()}")] 
df_lang1

,term_id,lang,term,reltype,related_term_id,related_lang,related_term
110,caAhC_cAXrKZU9rCcPAaPw,Turkish,göl,inherited_from,T6Wxr8YPVWK47B34DsG6KA,Proto-turkic,*kȫl
817,SC0fKM3-VcGTWvelEkpEXw,Turkish,ön,inherited_from,nlVlgr5dUjas0_4GqplLJQ,Proto-turkic,*ǖn
818,SC0fKM3-VcGTWvelEkpEXw,Turkish,ön,inherited_from,5g1DdR5OUPOxiQxCVcGW6A,Proto-turkic,*öŋ
819,SC0fKM3-VcGTWvelEkpEXw,Turkish,ön,inherited_from,6KC332NQU7Sx9sFKEv6QdQ,Proto-turkic,*oŋ
1345,5bVUD53NVEWYY0QAetV7iA,Turkish,net,inherited_from,Ru1rzGVDWpi2rTYD9-XJWQ,Old french,net
...,...,...,...,...,...,...,...
8853155,nxRVOzFvUzS4X7r165GWcw,Turkish,ordinatör,etymologically_related_to,tPEd3hNNXqeBt17YkY3I2Q,French,calculateur
8853651,pl-cU0pBVda2_BuEjBmtZw,Turkish,virman,has_prefix_with_root,9CJvE6k0WJmKvcWZQmQjxw,French,virer
8853652,pl-cU0pBVda2_BuEjBmtZw,Turkish,virman,has_suffix,8YtrMi5VXlSpZVOupUTcWg,French,ment
8853831,fc8biERQXFicQGtfESBJQQ,Turkish,angajman,has_prefix_with_root,qQY-6sksXJe832mC9wIBqQ,French,engager
8853832,fc8biERQXFicQGtfESBJQQ,Turkish,angajman,has_suffix,8YtrMi5VXlSpZVOupUTcWg,French,ment

In [95]:
df_lang2 = df_github_cross[(df_github_cross["lang"] == f"{lang_2.capitalize()}")]
df_lang2

,term_id,lang,term,reltype,related_term_id,related_lang,related_term
8,9dklyzlWU1GJG2HQTdn2Gw,English,breaker,borrowed_from,5hrBfLYUVKCz_apIVUIeCQ,Occitan,barrique
9,9dklyzlWU1GJG2HQTdn2Gw,English,breaker,derived_from,7k2Vvp3nXLy5CvsTUAGhnA,Old occitan,barrica
10,Sa9PLd8wVye-T_9yUc0DOw,English,unflappable,inherited_from,1s_U6-KHWmiJeKVbA96FWg,Middle english,un-
11,9dklyzlWU1GJG2HQTdn2Gw,English,breaker,derived_from,UJle1K0PXdyx7GycKtbdvQ,Vulgar latin,*barrica
12,Sa9PLd8wVye-T_9yUc0DOw,English,unflappable,inherited_from,tiwBatmsX3aT6yV_bBj4pA,Old english,un-
...,...,...,...,...,...,...,...
8854101,X9TbD7nbViavII1VL_kMCw,English,geotechnique,borrowed_from,l-rKJaTcXL65SH14LLHRgA,French,technique
8854102,X9TbD7nbViavII1VL_kMCw,English,geotechnique,etymologically_related_to,l-rKJaTcXL65SH14LLHRgA,French,technique
8854103,X9TbD7nbViavII1VL_kMCw,English,geotechnique,derived_from,YbyR0LCGX4qfUGCtxMAlNQ,Ancient greek,τεχνικός
8854104,X9TbD7nbViavII1VL_kMCw,English,geotechnique,etymologically_related_to,4bixcB-SUnyHLzonp8WarQ,Ancient greek,τέχνη
8854105,X9TbD7nbViavII1VL_kMCw,English,geotechnique,etymologically_related_to,cwWZ2hLaU1GuMpkyU45wHQ,Ancient greek,τίκτειν

In [96]:
set_lang1 = set(df_lang1["related_term_id"])
set_lang2= set(df_lang2["related_term_id"])

In [97]:
df_root = pd.DataFrame(set_lang1.intersection(set_lang2),columns=["related_term_id"])
df_root

             related_term_id
0     J11Q0WbyVqeZd9PP-Lyp5w
1     Tk3zgRteXFCah8veaVvZ0Q
2     VS8G3aCoWHSQntg1YI3Ueg
3     aJh4Qu1SXaqVmZ560j0qaA
4     IWKVhCumW-WQS_DQNvIKeQ
...                      ...
6573  g3t7tW67V-qWJA3YFUXMQQ
6574  m6F9p4lfXAmxGPDpiPecEA
6575  N0D8XBKVX8W3mgqrFdRdVw
6576  D1eta8DOVOSQT-7B8tveRA
6577  pz9X7OehXFSvQ53dec7KDw

[6578 rows x 1 columns]

In [98]:
df_root_merge = pd.merge(df_github_cross,df_root,how="inner",on="related_term_id")
df_root_merge.drop_duplicates(inplace=True)
df_root_merge

,term_id,lang,term,reltype,related_term_id,related_lang,related_term
0,LHuH1RvcUjWNUTR6QQF8fg,Spanish,palabra,derived_from,uXGtk5g-W8G_TlTxSHImpg,Latin,parabola
1,ljccVuPLVnivw8cc3nNYlQ,Italian,parolaccia,inherited_from,uXGtk5g-W8G_TlTxSHImpg,Latin,parabola
2,FWrE64OiVqyZhvrUCjx-lw,Italian,parolina,inherited_from,uXGtk5g-W8G_TlTxSHImpg,Latin,parabola
3,nna1S--BXFqttVpHavoanQ,Scots,barley,derived_from,uXGtk5g-W8G_TlTxSHImpg,Latin,parabola
4,nEVenuUoViaCv4A9BMUvbg,French,Parole,inherited_from,uXGtk5g-W8G_TlTxSHImpg,Latin,parabola
...,...,...,...,...,...,...,...
776499,cq1pMSwQXLiG-BfsI9kSYQ,English,cyberarsenal,derived_from,8sAvMylPV06vp_knMpEaQA,French,arsenal
776500,ZmAjiw8JUaezZF4CmOgD0A,Turkish,tersane,derived_from,uunt-HERUyi9KbO__wGPZg,Arabic,دَار الصِّنَاعَة
776501,cq1pMSwQXLiG-BfsI9kSYQ,English,cyberarsenal,derived_from,uunt-HERUyi9KbO__wGPZg,Arabic,دَار الصِّنَاعَة
776502,Z0yiLTJHUD2HHKu-RAxbXg,Turkish,kaşıkçı,has_affix,U9sgqrd8XCyr4zQERX_6Eg,Ottoman turkish,قاشق
776503,yviZV8jXWnSHcUvqUkGGRg,English,Khashoggi,has_affix,U9sgqrd8XCyr4zQERX_6Eg,Ottoman turkish,قاشق

In [99]:
test_main = df_root_merge[(df_root_merge["lang"]==f"{lang_1.capitalize()}")]
test_main.drop_duplicates(inplace=True)
test_main

/home/kurubal/anaconda3/envs/py39/lib/python3.9/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

,term_id,lang,term,reltype,related_term_id,related_lang,related_term
10,yglj90QEWaGcUI2-FXe41Q,Turkish,palavra,inherited_from,uXGtk5g-W8G_TlTxSHImpg,Latin,parabola
169,yglj90QEWaGcUI2-FXe41Q,Turkish,palavra,derived_from,JHVmHqAPXEq-YaIbd0B5Jg,Ancient greek,παραβολή
282,QDVQAg50WQymOq6pxRgCYw,Turkish,parabol,derived_from,JHVmHqAPXEq-YaIbd0B5Jg,Ancient greek,παραβολή
391,yglj90QEWaGcUI2-FXe41Q,Turkish,palavra,etymologically_related_to,r3NclALnW1ioq3gnbe1R5g,English,palaver
3492,vcrASsqQU7Cws9RWuDjoew,Turkish,ensest,has_affix,J5FnlsOjVgWaY5_YXTRlOg,Latin,in-
...,...,...,...,...,...,...,...
776492,TvL25-tdUN-GalXqFUi0RA,Turkish,botoks,blend_of,DcfZxeIRVKiurYCMr2SKKA,English,botulin
776496,4OaFsKu9U06KsiXLN1I86w,Turkish,huş,cognate_of,Prp1DBBWUTaz2Byw6yggQA,Persian,غوش
776497,ZmAjiw8JUaezZF4CmOgD0A,Turkish,tersane,derived_from,8sAvMylPV06vp_knMpEaQA,French,arsenal
776500,ZmAjiw8JUaezZF4CmOgD0A,Turkish,tersane,derived_from,uunt-HERUyi9KbO__wGPZg,Arabic,دَار الصِّنَاعَة
776502,Z0yiLTJHUD2HHKu-RAxbXg,Turkish,kaşıkçı,has_affix,U9sgqrd8XCyr4zQERX_6Eg,Ottoman turkish,قاشق

In [100]:
test_pair = df_root_merge[(df_root_merge["lang"]==f"{lang_2.capitalize()}")]
test_pair.drop_duplicates(inplace=True)
test_pair

/home/kurubal/anaconda3/envs/py39/lib/python3.9/site-packages/pandas/util/_decorators.py:311: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return func(*args, **kwargs)

,term_id,lang,term,reltype,related_term_id,related_lang,related_term
5,VKpprkitUaijmY8EeBCvHQ,English,parle,inherited_from,uXGtk5g-W8G_TlTxSHImpg,Latin,parabola
6,pC6Bp9lIXHGgnqNe3JxmFg,English,parlay,inherited_from,uXGtk5g-W8G_TlTxSHImpg,Latin,parabola
8,pa1DyTEyVOaIVZQPA8Hzjg,English,parlor,inherited_from,uXGtk5g-W8G_TlTxSHImpg,Latin,parabola
13,WB7OVE01XeSxWXeHsxGrxQ,English,parole,inherited_from,uXGtk5g-W8G_TlTxSHImpg,Latin,parabola
20,x0csKO2pXiChaUAIWqoSEA,English,polari,derived_from,uXGtk5g-W8G_TlTxSHImpg,Latin,parabola
...,...,...,...,...,...,...,...
776493,yqsO3OtPUC6vmU7xxxciLQ,English,brotox,blend_of,DcfZxeIRVKiurYCMr2SKKA,English,botulin
776495,YoaH-eGUVTq4sX_3kPDdQA,English,ispaghula,etymologically_related_to,Prp1DBBWUTaz2Byw6yggQA,Persian,غوش
776499,cq1pMSwQXLiG-BfsI9kSYQ,English,cyberarsenal,derived_from,8sAvMylPV06vp_knMpEaQA,French,arsenal
776501,cq1pMSwQXLiG-BfsI9kSYQ,English,cyberarsenal,derived_from,uunt-HERUyi9KbO__wGPZg,Arabic,دَار الصِّنَاعَة
776503,yviZV8jXWnSHcUvqUkGGRg,English,Khashoggi,has_affix,U9sgqrd8XCyr4zQERX_6Eg,Ottoman turkish,قاشق

In [101]:
df_result = pd.merge(test_main, test_pair, how="inner",on="related_term")
df_result.drop_duplicates(inplace=True)
df_result

,term_id_x,lang_x,term_x,reltype_x,related_term_id_x,related_lang_x,related_term,term_id_y,lang_y,term_y,reltype_y,related_term_id_y,related_lang_y
0,yglj90QEWaGcUI2-FXe41Q,Turkish,palavra,inherited_from,uXGtk5g-W8G_TlTxSHImpg,Latin,parabola,VKpprkitUaijmY8EeBCvHQ,English,parle,inherited_from,uXGtk5g-W8G_TlTxSHImpg,Latin
1,yglj90QEWaGcUI2-FXe41Q,Turkish,palavra,inherited_from,uXGtk5g-W8G_TlTxSHImpg,Latin,parabola,pC6Bp9lIXHGgnqNe3JxmFg,English,parlay,inherited_from,uXGtk5g-W8G_TlTxSHImpg,Latin
2,yglj90QEWaGcUI2-FXe41Q,Turkish,palavra,inherited_from,uXGtk5g-W8G_TlTxSHImpg,Latin,parabola,pa1DyTEyVOaIVZQPA8Hzjg,English,parlor,inherited_from,uXGtk5g-W8G_TlTxSHImpg,Latin
3,yglj90QEWaGcUI2-FXe41Q,Turkish,palavra,inherited_from,uXGtk5g-W8G_TlTxSHImpg,Latin,parabola,WB7OVE01XeSxWXeHsxGrxQ,English,parole,inherited_from,uXGtk5g-W8G_TlTxSHImpg,Latin
4,yglj90QEWaGcUI2-FXe41Q,Turkish,palavra,inherited_from,uXGtk5g-W8G_TlTxSHImpg,Latin,parabola,x0csKO2pXiChaUAIWqoSEA,English,polari,derived_from,uXGtk5g-W8G_TlTxSHImpg,Latin
...,...,...,...,...,...,...,...,...,...,...,...,...,...
588759,TvL25-tdUN-GalXqFUi0RA,Turkish,botoks,blend_of,DcfZxeIRVKiurYCMr2SKKA,English,botulin,yqsO3OtPUC6vmU7xxxciLQ,English,brotox,blend_of,DcfZxeIRVKiurYCMr2SKKA,English
588760,4OaFsKu9U06KsiXLN1I86w,Turkish,huş,cognate_of,Prp1DBBWUTaz2Byw6yggQA,Persian,غوش,YoaH-eGUVTq4sX_3kPDdQA,English,ispaghula,etymologically_related_to,Prp1DBBWUTaz2Byw6yggQA,Persian
588761,ZmAjiw8JUaezZF4CmOgD0A,Turkish,tersane,derived_from,8sAvMylPV06vp_knMpEaQA,French,arsenal,cq1pMSwQXLiG-BfsI9kSYQ,English,cyberarsenal,derived_from,8sAvMylPV06vp_knMpEaQA,French
588762,ZmAjiw8JUaezZF4CmOgD0A,Turkish,tersane,derived_from,uunt-HERUyi9KbO__wGPZg,Arabic,دَار الصِّنَاعَة,cq1pMSwQXLiG-BfsI9kSYQ,English,cyberarsenal,derived_from,uunt-HERUyi9KbO__wGPZg,Arabic
588763,Z0yiLTJHUD2HHKu-RAxbXg,Turkish,kaşıkçı,has_affix,U9sgqrd8XCyr4zQERX_6Eg,Ottoman turkish,قاشق,yviZV8jXWnSHcUvqUkGGRg,English,Khashoggi,has_affix,U9sgqrd8XCyr4zQERX_6Eg,Ottoman turkish

In [102]:
#df_result = df_result.head(1000000)

In [103]:
df_result.to_excel(f"{lang_1.capitalize()}_And_{lang_2.capitalize()}_Same_Root.xlsx",index=False)

In [17]:
df_test2 = pd.DataFrame(set(df_result["term_x"]),columns=[f"{lang_1.lower()}_word"])
df_test2

      turkish_word
0             broş
1            posta
2             plan
3     pamuk şekeri
4              göt
...            ...
2770      biyoloji
2771    birincilik
2772   i̇stanbullu
2773     dinsizlik
2774      salçalık

[2775 rows x 1 columns]

In [18]:
df_test2.to_excel("test2.xlsx", index=False)

In [16]:
pd.DataFrame(set(df_result["term_y"]),columns=[f"{lang_2.lower()}_word"])

         portuguese_word
0                   hall
1             malhadouro
2                 cabeça
3              discoteca
4         cuidadosamente
...                  ...
10181          moribundo
10182             clique
10183  incompatibilidade
10184        interiorano
10185           cachecol

[10186 rows x 1 columns]

In [84]:
df_result.to_excel("Turkish_And_Portuguese_Same_Root.xlsx",index=False)

#### Arabic Language Process

In [1]:
df_clean = pd.read_csv("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Data/All/etymology_cross_check2.csv")
#df_clean = df_clean.head(150000)
df_clean

,term_id,lang,term,reltype,related_term_id,related_lang,related_term
0,LHuH1RvcUjWNUTR6QQF8fg,Spanish,palabra,inherited_from,9w90qvZDUH-2OHPVZEGJSQ,Middle english,parlai
1,LHuH1RvcUjWNUTR6QQF8fg,Spanish,palabra,derived_from,Uy6v5wWuW6KGH4aTqGWnmA,Old french,parler
2,LHuH1RvcUjWNUTR6QQF8fg,Spanish,palabra,derived_from,HY24XyCcUZCYSa1Q6y2kPA,Late latin,parabolō
3,LHuH1RvcUjWNUTR6QQF8fg,Spanish,palabra,derived_from,uXGtk5g-W8G_TlTxSHImpg,Latin,parabola
4,LHuH1RvcUjWNUTR6QQF8fg,Spanish,palabra,derived_from,JHVmHqAPXEq-YaIbd0B5Jg,Ancient greek,παραβολή
...,...,...,...,...,...,...,...
8854119,3q28WGgPWs2K_SSglCAWvQ,Catalan,petitesa,inherited_from,TUnsO83vXXC1Us5rJgGyUg,Vulgar latin,*pittitus
8854120,3q28WGgPWs2K_SSglCAWvQ,Catalan,petitesa,etymologically_related_to,oUnwLLsHVymmwwiRXgrRow,Latin,pitinnus
8854121,3q28WGgPWs2K_SSglCAWvQ,Catalan,petitesa,etymologically_related_to,IGRZaHQ-VU-vpxMjdxSTlA,Latin,pitulus
8854122,3q28WGgPWs2K_SSglCAWvQ,Catalan,petitesa,etymologically_related_to,MDRrWciZWXGEj1KR9MUWtg,Latin,piccinus
8854123,3q28WGgPWs2K_SSglCAWvQ,Catalan,petitesa,cognate_of,SUJISOECWc6fDH00I_cTRQ,French,petit

In [2]:
#df_test = df_clean[df_clean.lang == "Arabic"]
#df_test

In [3]:
#df_test["term"].nunique()

In [4]:
df_related_arabic = df_clean[df_clean.related_lang == "Arabic"]
df_related_arabic

,term_id,lang,term,reltype,related_term_id,related_lang,related_term
240,gO8a39oEUY2RsyQxIfFfQQ,English,checkstring,derived_from,qwdsn8x6XF-HTKpcZo7Oow,Arabic,شَاه
584,i-mLFnKYUBON8yKHj0Y5oA,English,Z-boson,derived_from,PzMZaVy3UqWmKxAtjw_gLg,Arabic,صِفْر
1381,wkvXK0XUXv-l0ADRAfplvw,Arabic,صابون,cognate_of,uA8bKDiTXk2EPb95pMBCIw,Arabic,صَابُون
2647,PkGNd3GKX4GltfR8xYhcag,English,ounce,derived_from,iLTIBlq4W1enrh6LBTHyCw,Arabic,أُوقِيَّة
4126,U-sZX9qKU9iA0ZeIxhJPIw,English,racecar,derived_from,q3W15I4EUvG_oy1xaKS-jA,Arabic,رَأْس
...,...,...,...,...,...,...,...
8853515,H1OvbSUwVGiB2LYkdUtDKg,Maltese,għal għarrieda,etymologically_related_to,fVpepEipXYOtQ83zFSLGbw,Arabic,ع
8853871,WgXmwqOXXOiao_jraMkrqQ,Kazakh,саяхаттау,derived_from,InMwg6-uVW2yGsdBfAJAEg,Arabic,سِيَاحَة
8853928,JBkU_VzLVrCl_CfafSu7qQ,Bengali,খারাব,borrowed_from,ylRXVEy0VEqR55eF9NhivA,Arabic,خَرَاب
8853985,A4TSDLDGUGyb-VSakUKs5Q,Sicilian,Zuccaru,borrowed_from,ULI-I5kVXyC46wuGlM8K1g,Arabic,سُكَّر
8854043,Pnq619TbUBWzjgQv2oq2Hw,Azerbaijani,təmsilçi,borrowed_from,Yv1aIwBhVByI93ztnnOs-Q,Arabic,تَمْثِيل‎

In [5]:
df_select_lang = df_related_arabic[df_related_arabic.lang == "Turkish"]
df_select_lang

,term_id,lang,term,reltype,related_term_id,related_lang,related_term
8982,ZZOXAtMCUAOdIhVk2GVPBQ,Turkish,beygir,derived_from,AzRa4FX2XIuQ-Pn3rxagog,Arabic,بَارِئ
8983,ZZOXAtMCUAOdIhVk2GVPBQ,Turkish,beygir,borrowed_from,8IyTi0UiXPS-ynxBKJiOdg,Arabic,بَارّ
13812,YmTAc_WrWTyz7remY95glw,Turkish,kaide,borrowed_from,ttBCpOoQVPGr4vMagwFrmw,Arabic,قَاعِدَة
13813,YmTAc_WrWTyz7remY95glw,Turkish,kaide,has_root,cNgkUbiuXB6yUNcuqqS2Jg,Arabic,ق ع د
20546,6IjCkdZ-WceDHj_BsQJv1w,Turkish,bina,borrowed_from,2C9i6h-MXEK8blQ3Lq97eQ,Arabic,بِنَاء
...,...,...,...,...,...,...,...
8842927,z9zAeObqXa-j-PjFH4eViw,Turkish,vatanî,has_root,NjfuEYyiVLKZ6DLDln-Mrw,Arabic,و ط ن
8846005,vGZ-kjFgW9CHWeNEKFVSiA,Turkish,haber spikeri,derived_from,Ik_W08aeU5qdNF32oRKO8A,Arabic,خَبَر
8847835,dl54herJXt-Sc5Ta6ETw0A,Turkish,resmî dil,derived_from,zQAs9-uWVm6UGUF8K6kUng,Arabic,رَسْمِيّ
8849858,du1rjHPoWBeF3zSAXaDFKA,Turkish,halk dili,derived_from,dOSIqOnCV_GYWtFOTs1RRw,Arabic,خَلْق
8851015,0Yzd94TTX3K27B6lk37sag,Turkish,taarruz,derived_from,muyk8kVmXgSDcF0XCVLbog,Arabic,تَعَرُّض

In [6]:
df_var1 = pd.DataFrame(df_select_lang["term"].unique(), columns=["term"])
df_var1

              term
0           beygir
1            kaide
2             bina
3             harp
4              bal
..             ...
946         vatanî
947  haber spikeri
948      resmî dil
949      halk dili
950        taarruz

[951 rows x 1 columns]

In [7]:
df_var1.to_excel("Turkish_Term.xlsx", index=False)

In [8]:
df_var2 = pd.DataFrame(df_select_lang["related_term"].unique(), columns=["related_term"])
df_var2

    related_term
0         بَارِئ
1          بَارّ
2       قَاعِدَة
3          ق ع د
4         بِنَاء
..           ...
965        لَغْو
966        ل غ و
967     رَسْمِيّ
968        خَلْق
969     تَعَرُّض

[970 rows x 1 columns]

In [9]:
df_var2.to_excel("Arabic_Related_Term.xlsx", index=False)

In [10]:
df_var1_translate = pd.read_excel("Turkish Arabic Language Pair Translate.xlsx")
df_var1_translate

    turkish_word arabic_word
0         beygir        حصان
1          kaide      يتمركز
2           bina        بناء
3           harp         حرب
4            bal         عسل
..           ...         ...
965        لَغْو        لويو
966        ل غ و       ل غ و
967     رَسْمِيّ       رَسوم
968        خَلْق       uglْق
969     تَعَرُّض    تكوشرُّض

[970 rows x 2 columns]

In [11]:
df_var2.rename(columns={"related_term":"arabic_word"}, inplace=True)
df_var2

    arabic_word
0        بَارِئ
1         بَارّ
2      قَاعِدَة
3         ق ع د
4        بِنَاء
..          ...
965       لَغْو
966       ل غ و
967    رَسْمِيّ
968       خَلْق
969    تَعَرُّض

[970 rows x 1 columns]

In [12]:
pd.merge(df_var2,df_var1_translate, how="inner",on="arabic_word")

  arabic_word turkish_word
0           ع       عِزَّة
1         تاج          taç
2     باذنجان     patlıcan
3           و           ve
4       ن ظ ر        ن ظ ر
5       ل غ و        ل غ و

In [13]:
df_var2_translate = pd.read_excel("Arabic Turkish Language Pair Translate.xlsx")
df_var2_translate

    arabic_word turkish_word
0        بَارِئ      O masum
1         بَارّ        çubuk
2      قَاعِدَة        Temel
3         ق ع د        S P D
4        بِنَاء         bina
..          ...          ...
965       لَغْو          NaN
966       ل غ و          NaN
967    رَسْمِيّ          NaN
968       خَلْق          NaN
969    تَعَرُّض          NaN

[970 rows x 2 columns]

In [14]:
df_var1.rename(columns={"term":"turkish_word"}, inplace=True)
df_var1

      turkish_word
0           beygir
1            kaide
2             bina
3             harp
4              bal
..             ...
946         vatanî
947  haber spikeri
948      resmî dil
949      halk dili
950        taarruz

[951 rows x 1 columns]

In [15]:
pd.merge(df_var1,df_var2_translate, how="inner",on="turkish_word")

   turkish_word arabic_word
0          bina      بِنَاء
1        katran    قَطْرَان
2         barut       بارود
3         ceviz       جَوْز
4      affetmek       ص ف ح
5      cehennem    جَهَنَّم
6         sokak      زُقَاق
7         sıfır       صِفْر
8         sıfır       صَفَر
9         sabah      صَبَاح
10            o        أَنْ
11            o         إِن
12            o       إِنَّ
13          din       دَيْن
14     gergedan  كَرْكَدَّن
15         kalp       قَلْب
16          nar     رُمَّان
17        silah      سِلَاح
18       bulgur     بُرْغُل
19        miras     مِيرَاث
20        katil      قَاتِل
21        kitap      كِتَاب
22      tercüme   تَرْجَمَة
23         nane    نَعْنَاع
24         özel   خُصُوصِيّ
25     karanfil   قَرَنْفُل
26       hayvan    حَيَوَان
27        çorap     جَوْرَب
28         vaha      وَاحَة
29         vaha        واحة
30        Kuran  اَلْقُرْآن
31       zeytin    زَيْتُون
32          muz       مَوْز
33        sayfa     صَفْحَة
34       hamile      حَامِل
35       kelime     كَلِمَة
36        Mısır       مِصْر
37       halhal    خَلْخَال
38         saat      سَاعَة
39         akıl       عَقْل
40      kenevir      قِنَّب
41      hayırlı    مَيْمُون

In [2]:
df_etymology = pd.read_csv("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Data/All/etymwn.csv")
df_etymology

        lang      term                 reltype related_lang   related_term
0        aaq    senabe  etymological_origin_of          eng         sannup
1        abe  waniigan  etymological_origin_of          eng         wangan
2        abe  waniigan  etymological_origin_of          eng       wannigan
3        abs      beta  etymological_origin_of          zsm           beta
4        adt      yuru  etymological_origin_of          eng           euro
...      ...       ...                     ...          ...            ...
6031425  zul       ya-  etymological_origin_of          zul  inhlamvu yeso
6031426  zul       ya-  etymological_origin_of          zul  inja yasendle
6031427  zul       zi-         is_derived_from          zul           izi-
6031428  zul      zim-         is_derived_from          zul          izim-
6031429  zul      zin-         is_derived_from          zul          izin-

[6031430 rows x 5 columns]

In [9]:
df_lang1 = df_etymology[df_etymology.lang == f"ara"]
df_lang1

      lang             term                 reltype related_lang related_term
9668   ara  '''اِرْتِداد'''  etymological_origin_of          fas       ارتداد
9669   ara  '''اِرْتِداد'''  etymological_origin_of          urd       ارتداد
9670   ara       '''خاصّ'''  etymological_origin_of          urd          خاص
9671   ara      '''سلطان'''  etymological_origin_of          fas        سلطان
9672   ara      '''نَظَر'''  etymological_origin_of          fas          نظر
...    ...              ...                     ...          ...          ...
15640  ara           ’aswad  etymological_origin_of          eng        sudan
15641  ara                ﴾  etymologically_related          ara            ﴿
15642  ara                ﴿  etymologically_related          ara            ﴾
15643  ara                ﷼  etymological_origin_of          fas            ﷼
15644  ara                ﷼               etymology          spa         real

[5977 rows x 5 columns]

In [5]:
df_etymology.lang.unique()

array(['aaq', 'abe', 'abs', 'adt', 'afr', 'aii', 'ain', 'akk', 'akz',
       'ale', 'alq', 'amh', 'amj', 'ang', 'apw', 'ara', 'arg', 'arn',
       'arq', 'arw', 'ary', 'arz', 'ase', 'ast', 'auc', 'ava', 'ave',
       'axm', 'ayl', 'aym', 'aze', 'bak', 'bar', 'bdy', 'bel', 'ben',
       'bft', 'bis', 'bod', 'bre', 'bua', 'bul', 'byn', 'cat', 'ccc',
       'ceb', 'ces', 'cha', 'chc', 'che', 'chn', 'cho', 'chr', 'chu',
       'cic', 'cmn', 'cop', 'cor', 'cre', 'crh', 'csb', 'cym', 'dan',
       'del', 'dep', 'deu', 'div', 'dsb', 'dtd', 'dum', 'efi', 'egy',
       'ell', 'emn', 'eng', 'enm', 'enn', 'epo', 'ess', 'est', 'ett',
       'eus', 'evn', 'ewe', 'fao', 'fas', 'fij', 'fin', 'fon', 'fra',
       'frc', 'frk', 'frm', 'fro', 'frp', 'fry', 'fur', 'gae', 'gez',
       'gil', 'gla', 'gle', 'glg', 'glv', 'gmh', 'gml', 'gmy', 'goh',
       'got', 'grc', 'grn', 'grv', 'gsw', 'gug', 'guj', 'gul', 'gwi',
       'hak', 'hat', 'hau', 'haw', 'hbs', 'heb', 'hif', 'hil', 'hin',
       'hit', 'hop', 'hsb', 'hun', 'hur', 'hye', 'idb', 'ido', 'ike',
       'ikt', 'iku', 'ina', 'ind', 'inz', 'ipk', 'isl', 'ita', 'jam',
       'jav', 'jbo', 'jpn', 'kal', 'kan', 'kat', 'kaw', 'kaz', 'kbd',
       'khm', 'kin', 'kir', 'kjh', 'kju', 'kky', 'kld', 'kmb', 'kok',
       'kon', 'kor', 'kri', 'krl', 'ksd', 'ksh', 'kum', 'kur', 'kzj',
       'lad', 'lao', 'lat', 'lav', 'lij', 'lim', 'lin', 'lit', 'liv',
       'lkt', 'lld', 'lmo', 'lng', 'lou', 'ltc', 'ltz', 'lua', 'lug',
       'luo', 'lut', 'lzh', 'mah', 'mak', 'mal', 'mar', 'mas', 'mav',
       'mbc', 'mfr', 'mga', 'mic', 'min', 'mkd', 'mlg', 'mlt', 'mnc',
       'mnk', 'mod', 'moe', 'moh', 'mon', 'mri', 'msa', 'mwl', 'mxi',
       'mya', 'myv', 'nah', nan, 'nap', 'naq', 'nav', 'nay', 'nci', 'ndo',
       'nds', 'nep', 'nld', 'nno', 'nob', 'non', 'nor', 'nov', 'nys',
       'obr', 'obt', 'oci', 'oco', 'odt', 'ofs', 'oge', 'oji', 'okm',
       'ood', 'orc', 'ori', 'orv', 'osp', 'oss', 'osx', 'ota', 'otk',
       'owl', 'p_gem', 'p_gmw', 'p_ine', 'p_sla', 'pal', 'pan', 'pap',
       'pau', 'pcd', 'pdt', 'peo', 'phn', 'pim', 'pis', 'pjt', 'pli',
       'pml', 'pol', 'por', 'pox', 'ppl', 'prg', 'pro', 'pus', 'quc',
       'que', 'qwc', 'rap', 'rhg', 'rme', 'rmf', 'rmq', 'roh', 'rom',
       'ron', 'rop', 'rue', 'ruo', 'rup', 'rus', 'ryu', 'san', 'sat',
       'scn', 'sco', 'see', 'sei', 'sga', 'shh', 'sin', 'slk', 'slv',
       'sme', 'smo', 'sms', 'sna', 'som', 'sot', 'spa', 'sqi', 'srd',
       'srn', 'srs', 'stg', 'sth', 'stq', 'sun', 'sux', 'swa', 'swe',
       'syc', 'szl', 'tah', 'tam', 'tat', 'tcs', 'tcy', 'tel', 'tet',
       'tew', 'tgk', 'tgl', 'tha', 'tir', 'tiv', 'tnq', 'ton', 'tpi',
       'tpw', 'tsn', 'tuk', 'tur', 'twf', 'twi', 'txb', 'tzm', 'uga',
       'uig', 'ukr', 'ulk', 'umb', 'umu', 'urd', 'uzb', 'vai', 'vec',
       'vep', 'vie', 'vls', 'vma', 'vol', 'wam', 'wit', 'wlm', 'wln',
       'wol', 'wrh', 'wym', 'xaa', 'xbm', 'xce', 'xcl', 'xho', 'xmb',
       'xng', 'xno', 'xnt', 'xon', 'xpr', 'xtg', 'xto', 'yid', 'yol',
       'yor', 'yua', 'yue', 'yur', 'yxg', 'zai', 'zko', 'zku', 'zsm',
       'zul'], dtype=object)