### Selected Word Group In Youtube Sentence

In [1]:
import os
import re
import pandas as pd
import numpy as np
import glob
from functools import reduce
from pathlib import Path
import shutil
from itertools import islice

In [2]:
# language pair
lang_folder = "Turkish"  # Arabic, English, French, German, Turkish, Spanish, Portuguese, Dutch, Italian ==> target language for learner
#lang_pair = "Arabic"  # Arabic, English, French, German, Turkish, Spanish, Portuguese, Dutch, Italian ==> native language

# native word select for Part 2 
word_start = 0  # 0  # native word start index
word_end = 200 # 28  # native word end index

# source path
source_path = "/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Turkish/Deployment2/Result/Deploy2 Result Manuel/Turkish"

# parameter
file = "BCTM 3 gram Youtube Links Base File"  # without xlsx extention
sheets = "Elenenler"  # 2 gram target, 2 gram hybrid
file_ext = "Threegram"
first_column = 0  # start column location number
end_column = 1
time_shift = 0.6
sample_num = 6

# youtube sentence condition
sent_time_start = True  # True, False
sent_time_start_time = 700 # sn

In [3]:
path = f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/{lang_folder.capitalize()}/\
Deployment2/Result/3-Selected Word Group In Youtube Sentence/{lang_folder.capitalize()}"

Path(path).mkdir(parents=True, exist_ok=True)

In [4]:
def word_group_youtube(df, search_list, target_column, sample_num):
    '''
    word_group_youtube(df_youtube_sentence, search_list, "sentence", 6)
    ''' 
    df_search_result = pd.DataFrame()
    for j in search_list:
        try:
            df_select = df[df[f"{target_column}"].str.contains(fr"(?:\s|^){j}(?:\s|$)", na=True)].sample(sample_num)
        except:
            df_select = df[df[f"{target_column}"].str.contains(fr"(?:\s|^){j}(?:\s|$)", na=True)].head(sample_num)
        #df_result = df[df[f"{target_column}"].str.contains(fr"(?:\s|^){j}(?:\s|$)", na=True)]  # sentence length part
        #df_result.sort_values(f"{target_column}",key=lambda x:x.str.len(), inplace=True)
        #df_select = df_result.head(sample_num)
        df_select.insert(0,"search_string",j)
        df_search_result = pd.concat([df_search_result,df_select], axis=0)
    df_search_result.reset_index(inplace=True, drop=True)
    
    return df_search_result

In [5]:
def word_group_time_loc(df, search, start_sent, end_sent, sent, sent_video_id):
    '''
    word_group_time_loc(df_search_result, "search_string", "start_time", "end_time", "sentence", "video_id")
    '''
    df.reset_index(drop=True, inplace=True)
    word_time_loc_list = []
    for i in range(len(df)):
        word = df.loc[i,f"{search}"]
        start_time = df.loc[i,f"{start_sent}"]
        end_time = df.loc[i,f"{end_sent}"]
        sentence = df.loc[i,f"{sent}"]
        video_id = df.loc[i,f"{sent_video_id}"]
        time_length = end_time-start_time
        sentence_length = len(sentence)
        time_length_ratio = time_length/sentence_length
        loc_list = []
        for j in re.finditer(fr"(?:\s|^){word}(?:\s|$)", sentence, re.IGNORECASE|re.UNICODE):
            loc_list.append(j)
            start = loc_list[0].start()
            end = loc_list[0].end()
            start_loc = start_time+(start*time_length_ratio)
            end_loc = start_time+(end*time_length_ratio)
        word_time_loc_list.append([word,start_loc,end_loc,sentence,video_id])
    df_word_time_loc = pd.DataFrame(word_time_loc_list, columns=[f"{search}",f"{start_sent}",f"{end_sent}",f"{sent}",f"{sent_video_id}"])

    return df_word_time_loc

In [6]:
def word_count_result(df, column_list, set_condition=False): # df is dataframe, column_list is list value
    '''
    word_count_bool(df, column_list): df columns word count for word frequency\n
    df is dataframe, column_list is list value\n
    word_count_bool(df, ["word","twogram"]):
    '''
    list_all = []
    for i in df.loc[:,[x for x in column_list]].columns:
        if set_condition:
            var_list = set(df[f"{i}"].dropna().tolist())
        else:
            var_list = df[f"{i}"].dropna().tolist()
        for j in var_list:
            list_all.append(j)
    text = " ".join(list_all)
    word_list = re.findall(r"\w+",text, re.UNICODE)
    df_word_list = pd.DataFrame(word_list, columns=["word"])
    #df_word_list.rename(columns={0:"word"}, inplace=True)
    df_word_count = pd.DataFrame(df_word_list.value_counts())
    df_word_count.reset_index(inplace=True)
    df_word_count.rename(columns={0:"word_count"}, inplace=True)
    df_word_count.sort_values("word_count", ascending=False, inplace=True)
    
    return  df_word_count

In [7]:
df_word_all = pd.read_excel(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/{lang_folder.lower().capitalize()}/Deployment/Data/Word/Word_Merge_Preprocess.xlsx")
df_word_all

                word  frequency
0                bir   18835735
1                 bu   11062659
2                 ne    8025880
3                 ve    7766036
4               için    5484109
...              ...        ...
987924     karneleme          5
987925       karnaya          5
987926   dörtlümüzün          5
987927  karnavalınız          5
987928      hurmanın          5

[987929 rows x 2 columns]

In [8]:
df_word_select = df_word_all.iloc[word_start:word_end,]
df_word_select

           word  frequency
0           bir   18835735
1            bu   11062659
2            ne    8025880
3            ve    7766036
4          için    5484109
..          ...        ...
195        saat     399989
196      onunla     399330
197  yapıyorsun     398274
198       neler     397377
199       ister     396177

[200 rows x 2 columns]

In [9]:
df_youtube_sentence = pd.read_csv(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Youtube/Result/{lang_folder.capitalize()}/Sentence Clean Merge/Clean_Youtube_Sentence_Merge_Result.csv")
df_youtube_sentence

,start_time,end_time,sentence,video_id
0,00:02:51.948,00:02:58.829,özgür bunlar normalde kamyon daha büyük araçla...,8V9tq1pe8eI
1,00:03:00.956,00:03:04.236,burcu arka tarafı bağlamak kolay olmayacak,8V9tq1pe8eI
2,00:03:13.434,00:03:16.327,özgür arabaya yarım tur attıracağım,8V9tq1pe8eI
3,00:03:17.235,00:03:21.338,burcu biraz daha devam et devam et tamam oldu,8V9tq1pe8eI
4,00:03:27.806,00:03:33.383,burcu şimdilik iki tekere takacağız ama kar ka...,8V9tq1pe8eI
...,...,...,...,...
3063204,00:11:07.990,00:11:14.560,oynatma listesi linkini videonun sağ üst köşes...,MvWp9pWLihA
3063205,00:11:14.560,00:11:21.040,kısmına ekledim dilediğiniz kenar deseni uyarl...,MvWp9pWLihA
3063206,00:11:21.040,00:11:27.880,ibaretti bir sonraki farklı bir elle örgü eğit...,MvWp9pWLihA
3063207,00:11:27.880,00:11:32.290,kanalıma abone olarak videomu beğenmeyi unutma...,MvWp9pWLihA
3063208,00:00:03.280,00:00:12.200,merhaba arkadaşlar sizler için tren yaptım vid...,L_ERx2ZNheU

In [10]:
df_youtube_sentence['start_time'] = pd.to_timedelta(df_youtube_sentence['start_time']) # data type converted timedelta for second 
df_youtube_sentence['end_time'] = pd.to_timedelta(df_youtube_sentence['end_time'])

In [11]:
df_youtube_sentence['start_time'] = df_youtube_sentence['start_time'].apply(lambda x: x.total_seconds()) # convert seconds
df_youtube_sentence['end_time'] = df_youtube_sentence['end_time'].apply(lambda x: x.total_seconds())
df_youtube_sentence

,start_time,end_time,sentence,video_id
0,171.948,178.829,özgür bunlar normalde kamyon daha büyük araçla...,8V9tq1pe8eI
1,180.956,184.236,burcu arka tarafı bağlamak kolay olmayacak,8V9tq1pe8eI
2,193.434,196.327,özgür arabaya yarım tur attıracağım,8V9tq1pe8eI
3,197.235,201.338,burcu biraz daha devam et devam et tamam oldu,8V9tq1pe8eI
4,207.806,213.383,burcu şimdilik iki tekere takacağız ama kar ka...,8V9tq1pe8eI
...,...,...,...,...
3063204,667.990,674.560,oynatma listesi linkini videonun sağ üst köşes...,MvWp9pWLihA
3063205,674.560,681.040,kısmına ekledim dilediğiniz kenar deseni uyarl...,MvWp9pWLihA
3063206,681.040,687.880,ibaretti bir sonraki farklı bir elle örgü eğit...,MvWp9pWLihA
3063207,687.880,692.290,kanalıma abone olarak videomu beğenmeyi unutma...,MvWp9pWLihA
3063208,3.280,12.200,merhaba arkadaşlar sizler için tren yaptım vid...,L_ERx2ZNheU

In [12]:
if sent_time_start:
    df_youtube_select = df_youtube_sentence[df_youtube_sentence["start_time"] <= sent_time_start_time]
    df_youtube_select.reset_index(drop=True, inplace=True)
else:
    df_youtube_select = df_youtube_sentence

df_youtube_select

,start_time,end_time,sentence,video_id
0,171.948,178.829,özgür bunlar normalde kamyon daha büyük araçla...,8V9tq1pe8eI
1,180.956,184.236,burcu arka tarafı bağlamak kolay olmayacak,8V9tq1pe8eI
2,193.434,196.327,özgür arabaya yarım tur attıracağım,8V9tq1pe8eI
3,197.235,201.338,burcu biraz daha devam et devam et tamam oldu,8V9tq1pe8eI
4,207.806,213.383,burcu şimdilik iki tekere takacağız ama kar ka...,8V9tq1pe8eI
...,...,...,...,...
1050454,667.990,674.560,oynatma listesi linkini videonun sağ üst köşes...,MvWp9pWLihA
1050455,674.560,681.040,kısmına ekledim dilediğiniz kenar deseni uyarl...,MvWp9pWLihA
1050456,681.040,687.880,ibaretti bir sonraki farklı bir elle örgü eğit...,MvWp9pWLihA
1050457,687.880,692.290,kanalıma abone olarak videomu beğenmeyi unutma...,MvWp9pWLihA
1050458,3.280,12.200,merhaba arkadaşlar sizler için tren yaptım vid...,L_ERx2ZNheU

In [14]:
df_word_group_select = pd.read_excel(f"{source_path}/{file}.xlsx", sheet_name= f"{sheets}")
df_word_group_select

,bir şey yok,uK9kCxpB6t0,500,502,Unnamed: 4,https://www.youtube.com/watch?v=uK9kCxpB6t0&t=500s
0,bir şey var,qvPu7qxSnes,477,479,NaN,https://www.youtube.com/watch?v=qvPu7qxSnes&t=...
1,başka bir şey,U_tDGkeoFXs,489,491,NaN,https://www.youtube.com/watch?v=U_tDGkeoFXs&t=...
2,başka bir şey,BUxpgSVmM2Y,526,529,NaN,https://www.youtube.com/watch?v=BUxpgSVmM2Y&t=...
3,bir şey mi,OXGETrqx8JE,487,489,NaN,https://www.youtube.com/watch?v=OXGETrqx8JE&t=...
4,bir şey mi,17lFX_rY9LU,86,88,NaN,https://www.youtube.com/watch?v=17lFX_rY9LU&t=86s
...,...,...,...,...,...,...
984,bilmiyorum belki de,bsRxZRLB5fQ,1,5,NaN,https://www.youtube.com/watch?v=bsRxZRLB5fQ&t=1s
985,bilmiyorum belki de,etd2zOkEOyM,43,45,NaN,https://www.youtube.com/watch?v=etd2zOkEOyM&t=43s
986,bilmiyorum belki bu,4ghpZtvOxVw,136,138,NaN,https://www.youtube.com/watch?v=4ghpZtvOxVw&t=...
987,bugün büyük gün,SApb3kjbZvs,97,101,NaN,https://www.youtube.com/watch?v=SApb3kjbZvs&t=97s
988,o yüzden sizi,qolPvF5Sq2k,527,529,NaN,https://www.youtube.com/watch?v=qolPvF5Sq2k&t=...

In [19]:
search_list = []
for i in range(len(df_word_group_select)):
    for j in df_word_group_select.columns[first_column:end_column]:
        string = df_word_group_select.loc[i,j]
        
        if pd.isnull(string) == False and string != 'nan':
            search_list.append(string.strip())
            search_list = list(set(search_list))  # for unique value
        else:
            pass

In [20]:
len(search_list)

411

In [45]:
df_search_result = word_group_youtube(df_youtube_select, search_list, "sentence", sample_num)
df_search_result

,search_string,start_time,end_time,sentence,video_id
0,al şunu al,571.250,573.240,fatma abla al şunu al,eBKS1dCabuI
1,al şunu da,689.546,690.515,al şunu da hadi ben işe gidiyorum,EtWqWE8gdF0
2,al şunu da,657.980,659.080,haydi al şunu da,OcZJIp3KUYs
3,al şunu da,642.889,644.749,hadi aç bakayım al şunu da ısır,5e5vf1WrQYg
4,ama aslında gerçek,75.264,81.376,ama aslında gerçek anlamda gerçek öyle değildi...,yXkiaO7_SKI
...,...,...,...,...,...
1330,yok tamam mı,351.520,353.000,ama acele etmek yok tamam mı,ZmahvhKmnns
1331,yok tamam mı,274.780,278.560,şirin benim sana yalan borcum yok tamam mı ben...,mXgr8WVo8D4
1332,yoksa kötü mü,205.655,206.760,yoksa kötü mü olur bilemiyorum,jcqVzKEV9kI
1333,yoksa kötü mü,671.106,672.524,yoksa kötü mü,aPwTtMXPv3o
1334,zaten biliyorsun değil,405.463,409.235,ya bu eldiven sen parçaladın zaten biliyorsun ...,dSG4sD2bmXg

In [46]:
df_word_group_time_loc_result = word_group_time_loc(df_search_result, "search_string", "start_time", "end_time", "sentence", "video_id")
df_word_group_time_loc_result

,search_string,start_time,end_time,sentence,video_id
0,al şunu al,572.197619,573.240000,fatma abla al şunu al,eBKS1dCabuI
1,al şunu da,689.546000,689.869000,al şunu da hadi ben işe gidiyorum,EtWqWE8gdF0
2,al şunu da,658.323750,659.080000,haydi al şunu da,OcZJIp3KUYs
3,al şunu da,643.789000,644.509000,hadi aç bakayım al şunu da ısır,5e5vf1WrQYg
4,ama aslında gerçek,75.264000,76.876889,ama aslında gerçek anlamda gerçek öyle değildi...,yXkiaO7_SKI
...,...,...,...,...,...
1330,yok tamam mı,352.312857,353.000000,ama acele etmek yok tamam mı,ZmahvhKmnns
1331,yok tamam mı,276.346000,277.102000,şirin benim sana yalan borcum yok tamam mı ben...,mXgr8WVo8D4
1332,yoksa kötü mü,205.655000,206.170667,yoksa kötü mü olur bilemiyorum,jcqVzKEV9kI
1333,yoksa kötü mü,671.106000,672.524000,yoksa kötü mü,aPwTtMXPv3o
1334,zaten biliyorsun değil,407.418852,409.095296,ya bu eldiven sen parçaladın zaten biliyorsun ...,dSG4sD2bmXg

In [47]:
df_word_group_time_loc_result.start_time = df_word_group_time_loc_result.start_time.apply(lambda x: (x-time_shift))
df_word_group_time_loc_result.end_time = df_word_group_time_loc_result.end_time.apply(lambda x: (x+time_shift))
df_word_group_time_loc_result

,search_string,start_time,end_time,sentence,video_id
0,al şunu al,571.597619,573.840000,fatma abla al şunu al,eBKS1dCabuI
1,al şunu da,688.946000,690.469000,al şunu da hadi ben işe gidiyorum,EtWqWE8gdF0
2,al şunu da,657.723750,659.680000,haydi al şunu da,OcZJIp3KUYs
3,al şunu da,643.189000,645.109000,hadi aç bakayım al şunu da ısır,5e5vf1WrQYg
4,ama aslında gerçek,74.664000,77.476889,ama aslında gerçek anlamda gerçek öyle değildi...,yXkiaO7_SKI
...,...,...,...,...,...
1330,yok tamam mı,351.712857,353.600000,ama acele etmek yok tamam mı,ZmahvhKmnns
1331,yok tamam mı,275.746000,277.702000,şirin benim sana yalan borcum yok tamam mı ben...,mXgr8WVo8D4
1332,yoksa kötü mü,205.055000,206.770667,yoksa kötü mü olur bilemiyorum,jcqVzKEV9kI
1333,yoksa kötü mü,670.506000,673.124000,yoksa kötü mü,aPwTtMXPv3o
1334,zaten biliyorsun değil,406.818852,409.695296,ya bu eldiven sen parçaladın zaten biliyorsun ...,dSG4sD2bmXg

In [48]:
df_word_group_time_loc_result.start_time = df_word_group_time_loc_result.start_time.apply(lambda x: round(x))
df_word_group_time_loc_result.end_time = df_word_group_time_loc_result.end_time.apply(lambda x: round(x))
df_word_group_time_loc_result

,search_string,start_time,end_time,sentence,video_id
0,al şunu al,572,574,fatma abla al şunu al,eBKS1dCabuI
1,al şunu da,689,690,al şunu da hadi ben işe gidiyorum,EtWqWE8gdF0
2,al şunu da,658,660,haydi al şunu da,OcZJIp3KUYs
3,al şunu da,643,645,hadi aç bakayım al şunu da ısır,5e5vf1WrQYg
4,ama aslında gerçek,75,77,ama aslında gerçek anlamda gerçek öyle değildi...,yXkiaO7_SKI
...,...,...,...,...,...
1330,yok tamam mı,352,354,ama acele etmek yok tamam mı,ZmahvhKmnns
1331,yok tamam mı,276,278,şirin benim sana yalan borcum yok tamam mı ben...,mXgr8WVo8D4
1332,yoksa kötü mü,205,207,yoksa kötü mü olur bilemiyorum,jcqVzKEV9kI
1333,yoksa kötü mü,671,673,yoksa kötü mü,aPwTtMXPv3o
1334,zaten biliyorsun değil,407,410,ya bu eldiven sen parçaladın zaten biliyorsun ...,dSG4sD2bmXg

In [49]:
df_word_group_time_loc_result["video_url"] = "https://www.youtube.com/watch?v="+df_word_group_time_loc_result['video_id'].map(str)+"&t="+df_word_group_time_loc_result['start_time'].map(str)+"s"
df_word_group_time_loc_result

,search_string,start_time,end_time,sentence,video_id,video_url
0,al şunu al,572,574,fatma abla al şunu al,eBKS1dCabuI,https://www.youtube.com/watch?v=eBKS1dCabuI&t=...
1,al şunu da,689,690,al şunu da hadi ben işe gidiyorum,EtWqWE8gdF0,https://www.youtube.com/watch?v=EtWqWE8gdF0&t=...
2,al şunu da,658,660,haydi al şunu da,OcZJIp3KUYs,https://www.youtube.com/watch?v=OcZJIp3KUYs&t=...
3,al şunu da,643,645,hadi aç bakayım al şunu da ısır,5e5vf1WrQYg,https://www.youtube.com/watch?v=5e5vf1WrQYg&t=...
4,ama aslında gerçek,75,77,ama aslında gerçek anlamda gerçek öyle değildi...,yXkiaO7_SKI,https://www.youtube.com/watch?v=yXkiaO7_SKI&t=75s
...,...,...,...,...,...,...
1330,yok tamam mı,352,354,ama acele etmek yok tamam mı,ZmahvhKmnns,https://www.youtube.com/watch?v=ZmahvhKmnns&t=...
1331,yok tamam mı,276,278,şirin benim sana yalan borcum yok tamam mı ben...,mXgr8WVo8D4,https://www.youtube.com/watch?v=mXgr8WVo8D4&t=...
1332,yoksa kötü mü,205,207,yoksa kötü mü olur bilemiyorum,jcqVzKEV9kI,https://www.youtube.com/watch?v=jcqVzKEV9kI&t=...
1333,yoksa kötü mü,671,673,yoksa kötü mü,aPwTtMXPv3o,https://www.youtube.com/watch?v=aPwTtMXPv3o&t=...
1334,zaten biliyorsun değil,407,410,ya bu eldiven sen parçaladın zaten biliyorsun ...,dSG4sD2bmXg,https://www.youtube.com/watch?v=dSG4sD2bmXg&t=...

In [64]:
search_result_num = df_word_group_time_loc_result["search_string"].nunique()
search_result_num

317

In [86]:
df_result_word_manuel_count = word_count_result(df_word_group_time_loc_result, df_word_group_time_loc_result.columns[0:1], set_condition=True)
df_result_word_manuel_count

           word  word_count
0            bu          26
1            ne          22
2         değil          19
3            mi          15
4           çok          15
..          ...         ...
159        yeni           1
160  istiyorsun           1
161       haydi           1
162     değilim           1
182     gidelim           1

[183 rows x 2 columns]

In [100]:
# ???? 
df_word_count_merge = pd.merge(df_result_word_manuel_count, df_word_select[["word"]], how="inner", on="word")
df_word_count_merge.drop_duplicates(inplace=True)
df_word_count_merge.sort_values(by="word_count", ascending=False, inplace=True)
df_word_count_merge.reset_index(drop=True, inplace=True)
df_word_count_merge

        word  word_count
0         bu          26
1         ne          22
2      değil          19
3         mi          15
4        çok          15
..       ...         ...
172    olmaz           1
173      dur           1
174     seni           1
175    büyük           1
176  değilim           1

[177 rows x 2 columns]

In [104]:
set_word = set(df_word_select["word"])
#set_count = set(df_word_count_merge["word"])
set_count = set(df_result_word_manuel_count["word"])

In [105]:
set_word.difference(set_count)

{'anne',
 'asla',
 'baba',
 'beni',
 'bizi',
 'dostum',
 'geri',
 'git',
 'hey',
 'kendi',
 'küçük',
 'merhaba',
 'oh',
 'onları',
 'onunla',
 'pekala',
 'sanırım',
 'selam',
 'sizi',
 'tekrar',
 'teşekkürler',
 'tüm',
 'üzgünüm'}

In [ ]:
df_word_group_time_loc_result.to_excel(f"{lang_folder.capitalize()}_{search_result_num}_{file_ext}_\
{sample_num}_Youtube_{time_shift}s_Timeshift_Result.xlsx", index=False)

In [107]:
#df_word_count_merge.to_excel(f"{lang_folder.capitalize()}_{search_result_num}_{file_ext}_\
#{sample_num}_Youtube_{time_shift}s_Timeshift_Result_Word_Count.xlsx", index=False)

#### Copy Move And Delete

In [112]:
output_file = glob.glob(f"{lang_folder.capitalize()}_*_{sample_num}_Youtube_{time_shift}s_Timeshift_Result*.xlsx")
output_file

[]

In [ ]:
for y in output_file:
    source = y # source directory
    destination = path
    shutil.copy2(source, destination)

In [ ]:
for z in output_file:
    try:
        os.remove(z)
    except:
        pass

#### Temp

In [56]:
set_result = set(df_word_group_time_loc_result["search_string"].unique())
set_selected = set(search_list)

In [59]:
df_not_in_result = pd.DataFrame(set_selected.difference(set_result), columns=["not_in_youtube_result"])
df_not_in_result

     not_in_youtube_result
0          küçük kız vardı
1        haydi git buradan
2             o bize lazım
3         iyi olacak mısın
4             tabii eğer o
..                     ...
168     biri olabilir diye
169  haydi gidelim buradan
170  onunla birlikte değil
171          yoksa bizi mi
172    evet sanırım onları

[173 rows x 1 columns]

In [61]:
not_in_result_num = len(df_not_in_result)
not_in_result_num

173

In [ ]:
#df_not_in_result.to_excel(f"{lang_folder.capitalize()}_{not_in_result_num}_{file_ext}_\
#Not_In_{sample_num}_Youtube_{time_shift}s_Timeshift_Result.xlsx", index=False)

In [82]:
search_list2 = df_not_in_result["not_in_youtube_result"].to_list()

In [83]:
df_search_result2 = word_group_youtube(df_youtube_sentence, search_list2, "sentence", sample_num)
df_search_result2

,search_string,start_time,end_time,sentence,video_id
0,o bize lazım,787.320,788.180,o bize lazım,740EOWBVi5Y
1,o bize lazım,7924.575,7925.864,o bize lazım,G1WBHh_uWF4
2,o bize lazım,5310.455,5311.780,o bize lazım ağabey,QDeOzA5jE8I
3,o bize lazım,5312.380,5313.614,o bize lazım,QDeOzA5jE8I
4,iyi olacak mısın,2194.740,2196.320,daha iyi olacak mısın,uFqVjc0lUzc
...,...,...,...,...,...
157,sadece birkaç dakika,705.205,708.717,hermionenin asası bu şekilde sadece birkaç dak...,A0f5ba2teCU
158,sen zaten biliyorsun,5221.457,5226.457,ağabey sen zaten biliyorsun da ben yine söyley...,7fuvt2Q8Kgk
159,haydi gidelim buradan,5415.081,5417.333,haydi haydi gidelim buradan bir an önce,IqAwin7WV6E
160,yoksa bizi mi,5865.890,5868.170,gerçekten babanı tanıyor olabilir mi yoksa biz...,70daKdkwjeY
161,yoksa bizi mi,2155.301,2157.228,yoksa bizi mi öğrendi,aMWKWcdyYMo

In [84]:
search_result2_num = df_search_result2["search_string"].nunique()
search_result2_num

67