### Find Word Group Youtube Link

In [101]:
import os
import multiprocessing
#import multiprocessing as mp
from multiprocessing import Process, Manager, Pool, Queue
from itertools import islice
from collections import Counter
import re
import pandas as pd
import numpy as np
import glob
import nltk
from nltk import word_tokenize
from nltk import ngrams
from functools import reduce
from pathlib import Path
import shutil

In [102]:
nprocs = multiprocessing.cpu_count()
print(f"Number of CPU cores: {nprocs}")

Number of CPU cores: 16

In [103]:
# language pair
lang_folder = "Dutch"  # Arabic, English, French, German, Turkish, Spanish, Portuguese, Dutch, Italian ==> target language for learner
#lang_pair = "Intersect"  # Arabic, English, French, German, Turkish, Spanish, Portuguese, Dutch, Italian ==> native language

# adding native word to shared word
word_start = 0  # 0 native word start index
word_end = 200  # 28 native word end index

# youtube
sample_num = 7  # 7
time_shift = 0.6

In [106]:
def word_group_youtube(df, search_list, target_column, sample_num):
    '''
    word_group_youtube(df_youtube_sentence, search_list, "sentence", 6)\n
    df_youtube_sentence is dataframe and "sentence" is its column for external searching_list
    ''' 
    df_search_result = pd.DataFrame()
    for j in search_list:
        try:
            df_select = df[df[f"{target_column}"].str.contains(fr"(?:\s|^){j}(?:\s|$)", na=True)].sample(sample_num)
        except:
            df_select = df[df[f"{target_column}"].str.contains(fr"(?:\s|^){j}(?:\s|$)", na=True)].head(sample_num)
        #df_result = df[df[f"{target_column}"].str.contains(fr"(?:\s|^){j}(?:\s|$)", na=True)]  # sentence length part
        #df_result.sort_values(f"{target_column}",key=lambda x:x.str.len(), inplace=True)
        #df_select = df_result.head(sample_num)
        df_select.insert(0,"search_string",j)
        df_search_result = pd.concat([df_search_result,df_select], axis=0)
    df_search_result.reset_index(inplace=True, drop=True)
    
    return df_search_result

In [107]:
def word_group_time_loc(df, search, start_sent, end_sent, sent, sent_video_id):
    '''
    word_group_time_loc(df_search_result, "search_string", "start_time", "end_time", "sentence", "video_id")\n
    df_search_result is dataframe and "search_string", "start_time", "end_time", "sentence", "video_id" are its columns
    '''
    df.reset_index(drop=True, inplace=True)
    word_time_loc_list = []
    for i in range(len(df)):
        word = df.loc[i,f"{search}"]
        start_time = df.loc[i,f"{start_sent}"]
        end_time = df.loc[i,f"{end_sent}"]
        sentence = df.loc[i,f"{sent}"]
        video_id = df.loc[i,f"{sent_video_id}"]
        time_length = end_time-start_time
        sentence_length = len(sentence)
        time_length_ratio = time_length/sentence_length
        loc_list = []
        for j in re.finditer(fr"(?:\s|^){word}(?:\s|$)", sentence, re.IGNORECASE|re.UNICODE):
            loc_list.append(j)
            start = loc_list[0].start()
            end = loc_list[0].end()
            start_loc = start_time+(start*time_length_ratio)
            end_loc = start_time+(end*time_length_ratio)
        word_time_loc_list.append([word,start_loc,end_loc,sentence,video_id])
    df_word_time_loc = pd.DataFrame(word_time_loc_list, columns=[f"{search}",f"{start_sent}",f"{end_sent}",f"{sent}",f"{sent_video_id}"])

    return df_word_time_loc

In [108]:
def word_count_result(df, column_list, set_condition=False): # df is dataframe, column_list is list value
    '''
    word_count_bool(df, column_list): df columns word count for word frequency\n
    df is dataframe, column_list is list value\n
    word_count_bool(df, ["word","twogram"]):
    '''
    list_all = []
    for i in df.loc[:,[x for x in column_list]].columns:
        if set_condition:
            var_list = set(df[f"{i}"].dropna().tolist())
        else:
            var_list = df[f"{i}"].dropna().tolist()
        for j in var_list:
            list_all.append(j)
    text = " ".join(list_all)
    word_list = re.findall(r"\w+",text, re.UNICODE)
    df_word_list = pd.DataFrame(word_list, columns=["word"])
    #df_word_list.rename(columns={0:"word"}, inplace=True)
    df_word_count = pd.DataFrame(df_word_list.value_counts())
    df_word_count.reset_index(inplace=True)
    df_word_count.rename(columns={0:"word_count"}, inplace=True)
    df_word_count.sort_values("word_count", ascending=False, inplace=True)
    df_word_count.reset_index(inplace=True, drop=True)
    
    return  df_word_count

In [109]:
def word_usage_result(word_list, df_target, target_column, target_opt_column, word_usage_min, word_usage_max):
    '''
    word_usage_result(word_list, df_ngram_pair, "threegram", "frequency", 1, 5) \n
    word_list is a list, df_target is a dateframe, target_column is df_target dataframe target column, \n
    target_opt_column is df_target dataframe opt_target column, \n
    word_usage_min and word_usage_max word usage condition.
    '''    
    word_num_dict = {}
    for i in word_list:
        word_num_dict[f"{i}"] = 0
    
    result_list_select = []
    var_list = []
    for i in range(len(df_target)):
        target_value = df_target.loc[i,f"{target_column}"]
        opt_value = df_target.loc[i,f"{target_opt_column}"]
        words = word_tokenize(target_value)   
        temp_list = [word for word in words]
        temp_list = temp_list + var_list
        # word count for max
        dict_list_count = Counter(temp_list)
        count_list = list(dict_list_count.values())
        # word count for min
        count_list2 = list(word_num_dict.values())
    
        if any([True if i>word_usage_max else False for i in count_list]) or not(any([True if j<word_usage_min else False for j in count_list2])):
            pass
        else:
            var_list = temp_list
            result_list_select.append([target_value,opt_value]) 
    
            for item2 in dict_list_count.items(): 
                word_num_dict[item2[0]] = item2[1]        
    df_result = pd.DataFrame(result_list_select, columns=[f"{target_column}",f"{target_opt_column}"])
    df_result.sort_values(by="frequency", ascending=False, inplace=True)
    df_result.reset_index(drop=True, inplace=True)
    
    return df_result

In [110]:
path = f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/{lang_folder.capitalize()}/\
Talk Time/Result/Adjust Data Repeat"

Path(path).mkdir(parents=True, exist_ok=True)

In [ ]:
df_file = pd.read_excel("")
df_file

In [ ]:
search_list = df_file.iloc[:,[0]].to_list()

In [111]:
#disable_video_id_list = ["H6E6N70jYqI","BoaYsdPtJYA","HUZINsU40Fk","Et3diPcEmfY"]
disable_video_id_list = []

In [123]:
df_youtube_sentence = pd.read_csv(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Youtube/Result/{lang_folder.capitalize()}/Sentence Clean Merge/Clean_Youtube_Sentence_Merge_Result.csv")
df_youtube_sentence

,start_time,end_time,sentence,video_id
0,00:00:10.760,00:00:13.200,jongens hier ben ik dan,WA8MV8nX9s0
1,00:00:13.200,00:00:17.040,en we gaan iets heel maar dan ook heel geks me...,WA8MV8nX9s0
2,00:00:17.040,00:00:19.320,ik bedoel we gaan naar de royal bridge suite,WA8MV8nX9s0
3,00:00:19.900,00:00:23.760,dit is de meest luxe suite die je maar kan bed...,WA8MV8nX9s0
4,00:00:23.760,00:00:25.860,de meest bekende mensen hebben hier geslapen,WA8MV8nX9s0
...,...,...,...,...
611565,00:01:10.600,00:01:12.440,ik geloof in de kracht van kinderen,N0rCE0Ot8Os
611566,00:01:12.760,00:01:16.160,die instelling geven wij ook mee geloof in jezelf,N0rCE0Ot8Os
611567,00:01:17.000,00:01:18.920,mijn naam is melvin kolf,N0rCE0Ot8Os
611568,00:01:19.000,00:01:22.160,wil jij meer weten over leren en werken in dez...,N0rCE0Ot8Os
611569,00:01:22.240,00:01:25.360,kom dan langs in de week van zorg en welzijn,N0rCE0Ot8Os

In [124]:
df_youtube_sentence = df_youtube_sentence[~df_youtube_sentence["video_id"].isin(disable_video_id_list)]
df_youtube_sentence

,start_time,end_time,sentence,video_id
0,00:00:10.760,00:00:13.200,jongens hier ben ik dan,WA8MV8nX9s0
1,00:00:13.200,00:00:17.040,en we gaan iets heel maar dan ook heel geks me...,WA8MV8nX9s0
2,00:00:17.040,00:00:19.320,ik bedoel we gaan naar de royal bridge suite,WA8MV8nX9s0
3,00:00:19.900,00:00:23.760,dit is de meest luxe suite die je maar kan bed...,WA8MV8nX9s0
4,00:00:23.760,00:00:25.860,de meest bekende mensen hebben hier geslapen,WA8MV8nX9s0
...,...,...,...,...
611565,00:01:10.600,00:01:12.440,ik geloof in de kracht van kinderen,N0rCE0Ot8Os
611566,00:01:12.760,00:01:16.160,die instelling geven wij ook mee geloof in jezelf,N0rCE0Ot8Os
611567,00:01:17.000,00:01:18.920,mijn naam is melvin kolf,N0rCE0Ot8Os
611568,00:01:19.000,00:01:22.160,wil jij meer weten over leren en werken in dez...,N0rCE0Ot8Os
611569,00:01:22.240,00:01:25.360,kom dan langs in de week van zorg en welzijn,N0rCE0Ot8Os

In [125]:
df_youtube_sentence['start_time'] = pd.to_timedelta(df_youtube_sentence['start_time']) # data type converted timedelta for second 
df_youtube_sentence['end_time'] = pd.to_timedelta(df_youtube_sentence['end_time'])

<ipython-input-125-a8911ca4399e>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_youtube_sentence['start_time'] = pd.to_timedelta(df_youtube_sentence['start_time']) # data type converted timedelta for second
<ipython-input-125-a8911ca4399e>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_youtube_sentence['end_time'] = pd.to_timedelta(df_youtube_sentence['end_time'])

In [126]:
df_youtube_sentence['start_time'] = df_youtube_sentence['start_time'].apply(lambda x: x.total_seconds()) # convert seconds
df_youtube_sentence['end_time'] = df_youtube_sentence['end_time'].apply(lambda x: x.total_seconds())
df_youtube_sentence

<ipython-input-126-aa25c83efaa1>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_youtube_sentence['start_time'] = df_youtube_sentence['start_time'].apply(lambda x: x.total_seconds()) # convert seconds
<ipython-input-126-aa25c83efaa1>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_youtube_sentence['end_time'] = df_youtube_sentence['end_time'].apply(lambda x: x.total_seconds())

,start_time,end_time,sentence,video_id
0,10.76,13.20,jongens hier ben ik dan,WA8MV8nX9s0
1,13.20,17.04,en we gaan iets heel maar dan ook heel geks me...,WA8MV8nX9s0
2,17.04,19.32,ik bedoel we gaan naar de royal bridge suite,WA8MV8nX9s0
3,19.90,23.76,dit is de meest luxe suite die je maar kan bed...,WA8MV8nX9s0
4,23.76,25.86,de meest bekende mensen hebben hier geslapen,WA8MV8nX9s0
...,...,...,...,...
611565,70.60,72.44,ik geloof in de kracht van kinderen,N0rCE0Ot8Os
611566,72.76,76.16,die instelling geven wij ook mee geloof in jezelf,N0rCE0Ot8Os
611567,77.00,78.92,mijn naam is melvin kolf,N0rCE0Ot8Os
611568,79.00,82.16,wil jij meer weten over leren en werken in dez...,N0rCE0Ot8Os
611569,82.24,85.36,kom dan langs in de week van zorg en welzijn,N0rCE0Ot8Os

In [144]:
df_word_group = word_group_youtube(df_youtube_sentence, search_list, "sentence", sample_num)
df_word_group

,search_string,start_time,end_time,sentence,video_id
0,is dat zo,599.640,603.920,en op moment dat ik het een keer verkeerd loop...,VjYg2X32ryM
1,is dat zo,91.542,96.876,wat is er aan de hand in iran en waarom is dat...,ypikak3H9MI
2,is dat zo,623.281,625.176,is dat zo scherp bij transport van mest,USIYNJg2qSw
3,is dat zo,17.799,24.190,is dat zo ja ik werd vanochtend wakker om zes ...,NMUAd5R67K0
4,is dat zo,73.160,75.160,is dat zo zijn jullie altijd zo rustig,cUB3dxLXvSc
...,...,...,...,...,...
58,weet ik niet,41.420,43.780,hoe het eruit ziet als het straks gemengd is d...,RR2Xly7O0jA
59,weet ik niet,3788.080,3789.800,dat weet ik niet,1idPrF17UP0
60,weet ik niet,1380.570,1385.669,dat klopt dat is het en dan krijg je dat ie ee...,XRBb17aWENc
61,weet ik niet,158.080,160.080,weet ik niet ik keek hier door heen,SY4Gv78Mxbw
62,weet ik niet,54.380,57.000,dat weet ik niet dat ligt een beetje aan de di...,ebrpR5554yM

In [145]:
df_word_group_time_loc = word_group_time_loc(df_word_group, "search_string", "start_time", "end_time", "sentence", "video_id")
df_word_group_time_loc

,search_string,start_time,end_time,sentence,video_id
0,is dat zo,603.251250,603.920000,en op moment dat ik het een keer verkeerd loop...,VjYg2X32ryM
1,is dat zo,95.324291,96.391091,wat is er aan de hand in iran en waarom is dat...,ypikak3H9MI
2,is dat zo,623.281000,623.766897,is dat zo scherp bij transport van mest,USIYNJg2qSw
3,is dat zo,17.799000,18.639921,is dat zo ja ik werd vanochtend wakker om zes ...,NMUAd5R67K0
4,is dat zo,73.160000,73.686316,is dat zo zijn jullie altijd zo rustig,cUB3dxLXvSc
...,...,...,...,...,...
58,weet ik niet,43.277049,43.780000,hoe het eruit ziet als het straks gemengd is d...,RR2Xly7O0jA
59,weet ik niet,3788.402500,3789.800000,dat weet ik niet,1idPrF17UP0
60,weet ik niet,1384.683966,1385.495170,dat klopt dat is het en dan krijg je dat ie ee...,XRBb17aWENc
61,weet ik niet,158.080000,158.822857,weet ik niet ik keek hier door heen,SY4Gv78Mxbw
62,weet ik niet,54.504762,55.086984,dat weet ik niet dat ligt een beetje aan de di...,ebrpR5554yM

In [146]:
df_word_group_time_loc.start_time = df_word_group_time_loc.start_time.apply(lambda x: (x-time_shift))
df_word_group_time_loc.end_time = df_word_group_time_loc.end_time.apply(lambda x: (x+time_shift))
df_word_group_time_loc

,search_string,start_time,end_time,sentence,video_id
0,is dat zo,602.651250,604.520000,en op moment dat ik het een keer verkeerd loop...,VjYg2X32ryM
1,is dat zo,94.724291,96.991091,wat is er aan de hand in iran en waarom is dat...,ypikak3H9MI
2,is dat zo,622.681000,624.366897,is dat zo scherp bij transport van mest,USIYNJg2qSw
3,is dat zo,17.199000,19.239921,is dat zo ja ik werd vanochtend wakker om zes ...,NMUAd5R67K0
4,is dat zo,72.560000,74.286316,is dat zo zijn jullie altijd zo rustig,cUB3dxLXvSc
...,...,...,...,...,...
58,weet ik niet,42.677049,44.380000,hoe het eruit ziet als het straks gemengd is d...,RR2Xly7O0jA
59,weet ik niet,3787.802500,3790.400000,dat weet ik niet,1idPrF17UP0
60,weet ik niet,1384.083966,1386.095170,dat klopt dat is het en dan krijg je dat ie ee...,XRBb17aWENc
61,weet ik niet,157.480000,159.422857,weet ik niet ik keek hier door heen,SY4Gv78Mxbw
62,weet ik niet,53.904762,55.686984,dat weet ik niet dat ligt een beetje aan de di...,ebrpR5554yM

In [147]:
df_word_group_time_loc.start_time = df_word_group_time_loc.start_time.apply(lambda x: round(x))
df_word_group_time_loc.end_time = df_word_group_time_loc.end_time.apply(lambda x: round(x))
df_word_group_time_loc

,search_string,start_time,end_time,sentence,video_id
0,is dat zo,603,605,en op moment dat ik het een keer verkeerd loop...,VjYg2X32ryM
1,is dat zo,95,97,wat is er aan de hand in iran en waarom is dat...,ypikak3H9MI
2,is dat zo,623,624,is dat zo scherp bij transport van mest,USIYNJg2qSw
3,is dat zo,17,19,is dat zo ja ik werd vanochtend wakker om zes ...,NMUAd5R67K0
4,is dat zo,73,74,is dat zo zijn jullie altijd zo rustig,cUB3dxLXvSc
...,...,...,...,...,...
58,weet ik niet,43,44,hoe het eruit ziet als het straks gemengd is d...,RR2Xly7O0jA
59,weet ik niet,3788,3790,dat weet ik niet,1idPrF17UP0
60,weet ik niet,1384,1386,dat klopt dat is het en dan krijg je dat ie ee...,XRBb17aWENc
61,weet ik niet,157,159,weet ik niet ik keek hier door heen,SY4Gv78Mxbw
62,weet ik niet,54,56,dat weet ik niet dat ligt een beetje aan de di...,ebrpR5554yM

In [148]:
df_word_group_time_loc["video_url"] = "https://www.youtube.com/watch?v="+df_word_group_time_loc['video_id'].map(str)+"&t="+df_word_group_time_loc['start_time'].map(str)+"s"
df_word_group_time_loc

,search_string,start_time,end_time,sentence,video_id,video_url
0,is dat zo,603,605,en op moment dat ik het een keer verkeerd loop...,VjYg2X32ryM,https://www.youtube.com/watch?v=VjYg2X32ryM&t=...
1,is dat zo,95,97,wat is er aan de hand in iran en waarom is dat...,ypikak3H9MI,https://www.youtube.com/watch?v=ypikak3H9MI&t=95s
2,is dat zo,623,624,is dat zo scherp bij transport van mest,USIYNJg2qSw,https://www.youtube.com/watch?v=USIYNJg2qSw&t=...
3,is dat zo,17,19,is dat zo ja ik werd vanochtend wakker om zes ...,NMUAd5R67K0,https://www.youtube.com/watch?v=NMUAd5R67K0&t=17s
4,is dat zo,73,74,is dat zo zijn jullie altijd zo rustig,cUB3dxLXvSc,https://www.youtube.com/watch?v=cUB3dxLXvSc&t=73s
...,...,...,...,...,...,...
58,weet ik niet,43,44,hoe het eruit ziet als het straks gemengd is d...,RR2Xly7O0jA,https://www.youtube.com/watch?v=RR2Xly7O0jA&t=43s
59,weet ik niet,3788,3790,dat weet ik niet,1idPrF17UP0,https://www.youtube.com/watch?v=1idPrF17UP0&t=...
60,weet ik niet,1384,1386,dat klopt dat is het en dan krijg je dat ie ee...,XRBb17aWENc,https://www.youtube.com/watch?v=XRBb17aWENc&t=...
61,weet ik niet,157,159,weet ik niet ik keek hier door heen,SY4Gv78Mxbw,https://www.youtube.com/watch?v=SY4Gv78Mxbw&t=...
62,weet ik niet,54,56,dat weet ik niet dat ligt een beetje aan de di...,ebrpR5554yM,https://www.youtube.com/watch?v=ebrpR5554yM&t=54s

In [149]:
word_count_result(df_word_group_time_loc, ["search_string"], set_condition=True)

     word  word_count
0      is           4
1     wie           2
2      ik           2
3     dat           2
4    gaan           2
5   laten           1
6    goed           1
7     het           1
8     hij           1
9      je           1
10    jij           1
11   moet           1
12    wat           1
13   waar           1
14     we           1
15   weet           1
16    wil           1
17   niet           1
18    ben           1
19     zo           1

In [150]:
#df_word_group_time_loc.to_excel(f"{lang_folder.capitalize()}_Word_Group_With_{word_end}_Word_{sample_num}_Youtube_{time_shift}s_Timeshift_For_Talk_Time_Result.xlsx", index=False)