### Etymology TVS File

In [49]:
import pandas as pd
import numpy as np
import glob
import re
import nltk
from nltk import word_tokenize
from pathlib import Path
import shutil

#### Read TVS And Convert

In [50]:
#df_tvs = pd.read_csv("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Data/All/etymwn.tsv", sep="\t")
#df_tvs.rename(columns={"aaq: Pawanobskewi":"column_1","rel:etymological_origin_of":"column_2","eng: Penobscot":"column_3"}, inplace=True)
#df_tvs

In [51]:
#def low_func(x):
#    try:
#        var_out = x.lower()
#    except:
#        var_out = x
#    return var_out

In [52]:
#def strip_func(x):
#    try:
#        var_out = x.strip()
#    except:
#        var_out = x
#    return var_out

In [53]:
#df_col_1 = df_tvs["column_1"].str.split(":", n=-1, expand=True)
#df_col_1 = df_col_1.iloc[:,[0,1]]
#df_col_1.rename(columns={0:"lang",1:"term"}, inplace=True)
#df_col_2 = df_tvs["column_2"].str.split(":", n=-1, expand=True)
#df_col_2 = df_col_2.iloc[:,[1]]
#df_col_2.rename(columns={1:"reltype"}, inplace=True)
#df_col_3 = df_tvs["column_3"].str.split(":", n=-1, expand=True)
#df_col_3 = df_col_3.iloc[:,[0,1]]
#df_col_3.rename(columns={0:"related_lang",1:"related_term"}, inplace=True)

In [54]:
#df_tvs_expand =  pd.concat([df_col_1,df_col_2,df_col_3], axis=1)
#df_tvs_expand

In [55]:
#df_tvs_expand["lang"] = df_tvs_expand["lang"].apply(lambda x: low_func(x))
#df_tvs_expand["lang"] = df_tvs_expand["lang"].apply(lambda x: strip_func(x))
#df_tvs_expand["term"] = df_tvs_expand["term"].apply(lambda x: low_func(x))
#df_tvs_expand["term"] = df_tvs_expand["term"].apply(lambda x: strip_func(x))
#df_tvs_expand["reltype"] = df_tvs_expand["reltype"].apply(lambda x: low_func(x))
#df_tvs_expand["reltype"] = df_tvs_expand["reltype"].apply(lambda x: strip_func(x))
#df_tvs_expand["related_lang"] = df_tvs_expand["related_lang"].apply(lambda x: low_func(x))
#df_tvs_expand["related_lang"] = df_tvs_expand["related_lang"].apply(lambda x: strip_func(x))
#df_tvs_expand["related_term"] = df_tvs_expand["related_term"].apply(lambda x: low_func(x))
#df_tvs_expand["related_term"] = df_tvs_expand["related_term"].apply(lambda x: strip_func(x))

In [56]:
#df_tvs_expand.to_csv("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Data/All/etymwn.csv", index=False)

#### Read CSV File

##### Part 1

In [57]:
df_etymology = pd.read_csv("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Data/All/etymwn.csv")
df_etymology

        lang      term                 reltype related_lang   related_term
0        aaq    senabe  etymological_origin_of          eng         sannup
1        abe  waniigan  etymological_origin_of          eng         wangan
2        abe  waniigan  etymological_origin_of          eng       wannigan
3        abs      beta  etymological_origin_of          zsm           beta
4        adt      yuru  etymological_origin_of          eng           euro
...      ...       ...                     ...          ...            ...
6031425  zul       ya-  etymological_origin_of          zul  inhlamvu yeso
6031426  zul       ya-  etymological_origin_of          zul  inja yasendle
6031427  zul       zi-         is_derived_from          zul           izi-
6031428  zul      zim-         is_derived_from          zul          izim-
6031429  zul      zin-         is_derived_from          zul          izin-

[6031430 rows x 5 columns]

In [58]:
df_etymology[df_etymology["term"] == "radar"]

        lang   term                 reltype related_lang       related_term
221368   deu  radar  etymological_origin_of          deu          radarecho
221369   deu  radar        has_derived_form          deu             radare
221370   deu  radar        has_derived_form          deu             radars
1084071  eng  radar  etymological_origin_of          eng             jewdar
1084072  eng  radar  etymological_origin_of          eng          antiradar
1084073  eng  radar  etymological_origin_of          eng             gaydar
1084074  eng  radar  etymological_origin_of          eng              lidar
1084075  eng  radar  etymological_origin_of          eng           nonradar
1084076  eng  radar  etymological_origin_of          eng          radargram
1084077  eng  radar  etymological_origin_of          eng           subradar
1084078  eng  radar  etymological_origin_of          glg              radar
1084079  eng  radar  etymological_origin_of          jpn               レーダー
1084080  eng  radar  etymological_origin_of          spa              radar
1084081  eng  radar  etymologically_related          eng              lidar
1084082  eng  radar  etymologically_related          eng              sonar
1084083  eng  radar        has_derived_form          eng               -dar
1084084  eng  radar        has_derived_form          eng             jewdar
1084085  eng  radar        has_derived_form          eng             gaydar
1084086  eng  radar        has_derived_form          eng    monopulse radar
1084087  eng  radar        has_derived_form          eng      off the radar
1084088  eng  radar        has_derived_form          eng      passive radar
1084089  eng  radar        has_derived_form          eng    radar astronomy
1084090  eng  radar        has_derived_form          eng         radar dome
1084091  eng  radar        has_derived_form          eng  radar meteorology
1084092  eng  radar        has_derived_form          eng    radar reflector
1084093  eng  radar        has_derived_form          eng    radar telescope
1084094  eng  radar        has_derived_form          eng            radared
1084095  eng  radar        has_derived_form          eng           radaring
1084096  eng  radar        has_derived_form          eng             radars
1084097  eng  radar        has_derived_form          eng             radome
1084098  eng  radar        has_derived_form          eng    under the radar
2184059  fra  radar  etymological_origin_of          fra           géoradar
2184060  fra  radar        has_derived_form          fra            radares
2184061  fra  radar        has_derived_form          fra             radars
2435689  glg  radar               etymology          eng              radar
2435690  glg  radar        has_derived_form          glg            radares
3285721  ita  radar  etymological_origin_of          ita          antiradar
3285722  ita  radar  etymological_origin_of          ita         radarabile
3285723  ita  radar  etymological_origin_of          ita        radaristica
3285724  ita  radar  etymologically_related          ita          radarista
3285725  ita  radar  etymologically_related          ita        radaristica
4712105  lat  radar         is_derived_from          lat               rado
5723849  spa  radar               etymology          eng              radar
5910954  tur  radar        has_derived_form          tur           radarlar
5910955  tur  radar        has_derived_form          tur             radarı
5910956  tur  radar        has_derived_form          tur            radarın

In [59]:
lang_1 = "eng"  # tur, eng, fra, deu, por, spa, ita, nld, ara, rus
lang_2 = "tur"  # tur, eng, fra, deu, por, spa, ita, nld, ara, rus

if lang_1 == "tur":
    lang_3 = "Turkish"
elif lang_1 == "eng":
    lang_3 = "English"
elif lang_1 == "fra":
    lang_3 = "French"
elif lang_1 == "deu":
    lang_3 = "German"
elif lang_1 == "por":
    lang_3 = "Portuguese"
elif lang_1 == "spa":
    lang_3 = "Spanish"
elif lang_1 == "ita":
    lang_3 = "Italian"
elif lang_1 == "nld":
    lang_3 = "Dutch"
elif lang_1 == "ara":
    lang_3 = "Arabic"
elif lang_1 == "rus":
    lang_3 = "Russian"
else:
    pass

if lang_2 == "tur":
    lang_4 = "Turkish"
elif lang_2 == "eng":
    lang_4 = "English"
elif lang_2 == "fra":
    lang_4 = "French"
elif lang_2 == "deu":
    lang_4 = "German"
elif lang_2 == "por":
    lang_4 = "Portuguese"
elif lang_2 == "spa":
    lang_4 = "Spanish"
elif lang_2 == "ita":
    lang_4 = "Italian"
elif lang_2 == "nld":
    lang_4 = "Dutch"
elif lang_2 == "ara":
    lang_4 = "Arabic"
elif lang_2 == "rus":
    lang_4 = "Russian"
else:
    pass

print(f"{lang_1}\n{lang_2}\n{lang_3}\n{lang_4}")

eng
tur
English
Turkish

In [60]:
#Path(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Web Scrapping/Result/{lang_3.capitalize()}").mkdir(parents=True, exist_ok=True)

In [61]:
df_lang1 = df_etymology[df_etymology.lang == f"{lang_1.lower()}"]
df_lang1.reset_index(drop=True, inplace=True)
df_lang1 = df_lang1[~(df_lang1["related_lang"] == f"{lang_1.lower()}")]
df_lang1 = df_lang1[~(df_lang1["related_lang"] == f"{lang_2.lower()}")]
df_lang1

,lang,term,reltype,related_lang,related_term
12,eng,''[[belly]] [[hot]]'',etymological_origin_of,tpi,belhat
13,eng,''[[body]] [[check]]'',etymological_origin_of,jpn,bodīchekku
14,eng,''[[body]] [[check]]'',etymological_origin_of,jpn,ボディーチェック
15,eng,''[[cane]] [[top]]'',etymological_origin_of,hif,kantaap
16,eng,''[[come]] [[up]]'',etymological_origin_of,tpi,kamap
...,...,...,...,...,...
990944,eng,œnotrus,etymology,grc,οἴνωτρος
990945,eng,œnoë,etymology,grc,οἰνόη
990999,eng,œcumene,etymology,lat,oecumenicus
991146,eng,стриптиз,etymological_origin_of,hye,ստրիպտիզ
991149,eng,ḍamma,etymology,ara,ضمة

In [62]:
df_lang2 = df_etymology[df_etymology.lang == f"{lang_2.lower()}"]
df_lang2.reset_index(drop=True, inplace=True)
df_lang2 = df_lang2[~(df_lang2["related_lang"] == f"{lang_1.lower()}")]
df_lang2 = df_lang2[~(df_lang2["related_lang"] == f"{lang_2.lower()}")]
df_lang2

      lang    term                 reltype related_lang related_term
118    tur     -cı  etymological_origin_of          lad         -djí
457    tur    -luk  etymological_origin_of          hbs         -luk
996    tur     -çi  etymological_origin_of          hye          -չի
1066   tur   allah  etymological_origin_of          rus        аллах
1067   tur   allah               etymology          ara         الله
...    ...     ...                     ...          ...          ...
22642  tur    نجار  etymological_origin_of          hye     նաջարյան
22643  tur    نجار  etymological_origin_of          hye        նաջար
22644  tur  ‏پاشا‎  etymological_origin_of          hun         pasa
22645  tur    ﮔﺎﻭﺭ  etymological_origin_of          hun        gyaur
22646  tur    ﮔﺎﻭﺭ               etymology          fas          گبر

[2268 rows x 5 columns]

In [63]:
df_lang1_lang2 = pd.merge(df_lang1,df_lang2,how="inner",on=["related_lang","related_term"])
df_lang1_lang2.drop_duplicates(inplace=True)
df_lang1_lang2.reset_index(drop=True, inplace=True)
df_lang1_lang2

,lang_x,term_x,reltype_x,related_lang,related_term,lang_y,term_y,reltype_y
0,eng,al jazeera,etymology,ara,جزيرة,tur,cezire,etymology
1,eng,algiedi,etymology,ara,جدي,tur,ciddi,etymology
2,eng,allah,etymology,ara,الله,tur,allah,etymology
3,eng,aristotle,etymology,grc,ἀριστοτέλης,tur,aristo,etymology
4,eng,augustus,etymology,lat,augustus,tur,ağustos,etymology
...,...,...,...,...,...,...,...,...
233,eng,waw,etymology,ara,واو,tur,vav,etymology
234,eng,wolfram,etymology,deu,wolfram,tur,volfram,etymology
235,eng,yogourt,etymology,fra,yogourt,tur,yoğurt,etymological_origin_of
236,eng,zulm,etymology,ara,ظلم,tur,zulüm,etymology
237,eng,éclair,etymology,fra,éclair,tur,ekler,etymology

In [64]:
df_lang1_lang2_result1 = df_lang1_lang2.loc[:,["term_x","term_y"]]
df_lang1_lang2_result1.rename(columns={"term_x":"dict_entry_main","term_y":f"{lang_4.lower()}_word"}, inplace=True)
df_lang1_lang2_result1.reset_index(drop=True, inplace=True)
df_lang1_lang2_result1

    dict_entry_main turkish_word
0        al jazeera       cezire
1           algiedi        ciddi
2             allah        allah
3         aristotle       aristo
4          augustus      ağustos
..              ...          ...
233             waw          vav
234         wolfram      volfram
235         yogourt       yoğurt
236            zulm        zulüm
237          éclair        ekler

[238 rows x 2 columns]

##### Part 2

In [65]:
df_lang1_lang2_result2 = df_etymology[(df_etymology["lang"] == f"{lang_1.lower()}") & (df_etymology["related_lang"] == f"{lang_2.lower()}")]
df_lang1_lang2_result2

        lang            term    reltype related_lang    related_term
395536   eng  afyonkarahisar  etymology          tur  afyonkarahisar
397398   eng            aras  etymology          tur            aras
397749   eng          arnaut  etymology          tur         arnavut
397965   eng           aslan  etymology          tur           aslan
399195   eng          balkan  etymology          tur          balkan
...      ...             ...        ...          ...             ...
1334909  eng           yuruk  etymology          tur           yürük
1335133  eng            zarf  etymology          tur            zarf
1335881  eng          ziamet  etymology          tur          zeamet
1335954  eng            zill  etymology          tur             zil
1337849  eng           zurna  etymology          tur           zurna

[166 rows x 5 columns]

In [66]:
df_lang1_lang2_result2 = df_lang1_lang2_result2.loc[:,["term","related_term"]]
df_lang1_lang2_result2.rename(columns={"term":"dict_entry_main","related_term":f"{lang_4.lower()}_word"}, inplace=True)
df_lang1_lang2_result2.reset_index(drop=True, inplace=True)
df_lang1_lang2_result2

    dict_entry_main    turkish_word
0    afyonkarahisar  afyonkarahisar
1              aras            aras
2            arnaut         arnavut
3             aslan           aslan
4            balkan          balkan
..              ...             ...
161           yuruk           yürük
162            zarf            zarf
163          ziamet          zeamet
164            zill             zil
165           zurna           zurna

[166 rows x 2 columns]

##### Concat Part 1 And Part 2

In [67]:
#df_part1_part2_concat = pd.concat([df_lang1_lang2_word_check,df_lang1_lang2_word_check2], axis=0)
df_part1_part2_concat = pd.concat([df_lang1_lang2_result1,df_lang1_lang2_result2], axis=0)
df_part1_part2_concat.drop_duplicates(inplace=True)
df_part1_part2_concat.reset_index(drop=True, inplace=True)
df_part1_part2_concat

    dict_entry_main turkish_word
0        al jazeera       cezire
1           algiedi        ciddi
2             allah        allah
3         aristotle       aristo
4          augustus      ağustos
..              ...          ...
396           yuruk        yürük
397            zarf         zarf
398          ziamet       zeamet
399            zill          zil
400           zurna        zurna

[401 rows x 2 columns]

In [68]:
df_part1_part2_concat.to_excel(f"{lang_3.capitalize()}_And_{lang_4.capitalize()}_Etymologeek_Concat_Result2.xlsx", index=False)