### Youtube Sentence Adjust Word List Ratio

In [1]:
import pandas as pd
import numpy as np
import re
import glob

In [2]:
folder_name = "Turkish"
word_num = 28

In [3]:
df_adjust_word = pd.read_excel(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/{folder_name.lower().capitalize()}/Deployment/Result/Level 1/Word_{word_num}.xlsx")
df_adjust_word

     word  frequency
0     bir   18835735
1      bu   11062659
2      ne    8025880
3      ve    7766036
4    için    5484109
5      mi    5362714
6     ben    4908913
7      de    4880315
8     çok    4852169
9     ama    4661966
10    var    4389551
11   evet    4324786
12     mı    4001316
13  değil    3883885
14     da    3610161
15    şey    3602024
16  hayır    3406992
17   daha    3317577
18    sen    3283654
19  kadar    2697900
20   bana    2659182
21    yok    2491685
22    onu    2486889
23   seni    2454988
24   beni    2446696
25   bunu    2445337
26   gibi    2427957
27    iyi    2383224

In [24]:
df_youtube_sentence = pd.read_csv(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Youtube/Result/{folder_name.lower().capitalize()}/Sentence Clean Merge/Clean_Youtube_Sentence_Merge_Result.csv")
df_youtube_sentence = df_youtube_sentence.head(5000)
df_youtube_sentence

In [27]:
def sentence_word_ratio(df_word,df_sentence, word_column_name, sentence_column_name, word_num): # df_word and df_sentence are dataframe, word_column_name and sentence_column_name are string, word_num is an integer
    word_set = set(df_word[f"{word_column_name}"].to_list())
    for i in range(len(df_sentence)):
        sentence = df_sentence.loc[i,f"{sentence_column_name}"]
        sent_word = re.findall(r"\w+", sentence, re.UNICODE)
        sent_word_set = set(sent_word)
        intersect_word = word_set.intersection(sent_word_set)
        different_word = sent_word_set.difference(word_set)
        df_sentence.loc[i,f"{word_num}_word_ratio"] = (len(intersect_word)/len(sent_word)+0.01)*100
        df_sentence.loc[i,"different_word"] = [different_word]
        #df_sentence.loc[i,"intersect_word"] = [intersect_word]

    df_sentence.reset_index(inplace=True)    
    return df_sentence

In [28]:
sentence_word_ratio(df_adjust_word,df_youtube_sentence,"word","sentence",28)

,index,start_time,end_time,sentence,video_id,28_word_ratio,different_word
0,0,00:00:06.680,00:00:07.340,sen kimsin peki,JR7nKXxUVtM,34.333333,"{kimsin, peki}"
1,1,00:00:07.340,00:00:08.600,parolayı söyle,JR7nKXxUVtM,1.000000,"{parolayı, söyle}"
2,2,00:00:09.440,00:00:11.060,ya ben kim olacağım,JR7nKXxUVtM,26.000000,"{kim, olacağım, ya}"
3,3,00:00:11.060,00:00:11.860,keloğlan ım,JR7nKXxUVtM,1.000000,"{ım, keloğlan}"
4,4,00:00:13.380,00:00:13.880,ey,JR7nKXxUVtM,1.000000,{ey}
...,...,...,...,...,...,...,...
4995,4995,00:03:26.780,00:03:28.160,böyle bile yiyebiliriz,cQjX9DzXTw0,1.000000,"{bile, böyle, yiyebiliriz}"
4996,4996,00:03:28.260,00:03:30.540,kıvama geldiğinde artık tamamdır,cQjX9DzXTw0,1.000000,"{kıvama, geldiğinde, artık, tamamdır}"
4997,4997,00:03:30.540,00:03:34.840,böyle ağzınıza böyle çıtır çıtır şeker tadı da...,cQjX9DzXTw0,8.692308,"{şeker, çıtır, lazım, o, böyle, önemli, gelmem..."
4998,4998,00:03:34.840,00:03:37.060,şimdi bundan sonra artık çırpıcı ile devam ede...,cQjX9DzXTw0,1.000000,"{devam, sonra, artık, bundan, çırpıcı, ile, şi..."
4999,4999,00:03:37.060,00:03:39.380,yumurtaları tek tek kırıp karıştıracağım,cQjX9DzXTw0,1.000000,"{tek, yumurtaları, kırıp, karıştıracağım}"

In [24]:
a = ["ali", "mehmet", "ahmet"]

In [25]:
set_a = set(a)

In [26]:
c = ["ali", "ceylan"]

In [27]:
set_c = set(c)

In [28]:
set_c.difference(set_a)

{'ceylan'}

In [29]:
set_c.intersection(set_a)

{'ali'}

In [14]:
b = set(a)

In [15]:
df_youtube_sentence.loc[1,"diff_word"] = b

In [16]:
df_youtube_sentence

,start_time,end_time,sentence,video_id,diff_word
0,00:00:06.680,00:00:07.340,sen kimsin peki,JR7nKXxUVtM,"ali, mehmet, ahmet"
1,00:00:07.340,00:00:08.600,parolayı söyle,JR7nKXxUVtM,"ali, mehmet, ahmet"
2,00:00:09.440,00:00:11.060,ya ben kim olacağım,JR7nKXxUVtM,NaN
3,00:00:11.060,00:00:11.860,keloğlan ım,JR7nKXxUVtM,NaN
4,00:00:13.380,00:00:13.880,ey,JR7nKXxUVtM,NaN
...,...,...,...,...,...
387903,00:02:11.720,00:02:14.440,gözlerin bir an bile çıkmadı aklımdan,7R3K6EDaBGE,NaN
387904,00:02:15.560,00:02:19.320,koynumdaysa hala o ufak bin lira,7R3K6EDaBGE,NaN
387905,00:02:20.320,00:02:21.200,sahi,7R3K6EDaBGE,NaN
387906,00:02:21.720,00:02:24.480,diğer eşi sende mi hala,7R3K6EDaBGE,NaN
387907,00:02:30.000,00:02:35.000,ufak bin lira,7R3K6EDaBGE,NaN