### Deploy Master Process

In [1]:
import pandas as pd
import numpy as np
import re
import json
import nltk
from nltk import word_tokenize

In [2]:
df_deploy_master = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quran/Text/Result/Deploy Result/Master 01042022.xlsx")
df_deploy_master

,surah,ayah,word rank,juz,page,surah arabic,surah latin,word count ayah,letter count ayah,tanzil_clean,...,twogram_bangla,twogram_russian,threegram_string,threegram_english,threegram_turkish,threegram_urdu,threegram_hindi,threegram_indonesian,threegram_bangla,threegram_russian
0,1,1,1,1,1,الفاتحة,Al-Fatiha,4,19,بسم,...,আল্লাহর নামে,Во имя Бога,بسم الله الرحمن,"in the name of ALLAH, the most mercifull",merhametli olan Allah adıyla,اللہ کے نام سے جو سب سے زیادہ رحم کرنے والا ہے۔,"अल्लाह के नाम पर, सबसे दयालु",dengan menyebut nama ALLAH yang maha penyayang,পরম করুণাময় আল্লাহর নামে,во имя АЛЛАХА Милостивого
1,1,1,2,1,1,الفاتحة,Al-Fatiha,4,19,الله,...,পরম করুণাময় ঈশ্বর,Бог Милостивый,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1,3,1,1,الفاتحة,Al-Fatiha,4,19,الرحمن,...,পরম করুণাময়,Самый Милосердный,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,1,4,1,1,الفاتحة,Al-Fatiha,4,19,الرحيم,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2,1,1,1,الفاتحة,Al-Fatiha,4,18,الحمد,...,সৃষ্টিকর্তাকে ধন্যবাদ,Слава Богу,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78242,114,5,4,30,604,الناس,An-Nas,5,20,صدور,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78243,114,5,5,30,604,الناس,An-Nas,5,20,الناس,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78244,114,6,1,30,604,الناس,An-Nas,3,13,من,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78245,114,6,2,30,604,الناس,An-Nas,3,13,الجنة,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78246,114,6,3,30,604,الناس,An-Nas,3,13,والناس,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df_deploy_master[df_deploy_master.ayah == 0].loc[:,["level 1", "level 2", "level 3", "level 4"]]

       level 1  level 2  level 3  level 4
29           1        2        3        0
30           1        2        3        0
31           1        2        3        0
32           1        2        2        0
6174         1        2        3        0
...        ...      ...      ...      ...
78199        1        2        2        0
78223        1        2        3        0
78224        1        2        3        0
78225        1        2        3        0
78226        1        2        2        0

[448 rows x 4 columns]

In [9]:
for i in range(len(df_deploy_master)):
    if df_deploy_master.loc[i,"ayah"] == 0:
        df_deploy_master.loc[i,"level 1"] = 0
        df_deploy_master.loc[i,"level 2"] = 0
        df_deploy_master.loc[i,"level 3"] = 0
        df_deploy_master.loc[i,"level 4"] = 0

In [10]:
df_deploy_master[df_deploy_master.ayah == 0].loc[:,["level 1", "level 2", "level 3", "level 4"]]

       level 1  level 2  level 3  level 4
29           0        0        0        0
30           0        0        0        0
31           0        0        0        0
32           0        0        0        0
6174         0        0        0        0
...        ...      ...      ...      ...
78199        0        0        0        0
78223        0        0        0        0
78224        0        0        0        0
78225        0        0        0        0
78226        0        0        0        0

[448 rows x 4 columns]

In [17]:
#df_deploy_master.to_excel("Master 20042022.xlsx", index=False)

#### Level 4 Disable

In [11]:
df_deploy_master = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quran/Text/Result/Deploy Result/Master 20042022.xlsx")
df_deploy_master

,surah,ayah,word rank,juz,page,surah arabic,surah latin,word count ayah,letter count ayah,tanzil_clean,...,twogram_bangla,twogram_russian,threegram_string,threegram_english,threegram_turkish,threegram_urdu,threegram_hindi,threegram_indonesian,threegram_bangla,threegram_russian
0,1,1,1,1,1,الفاتحة,Al-Fatiha,4,19,بسم,...,আল্লাহর নামে,Во имя Бога,بسم الله الرحمن,"in the name of ALLAH, the most mercifull",merhametli olan Allah adıyla,اللہ کے نام سے جو سب سے زیادہ رحم کرنے والا ہے۔,"अल्लाह के नाम पर, सबसे दयालु",dengan menyebut nama ALLAH yang maha penyayang,পরম করুণাময় আল্লাহর নামে,во имя АЛЛАХА Милостивого
1,1,1,2,1,1,الفاتحة,Al-Fatiha,4,19,الله,...,পরম করুণাময় ঈশ্বর,Бог Милостивый,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1,3,1,1,الفاتحة,Al-Fatiha,4,19,الرحمن,...,পরম করুণাময়,Самый Милосердный,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,1,4,1,1,الفاتحة,Al-Fatiha,4,19,الرحيم,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2,1,1,1,الفاتحة,Al-Fatiha,4,18,الحمد,...,সৃষ্টিকর্তাকে ধন্যবাদ,Слава Богу,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78242,114,5,4,30,604,الناس,An-Nas,5,20,صدور,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78243,114,5,5,30,604,الناس,An-Nas,5,20,الناس,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78244,114,6,1,30,604,الناس,An-Nas,3,13,من,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78245,114,6,2,30,604,الناس,An-Nas,3,13,الجنة,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78246,114,6,3,30,604,الناس,An-Nas,3,13,والناس,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df_deploy_master.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 78247 entries, 0 to 78246
Data columns (total 50 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   surah                         78247 non-null  int64
 1   ayah                          78247 non-null  int64
 2   word rank                     78247 non-null  int64
 3   juz                           78247 non-null  int64
 4   page                          78247 non-null  int64
 5   surah arabic                  78247 non-null  object
 6   surah latin                   78247 non-null  object
 7   word count ayah               78247 non-null  int64
 8   letter count ayah             78247 non-null  int64
 9   tanzil_clean                  78247 non-null  object
 10  buckwalter_word_tanzil_clean  78247 non-null  object
 11  tanzil_plain                  78247 non-null  object
 12  buckwalter_word_tanzil_plain  78247 non-null  object
 13  root                          49968 non-null  object
 14  root_arabic                   49968 non-null  object
 15  tag                           49967 non-null  object
 16  level 1                       78247 non-null  int64
 17  level 2                       78247 non-null  int64
 18  level 3                       78247 non-null  int64
 19  level 4                       78247 non-null  int64
 20  2gram                         78247 non-null  int64
 21  3gram                         78247 non-null  int64
 22  start_time                    77791 non-null  float64
 23  end_time                      77791 non-null  float64
 24  repeat flag                   0 non-null      float64
 25  index                         78247 non-null  int64
 26  arabic                        77799 non-null  object
 27  translate_english             77799 non-null  object
 28  translate_urdu                77798 non-null  object
 29  translate_hindi               77799 non-null  object
 30  translate_indonesian          77798 non-null  object
 31  translate_bangla              77799 non-null  object
 32  translate_turkish             77799 non-null  object
 33  translate_russian             77797 non-null  object
 34  twogram_string                7132 non-null   object
 35  twogram_english               7132 non-null   object
 36  twogram_turkish               7132 non-null   object
 37  twogram_urdu                  7132 non-null   object
 38  twogram_hindi                 7132 non-null   object
 39  twogram_indonesian            7132 non-null   object
 40  twogram_bangla                7132 non-null   object
 41  twogram_russian               7132 non-null   object
 42  threegram_string              3062 non-null   object
 43  threegram_english             3062 non-null   object
 44  threegram_turkish             3062 non-null   object
 45  threegram_urdu                3062 non-null   object
 46  threegram_hindi               3062 non-null   object
 47  threegram_indonesian          3062 non-null   object
 48  threegram_bangla              3062 non-null   object
 49  threegram_russian             3062 non-null   object
dtypes: float64(3), int64(14), object(33)
memory usage: 29.8+ MB

In [13]:
df_deploy_master[df_deploy_master.root == "Alh"]["level 4"].value_counts()

4    2851
Name: level 4, dtype: int64

In [14]:
for i in range(len(df_deploy_master)):
    if (df_deploy_master.loc[i,"root"] == "Alh") & (df_deploy_master.loc[i,"level 4"] == 4):
        df_deploy_master.loc[i,"level 4"] = 0

In [15]:
df_deploy_master

,surah,ayah,word rank,juz,page,surah arabic,surah latin,word count ayah,letter count ayah,tanzil_clean,...,twogram_bangla,twogram_russian,threegram_string,threegram_english,threegram_turkish,threegram_urdu,threegram_hindi,threegram_indonesian,threegram_bangla,threegram_russian
0,1,1,1,1,1,الفاتحة,Al-Fatiha,4,19,بسم,...,আল্লাহর নামে,Во имя Бога,بسم الله الرحمن,"in the name of ALLAH, the most mercifull",merhametli olan Allah adıyla,اللہ کے نام سے جو سب سے زیادہ رحم کرنے والا ہے۔,"अल्लाह के नाम पर, सबसे दयालु",dengan menyebut nama ALLAH yang maha penyayang,পরম করুণাময় আল্লাহর নামে,во имя АЛЛАХА Милостивого
1,1,1,2,1,1,الفاتحة,Al-Fatiha,4,19,الله,...,পরম করুণাময় ঈশ্বর,Бог Милостивый,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1,3,1,1,الفاتحة,Al-Fatiha,4,19,الرحمن,...,পরম করুণাময়,Самый Милосердный,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,1,4,1,1,الفاتحة,Al-Fatiha,4,19,الرحيم,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2,1,1,1,الفاتحة,Al-Fatiha,4,18,الحمد,...,সৃষ্টিকর্তাকে ধন্যবাদ,Слава Богу,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78242,114,5,4,30,604,الناس,An-Nas,5,20,صدور,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78243,114,5,5,30,604,الناس,An-Nas,5,20,الناس,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78244,114,6,1,30,604,الناس,An-Nas,3,13,من,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78245,114,6,2,30,604,الناس,An-Nas,3,13,الجنة,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78246,114,6,3,30,604,الناس,An-Nas,3,13,والناس,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [16]:
df_deploy_master[df_deploy_master.root == "Alh"]["level 4"].value_counts()

0    2851
Name: level 4, dtype: int64

In [18]:
df_deploy_master[df_deploy_master["buckwalter_word_tanzil_clean"] == "Allh"]["level 4"].value_counts()

0    2265
Name: level 4, dtype: int64

In [17]:
df_deploy_master.to_excel("Master 16052022.xlsx", index=False)

#### Level 1, 2, 3 Disable

In [9]:
df_deploy_master = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quran/Text/Result/Deploy Result/Master 16052022.xlsx")
df_deploy_master

,surah,ayah,word rank,juz,page,surah arabic,surah latin,word count ayah,letter count ayah,tanzil_clean,...,twogram_bangla,twogram_russian,threegram_string,threegram_english,threegram_turkish,threegram_urdu,threegram_hindi,threegram_indonesian,threegram_bangla,threegram_russian
0,1,1,1,1,1,الفاتحة,Al-Fatiha,4,19,بسم,...,আল্লাহর নামে,Во имя Бога,بسم الله الرحمن,"in the name of ALLAH, the most mercifull",merhametli olan Allah adıyla,اللہ کے نام سے جو سب سے زیادہ رحم کرنے والا ہے۔,"अल्लाह के नाम पर, सबसे दयालु",dengan menyebut nama ALLAH yang maha penyayang,পরম করুণাময় আল্লাহর নামে,во имя АЛЛАХА Милостивого
1,1,1,2,1,1,الفاتحة,Al-Fatiha,4,19,الله,...,পরম করুণাময় ঈশ্বর,Бог Милостивый,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1,3,1,1,الفاتحة,Al-Fatiha,4,19,الرحمن,...,পরম করুণাময়,Самый Милосердный,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,1,4,1,1,الفاتحة,Al-Fatiha,4,19,الرحيم,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2,1,1,1,الفاتحة,Al-Fatiha,4,18,الحمد,...,সৃষ্টিকর্তাকে ধন্যবাদ,Слава Богу,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78242,114,5,4,30,604,الناس,An-Nas,5,20,صدور,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78243,114,5,5,30,604,الناس,An-Nas,5,20,الناس,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78244,114,6,1,30,604,الناس,An-Nas,3,13,من,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78245,114,6,2,30,604,الناس,An-Nas,3,13,الجنة,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78246,114,6,3,30,604,الناس,An-Nas,3,13,والناس,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
for i in range(len(df_deploy_master)):
    if (df_deploy_master.loc[i,"root"] == "Alh") | (df_deploy_master.loc[i,"buckwalter_word_tanzil_clean"] == "Allh"):
        if df_deploy_master.loc[i,"level 1"] == 1:
            df_deploy_master.loc[i,"level 1"] = 0
        if df_deploy_master.loc[i,"level 2"] == 1:
            df_deploy_master.loc[i,"level 2"] = 0
        if df_deploy_master.loc[i,"level 3"] == 1:
            df_deploy_master.loc[i,"level 3"] = 0
    else:
        pass

In [11]:
df_deploy_master

,surah,ayah,word rank,juz,page,surah arabic,surah latin,word count ayah,letter count ayah,tanzil_clean,...,twogram_bangla,twogram_russian,threegram_string,threegram_english,threegram_turkish,threegram_urdu,threegram_hindi,threegram_indonesian,threegram_bangla,threegram_russian
0,1,1,1,1,1,الفاتحة,Al-Fatiha,4,19,بسم,...,আল্লাহর নামে,Во имя Бога,بسم الله الرحمن,"in the name of ALLAH, the most mercifull",merhametli olan Allah adıyla,اللہ کے نام سے جو سب سے زیادہ رحم کرنے والا ہے۔,"अल्लाह के नाम पर, सबसे दयालु",dengan menyebut nama ALLAH yang maha penyayang,পরম করুণাময় আল্লাহর নামে,во имя АЛЛАХА Милостивого
1,1,1,2,1,1,الفاتحة,Al-Fatiha,4,19,الله,...,পরম করুণাময় ঈশ্বর,Бог Милостивый,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1,3,1,1,الفاتحة,Al-Fatiha,4,19,الرحمن,...,পরম করুণাময়,Самый Милосердный,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,1,4,1,1,الفاتحة,Al-Fatiha,4,19,الرحيم,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2,1,1,1,الفاتحة,Al-Fatiha,4,18,الحمد,...,সৃষ্টিকর্তাকে ধন্যবাদ,Слава Богу,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78242,114,5,4,30,604,الناس,An-Nas,5,20,صدور,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78243,114,5,5,30,604,الناس,An-Nas,5,20,الناس,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78244,114,6,1,30,604,الناس,An-Nas,3,13,من,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78245,114,6,2,30,604,الناس,An-Nas,3,13,الجنة,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78246,114,6,3,30,604,الناس,An-Nas,3,13,والناس,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df_deploy_master.to_excel("Master 17052022.xlsx", index=False)

#### Divide Juz

In [2]:
df_deploy_master = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quran/Text/Result/Deploy Result/Master 17052022.xlsx")
df_deploy_master

,surah,ayah,word rank,juz,page,surah arabic,surah latin,word count ayah,letter count ayah,tanzil_clean,...,twogram_bangla,twogram_russian,threegram_string,threegram_english,threegram_turkish,threegram_urdu,threegram_hindi,threegram_indonesian,threegram_bangla,threegram_russian
0,1,1,1,1,1,الفاتحة,Al-Fatiha,4,19,بسم,...,আল্লাহর নামে,Во имя Бога,بسم الله الرحمن,"in the name of ALLAH, the most mercifull",merhametli olan Allah adıyla,اللہ کے نام سے جو سب سے زیادہ رحم کرنے والا ہے۔,"अल्लाह के नाम पर, सबसे दयालु",dengan menyebut nama ALLAH yang maha penyayang,পরম করুণাময় আল্লাহর নামে,во имя АЛЛАХА Милостивого
1,1,1,2,1,1,الفاتحة,Al-Fatiha,4,19,الله,...,পরম করুণাময় ঈশ্বর,Бог Милостивый,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1,1,3,1,1,الفاتحة,Al-Fatiha,4,19,الرحمن,...,পরম করুণাময়,Самый Милосердный,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1,1,4,1,1,الفاتحة,Al-Fatiha,4,19,الرحيم,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1,2,1,1,1,الفاتحة,Al-Fatiha,4,18,الحمد,...,সৃষ্টিকর্তাকে ধন্যবাদ,Слава Богу,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78242,114,5,4,30,604,الناس,An-Nas,5,20,صدور,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78243,114,5,5,30,604,الناس,An-Nas,5,20,الناس,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78244,114,6,1,30,604,الناس,An-Nas,3,13,من,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78245,114,6,2,30,604,الناس,An-Nas,3,13,الجنة,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78246,114,6,3,30,604,الناس,An-Nas,3,13,والناس,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
df_juz_30 = df_deploy_master[df_deploy_master["juz"] == 30]
df_juz_30

,surah,ayah,word rank,juz,page,surah arabic,surah latin,word count ayah,letter count ayah,tanzil_clean,...,twogram_bangla,twogram_russian,threegram_string,threegram_english,threegram_turkish,threegram_urdu,threegram_hindi,threegram_indonesian,threegram_bangla,threegram_russian
75785,78,0,1,30,582,النبأ,An-Naba',4,19,بسم,...,আল্লাহর নামে,Во имя Бога,بسم الله الرحمن,"in the name of ALLAH, the most mercifull",merhametli olan Allah adıyla,اللہ کے نام سے جو سب سے زیادہ رحم کرنے والا ہے۔,"अल्लाह के नाम पर, सबसे दयालु",dengan menyebut nama ALLAH yang maha penyayang,পরম করুণাময় আল্লাহর নামে,во имя АЛЛАХА Милостивого
75786,78,0,2,30,582,النبأ,An-Naba',4,19,الله,...,পরম করুণাময় ঈশ্বর,Бог Милостивый,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75787,78,0,3,30,582,النبأ,An-Naba',4,19,الرحمن,...,পরম করুণাময়,Самый Милосердный,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75788,78,0,4,30,582,النبأ,An-Naba',4,19,الرحيم,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75789,78,1,1,30,582,النبأ,An-Naba',2,10,عم,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78242,114,5,4,30,604,الناس,An-Nas,5,20,صدور,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78243,114,5,5,30,604,الناس,An-Nas,5,20,الناس,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78244,114,6,1,30,604,الناس,An-Nas,3,13,من,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78245,114,6,2,30,604,الناس,An-Nas,3,13,الجنة,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78246,114,6,3,30,604,الناس,An-Nas,3,13,والناس,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df_juz_30.to_excel(f"Quran_Juz_30_17052022.xlsx", index=False)

In [4]:
df_deploy_master.columns

Index(['surah', 'ayah', 'word rank', 'juz', 'page', 'surah arabic',
       'surah latin', 'word count ayah', 'letter count ayah', 'tanzil_clean',
       'buckwalter_word_tanzil_clean', 'tanzil_plain',
       'buckwalter_word_tanzil_plain', 'root', 'root_arabic', 'tag', 'level 1',
       'level 2', 'level 3', 'level 4', '2gram', '3gram', 'start_time',
       'end_time', 'repeat flag', 'index', 'arabic', 'translate_english',
       'translate_urdu', 'translate_hindi', 'translate_indonesian',
       'translate_bangla', 'translate_turkish', 'translate_russian',
       'twogram_string', 'twogram_english', 'twogram_turkish', 'twogram_urdu',
       'twogram_hindi', 'twogram_indonesian', 'twogram_bangla',
       'twogram_russian', 'threegram_string', 'threegram_english',
       'threegram_turkish', 'threegram_urdu', 'threegram_hindi',
       'threegram_indonesian', 'threegram_bangla', 'threegram_russian'],
      dtype='object')

In [5]:
df_deploy_select = df_deploy_master.iloc[:,[3,4,0,1,2,6,16,17,18,19,11]]
df_deploy_select

,juz,page,surah,ayah,word rank,surah latin,level 1,level 2,level 3,level 4,tanzil_plain
0,1,1,1,1,1,Al-Fatiha,1,2,3,4,بِسْمِ
1,1,1,1,1,2,Al-Fatiha,1,2,3,4,اللَّهِ
2,1,1,1,1,3,Al-Fatiha,1,2,3,4,الرَّحْمَٰنِ
3,1,1,1,1,4,Al-Fatiha,1,2,2,4,الرَّحِيمِ
4,1,1,1,2,1,Al-Fatiha,0,0,2,4,الْحَمْدُ
...,...,...,...,...,...,...,...,...,...,...,...
78242,30,604,114,5,4,An-Nas,0,0,0,0,صُدُورِ
78243,30,604,114,5,5,An-Nas,1,1,1,4,النَّاسِ
78244,30,604,114,6,1,An-Nas,1,1,1,0,مِنَ
78245,30,604,114,6,2,An-Nas,0,1,1,4,الْجِنَّةِ
78246,30,604,114,6,3,An-Nas,0,0,0,4,وَالنَّاسِ

In [6]:
df_deploy_select[df_deploy_select["juz"] == 1]

,juz,page,surah,ayah,word rank,surah latin,level 1,level 2,level 3,level 4,tanzil_plain
0,1,1,1,1,1,Al-Fatiha,1,2,3,4,بِسْمِ
1,1,1,1,1,2,Al-Fatiha,1,2,3,4,اللَّهِ
2,1,1,1,1,3,Al-Fatiha,1,2,3,4,الرَّحْمَٰنِ
3,1,1,1,1,4,Al-Fatiha,1,2,2,4,الرَّحِيمِ
4,1,1,1,2,1,Al-Fatiha,0,0,2,4,الْحَمْدُ
...,...,...,...,...,...,...,...,...,...,...,...
2532,1,21,2,141,11,Al-Baqara,1,1,1,0,وَلَا
2533,1,21,2,141,12,Al-Baqara,0,0,0,4,تُسْأَلُونَ
2534,1,21,2,141,13,Al-Baqara,0,0,0,0,عَمَّا
2535,1,21,2,141,14,Al-Baqara,1,2,2,4,كَانُوا
2536,1,21,2,141,15,Al-Baqara,0,2,2,4,يَعْمَلُونَ

In [ ]:
for i in range(1,31):
    df_juz = df_deploy_select[df_deploy_select["juz"] == i]
    df_juz.to_excel(f"Quran_Juz_{i}.xlsx", index=False)

#### Multi Index Process

In [3]:
df_twogram_first_multi = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quran/Text/Result/9-Translate Process/Arabic_Buckwalter_All_Twogram_Multi_First_Indexes.xlsx")
df_twogram_first_multi

      first_index
0           59848
1           65770
2           49668
3           11639
4           49685
...           ...
1783         6451
1784        44360
1785        77922
1786        77954
1787        77963

[1788 rows x 1 columns]

In [4]:
df_threegram_first_multi = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quran/Text/Result/9-Translate Process/Arabic_Buckwalter_All_Threegram_Multi_First_Indexes.xlsx")
df_threegram_first_multi

     first_index
0          18858
1          52219
2          52151
3           7881
4          70857
..           ...
921        77781
922          610
923          333
924         1326
925        69831

[926 rows x 1 columns]

In [5]:
df_2_2_and_3_1 = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quran/Text/Result/9-Translate Process/Arabic_Buckwalter_All_Twogram_Second_And_Threegram_First_Multi_Indexes.xlsx")
df_2_2_and_3_1

     2_2_and_3_1
0              5
1          53255
2          53256
3          71689
4          71691
..           ...
593        36842
594        34809
595        26620
596        28670
597        28671

[598 rows x 1 columns]

In [6]:
df_3_3_and_2_1 = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quran/Text/Result/9-Translate Process/Arabic_Buckwalter_All_Threegram_Third_And_Twogram_First_Multi_Indexes.xlsx")
df_3_3_and_2_1

     3_3_and_2_1
0          28672
1              2
2          22531
3          71684
4          53256
..           ...
828        71664
829        65521
830        73719
831         8185
832        28671

[833 rows x 1 columns]

In [ ]:
df_deploy_master.filter()