### SparkNLP N Gram Lemma Analysis

In [1]:
import pandas as pd
import numpy as np
import re
import glob

In [6]:
df_twogram_json = pd.read_json("g_Igztvb0RZ0UkLclbPyS.json")
df_twogram_json = df_twogram_json.loc[:,["index","lem"]]
df_twogram_json.dropna(inplace=True)
df_twogram_json

        index      lem
0           0      bir
1           0      şey
2           1    değil
3           1       mi
4           2      ben
...       ...      ...
199995  99997      vur
199996  99998     peki
199997  99998      dün
199998  99999  kontrol
199999  99999       et

[200000 rows x 2 columns]

In [7]:
df_twogram_json_join = df_twogram_json.groupby(["index"])["lem"].apply(" ".join).reset_index()
df_twogram_json_join

       index          lem
0          0      bir şey
1          1     değil mi
2          2       ben de
3          3  teşekkür et
4          4        ne ol
...      ...          ...
99995  99995   şey olumlu
99996  99996    bura içki
99997  99997       et vur
99998  99998     peki dün
99999  99999   kontrol et

[100000 rows x 2 columns]

In [8]:
df_twogram_json_join.drop_duplicates()

       index          lem
0          0      bir şey
1          1     değil mi
2          2       ben de
3          3  teşekkür et
4          4        ne ol
...      ...          ...
99995  99995   şey olumlu
99996  99996    bura içki
99997  99997       et vur
99998  99998     peki dün
99999  99999   kontrol et

[100000 rows x 2 columns]

### Lemma Model Result

In [27]:
df_word = pd.read_excel(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Turkish/Deployment/Data/Word/Word_Merge_Preprocess.xlsx")
df_word = df_word.head(45000)
df_word

                word  frequency
0                bir   18835735
1                 bu   11062659
2                 ne    8025880
3                 ve    7766036
4               için    5484109
...              ...        ...
44995        hayırbu        871
44996   konferansına        871
44997     kardeşisin        871
44998  kaldırıyorsun        871
44999     kuzenlerim        871

[45000 rows x 2 columns]

In [28]:
df_lemma = pd.read_json("tr.lemma.atis.json")
df_lemma

         index              lem            token
0            0              bir              bir
1            1               bu               bu
2            2               ne               ne
3            3               ve               ve
4            4             için             için
...        ...              ...              ...
99996    99996          seppuku          seppuku
99997    99997     tırmandığını     tırmandığını
99998    99998    çözülemeyecek    çözülemeyecek
99999    99999  hatırlamıyormuş  hatırlamıyormuş
100000  100000             None             None

[100001 rows x 3 columns]

In [29]:
df_lemma = df_lemma[["token","lem"]]
df_lemma.rename(columns={"token":"word", "lem":"lemma.atis"}, inplace=True)
df_lemma

/home/kurubal/anaconda3/envs/py39/lib/python3.9/site-packages/pandas/core/frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

                   word       lemma.atis
0                   bir              bir
1                    bu               bu
2                    ne               ne
3                    ve               ve
4                  için             için
...                 ...              ...
99996           seppuku          seppuku
99997      tırmandığını     tırmandığını
99998     çözülemeyecek    çözülemeyecek
99999   hatırlamıyormuş  hatırlamıyormuş
100000             None             None

[100001 rows x 2 columns]

In [30]:
df_word_lemma_merge = pd.merge(df_word, df_lemma, how="left", on="word")
df_word_lemma_merge.drop_duplicates(inplace=True)
df_word_lemma_merge

                word  frequency     lemma.atis
0                bir   18835735            bir
1                 bu   11062659             bu
2                 ne    8025880             ne
3                 ve    7766036             ve
4               için    5484109           için
...              ...        ...            ...
44995        hayırbu        871        hayırbu
44996   konferansına        871   konferansına
44997     kardeşisin        871     kardeşisin
44998  kaldırıyorsun        871  kaldırıyorsun
44999     kuzenlerim        871     kuzenlerim

[45000 rows x 3 columns]

In [45]:
df_lemma = pd.read_json("tr.lemma.boun.json")
df_lemma = df_lemma[["token","lem"]]
df_lemma.rename(columns={"token":"word", "lem":"lemma.boun"}, inplace=True)
df_lemma

                   word      lemma.lemma
0                   bir              bir
1                    bu               bu
2                    ne               ne
3                    ve               ve
4                  için               da
...                 ...              ...
99996           seppuku          seppuku
99997      tırmandığını     tırmandığını
99998     çözülemeyecek    çözülemeyecek
99999   hatırlamıyormuş  hatırlamıyormuş
100000             None             None

[100001 rows x 2 columns]

In [46]:
df_word_lemma_merge = pd.merge(df_word_lemma_merge, df_lemma, how="left", on="word")
df_word_lemma_merge.drop_duplicates(inplace=True)
df_word_lemma_merge

,word,frequency,lemma.atis,lemma.tourism,lemma.boun,lemma.framenet,lemma.imst,lemma.kenet,lemma.penn,lemma.spacylookup,lemma.lemma
0,bir,18835735,bir,bir,bir,bir,bir,bir,bir,bir,bir
1,bu,11062659,bu,bu,bu,bu,bu,bu,bu,bu,bu
2,ne,8025880,ne,ne,ne,ne,ne,ne,ne,ne,ne
3,ve,7766036,ve,ve,ve,ve,ve,ve,ve,ve,ve
4,için,5484109,için,için,için,için,için,iç,da,için,da
...,...,...,...,...,...,...,...,...,...,...,...
44995,hayırbu,871,hayırbu,hayırbu,hayırbu,hayırbu,hayırbu,hayırbu,hayırbu,hayırbu,hayırbu
44996,konferansına,871,konferansına,konferansına,konferansına,konferansına,konferansına,konferansına,konferansına,konferans,konferansına
44997,kardeşisin,871,kardeşisin,kardeşisin,kardeşisin,kardeşisin,kardeşisin,kardeşisin,kardeşisin,kardeş,kardeşisin
44998,kaldırıyorsun,871,kaldırıyorsun,kaldırıyorsun,kaldırıyorsun,kaldırıyorsun,kaldırıyorsun,kaldırıyorsun,kaldırıyorsun,kaldır,kaldırıyorsun
44999,kuzenlerim,871,kuzenlerim,kuzenlerim,kuzenlerim,kuzenlerim,kuzenlerim,kuzenlerim,kuzenlerim,kuzen,kuzenlerim

In [47]:
df_word_lemma_merge.to_excel("Turkish_45000_Word_All_Lemma_Result.xlsx", index=False)

### Pos Tag

In [5]:
df_word = pd.read_excel(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Turkish/Deployment/Data/Word/Word_Merge_Preprocess.xlsx")
df_word = df_word.head(45000)
df_word

                word  frequency
0                bir   18835735
1                 bu   11062659
2                 ne    8025880
3                 ve    7766036
4               için    5484109
...              ...        ...
44995        hayırbu        871
44996   konferansına        871
44997     kardeşisin        871
44998  kaldırıyorsun        871
44999     kuzenlerim        871

[45000 rows x 2 columns]

In [6]:
df_pos = pd.read_json("tr.pos.atis.json")
df_pos

       index    pos            token
0          0    DET              bir
1          1    DET               bu
2          2    ADV               ne
3          3  CCONJ               ve
4          4    ADP             için
...      ...    ...              ...
99995  99995   NOUN           casusa
99996  99996   NOUN          seppuku
99997  99997   NOUN     tırmandığını
99998  99998    ADJ    çözülemeyecek
99999  99999   VERB  hatırlamıyormuş

[100000 rows x 3 columns]

In [7]:
df_pos = df_pos[["token","pos"]]
df_pos.rename(columns={"token":"word", "pos":"pos.atis"}, inplace=True)
df_pos

/home/kurubal/anaconda3/envs/py39/lib/python3.9/site-packages/pandas/core/frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

                  word pos.atis
0                  bir      DET
1                   bu      DET
2                   ne      ADV
3                   ve    CCONJ
4                 için      ADP
...                ...      ...
99995           casusa     NOUN
99996          seppuku     NOUN
99997     tırmandığını     NOUN
99998    çözülemeyecek      ADJ
99999  hatırlamıyormuş     VERB

[100000 rows x 2 columns]

In [8]:
df_word_pos_merge = pd.merge(df_word, df_pos, how="left", on="word")
df_word_pos_merge.drop_duplicates(inplace=True)
df_word_pos_merge

                word  frequency pos.atis
0                bir   18835735      DET
1                 bu   11062659      DET
2                 ne    8025880      ADV
3                 ve    7766036    CCONJ
4               için    5484109      ADP
...              ...        ...      ...
44995        hayırbu        871     VERB
44996   konferansına        871     NOUN
44997     kardeşisin        871     VERB
44998  kaldırıyorsun        871     VERB
44999     kuzenlerim        871     VERB

[45000 rows x 3 columns]

In [26]:
df_pos = pd.read_json("tr.pos.boun.json")
df_pos = df_pos[["token","pos"]]
df_pos.rename(columns={"token":"word", "pos":"pos.boun"}, inplace=True)
df_pos

                  word pos.boun
0                  bir      DET
1                   bu      DET
2                   ne     PRON
3                   ve    CCONJ
4                 için      ADP
...                ...      ...
99995           casusa     NOUN
99996          seppuku     NOUN
99997     tırmandığını     NOUN
99998    çözülemeyecek     VERB
99999  hatırlamıyormuş     VERB

[100000 rows x 2 columns]

In [24]:
df_word_pos_merge = pd.merge(df_word_pos_merge, df_pos, how="left", on="word")
df_word_pos_merge.drop_duplicates(inplace=True)
df_word_pos_merge

,word,frequency,pos.atis,pos.ud_imst,pos.boun,pos.framenet,pos.imst,pos.kenet,pos.penn,pos.tourism,pos.pos
0,bir,18835735,DET,NUM,DET,DET,DET,DET,DET,NOUN,DET
1,bu,11062659,DET,DET,DET,DET,DET,DET,DET,DET,DET
2,ne,8025880,ADV,PRON,PRON,ADJ,PRON,ADV,CCONJ,ADV,PRON
3,ve,7766036,CCONJ,CCONJ,CCONJ,CCONJ,CCONJ,CCONJ,CCONJ,CCONJ,CCONJ
4,için,5484109,ADP,ADP,ADP,ADP,ADP,ADP,ADP,NOUN,ADP
...,...,...,...,...,...,...,...,...,...,...,...
44995,hayırbu,871,VERB,NOUN,NOUN,VERB,PUNCT,NOUN,NOUN,NOUN,NOUN
44996,konferansına,871,NOUN,NOUN,NOUN,NOUN,NOUN,NOUN,NOUN,NOUN,NOUN
44997,kardeşisin,871,VERB,NOUN,VERB,VERB,PUNCT,VERB,NOUN,NOUN,VERB
44998,kaldırıyorsun,871,VERB,VERB,VERB,VERB,VERB,VERB,NOUN,NOUN,VERB
44999,kuzenlerim,871,VERB,NOUN,NOUN,NOUN,PUNCT,NOUN,NOUN,NOUN,NOUN

In [25]:
df_word_pos_merge.to_excel("Turkish_45000_Word_All_Pos_Result.xlsx", index=False)

In [2]:
df_lemma_all = pd.read_excel("Turkish_10000_Word_All_Lemma_Result.xlsx")
df_lemma_all

,word,lemma.atis,lemma.boun,lemma.framenet,lemma.imst,lemma,lemma.kenet,lemma.penn,lemma.spacylookup,lemma.tourism
0,bir,bir,bir,bir,bir,bir,bir,bir,bir,bir
1,bu,bu,bu,bu,bu,bu,bu,bu,bu,bu
2,ne,ne,ne,ne,ne,ne,ne,ne,ne,ne
3,ve,ve,ve,ve,ve,ve,ve,ve,ve,ve
4,için,için,için,için,için,da,iç,da,için,için
...,...,...,...,...,...,...,...,...,...,...
99995,casusa,casusa,casusa,casusa,casusa,casusa,casusa,casusa,casus,casusa
99996,seppuku,seppuku,seppuku,seppuku,seppuku,seppuku,seppuku,seppuku,seppuku,seppuku
99997,tırmandığını,tırmandığını,tırmandığını,tırmandığını,tırmandığını,tırmandığını,tırmandığını,tırmandığını,tırman,tırmandığını
99998,çözülemeyecek,çözülemeyecek,çözülemeyecek,çözülemeyecek,çözülemeyecek,çözülemeyecek,çözülemeyecek,çözülemeyecek,çöz,çözülemeyecek
99999,hatırlamıyormuş,hatırlamıyormuş,hatırlamıyormuş,hatırlamıyormuş,hatırlamıyormuş,hatırlamıyormuş,hatırlamıyormuş,hatırlamıyormuş,hatırla,hatırlamıyormuş

In [3]:
df_lemma_all.columns

Index(['word', 'lemma.atis', 'lemma.boun', 'lemma.framenet', 'lemma.imst',
       'lemma', 'lemma.kenet', 'lemma.penn', 'lemma.spacylookup',
       'lemma.tourism'],
      dtype='object')

In [8]:
for i in df_lemma_all.columns:
    new_name = i.strip()
    df_lemma_all.rename(columns={f"{i}":f"{new_name}"}, inplace=True)

In [10]:
def strip(df):
    for i in df.columns:
        new_name = i.strip()
        df.rename(columns={f"{i}":f"{new_name}"}, inplace=True)
        df[f"{new_name}"] = df[f"{new_name}"].apply(lambda x: x.strip())
    
    return df

In [5]:
test = " alie"

In [6]:
test.strip()

'alie'

In [13]:
df_test = strip(df_lemma_all)
df_test

,word,lemma.atis,lemma.boun,lemma.framenet,lemma.imst,lemma,lemma.kenet,lemma.penn,lemma.spacylookup,lemma.tourism
0,bir,bir,bir,bir,bir,bir,bir,bir,bir,bir
1,bu,bu,bu,bu,bu,bu,bu,bu,bu,bu
2,ne,ne,ne,ne,ne,ne,ne,ne,ne,ne
3,ve,ve,ve,ve,ve,ve,ve,ve,ve,ve
4,için,için,için,için,için,da,iç,da,için,için
...,...,...,...,...,...,...,...,...,...,...
99995,casusa,casusa,casusa,casusa,casusa,casusa,casusa,casusa,casus,casusa
99996,seppuku,seppuku,seppuku,seppuku,seppuku,seppuku,seppuku,seppuku,seppuku,seppuku
99997,tırmandığını,tırmandığını,tırmandığını,tırmandığını,tırmandığını,tırmandığını,tırmandığını,tırmandığını,tırman,tırmandığını
99998,çözülemeyecek,çözülemeyecek,çözülemeyecek,çözülemeyecek,çözülemeyecek,çözülemeyecek,çözülemeyecek,çözülemeyecek,çöz,çözülemeyecek
99999,hatırlamıyormuş,hatırlamıyormuş,hatırlamıyormuş,hatırlamıyormuş,hatırlamıyormuş,hatırlamıyormuş,hatırlamıyormuş,hatırlamıyormuş,hatırla,hatırlamıyormuş

In [15]:
df_test2 = df_test.head(10000)
df_test2

,word,lemma.atis,lemma.boun,lemma.framenet,lemma.imst,lemma,lemma.kenet,lemma.penn,lemma.spacylookup,lemma.tourism
0,bir,bir,bir,bir,bir,bir,bir,bir,bir,bir
1,bu,bu,bu,bu,bu,bu,bu,bu,bu,bu
2,ne,ne,ne,ne,ne,ne,ne,ne,ne,ne
3,ve,ve,ve,ve,ve,ve,ve,ve,ve,ve
4,için,için,için,için,için,da,iç,da,için,için
...,...,...,...,...,...,...,...,...,...,...
9995,arkadaşa,arkadaşa,arkadaş,arkadaş,arkadaşa,arkadaşa,arkadaş,arkadaşa,arkadaş,arkadaşa
9996,değişmez,değişmez,değiş,değişmez,değiş,değiş,değiş,değiş,değişmez,değişmez
9997,çocuğumu,çocuğumu,çocuğumu,çocuğumu,çocuğumu,çocuğumu,çocuğumu,çocuğumu,çocuk,çocuğumu
9998,yerimizi,yerimizi,yerimizi,yerimizi,yerimizi,yerimizi,yerimizi,yerimizi,yer,yerimizi
9999,değiştirip,değiştirip,değiş,değiştirip,değiş,değiştirip,değiştirip,değiştirip,değiş,değiştirip

In [16]:
df_test2["lemma.spacylookup"].nunique()

3307

In [19]:
for column in df_test2.columns:
    column_nunique = df_test2[f"{column}"].nunique()
    print(f"{column} : {column_nunique}")

word : 10000
lemma.atis : 9658
lemma.boun : 6100
lemma.framenet : 8541
lemma.imst : 7424
lemma : 6940
lemma.kenet : 6010
lemma.penn : 6940
lemma.spacylookup : 3307
lemma.tourism : 10000