### SparkNLP N Gram Lemma Analysis

In [1]:
import pandas as pd
import numpy as np
import re
import glob

In [6]:
df_twogram_json = pd.read_json("g_Igztvb0RZ0UkLclbPyS.json")
df_twogram_json = df_twogram_json.loc[:,["index","lem"]]
df_twogram_json.dropna(inplace=True)
df_twogram_json

        index      lem
0           0      bir
1           0      şey
2           1    değil
3           1       mi
4           2      ben
...       ...      ...
199995  99997      vur
199996  99998     peki
199997  99998      dün
199998  99999  kontrol
199999  99999       et

[200000 rows x 2 columns]

In [7]:
df_twogram_json_join = df_twogram_json.groupby(["index"])["lem"].apply(" ".join).reset_index()
df_twogram_json_join

       index          lem
0          0      bir şey
1          1     değil mi
2          2       ben de
3          3  teşekkür et
4          4        ne ol
...      ...          ...
99995  99995   şey olumlu
99996  99996    bura içki
99997  99997       et vur
99998  99998     peki dün
99999  99999   kontrol et

[100000 rows x 2 columns]

In [8]:
df_twogram_json_join.drop_duplicates()

       index          lem
0          0      bir şey
1          1     değil mi
2          2       ben de
3          3  teşekkür et
4          4        ne ol
...      ...          ...
99995  99995   şey olumlu
99996  99996    bura içki
99997  99997       et vur
99998  99998     peki dün
99999  99999   kontrol et

[100000 rows x 2 columns]

### Lemma Model Result

In [24]:
df_word = pd.read_excel("10000 word.xlsx")
df_word

                  word
0                  bir
1                   bu
2                   ne
3                   ve
4                 için
...                ...
99995           casusa
99996          seppuku
99997     tırmandığını
99998    çözülemeyecek
99999  hatırlamıyormuş

[100000 rows x 1 columns]

In [25]:
df_lemma = pd.read_json("tr.lemma.atis.json")
df_lemma

         index              lem            token
0            0              bir              bir
1            1               bu               bu
2            2               ne               ne
3            3               ve               ve
4            4             için             için
...        ...              ...              ...
99996    99996          seppuku          seppuku
99997    99997     tırmandığını     tırmandığını
99998    99998    çözülemeyecek    çözülemeyecek
99999    99999  hatırlamıyormuş  hatırlamıyormuş
100000  100000             None             None

[100001 rows x 3 columns]

In [26]:
df_lemma = df_lemma[["token","lem"]]
df_lemma.rename(columns={"token":"word", "lem":"lemma.atis"}, inplace=True)
df_lemma

/home/kurubal/anaconda3/envs/py39/lib/python3.9/site-packages/pandas/core/frame.py:5039: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

                   word       lemma.atis
0                   bir              bir
1                    bu               bu
2                    ne               ne
3                    ve               ve
4                  için             için
...                 ...              ...
99996           seppuku          seppuku
99997      tırmandığını     tırmandığını
99998     çözülemeyecek    çözülemeyecek
99999   hatırlamıyormuş  hatırlamıyormuş
100000             None             None

[100001 rows x 2 columns]

In [27]:
df_word_lemma_merge = pd.merge(df_word, df_lemma, how="left", on="word")
df_word_lemma_merge.drop_duplicates(inplace=True)
df_word_lemma_merge

                  word       lemma.atis
0                  bir              bir
1                   bu               bu
2                   ne               ne
3                   ve               ve
4                 için             için
...                ...              ...
99995           casusa           casusa
99996          seppuku          seppuku
99997     tırmandığını     tırmandığını
99998    çözülemeyecek    çözülemeyecek
99999  hatırlamıyormuş  hatırlamıyormuş

[100000 rows x 2 columns]

In [42]:
df_lemma = pd.read_json("tr.lemma.tourism.json")
df_lemma = df_lemma[["token","lem"]]
df_lemma.rename(columns={"token":"word", "lem":"lemma.tourism"}, inplace=True)
df_lemma

                   word    lemma.tourism
0                   bir              bir
1                    bu               bu
2                    ne               ne
3                    ve               ve
4                  için             için
...                 ...              ...
99996           seppuku          seppuku
99997      tırmandığını     tırmandığını
99998     çözülemeyecek    çözülemeyecek
99999   hatırlamıyormuş  hatırlamıyormuş
100000             None             None

[100001 rows x 2 columns]

In [43]:
df_word_lemma_merge = pd.merge(df_word_lemma_merge, df_lemma, how="left", on="word")
df_word_lemma_merge.drop_duplicates(inplace=True)
df_word_lemma_merge

,word,lemma.atis,lemma.boun,lemma.framenet,lemma.imst,lemma,lemma.kenet,lemma.penn,lemma.spacylookup,lemma.tourism
0,bir,bir,bir,bir,bir,bir,bir,bir,bir,bir
1,bu,bu,bu,bu,bu,bu,bu,bu,bu,bu
2,ne,ne,ne,ne,ne,ne,ne,ne,ne,ne
3,ve,ve,ve,ve,ve,ve,ve,ve,ve,ve
4,için,için,için,için,için,da,iç,da,için,için
...,...,...,...,...,...,...,...,...,...,...
99995,casusa,casusa,casusa,casusa,casusa,casusa,casusa,casusa,casus,casusa
99996,seppuku,seppuku,seppuku,seppuku,seppuku,seppuku,seppuku,seppuku,seppuku,seppuku
99997,tırmandığını,tırmandığını,tırmandığını,tırmandığını,tırmandığını,tırmandığını,tırmandığını,tırmandığını,tırman,tırmandığını
99998,çözülemeyecek,çözülemeyecek,çözülemeyecek,çözülemeyecek,çözülemeyecek,çözülemeyecek,çözülemeyecek,çözülemeyecek,çöz,çözülemeyecek
99999,hatırlamıyormuş,hatırlamıyormuş,hatırlamıyormuş,hatırlamıyormuş,hatırlamıyormuş,hatırlamıyormuş,hatırlamıyormuş,hatırlamıyormuş,hatırla,hatırlamıyormuş

In [44]:
df_word_lemma_merge.to_excel("Turkish_10000_Word_All_Lemma_Result.xlsx", index=False)

### Pos Tag

In [ ]:
df_word = pd.read_excel("10000 word.xlsx")
df_word