### Halı Şube Satış Analiz

In [1]:
import unicodedata
import datetime as dt
import os
import sys
import re
import numpy as np
import pandas as pd
import math
from pathlib import Path
import nltk
from nltk import word_tokenize 
import shutil
from os.path import isfile, join
import matplotlib.pyplot as plt
import seaborn as sns
import glob
import locale
from locale import atof
from geopy.geocoders import Nominatim
from geopy.point import Point
from geopy.exc import GeocoderTimedOut
from functools import reduce

#### Functions

In [2]:
# custom character alphabet for word
tr = re.compile(r"[abcçdefgğhıijklmnoöprsştuüvyzqxw]+", re.IGNORECASE|re.UNICODE) # Turkish filters='!"#$%&()*+,-./:;<=>?@[\\]^_`{|}~\t\n0123456789'
en = re.compile(r"[abcdefghıijklmnopqrstxuvwyz]+", re.IGNORECASE|re.UNICODE) # English
nl = re.compile(r"[abcdefghıijklmnopqrstxuvwyzāăēĕīĭōŏūŭ]+", re.IGNORECASE|re.UNICODE) # Dutch (Flemenk)
fr = re.compile(r"[abcçdefghıijklmnopqrstxuvwyzàâæèéêëîïôœùûüÿ]+", re.IGNORECASE|re.UNICODE) # French
de = re.compile(r"[abcdefghıijklmnopqrstxuvwyzäöüß]+", re.IGNORECASE|re.UNICODE) # German
es = re.compile(r"[abcdefghıijklmnopqrstxuvwyzñáéíóú]+", re.IGNORECASE|re.UNICODE) # Spanish (¿¡)
pt = re.compile(r"[abcçdefghıijklmnopqrstxuvwyzàáâãéêíóôõú]+", re.IGNORECASE|re.UNICODE) # Portuguese
it = re.compile(r"[abcdefghıijklmnopqrstxuvwyzàéèìòùî]+", re.IGNORECASE|re.UNICODE) # Italian
ar = re.compile(r"[ٿصؼۤڳڲؿڎػڠجڿ٬ٸؽؒؓطۄڀۂؘؔتٚڛےٝڜؖڦ٫ډ۰زۇٖۀ،لۓعٮێڔ۶ؚۧۜڤۏإٞٷؗۖ؈ژۣؕؑٴأۻڸۺگاڴڹۯ؉ْڌ؍ي؟ـٟړۅؐڶُىڽېًۢؠضۚڄٛڏٱۦ٩س٦ڼڂٔۘ٠ښٌٍ۬ٳ۾ٲږذۋٵٜ٘ڞڅںٗهڣۿپڒۥۗڋیؙم؞ثۨٹڵڪظٶۭ١ڭەڨحٕ؎ٺڷٰ۪۫ڻڥۛڑڟټآڡغګ؊ّٯڧڮ؏ۮ؋ؤ٪ؾڗۼق۟دکوِڰڐۃ۽ہفرڇچڝ۴بۈٽڕۡھةٓڃئ؛ڬٙڙڢڱۊَۆۉځ۠ۍۑۙڊنءڈٻشڍ؇۵كخ\ا]+", re.IGNORECASE|re.UNICODE) # Arabic

In [3]:
def convert_one_character_letter(text):
    '''This function converts two byte occupy of letter to one byte unicode character without any visual change \n
    like as Turkish character ç,ş,ö,ğ. \n
    convert_one_character_letter(text): text is any string word or sentence.
    '''
    new_text = unicodedata.normalize('NFC', f"{text}")
    return new_text

In [4]:
def clean_text(text, custom_alp=tr): # for only string in specific language
    '''This function extract custom_alp character from string \n
    clean_text(text, custom_alp): text is any string word or sentence and custom_alp is specific alphabet.
    '''
    # text_clean = re.findall(custom_alp, text)
    text_result_list = []
    text_list = re.findall(r'\S+', text)
    for text_var in text_list:
        text_clean = re.findall(custom_alp, str(text_var))
        text_result_var = "".join(text_clean)
        text_result_list.append(text_result_var)
    text_result = " ".join(text_result_list)
    return text_result

In [5]:
def lower_func(text):
    '''This function convert string character to lowercase. \n
    lower_func(text=str): text is any string word or sentence
    '''
    string_lower = str.lower(text)
    return string_lower

In [6]:
def upper_func(text):
    '''This function convert string character to uppercase. \n
    upper_func(text=str): text is any string word or sentence
    '''
    string_upper = str.upper(text)
    return string_upper

In [7]:
def capitalize_func(text):
    '''This function convert string character to capitalize case. \n
    capitalize_func(text=str): text is any string word or sentence
    '''
    string_capitalize = str.capitalize(text)
    return string_capitalize

In [8]:
def title_func(text):
    '''This function convert string character to title as each word start with capital letter. \n
    title_func(text=str): text is any string word or sentence
    '''
    string_title = str.title(text)
    return string_title

In [9]:
def character_clean_lower_text(text, custom_alp=tr): # for only string in specific language
    '''This function converts two byte occupy of letter to one byte unicode character without any visual change \n
    like as Turkish character ç,ş,ö,ğ. And also extract custom_alp character from string and convert to lowercase. \n
    character_clean_lower_text(text, custom_alp): text is any string word or sentence and custom_alp is specific alphabet.  
    '''
    new_text = unicodedata.normalize('NFC', f"{text}")
    text_result_list = []
    text_list = re.findall(r'\S+', new_text)  # like as word tokenize
    for text_var in text_list:
        text_clean = re.findall(custom_alp, str(text_var))
        text_result_var = "".join(text_clean)
        text_result_list.append(text_result_var)
    text_join = " ".join(text_result_list)
    text_result = str.lower(text_join)
    return text_result

In [10]:
def convert_to_float(value):
    '''This function convert string numeric value to float type. Like as 1.200,15
    convert_to_float(value): value is a string numeric value
    '''
    value = value.replace(".","").replace(",",".")
    return float(value)

In [11]:
def whitespace_del(text):
    '''This function provides removing left right white space.\n
    whitespace_del(text): text is a string value as word or sentence.
    '''
    text_var = str(text)
    text_var = text_var.strip()  # rstrip lstrip
    return text_var

#### Read Data

In [12]:
variable_date = "24.03.2023-31.08.2024"
input_path = fr"C:\Users\user\Desktop\Data Analysis\TurkuaHome\Sales_Report\Data\Satış\{variable_date}"
output_path = fr"C:\Users\user\Downloads"

data_file = fr"Novo_Halı_Satış ({variable_date})"

In [13]:
df_sales = pd.read_excel(fr"{input_path}\{data_file}.xlsx")
df_sales

,Cari Ünvan,Kodu,Stok Adı,Şehir,Satış Sorumlusu,Tarih,Miktar m2,Tutar TL
0,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSTANBUL,İSMAİL KURT,2023-04-04,2.16,347.760
1,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSTANBUL,İSMAİL KURT,2023-04-04,1.00,178.000
2,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,"ROMA (KOTAÇMAZI 1200 GR,3MM SÜNGER,MİKROBAMBU ...",İSTANBUL,İSMAİL KURT,2023-04-04,24.72,3979.920
3,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSTANBUL,İSMAİL KURT,2023-04-04,4.89,860.640
4,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,"ROMA (KOTAÇMAZI 1200 GR,3MM SÜNGER,MİKROBAMBU ...",İSTANBUL,İSMAİL KURT,2023-04-04,6.00,946.200
...,...,...,...,...,...,...,...,...
39635,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,ANGORA 30 MM SUED TABAN,BOLU,CAN AHMET VURAL,2024-08-30,1.35,784.224
39636,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,BOLU,CAN AHMET VURAL,2024-08-30,3.36,1147.608
39637,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,BOLU,CAN AHMET VURAL,2024-08-30,5.60,1912.680
39638,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,MİRA 1300 GR KAYMAZ TABAN PAMUK POLYESTER ŞÖNİL,BOLU,CAN AHMET VURAL,2024-08-30,3.68,1189.341
39639,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,MİRA 1300 GR KAYMAZ TABAN PAMUK POLYESTER ŞÖNİL,BOLU,CAN AHMET VURAL,2024-08-30,3.68,1189.341

In [14]:
df_city_location = pd.read_excel(r"C:\Users\user\Desktop\Data Analysis\Adoba\Sales_Report\Data\Geo Location\Master\Entegra City Location.xlsx")
df_city_location.drop("id", axis=1, inplace=True)
df_city_location

               city       country    invoice_city   latitude  longitude
0             Adana        Turkey           Adana  37.143800  35.498409
1          Adiyaman        Turkey        Adıyaman  37.763750  38.276348
2          Adiyaman        Turkey        Adiyaman  37.763750  38.276348
3    Afyonkarahisar        Turkey  Afyonkarahisar  38.685273  30.642741
4    Afyonkarahisar        Turkey           Afyon  38.685273  30.642741
..              ...           ...             ...        ...        ...
262           Yanbu  Saudi Arabia           Yanbu  24.094893  38.070525
263        Az Zulfi  Saudi Arabia           Zulfi  26.311619  44.832951
264        Qairawan       Tunisia        Qairawan  35.673549  10.098636
265        Al Khodh          Oman        Al Khodh  23.565997  58.118169
266      Almaabilah          Oman      Almaabilah  23.648131  58.146199

[267 rows x 5 columns]

#### Analysis

In [15]:
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39640 entries, 0 to 39639
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Cari Ünvan       39640 non-null  object
 1   Kodu             39625 non-null  object
 2   Stok Adı         39640 non-null  object
 3   Şehir            39362 non-null  object
 4   Satış Sorumlusu  39640 non-null  object
 5   Tarih            39640 non-null  datetime64[ns]
 6   Miktar m2        39640 non-null  float64
 7   Tutar TL         39640 non-null  float64
dtypes: datetime64[ns](1), float64(2), object(5)
memory usage: 2.4+ MB

In [16]:
df_sales[df_sales.isna().any(axis=1)]

,Cari Ünvan,Kodu,Stok Adı,Şehir,Satış Sorumlusu,Tarih,Miktar m2,Tutar TL
305,KARİZMA DEKORASYON MOBİLYA İNŞAAT SANAYİ VE DI...,120.01.279,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,NaN,İSMAİL KURT,2023-07-28,1.00,253.0
306,KARİZMA DEKORASYON MOBİLYA İNŞAAT SANAYİ VE DI...,120.01.279,MARS BEYAZ DOT TABAN PELUŞ,NaN,İSMAİL KURT,2023-07-28,1.00,204.0
307,KARİZMA DEKORASYON MOBİLYA İNŞAAT SANAYİ VE DI...,120.01.279,MARS BEYAZ DOT TABAN PELUŞ,NaN,İSMAİL KURT,2023-07-28,1.00,204.0
308,KARİZMA DEKORASYON MOBİLYA İNŞAAT SANAYİ VE DI...,120.01.279,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,NaN,İSMAİL KURT,2023-07-28,1.44,364.0
309,KARİZMA DEKORASYON MOBİLYA İNŞAAT SANAYİ VE DI...,120.01.279,"ROMA (KOTAÇMAZI 1200 GR,3MM SÜNGER,MİKROBAMBU ...",NaN,İSMAİL KURT,2023-07-28,3.00,723.0
...,...,...,...,...,...,...,...,...
9749,SELAMİ AY,NaN,"ROMA (KOTAÇMAZI 1200 GR,3MM SÜNGER,MİKROBAMBU ...",NaN,CUMA YÜRDEN,2023-11-17,2.16,626.4
9750,SELAMİ AY,NaN,"ROMA (KOTAÇMAZI 1200 GR,3MM SÜNGER,MİKROBAMBU ...",NaN,CUMA YÜRDEN,2023-11-17,2.16,626.4
9751,SELAMİ AY,NaN,"YAKUT (KOTAÇMAZI 1200 GR,3MM SÜNGER , 125 KUMAŞ )",NaN,CUMA YÜRDEN,2023-11-17,2.16,475.2
9752,SELAMİ AY,NaN,"BERLİN (KAZAYAĞI PAMUK TABAN 750GR,SÜNGER,MİKR...",NaN,CUMA YÜRDEN,2023-11-17,2.16,540.0
9753,SELAMİ AY,NaN,"YAKUT (KOTAÇMAZI 1200 GR,3MM SÜNGER , 125 KUMAŞ )",NaN,CUMA YÜRDEN,2023-11-17,2.16,475.2

In [17]:
df_sales.fillna("Diger", inplace=True)
df_sales

,Cari Ünvan,Kodu,Stok Adı,Şehir,Satış Sorumlusu,Tarih,Miktar m2,Tutar TL
0,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSTANBUL,İSMAİL KURT,2023-04-04,2.16,347.760
1,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSTANBUL,İSMAİL KURT,2023-04-04,1.00,178.000
2,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,"ROMA (KOTAÇMAZI 1200 GR,3MM SÜNGER,MİKROBAMBU ...",İSTANBUL,İSMAİL KURT,2023-04-04,24.72,3979.920
3,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSTANBUL,İSMAİL KURT,2023-04-04,4.89,860.640
4,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,"ROMA (KOTAÇMAZI 1200 GR,3MM SÜNGER,MİKROBAMBU ...",İSTANBUL,İSMAİL KURT,2023-04-04,6.00,946.200
...,...,...,...,...,...,...,...,...
39635,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,ANGORA 30 MM SUED TABAN,BOLU,CAN AHMET VURAL,2024-08-30,1.35,784.224
39636,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,BOLU,CAN AHMET VURAL,2024-08-30,3.36,1147.608
39637,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,BOLU,CAN AHMET VURAL,2024-08-30,5.60,1912.680
39638,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,MİRA 1300 GR KAYMAZ TABAN PAMUK POLYESTER ŞÖNİL,BOLU,CAN AHMET VURAL,2024-08-30,3.68,1189.341
39639,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,MİRA 1300 GR KAYMAZ TABAN PAMUK POLYESTER ŞÖNİL,BOLU,CAN AHMET VURAL,2024-08-30,3.68,1189.341

In [18]:
df_sales[df_sales.isna().any(axis=1)]

Empty DataFrame
Columns: [Cari Ünvan, Kodu, Stok Adı, Şehir, Satış Sorumlusu, Tarih, Miktar m2, Tutar TL]
Index: []

In [19]:
df_sales.columns = [x.lower() for x in df_sales.columns]
df_sales.columns = [x.strip() for x in df_sales.columns]
df_sales.rename(columns={"stok adı":"ürün"}, inplace=True)
df_sales

,cari ünvan,kodu,ürün,şehir,satış sorumlusu,tarih,miktar m2,tutar tl
0,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSTANBUL,İSMAİL KURT,2023-04-04,2.16,347.760
1,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSTANBUL,İSMAİL KURT,2023-04-04,1.00,178.000
2,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,"ROMA (KOTAÇMAZI 1200 GR,3MM SÜNGER,MİKROBAMBU ...",İSTANBUL,İSMAİL KURT,2023-04-04,24.72,3979.920
3,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSTANBUL,İSMAİL KURT,2023-04-04,4.89,860.640
4,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,"ROMA (KOTAÇMAZI 1200 GR,3MM SÜNGER,MİKROBAMBU ...",İSTANBUL,İSMAİL KURT,2023-04-04,6.00,946.200
...,...,...,...,...,...,...,...,...
39635,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,ANGORA 30 MM SUED TABAN,BOLU,CAN AHMET VURAL,2024-08-30,1.35,784.224
39636,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,BOLU,CAN AHMET VURAL,2024-08-30,3.36,1147.608
39637,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,BOLU,CAN AHMET VURAL,2024-08-30,5.60,1912.680
39638,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,MİRA 1300 GR KAYMAZ TABAN PAMUK POLYESTER ŞÖNİL,BOLU,CAN AHMET VURAL,2024-08-30,3.68,1189.341
39639,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,MİRA 1300 GR KAYMAZ TABAN PAMUK POLYESTER ŞÖNİL,BOLU,CAN AHMET VURAL,2024-08-30,3.68,1189.341

In [20]:
df_sales.select_dtypes(include='object')

,cari ünvan,kodu,ürün,şehir,satış sorumlusu
0,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSTANBUL,İSMAİL KURT
1,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSTANBUL,İSMAİL KURT
2,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,"ROMA (KOTAÇMAZI 1200 GR,3MM SÜNGER,MİKROBAMBU ...",İSTANBUL,İSMAİL KURT
3,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSTANBUL,İSMAİL KURT
4,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,"ROMA (KOTAÇMAZI 1200 GR,3MM SÜNGER,MİKROBAMBU ...",İSTANBUL,İSMAİL KURT
...,...,...,...,...,...
39635,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,ANGORA 30 MM SUED TABAN,BOLU,CAN AHMET VURAL
39636,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,BOLU,CAN AHMET VURAL
39637,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,BOLU,CAN AHMET VURAL
39638,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,MİRA 1300 GR KAYMAZ TABAN PAMUK POLYESTER ŞÖNİL,BOLU,CAN AHMET VURAL
39639,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,MİRA 1300 GR KAYMAZ TABAN PAMUK POLYESTER ŞÖNİL,BOLU,CAN AHMET VURAL

In [21]:
object_columns = df_sales.select_dtypes(include='object').columns
object_columns

Index(['cari ünvan', 'kodu', 'ürün', 'şehir', 'satış sorumlusu'], dtype='object')

In [22]:
for column in object_columns:
    df_sales[f"{column}"] = df_sales[f"{column}"].apply(lambda x: convert_one_character_letter(x))
    df_sales[f"{column}"] = df_sales[f"{column}"].apply(lambda x: x.strip())

df_sales

,cari ünvan,kodu,ürün,şehir,satış sorumlusu,tarih,miktar m2,tutar tl
0,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSTANBUL,İSMAİL KURT,2023-04-04,2.16,347.760
1,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSTANBUL,İSMAİL KURT,2023-04-04,1.00,178.000
2,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,"ROMA (KOTAÇMAZI 1200 GR,3MM SÜNGER,MİKROBAMBU ...",İSTANBUL,İSMAİL KURT,2023-04-04,24.72,3979.920
3,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSTANBUL,İSMAİL KURT,2023-04-04,4.89,860.640
4,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,"ROMA (KOTAÇMAZI 1200 GR,3MM SÜNGER,MİKROBAMBU ...",İSTANBUL,İSMAİL KURT,2023-04-04,6.00,946.200
...,...,...,...,...,...,...,...,...
39635,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,ANGORA 30 MM SUED TABAN,BOLU,CAN AHMET VURAL,2024-08-30,1.35,784.224
39636,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,BOLU,CAN AHMET VURAL,2024-08-30,3.36,1147.608
39637,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,BOLU,CAN AHMET VURAL,2024-08-30,5.60,1912.680
39638,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,MİRA 1300 GR KAYMAZ TABAN PAMUK POLYESTER ŞÖNİL,BOLU,CAN AHMET VURAL,2024-08-30,3.68,1189.341
39639,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,MİRA 1300 GR KAYMAZ TABAN PAMUK POLYESTER ŞÖNİL,BOLU,CAN AHMET VURAL,2024-08-30,3.68,1189.341

In [23]:
test = "ali ata bak"

In [24]:
test.split(' ', 1)[0]

'ali'

In [25]:
df_sales["model"] = df_sales["ürün"].apply(lambda x: x.split(' ', 1)[0])
df_sales["model"] = df_sales["model"].apply(lambda x: x.strip())
df_sales

,cari ünvan,kodu,ürün,şehir,satış sorumlusu,tarih,miktar m2,tutar tl,model
0,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSTANBUL,İSMAİL KURT,2023-04-04,2.16,347.760,NEPTÜN
1,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSTANBUL,İSMAİL KURT,2023-04-04,1.00,178.000,NEPTÜN
2,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,"ROMA (KOTAÇMAZI 1200 GR,3MM SÜNGER,MİKROBAMBU ...",İSTANBUL,İSMAİL KURT,2023-04-04,24.72,3979.920,ROMA
3,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSTANBUL,İSMAİL KURT,2023-04-04,4.89,860.640,NEPTÜN
4,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,"ROMA (KOTAÇMAZI 1200 GR,3MM SÜNGER,MİKROBAMBU ...",İSTANBUL,İSMAİL KURT,2023-04-04,6.00,946.200,ROMA
...,...,...,...,...,...,...,...,...,...
39635,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,ANGORA 30 MM SUED TABAN,BOLU,CAN AHMET VURAL,2024-08-30,1.35,784.224,ANGORA
39636,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,BOLU,CAN AHMET VURAL,2024-08-30,3.36,1147.608,NEPTÜN
39637,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,BOLU,CAN AHMET VURAL,2024-08-30,5.60,1912.680,NEPTÜN
39638,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,MİRA 1300 GR KAYMAZ TABAN PAMUK POLYESTER ŞÖNİL,BOLU,CAN AHMET VURAL,2024-08-30,3.68,1189.341,MİRA
39639,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,MİRA 1300 GR KAYMAZ TABAN PAMUK POLYESTER ŞÖNİL,BOLU,CAN AHMET VURAL,2024-08-30,3.68,1189.341,MİRA

In [26]:
df_sales.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39640 entries, 0 to 39639
Data columns (total 9 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   cari ünvan       39640 non-null  object
 1   kodu             39640 non-null  object
 2   ürün             39640 non-null  object
 3   şehir            39640 non-null  object
 4   satış sorumlusu  39640 non-null  object
 5   tarih            39640 non-null  datetime64[ns]
 6   miktar m2        39640 non-null  float64
 7   tutar tl         39640 non-null  float64
 8   model            39640 non-null  object
dtypes: datetime64[ns](1), float64(2), object(6)
memory usage: 2.7+ MB

In [27]:
df_city_location

               city       country    invoice_city   latitude  longitude
0             Adana        Turkey           Adana  37.143800  35.498409
1          Adiyaman        Turkey        Adıyaman  37.763750  38.276348
2          Adiyaman        Turkey        Adiyaman  37.763750  38.276348
3    Afyonkarahisar        Turkey  Afyonkarahisar  38.685273  30.642741
4    Afyonkarahisar        Turkey           Afyon  38.685273  30.642741
..              ...           ...             ...        ...        ...
262           Yanbu  Saudi Arabia           Yanbu  24.094893  38.070525
263        Az Zulfi  Saudi Arabia           Zulfi  26.311619  44.832951
264        Qairawan       Tunisia        Qairawan  35.673549  10.098636
265        Al Khodh          Oman        Al Khodh  23.565997  58.118169
266      Almaabilah          Oman      Almaabilah  23.648131  58.146199

[267 rows x 5 columns]

In [28]:
df_sales_location = pd.merge(df_sales, df_city_location, how="left", left_on=df_sales["şehir"].str.capitalize(), right_on=df_city_location["invoice_city"].str.capitalize())
df_sales_location

,key_0,cari ünvan,kodu,ürün,şehir,satış sorumlusu,tarih,miktar m2,tutar tl,model,city,country,invoice_city,latitude,longitude
0,İstanbul,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSTANBUL,İSMAİL KURT,2023-04-04,2.16,347.760,NEPTÜN,Istanbul,Turkey,İstanbul,41.006381,28.975872
1,İstanbul,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSTANBUL,İSMAİL KURT,2023-04-04,1.00,178.000,NEPTÜN,Istanbul,Turkey,İstanbul,41.006381,28.975872
2,İstanbul,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,"ROMA (KOTAÇMAZI 1200 GR,3MM SÜNGER,MİKROBAMBU ...",İSTANBUL,İSMAİL KURT,2023-04-04,24.72,3979.920,ROMA,Istanbul,Turkey,İstanbul,41.006381,28.975872
3,İstanbul,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSTANBUL,İSMAİL KURT,2023-04-04,4.89,860.640,NEPTÜN,Istanbul,Turkey,İstanbul,41.006381,28.975872
4,İstanbul,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,"ROMA (KOTAÇMAZI 1200 GR,3MM SÜNGER,MİKROBAMBU ...",İSTANBUL,İSMAİL KURT,2023-04-04,6.00,946.200,ROMA,Istanbul,Turkey,İstanbul,41.006381,28.975872
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
39635,Bolu,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,ANGORA 30 MM SUED TABAN,BOLU,CAN AHMET VURAL,2024-08-30,1.35,784.224,ANGORA,Bolu,Turkey,Bolu,40.621210,31.646026
39636,Bolu,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,BOLU,CAN AHMET VURAL,2024-08-30,3.36,1147.608,NEPTÜN,Bolu,Turkey,Bolu,40.621210,31.646026
39637,Bolu,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,BOLU,CAN AHMET VURAL,2024-08-30,5.60,1912.680,NEPTÜN,Bolu,Turkey,Bolu,40.621210,31.646026
39638,Bolu,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,MİRA 1300 GR KAYMAZ TABAN PAMUK POLYESTER ŞÖNİL,BOLU,CAN AHMET VURAL,2024-08-30,3.68,1189.341,MİRA,Bolu,Turkey,Bolu,40.621210,31.646026
39639,Bolu,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,MİRA 1300 GR KAYMAZ TABAN PAMUK POLYESTER ŞÖNİL,BOLU,CAN AHMET VURAL,2024-08-30,3.68,1189.341,MİRA,Bolu,Turkey,Bolu,40.621210,31.646026

In [29]:
df_sales_select = df_sales_location.drop(["key_0","invoice_city","şehir"], axis=1)
df_sales_select

,cari ünvan,kodu,ürün,satış sorumlusu,tarih,miktar m2,tutar tl,model,city,country,latitude,longitude
0,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSMAİL KURT,2023-04-04,2.16,347.760,NEPTÜN,Istanbul,Turkey,41.006381,28.975872
1,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSMAİL KURT,2023-04-04,1.00,178.000,NEPTÜN,Istanbul,Turkey,41.006381,28.975872
2,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,"ROMA (KOTAÇMAZI 1200 GR,3MM SÜNGER,MİKROBAMBU ...",İSMAİL KURT,2023-04-04,24.72,3979.920,ROMA,Istanbul,Turkey,41.006381,28.975872
3,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSMAİL KURT,2023-04-04,4.89,860.640,NEPTÜN,Istanbul,Turkey,41.006381,28.975872
4,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,"ROMA (KOTAÇMAZI 1200 GR,3MM SÜNGER,MİKROBAMBU ...",İSMAİL KURT,2023-04-04,6.00,946.200,ROMA,Istanbul,Turkey,41.006381,28.975872
...,...,...,...,...,...,...,...,...,...,...,...,...
39635,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,ANGORA 30 MM SUED TABAN,CAN AHMET VURAL,2024-08-30,1.35,784.224,ANGORA,Bolu,Turkey,40.621210,31.646026
39636,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,CAN AHMET VURAL,2024-08-30,3.36,1147.608,NEPTÜN,Bolu,Turkey,40.621210,31.646026
39637,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,CAN AHMET VURAL,2024-08-30,5.60,1912.680,NEPTÜN,Bolu,Turkey,40.621210,31.646026
39638,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,MİRA 1300 GR KAYMAZ TABAN PAMUK POLYESTER ŞÖNİL,CAN AHMET VURAL,2024-08-30,3.68,1189.341,MİRA,Bolu,Turkey,40.621210,31.646026
39639,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,MİRA 1300 GR KAYMAZ TABAN PAMUK POLYESTER ŞÖNİL,CAN AHMET VURAL,2024-08-30,3.68,1189.341,MİRA,Bolu,Turkey,40.621210,31.646026

In [30]:
df_sales_select.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39640 entries, 0 to 39639
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   cari ünvan       39640 non-null  object
 1   kodu             39640 non-null  object
 2   ürün             39640 non-null  object
 3   satış sorumlusu  39640 non-null  object
 4   tarih            39640 non-null  datetime64[ns]
 5   miktar m2        39640 non-null  float64
 6   tutar tl         39640 non-null  float64
 7   model            39640 non-null  object
 8   city             39230 non-null  object
 9   country          39230 non-null  object
 10  latitude         39230 non-null  float64
 11  longitude        39230 non-null  float64
dtypes: datetime64[ns](1), float64(4), object(7)
memory usage: 3.6+ MB

In [31]:
df_sales_select[df_sales_select.isna().any(axis=1)]

,cari ünvan,kodu,ürün,satış sorumlusu,tarih,miktar m2,tutar tl,model,city,country,latitude,longitude
305,KARİZMA DEKORASYON MOBİLYA İNŞAAT SANAYİ VE DI...,120.01.279,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSMAİL KURT,2023-07-28,1.00,253.000,NEPTÜN,NaN,NaN,NaN,NaN
306,KARİZMA DEKORASYON MOBİLYA İNŞAAT SANAYİ VE DI...,120.01.279,MARS BEYAZ DOT TABAN PELUŞ,İSMAİL KURT,2023-07-28,1.00,204.000,MARS,NaN,NaN,NaN,NaN
307,KARİZMA DEKORASYON MOBİLYA İNŞAAT SANAYİ VE DI...,120.01.279,MARS BEYAZ DOT TABAN PELUŞ,İSMAİL KURT,2023-07-28,1.00,204.000,MARS,NaN,NaN,NaN,NaN
308,KARİZMA DEKORASYON MOBİLYA İNŞAAT SANAYİ VE DI...,120.01.279,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSMAİL KURT,2023-07-28,1.44,364.000,NEPTÜN,NaN,NaN,NaN,NaN
309,KARİZMA DEKORASYON MOBİLYA İNŞAAT SANAYİ VE DI...,120.01.279,"ROMA (KOTAÇMAZI 1200 GR,3MM SÜNGER,MİKROBAMBU ...",İSMAİL KURT,2023-07-28,3.00,723.000,ROMA,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
38864,AHMET KAPLAN-EVSER HALI,120.01.311,BEGONYA 1650 GR POLYESTER KAYMAZ TABAN DOKUMA,MUSTAFA ÇETİN,2024-08-28,3.60,1537.542,BEGONYA,NaN,NaN,NaN,NaN
38865,AHMET KAPLAN-EVSER HALI,120.01.311,HAVANA BUBBLE TAVŞAN TÜYÜ POST KAZAYAĞI PAMUK ...,MUSTAFA ÇETİN,2024-08-28,3.00,1983.285,HAVANA,NaN,NaN,NaN,NaN
39375,HASAN UĞUR-UĞUR TİCARET,120.02.0299,MİRA 1300 GR KAYMAZ TABAN PAMUK POLYESTER ŞÖNİL,MUSTAFA ÇETİN,2024-08-30,5.80,1874.502,MİRA,NaN,NaN,NaN,NaN
39385,SAFİYE KARATOPCU-KARATOPÇULAR MANİFATURA,120.01.668,HAVANA BUBBLE TAVŞAN TÜYÜ POST KAZAYAĞI PAMUK ...,MUSTAFA ÇETİN,2024-08-30,0.80,587.640,HAVANA,NaN,NaN,NaN,NaN
39416,AHMET YILMAZ-HAKAN HALI MOBİLYA,120.02.0329,"YAKUT (KOTAÇMAZI 1200 GR,3MM SÜNGER , 125 KUMAŞ )",MUSTAFA ÇETİN,2024-08-30,1.76,501.600,YAKUT,NaN,NaN,NaN,NaN

In [32]:
df_sales_select.fillna("Diger", inplace=True)
df_sales_select

C:\Users\user\AppData\Local\Temp\ipykernel_4224\4046441013.py:1: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'Diger' has dtype incompatible with float64, please explicitly cast to a compatible dtype first.
  df_sales_select.fillna("Diger", inplace=True)

,cari ünvan,kodu,ürün,satış sorumlusu,tarih,miktar m2,tutar tl,model,city,country,latitude,longitude
0,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSMAİL KURT,2023-04-04,2.16,347.760,NEPTÜN,Istanbul,Turkey,41.006381,28.975872
1,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSMAİL KURT,2023-04-04,1.00,178.000,NEPTÜN,Istanbul,Turkey,41.006381,28.975872
2,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,"ROMA (KOTAÇMAZI 1200 GR,3MM SÜNGER,MİKROBAMBU ...",İSMAİL KURT,2023-04-04,24.72,3979.920,ROMA,Istanbul,Turkey,41.006381,28.975872
3,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,İSMAİL KURT,2023-04-04,4.89,860.640,NEPTÜN,Istanbul,Turkey,41.006381,28.975872
4,MİRZA KİLİM LİMİTED ŞİRKETİ,120.01.076,"ROMA (KOTAÇMAZI 1200 GR,3MM SÜNGER,MİKROBAMBU ...",İSMAİL KURT,2023-04-04,6.00,946.200,ROMA,Istanbul,Turkey,41.006381,28.975872
...,...,...,...,...,...,...,...,...,...,...,...,...
39635,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,ANGORA 30 MM SUED TABAN,CAN AHMET VURAL,2024-08-30,1.35,784.224,ANGORA,Bolu,Turkey,40.62121,31.646026
39636,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,CAN AHMET VURAL,2024-08-30,3.36,1147.608,NEPTÜN,Bolu,Turkey,40.62121,31.646026
39637,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,CAN AHMET VURAL,2024-08-30,5.60,1912.680,NEPTÜN,Bolu,Turkey,40.62121,31.646026
39638,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,MİRA 1300 GR KAYMAZ TABAN PAMUK POLYESTER ŞÖNİL,CAN AHMET VURAL,2024-08-30,3.68,1189.341,MİRA,Bolu,Turkey,40.62121,31.646026
39639,HİLMİ YİĞİT-YİĞİT BÜNYAN HALI,120.01.351,MİRA 1300 GR KAYMAZ TABAN PAMUK POLYESTER ŞÖNİL,CAN AHMET VURAL,2024-08-30,3.68,1189.341,MİRA,Bolu,Turkey,40.62121,31.646026

In [33]:
df_sales_select.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 39640 entries, 0 to 39639
Data columns (total 12 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   cari ünvan       39640 non-null  object
 1   kodu             39640 non-null  object
 2   ürün             39640 non-null  object
 3   satış sorumlusu  39640 non-null  object
 4   tarih            39640 non-null  datetime64[ns]
 5   miktar m2        39640 non-null  float64
 6   tutar tl         39640 non-null  float64
 7   model            39640 non-null  object
 8   city             39640 non-null  object
 9   country          39640 non-null  object
 10  latitude         39640 non-null  object
 11  longitude        39640 non-null  object
dtypes: datetime64[ns](1), float64(2), object(9)
memory usage: 3.6+ MB

In [34]:
df_sales_select.to_excel(r"C:\Users\user\Downloads\Halı Satış Sorumlusu Satış For Tableau (24.03.2023-31.08.2024).xlsx", index=False)

In [244]:
df_sales_select_group_product_m2 = df_sales_select.groupby(["satış sorumlusu","ürün"])["miktar m2"].sum().reset_index()
df_sales_select_group_product_m2_sort = df_sales_select_group_product_m2.sort_values(["satış sorumlusu","miktar m2"], ascending=[True,False])
df_sales_select_group_product_m2_sort = df_sales_select_group_product_m2_sort.reset_index(drop=True)
df_sales_select_group_product_m2_sort

,satış sorumlusu,ürün,miktar m2
0,ALİ YILDIRIM,MİRA 1300 GR KAYMAZ TABAN PAMUK POLYESTER ŞÖNİL,1826.68
1,ALİ YILDIRIM,LUNA 1300 GR KAYMAZ TABAN PAMUK POLYESTER ŞÖNİL,874.95
2,ALİ YILDIRIM,MARS BEYAZ DOT TABAN PELUŞ,863.46
3,ALİ YILDIRIM,"ROMA (KOTAÇMAZI 1200 GR,3MM SÜNGER,MİKROBAMBU ...",525.42
4,ALİ YILDIRIM,ORKİDE 1300 GR ÇÖKENLİ POLYESTER AKRİLİK KAYMA...,468.44
...,...,...,...
465,ŞABAN SİLAHŞÖR,LUNA 1300 GR KAYMAZ TABAN PAMUK POLYESTER ŞÖNİL,7.10
466,ŞABAN SİLAHŞÖR,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,6.00
467,ŞABAN SİLAHŞÖR,"BERLİN (KAZAYAĞI PAMUK TABAN 750GR,SÜNGER,MİKR...",5.74
468,ŞABAN SİLAHŞÖR,"MİMOZA (450 EKO B.DOT, 3MM SÜNGER, 125 GR KUMAŞ",4.80
469,ŞABAN SİLAHŞÖR,ANGORA 30 MM SUED TABAN,2.15

In [56]:
df_sales_select_group_product_m2_sort.to_excel(r"C:\Users\user\Downloads\Halı Satış Sorumlusu Ürün Satış M2 (24.03.2023-31.08.2024).xlsx", index=False)

In [246]:
df_sales_select_group_model_m2 = df_sales_select.groupby(["satış sorumlusu","model"])["miktar m2"].sum().reset_index()
df_sales_select_group_model_m2_sort = df_sales_select_group_model_m2.sort_values(["satış sorumlusu","miktar m2"], ascending=[True,False])
df_sales_select_group_model_m2_sort = df_sales_select_group_model_m2_sort.reset_index(drop=True)
df_sales_select_group_model_m2_sort

    satış sorumlusu   model  miktar m2
0      ALİ YILDIRIM    MİRA    1826.68
1      ALİ YILDIRIM    LUNA     924.79
2      ALİ YILDIRIM    MARS     863.46
3      ALİ YILDIRIM    ROMA     525.42
4      ALİ YILDIRIM  ORKİDE     468.44
..              ...     ...        ...
449  ŞABAN SİLAHŞÖR    LUNA       7.10
450  ŞABAN SİLAHŞÖR  NEPTÜN       6.00
451  ŞABAN SİLAHŞÖR  BERLİN       5.74
452  ŞABAN SİLAHŞÖR  MİMOZA       4.80
453  ŞABAN SİLAHŞÖR  ANGORA       2.15

[454 rows x 3 columns]

In [ ]:
df_sales_select_group_model_m2_sort.to_excel(r"C:\Users\user\Downloads\Halı Satış Sorumlusu Model Satış M2 (24.03.2023-31.08.2024).xlsx", index=False)

In [248]:
df_sales_select_group_product_total_tl = df_sales_select.groupby(["satış sorumlusu","ürün"])["tutar tl"].sum().reset_index()
df_sales_select_group_product_total_tl_sort = df_sales_select_group_product_total_tl.sort_values(["satış sorumlusu","tutar tl"], ascending=[True,False])
df_sales_select_group_product_total_tl_sort = df_sales_select_group_product_total_tl_sort.reset_index(drop=True)
df_sales_select_group_product_total_tl_sort

,satış sorumlusu,ürün,tutar tl
0,ALİ YILDIRIM,MİRA 1300 GR KAYMAZ TABAN PAMUK POLYESTER ŞÖNİL,604328.9665
1,ALİ YILDIRIM,LUNA 1300 GR KAYMAZ TABAN PAMUK POLYESTER ŞÖNİL,302885.9570
2,ALİ YILDIRIM,ORKİDE 1300 GR ÇÖKENLİ POLYESTER AKRİLİK KAYMA...,195054.0500
3,ALİ YILDIRIM,"ROMA (KOTAÇMAZI 1200 GR,3MM SÜNGER,MİKROBAMBU ...",177824.6870
4,ALİ YILDIRIM,HAVANA BUBBLE TAVŞAN TÜYÜ POST KAZAYAĞI PAMUK ...,149907.4615
...,...,...,...
465,ŞABAN SİLAHŞÖR,LUNA 1300 GR KAYMAZ TABAN PAMUK POLYESTER ŞÖNİL,2661.7900
466,ŞABAN SİLAHŞÖR,NEPTÜN 1200 GR KOTAÇMAZI PAMUK TABAN PELUŞ,2277.0000
467,ŞABAN SİLAHŞÖR,"BERLİN (KAZAYAĞI PAMUK TABAN 750GR,SÜNGER,MİKR...",1925.2000
468,ŞABAN SİLAHŞÖR,ANGORA 30 MM SUED TABAN,1439.0200
469,ŞABAN SİLAHŞÖR,"MİMOZA (450 EKO B.DOT, 3MM SÜNGER, 125 GR KUMAŞ",825.1200

In [ ]:
df_sales_select_group_product_total_tl_sort.to_excel(r"C:\Users\user\Downloads\Halı Satış Sorumlusu Ürün Satış Toplam TL(24.03.2023-31.08.2024).xlsx", index=False)

In [249]:
df_sales_select_group_model_total_tl = df_sales_select.groupby(["satış sorumlusu","model"])["tutar tl"].sum().reset_index()
df_sales_select_group_model_total_tl_sort = df_sales_select_group_model_total_tl.sort_values(["satış sorumlusu","tutar tl"], ascending=[True,False])
df_sales_select_group_model_total_tl_sort = df_sales_select_group_model_total_tl_sort.reset_index(drop=True)
df_sales_select_group_model_total_tl_sort

    satış sorumlusu   model     tutar tl
0      ALİ YILDIRIM    MİRA  604328.9665
1      ALİ YILDIRIM    LUNA  321498.6170
2      ALİ YILDIRIM  ORKİDE  195054.0500
3      ALİ YILDIRIM    ROMA  177824.6870
4      ALİ YILDIRIM  HAVANA  149907.4615
..              ...     ...          ...
449  ŞABAN SİLAHŞÖR    LUNA    2661.7900
450  ŞABAN SİLAHŞÖR  NEPTÜN    2277.0000
451  ŞABAN SİLAHŞÖR  BERLİN    1925.2000
452  ŞABAN SİLAHŞÖR  ANGORA    1439.0200
453  ŞABAN SİLAHŞÖR  MİMOZA     825.1200

[454 rows x 3 columns]

In [ ]:
df_sales_select_group_model_total_tl_sort.to_excel(r"C:\Users\user\Downloads\Halı Satış Sorumlusu Model Satış Toplam TL 24.03.2023-31.08.2024).xlsx", index=False)