### Deployment Result

In [1]:
import pandas as pd
import numpy as np
import re
from camel_tools.utils.charmap import CharMapper
from lang_trans.arabic import buckwalter
import nltk
from nltk import word_tokenize
from nltk import ngrams
import json
import re

In [2]:
df_word_merge = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/6-Morphology And Tanzil/Arabic_Buckwalter_Clean_Plain_Word_Merge_Tanzil.xlsx")
df_word_merge

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain
0,1,1,1,بسم,bsm,بِسْمِ,bisomi
1,1,1,2,الله,Allh,اللَّهِ,All~ahi
2,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni
3,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi
4,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu
...,...,...,...,...,...,...,...
78243,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri
78244,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi
78245,114,6,1,من,mn,مِنَ,mina
78246,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api
78247,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi

In [3]:
df_select_word = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/5-Tanzil Analysis/Arabic_Buckwalter_Word_Frequency_Tanzil_Clean.xlsx")
df_select_word

      arabic_word_tanzil_clean buckwalter_word_tanzil_clean  frequency
0                           من                           mn       2763
1                         الله                         Allh       2265
2                           في                           fy       1185
3                           ما                           mA       1013
4                           إن                           <n        966
...                        ...                          ...        ...
14863                    مرفقا                        mrfqA          1
14864                    ويهيئ                        wyhy}          1
14865                     ينشر                         yn$r          1
14866                    فأووا                        f>wwA          1
14867                    يوسوس                        ywsws          1

[14868 rows x 3 columns]

In [4]:
df_select_word_100 = df_select_word.iloc[0:100,]
df_select_word_100_200 = df_select_word.iloc[100:200,]
df_select_word_200 = df_select_word.iloc[0:200,]

#### Adding Color Column

In [5]:
select_word_list_100 = df_select_word_100.iloc[:,0].to_list()
select_word_list_100_200 = df_select_word_100_200.iloc[:,0].to_list()
select_word_list_200 = df_select_word_200.iloc[:,0].to_list()
#select_word_list

In [6]:
select_word_text_100 = " ".join(select_word_list_100)
select_word_text_100_200 = " ".join(select_word_list_100_200)
select_word_text_200 = " ".join(select_word_list_200)

In [7]:
# 1 Way
def compare_word_text(word, word_text):
    if re.search(fr"(?:\s|^){word}(?:\s|$)", word_text):
        return 1
    else:
        return 0

In [8]:
df_word_merge.iloc[:,3].apply(lambda x: compare_word_text(x, select_word_text_100))

0        1
1        1
2        1
3        1
4        0
        ..
78243    0
78244    1
78245    1
78246    0
78247    0
Name: arabic_word_tanzil_clean, Length: 78248, dtype: int64

In [28]:
## 2 Way
#def compare_word_list(word, word_list):
#    for i in word_list:
#        if re.search(fr"(?:\s|^){i}(?:\s|$)", word):
#            return 1

In [29]:
#df_word_merge.iloc[:,3].apply(lambda x: compare_word_list(x, select_word_list))

In [30]:
#df_word_merge["color"] = df_word_merge.iloc[:,3].apply(lambda x: compare_word_list(x, select_word_list))
#df_word_merge

In [31]:
#df_word_merge.color = df_word_merge.color.fillna(0)
#df_word_merge

In [ ]:
#df_word_merge.color.sum()

In [9]:
df_word_merge["first_100_word"] = df_word_merge.iloc[:,3].apply(lambda x: compare_word_text(x, select_word_text_100))
df_word_merge

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,first_100_word
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,1
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,1
2,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,1
3,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,1
4,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,0
...,...,...,...,...,...,...,...,...
78243,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,0
78244,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,1
78245,114,6,1,من,mn,مِنَ,mina,1
78246,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,0
78247,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,0

In [10]:
df_word_merge["100_200_word"] = df_word_merge.iloc[:,3].apply(lambda x: compare_word_text(x, select_word_text_100_200))
df_word_merge

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,first_100_word,100_200_word
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,1,0
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,1,0
2,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,1,0
3,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,1,0
4,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,0,0
...,...,...,...,...,...,...,...,...,...
78243,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,0,0
78244,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,1,0
78245,114,6,1,من,mn,مِنَ,mina,1,0
78246,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,0,1
78247,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,0,0

In [11]:
df_word_merge["first_200_word"] = df_word_merge.iloc[:,3].apply(lambda x: compare_word_text(x, select_word_text_200))
df_word_merge

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,first_100_word,100_200_word,first_200_word
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,1,0,1
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,1,0,1
2,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,1,0,1
3,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,1,0,1
4,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,0,0,0
...,...,...,...,...,...,...,...,...,...,...
78243,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,0,0,0
78244,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,1,0,1
78245,114,6,1,من,mn,مِنَ,mina,1,0,1
78246,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,0,1,1
78247,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,0,0,0

In [12]:
df_root = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/2-Morphology Root Analysis/Arabic_Buckwalter_Form_Root_Morphology.xlsx")
df_root

       num_1  num_2  num_3  num_4        form  tag  root root_arabic
0          1      1      1      2        somi    N   smw         سمو
1          1      1      2      1     {ll~ahi   PN   Alh         اله
2          1      1      3      2  r~aHoma`ni  ADJ   rHm         رحم
3          1      1      4      2    r~aHiymi  ADJ   rHm         رحم
4          1      2      1      2      Hamodu    N   Hmd         حمد
...      ...    ...    ...    ...         ...  ...   ...         ...
49963    114      5      2      1  yuwasowisu    V  wsws        وسوس
49964    114      5      4      1     Suduwri    N   Sdr         صدر
49965    114      5      5      2      n~aAsi    N   nws         نوس
49966    114      6      2      2     jin~api    N   jnn         جنن
49967    114      6      3      3      n~aAsi    N   nws         نوس

[49968 rows x 8 columns]

In [13]:
df_word_root_merge = pd.merge(df_word_merge,df_root, how="left", on=["num_1","num_2","num_3"])
df_word_root_merge = df_word_root_merge.iloc[:,[0,1,2,3,4,5,6,11,13,14,12,7,8,9]]
df_word_root_merge

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,form,root,root_arabic,tag,first_100_word,100_200_word,first_200_word
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,somi,smw,سمو,N,1,0,1
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,{ll~ahi,Alh,اله,PN,1,0,1
2,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,r~aHoma`ni,rHm,رحم,ADJ,1,0,1
3,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,r~aHiymi,rHm,رحم,ADJ,1,0,1
4,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,Hamodu,Hmd,حمد,N,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78244,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,Suduwri,Sdr,صدر,N,0,0,0
78245,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,n~aAsi,nws,نوس,N,1,0,1
78246,114,6,1,من,mn,مِنَ,mina,NaN,NaN,NaN,NaN,1,0,1
78247,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,jin~api,jnn,جنن,N,0,1,1
78248,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,n~aAsi,nws,نوس,N,0,0,0

In [14]:
df_word_root_merge.drop_duplicates(inplace=True)

In [15]:
df_word_root_merge

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,form,root,root_arabic,tag,first_100_word,100_200_word,first_200_word
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,somi,smw,سمو,N,1,0,1
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,{ll~ahi,Alh,اله,PN,1,0,1
2,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,r~aHoma`ni,rHm,رحم,ADJ,1,0,1
3,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,r~aHiymi,rHm,رحم,ADJ,1,0,1
4,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,Hamodu,Hmd,حمد,N,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78244,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,Suduwri,Sdr,صدر,N,0,0,0
78245,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,n~aAsi,nws,نوس,N,1,0,1
78246,114,6,1,من,mn,مِنَ,mina,NaN,NaN,NaN,NaN,1,0,1
78247,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,jin~api,jnn,جنن,N,0,1,1
78248,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,n~aAsi,nws,نوس,N,0,0,0

In [16]:
#df_word_root_merge.to_excel("Arabic_Buckwalter_Word_Root_Color.xlsx",index=False)

#### Adding N Gram Flag

In [12]:
#df_twogram = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/4-N Gram/Arabic_Clean_Twogram_Frequency_From_DataFrame_Tanzil.xlsx")
df_twogram = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/4-N Gram/Arabic_Clean_Twogram_Frequency_From_DataFrame_Tanzil2.xlsx")
#df_twogram = df_twogram.iloc[0:100,]
df_twogram = df_twogram.iloc[100:200,]
#df_twogram = df_twogram.iloc[0:200,]
df_twogram

         twogram
100    الله غفور
101        قل إن
102      بكل شيء
103      عن سبيل
104      لا يهدي
..           ...
195    وأولئك هم
196  من المشركين
197      ولو شاء
198   إنهم كانوا
199      من ربهم

[100 rows x 1 columns]

In [13]:
df_sent = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/5-Tanzil Analysis/Arabic_Buckwalter_Sent_Tanzil_Clean.xlsx")
df_sent

      num_1  num_2  arabic_sent_tanzil_clean buckwalter_sent_tanzil_clean
0         1      1    بسم الله الرحمن الرحيم       bsm Allh AlrHmn AlrHym
1         1      2     الحمد لله رب العالمين        AlHmd llh rb AlEAlmyn
2         1      3             الرحمن الرحيم                AlrHmn AlrHym
3         1      4            مالك يوم الدين               mAlk ywm Aldyn
4         1      5    إياك نعبد وإياك نستعين       <yAk nEbd w<yAk nstEyn
...     ...    ...                       ...                          ...
6231    114      2                 ملك الناس                    mlk AlnAs
6232    114      3                 إله الناس                    <lh AlnAs
6233    114      4      من شر الوسواس الخناس         mn $r AlwswAs AlxnAs
6234    114      5  الذي يوسوس في صدور الناس     Al*y ywsws fy Sdwr AlnAs
6235    114      6           من الجنة والناس              mn Aljnp wAlnAs

[6236 rows x 4 columns]

In [14]:
# Two Gram
df_sent_twogram_result = pd.DataFrame()
for i in df_twogram.iloc[:,0]:
    try:
        sent_in_video = df_sent[df_sent.arabic_sent_tanzil_clean.str.contains(fr"(^|\s){i}(\s|$)", regex=True)]
        #sent_in_video = df_sent[df_sent.arabic_sent_tanzil_clean.str.contains(fr"(^|\s){i}(\s|$)")].sample(10)
    except:
        sent_in_video = df_sent[df_sent.arabic_sent_tanzil_clean.str.contains(fr"(^|\s){i}(\s|$)", regex=True)] 
        #sent_in_video = df_sent[df_sent.arabic_sent_tanzil_clean.str.contains(fr"(^|\s){i}(\s|$)")].head(10) 
    sent_in_video.insert(0,"twogram",i)
    df_sent_twogram_result = pd.concat([df_sent_twogram_result,sent_in_video], axis=0)
df_sent_twogram_result.reset_index(drop=True, inplace=True)
df_sent_twogram_result

<ipython-input-14-40e6f74a9873>:5: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  sent_in_video = df_sent[df_sent.arabic_sent_tanzil_clean.str.contains(fr"(^|\s){i}(\s|$)", regex=True)]

,twogram,num_1,num_2,arabic_sent_tanzil_clean,buckwalter_sent_tanzil_clean
0,الله غفور,2,173,إنما حرم عليكم الميتة والدم ولحم الخنزير وما أ...,<nmA Hrm Elykm Almytp wAldm wlHm Alxnzyr wmA >...
1,الله غفور,2,182,فمن خاف من موص جنفا أو إثما فأصلح بينهم فلا إث...,fmn xAf mn mwS jnfA >w <vmA f>SlH bynhm flA <v...
2,الله غفور,2,192,فإن انتهوا فإن الله غفور رحيم,f<n AnthwA f<n Allh gfwr rHym
3,الله غفور,2,199,ثم أفيضوا من حيث أفاض الناس واستغفروا الله إن ...,vm >fyDwA mn Hyv >fAD AlnAs wAstgfrwA Allh <n ...
4,الله غفور,2,226,للذين يؤلون من نسائهم تربص أربعة أشهر فإن فاءو...,ll*yn y&lwn mn nsA}hm trbS >rbEp >$hr f<n fA'w...
...,...,...,...,...,...
1981,من ربهم,31,5,أولئك على هدى من ربهم وأولئك هم المفلحون,>wl}k ElY hdY mn rbhm w>wl}k hm AlmflHwn
1982,من ربهم,47,2,والذين آمنوا وعملوا الصالحات وآمنوا بما نزل عل...,wAl*yn |mnwA wEmlwA AlSAlHAt w|mnwA bmA nzl El...
1983,من ربهم,47,3,ذلك بأن الذين كفروا اتبعوا الباطل وأن الذين آم...,*lk b>n Al*yn kfrwA AtbEwA AlbATl w>n Al*yn |m...
1984,من ربهم,47,15,مثل الجنة التي وعد المتقون فيها أنهار من ماء غ...,mvl Aljnp Alty wEd Almtqwn fyhA >nhAr mn mA' g...
1985,من ربهم,53,23,إن هي إلا أسماء سميتموها أنتم وآباؤكم ما أنزل ...,<n hy <lA >smA' smytmwhA >ntm w|bA&km mA >nzl ...

In [15]:
# ngram_loc_list = []
# for i in range(len(df_sent_ngram_result)):
#     num_1 = df_sent_ngram_result.loc[i,"num_1"]
#     num_2 = df_sent_ngram_result.loc[i,"num_2"]
#     sent = df_sent_ngram_result.loc[i,"arabic_sent_tanzil_clean"]
#     ngram = df_sent_ngram_result.loc[i,"ngram"]
#     sent_token = word_tokenize(sent)
#     ngram_token = word_tokenize(ngram)
#     for j in ngram_token:
#         for k in range(len(sent_token)):
#             if j == sent_token[k]:
#                 num_3 = k+1
#                 ngram_loc_list.append((num_1,num_2,num_3,j,sent))
#                 
# df_ngram_loc = pd.DataFrame(ngram_loc_list)
# df_ngram_loc.rename(columns={0:"num_1",1:"num_2",2:"num_3",3:"ngram_word",4:"arabic_sent_tanzil_clean"},inplace=True)
# df_ngram_loc

In [16]:
# Two Gram
twogram_loc_list = []
for i in range(len(df_sent_twogram_result)):
    num_1 = df_sent_twogram_result.loc[i,"num_1"]
    num_2 = df_sent_twogram_result.loc[i,"num_2"]
    sent = df_sent_twogram_result.loc[i,"arabic_sent_tanzil_clean"]
    ngram = df_sent_twogram_result.loc[i,"twogram"]
    sent_token = word_tokenize(sent)
    ngram_token = word_tokenize(ngram)    
    for j in range(len(ngram_token)):        
        for k in range(len(sent_token)):
            if ngram_token[j] == sent_token[k]:
                try:
                    if ngram_token[j+1] == sent_token[k+1]:
                        num_3 = k+1  # +1 because of k begins with 0 
                        twogram_loc_list.append((num_1,num_2,num_3,ngram_token[j],sent))
                        twogram_loc_list.append((num_1,num_2,num_3+1,ngram_token[j+1],sent))
                except:
                    pass
                
df_twogram_loc = pd.DataFrame(twogram_loc_list)
df_twogram_loc.rename(columns={0:"num_1",1:"num_2",2:"num_3",3:"arabic_word_tanzil_clean",4:"arabic_sent_tanzil_clean"},inplace=True)
df_twogram_loc["100_200_twogram"] = 2
df_twogram_loc

,num_1,num_2,num_3,arabic_word_tanzil_clean,arabic_sent_tanzil_clean,100_200_twogram
0,2,173,23,الله,إنما حرم عليكم الميتة والدم ولحم الخنزير وما أ...,2
1,2,173,24,غفور,إنما حرم عليكم الميتة والدم ولحم الخنزير وما أ...,2
2,2,182,14,الله,فمن خاف من موص جنفا أو إثما فأصلح بينهم فلا إث...,2
3,2,182,15,غفور,فمن خاف من موص جنفا أو إثما فأصلح بينهم فلا إث...,2
4,2,192,4,الله,فإن انتهوا فإن الله غفور رحيم,2
...,...,...,...,...,...,...
4021,47,3,13,ربهم,ذلك بأن الذين كفروا اتبعوا الباطل وأن الذين آم...,2
4022,47,15,33,من,مثل الجنة التي وعد المتقون فيها أنهار من ماء غ...,2
4023,47,15,34,ربهم,مثل الجنة التي وعد المتقون فيها أنهار من ماء غ...,2
4024,53,23,23,من,إن هي إلا أسماء سميتموها أنتم وآباؤكم ما أنزل ...,2
4025,53,23,24,ربهم,إن هي إلا أسماء سميتموها أنتم وآباؤكم ما أنزل ...,2

In [17]:
df_twogram_loc.to_excel("Arabic_100_200_Twogram_Loc_With_Sent2.xlsx",index=False)

In [26]:
#df_threegram = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/4-N Gram/Arabic_Clean_Threegram_Frequency_From_DataFrame_Tanzil.xlsx")
df_threegram = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/4-N Gram/Arabic_Clean_Threegram_Frequency_From_DataFrame_Tanzil2.xlsx")
#df_threegram = df_threegram.iloc[0:100,]
df_threegram = df_threegram.iloc[100:200,]
#df_threegram = df_threegram.iloc[0:200,]
df_threegram

             threegram
100  لا يؤمنون بالآخرة
101       الله لا يهدي
102          إن هو إلا
103    الذين آمنوا إذا
104          ألم تر أن
..                 ...
195          كل نفس ما
196        إن وعد الله
197        إلا أن يشاء
198    لو كانوا يعلمون
199  الذين أوتوا العلم

[100 rows x 1 columns]

In [27]:
# Three Gram
df_sent_threegram_result = pd.DataFrame()
for i in df_threegram.iloc[:,0]:
    try:
        sent_in_video = df_sent[df_sent.arabic_sent_tanzil_clean.str.contains(fr"(^|\s){i}(\s|$)", regex=True)]
        #sent_in_video = df_sent[df_sent.arabic_sent_tanzil_clean.str.contains(fr"(^|\s){i}(\s|$)")].sample(10)
    except:
        sent_in_video = df_sent[df_sent.arabic_sent_tanzil_clean.str.contains(fr"(^|\s){i}(\s|$)", regex=True)] 
        #sent_in_video = df_sent[df_sent.arabic_sent_tanzil_clean.str.contains(fr"(^|\s){i}(\s|$)")].head(10) 
    sent_in_video.insert(0,"threegram",i)
    df_sent_threegram_result = pd.concat([df_sent_threegram_result,sent_in_video], axis=0)
df_sent_threegram_result.reset_index(drop=True, inplace=True)
df_sent_threegram_result

<ipython-input-27-4b5e989fca7f>:5: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  sent_in_video = df_sent[df_sent.arabic_sent_tanzil_clean.str.contains(fr"(^|\s){i}(\s|$)", regex=True)]

,threegram,num_1,num_2,arabic_sent_tanzil_clean,buckwalter_sent_tanzil_clean
0,لا يؤمنون بالآخرة,6,113,ولتصغى إليه أفئدة الذين لا يؤمنون بالآخرة ولير...,wltSgY <lyh >f}dp Al*yn lA y&mnwn bAl|xrp wlyr...
1,لا يؤمنون بالآخرة,6,150,قل هلم شهداءكم الذين يشهدون أن الله حرم هذا فإ...,ql hlm $hdA'km Al*yn y$hdwn >n Allh Hrm h*A f<...
2,لا يؤمنون بالآخرة,16,22,إلهكم إله واحد فالذين لا يؤمنون بالآخرة قلوبهم...,<lhkm <lh wAHd fAl*yn lA y&mnwn bAl|xrp qlwbhm...
3,لا يؤمنون بالآخرة,16,60,للذين لا يؤمنون بالآخرة مثل السوء ولله المثل ا...,ll*yn lA y&mnwn bAl|xrp mvl Alsw' wllh Almvl A...
4,لا يؤمنون بالآخرة,17,10,وأن الذين لا يؤمنون بالآخرة أعتدنا لهم عذابا أ...,w>n Al*yn lA y&mnwn bAl|xrp >EtdnA lhm E*AbA >...
...,...,...,...,...,...
906,الذين أوتوا العلم,22,54,وليعلم الذين أوتوا العلم أنه الحق من ربك فيؤمن...,wlyElm Al*yn >wtwA AlElm >nh AlHq mn rbk fy&mn...
907,الذين أوتوا العلم,28,80,وقال الذين أوتوا العلم ويلكم ثواب الله خير لمن...,wqAl Al*yn >wtwA AlElm wylkm vwAb Allh xyr lmn...
908,الذين أوتوا العلم,29,49,بل هو آيات بينات في صدور الذين أوتوا العلم وما...,bl hw |yAt bynAt fy Sdwr Al*yn >wtwA AlElm wmA...
909,الذين أوتوا العلم,30,56,وقال الذين أوتوا العلم والإيمان لقد لبثتم في ك...,wqAl Al*yn >wtwA AlElm wAl<ymAn lqd lbvtm fy k...
910,الذين أوتوا العلم,34,6,ويرى الذين أوتوا العلم الذي أنزل إليك من ربك ه...,wyrY Al*yn >wtwA AlElm Al*y >nzl <lyk mn rbk h...

In [28]:
# Three Gram
threegram_loc_list = []
for i in range(len(df_sent_threegram_result)):
    num_1 = df_sent_threegram_result.loc[i,"num_1"]
    num_2 = df_sent_threegram_result.loc[i,"num_2"]
    sent = df_sent_threegram_result.loc[i,"arabic_sent_tanzil_clean"]
    ngram = df_sent_threegram_result.loc[i,"threegram"]
    sent_token = word_tokenize(sent)
    ngram_token = word_tokenize(ngram)    
    for j in range(len(ngram_token)):        
        for k in range(len(sent_token)):
            if ngram_token[j] == sent_token[k]:
                try:
                    if ngram_token[j+1] == sent_token[k+1]:
                        if ngram_token[j+2] == sent_token[k+2]:
                            num_3 = k+1
                            threegram_loc_list.append((num_1,num_2,num_3,ngram_token[j],sent))
                            threegram_loc_list.append((num_1,num_2,num_3+1,ngram_token[j+1],sent))
                            threegram_loc_list.append((num_1,num_2,num_3+2,ngram_token[j+2],sent))
                except:
                    pass
                
df_threegram_loc = pd.DataFrame(threegram_loc_list)
df_threegram_loc.rename(columns={0:"num_1",1:"num_2",2:"num_3",3:"arabic_word_tanzil_clean",4:"arabic_sent_tanzil_clean"},inplace=True)
df_threegram_loc["100_200_threegram"] = 3
df_threegram_loc

,num_1,num_2,num_3,arabic_word_tanzil_clean,arabic_sent_tanzil_clean,100_200_threegram
0,6,113,5,لا,ولتصغى إليه أفئدة الذين لا يؤمنون بالآخرة ولير...,3
1,6,113,6,يؤمنون,ولتصغى إليه أفئدة الذين لا يؤمنون بالآخرة ولير...,3
2,6,113,7,بالآخرة,ولتصغى إليه أفئدة الذين لا يؤمنون بالآخرة ولير...,3
3,6,150,22,لا,قل هلم شهداءكم الذين يشهدون أن الله حرم هذا فإ...,3
4,6,150,23,يؤمنون,قل هلم شهداءكم الذين يشهدون أن الله حرم هذا فإ...,3
...,...,...,...,...,...,...
2734,30,56,3,أوتوا,وقال الذين أوتوا العلم والإيمان لقد لبثتم في ك...,3
2735,30,56,4,العلم,وقال الذين أوتوا العلم والإيمان لقد لبثتم في ك...,3
2736,34,6,2,الذين,ويرى الذين أوتوا العلم الذي أنزل إليك من ربك ه...,3
2737,34,6,3,أوتوا,ويرى الذين أوتوا العلم الذي أنزل إليك من ربك ه...,3
2738,34,6,4,العلم,ويرى الذين أوتوا العلم الذي أنزل إليك من ربك ه...,3

In [29]:
df_threegram_loc.to_excel("Arabic_100_200_Threegram_Loc_With_Sent2.xlsx",index=False)

#### Merge Word NGram Root Flags

In [47]:
df_first_word = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/7-Deployment/Arabic_Buckwalter_Word_Root_Color2.xlsx")
#df_first_word = df_first_word.iloc[:,[0,1,2,3,4,5,6,8,9,17,18,19,20]]
df_first_word

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,form,root,root_arabic,tag,first_100_word,100_200_word,first_200_word
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,somi,smw,سمو,N,1,0,1
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,{ll~ahi,Alh,اله,PN,1,0,1
2,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,r~aHoma`ni,rHm,رحم,ADJ,1,0,1
3,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,r~aHiymi,rHm,رحم,ADJ,1,0,1
4,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,Hamodu,Hmd,حمد,N,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78244,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,Suduwri,Sdr,صدر,N,0,0,0
78245,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,n~aAsi,nws,نوس,N,1,0,1
78246,114,6,1,من,mn,مِنَ,mina,NaN,NaN,NaN,NaN,1,0,1
78247,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,jin~api,jnn,جنن,N,0,1,1
78248,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,n~aAsi,nws,نوس,N,0,0,0

In [49]:
df_first_100_twogram = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/7-Deployment/Arabic_First_100_Twogram_Loc_With_Sent2.xlsx")
df_first_100_twogram = df_first_100_twogram.iloc[:,[0,1,2,5]]
df_first_100_twogram

       num_1  num_2  num_3  first_200_twogram
0          2     20     20                  2
1          2     20     21                  2
2          2     26      1                  2
3          2     26      2                  2
4          2     67      5                  2
...      ...    ...    ...                ...
10233     47      9      6                  2
10234     53     23      9                  2
10235     53     23     10                  2
10236     65     10     14                  2
10237     65     10     15                  2

[10238 rows x 4 columns]

In [50]:
df_merge_word_ngrams = pd.merge(df_first_word,df_first_100_twogram, how="left", on=["num_1","num_2","num_3"])
df_merge_word_ngrams.drop_duplicates(inplace=True)
df_merge_word_ngrams.iloc[:,-1].fillna(0, inplace=True)
df_merge_word_ngrams

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,form,root,root_arabic,tag,first_100_word,100_200_word,first_200_word,first_200_twogram
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,somi,smw,سمو,N,1,0,1,2.0
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,{ll~ahi,Alh,اله,PN,1,0,1,2.0
3,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,r~aHoma`ni,rHm,رحم,ADJ,1,0,1,2.0
5,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,r~aHiymi,rHm,رحم,ADJ,1,0,1,2.0
6,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,Hamodu,Hmd,حمد,N,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79362,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,Suduwri,Sdr,صدر,N,0,0,0,0.0
79363,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,n~aAsi,nws,نوس,N,1,0,1,0.0
79364,114,6,1,من,mn,مِنَ,mina,NaN,NaN,NaN,NaN,1,0,1,0.0
79365,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,jin~api,jnn,جنن,N,0,1,1,0.0
79366,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,n~aAsi,nws,نوس,N,0,0,0,0.0

In [51]:
df_100_200_twogram = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/7-Deployment/Arabic_100_200_Twogram_Loc_With_Sent2.xlsx")
df_100_200_twogram = df_100_200_twogram.iloc[:,[0,1,2,5]]
df_100_200_twogram

      num_1  num_2  num_3  first_200_twogram
0         2    173     23                  2
1         2    173     24                  2
2         2    182     14                  2
3         2    182     15                  2
4         2    192      4                  2
...     ...    ...    ...                ...
4021     47      3     13                  2
4022     47     15     33                  2
4023     47     15     34                  2
4024     53     23     23                  2
4025     53     23     24                  2

[4026 rows x 4 columns]

In [52]:
df_merge_word_ngrams2 = pd.merge(df_merge_word_ngrams,df_100_200_twogram, how="left", on=["num_1","num_2","num_3"])
df_merge_word_ngrams2.drop_duplicates(inplace=True)
df_merge_word_ngrams2.iloc[:,-1].fillna(0, inplace=True)
df_merge_word_ngrams2

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,form,root,root_arabic,tag,first_100_word,100_200_word,first_200_word,first_200_twogram_x,first_200_twogram_y
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,somi,smw,سمو,N,1,0,1,2.0,0.0
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,{ll~ahi,Alh,اله,PN,1,0,1,2.0,0.0
2,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,r~aHoma`ni,rHm,رحم,ADJ,1,0,1,2.0,0.0
3,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,r~aHiymi,rHm,رحم,ADJ,1,0,1,2.0,0.0
4,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,Hamodu,Hmd,حمد,N,0,0,0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78389,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,Suduwri,Sdr,صدر,N,0,0,0,0.0,0.0
78390,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,n~aAsi,nws,نوس,N,1,0,1,0.0,0.0
78391,114,6,1,من,mn,مِنَ,mina,NaN,NaN,NaN,NaN,1,0,1,0.0,0.0
78392,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,jin~api,jnn,جنن,N,0,1,1,0.0,0.0
78393,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,n~aAsi,nws,نوس,N,0,0,0,0.0,0.0

In [103]:
df_first_200_twogram = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/7-Deployment/Arabic_First_200_Twogram_Loc_With_Sent2.xlsx")
df_first_200_twogram = df_first_200_twogram.iloc[:,[0,1,2,5]]
df_first_200_twogram

       num_1  num_2  num_3  first_200_twogram
0          2     20     20                  2
1          2     20     21                  2
2          2     26      1                  2
3          2     26      2                  2
4          2     67      5                  2
...      ...    ...    ...                ...
15581     51     30      6                  2
15582     52     28      6                  2
15583     52     28      7                  2
15584     85     13      1                  2
15585     85     13      2                  2

[15586 rows x 4 columns]

In [104]:
df_merge_word_ngrams3 = pd.merge(df_merge_word_ngrams2,df_first_200_twogram, how="left", on=["num_1","num_2","num_3"])
df_merge_word_ngrams3.drop_duplicates(inplace=True)
df_merge_word_ngrams3.iloc[:,-1].fillna(0, inplace=True)
df_merge_word_ngrams3

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,root,root_arabic,index,first_100_word,100_200_word,first_200_word,first_100_twogram,100_200_twogram,first_200_twogram
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,smw,سمو,0,1,0,1,2.0,0.0,2.0
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,Alh,اله,1,1,0,1,2.0,0.0,2.0
3,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,rHm,رحم,2,1,0,1,2.0,0.0,2.0
5,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,rHm,رحم,3,1,0,1,2.0,0.0,2.0
6,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,Hmd,حمد,4,0,0,0,0.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80805,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,Sdr,صدر,78244,0,0,0,0.0,0.0,0.0
80806,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,nws,نوس,78245,1,0,1,0.0,0.0,0.0
80807,114,6,1,من,mn,مِنَ,mina,NaN,NaN,78246,1,0,1,0.0,0.0,0.0
80808,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,jnn,جنن,78247,0,1,1,0.0,0.0,0.0
80809,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,nws,نوس,78248,0,0,0,0.0,0.0,0.0

In [105]:
df_first_100_threegram = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/7-Deployment/Arabic_First_100_Threegram_Loc_With_Sent2.xlsx")
df_first_100_threegram = df_first_100_threegram.iloc[:,[0,1,2,5]]
df_first_100_threegram

      num_1  num_2  num_3  first_100_threegram
0         1      1      1                    3
1         1      1      2                    3
2         1      1      3                    3
3         2      1      1                    3
4         2      1      2                    3
...     ...    ...    ...                  ...
7225     58     14      3                    3
7226     58     14      4                    3
7227     59     11      2                    3
7228     59     11      3                    3
7229     59     11      4                    3

[7230 rows x 4 columns]

In [106]:
df_merge_word_ngrams4 = pd.merge(df_merge_word_ngrams3,df_first_100_threegram, how="left", on=["num_1","num_2","num_3"])
df_merge_word_ngrams4.drop_duplicates(inplace=True)
df_merge_word_ngrams4.iloc[:,-1].fillna(0, inplace=True)
df_merge_word_ngrams4

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,root,root_arabic,index,first_100_word,100_200_word,first_200_word,first_100_twogram,100_200_twogram,first_200_twogram,first_100_threegram
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,smw,سمو,0,1,0,1,2.0,0.0,2.0,3.0
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,Alh,اله,1,1,0,1,2.0,0.0,2.0,3.0
3,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,rHm,رحم,2,1,0,1,2.0,0.0,2.0,3.0
5,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,rHm,رحم,3,1,0,1,2.0,0.0,2.0,3.0
6,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,Hmd,حمد,4,0,0,0,0.0,2.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79862,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,Sdr,صدر,78244,0,0,0,0.0,0.0,0.0,0.0
79863,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,nws,نوس,78245,1,0,1,0.0,0.0,0.0,0.0
79864,114,6,1,من,mn,مِنَ,mina,NaN,NaN,78246,1,0,1,0.0,0.0,0.0,0.0
79865,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,jnn,جنن,78247,0,1,1,0.0,0.0,0.0,0.0
79866,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,nws,نوس,78248,0,0,0,0.0,0.0,0.0,0.0

In [107]:
df_100_200_threegram = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/7-Deployment/Arabic_100_200_Threegram_Loc_With_Sent2.xlsx")
df_100_200_threegram = df_100_200_threegram.iloc[:,[0,1,2,5]]
df_100_200_threegram

      num_1  num_2  num_3  100_200_threegram
0         3     55     20                  3
1         3     55     21                  3
2         3     55     22                  3
3         4     87      7                  3
4         4     87      8                  3
...     ...    ...    ...                ...
2962     26    174      6                  3
2963     26    174      7                  3
2964     26    190      5                  3
2965     26    190      6                  3
2966     26    190      7                  3

[2967 rows x 4 columns]

In [108]:
df_merge_word_ngrams5 = pd.merge(df_merge_word_ngrams4,df_100_200_threegram, how="left", on=["num_1","num_2","num_3"])
df_merge_word_ngrams5.drop_duplicates(inplace=True)
df_merge_word_ngrams5.iloc[:,-1].fillna(0, inplace=True)
df_merge_word_ngrams5

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,root,root_arabic,index,first_100_word,100_200_word,first_200_word,first_100_twogram,100_200_twogram,first_200_twogram,first_100_threegram,100_200_threegram
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,smw,سمو,0,1,0,1,2.0,0.0,2.0,3.0,0.0
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,Alh,اله,1,1,0,1,2.0,0.0,2.0,3.0,0.0
2,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,rHm,رحم,2,1,0,1,2.0,0.0,2.0,3.0,0.0
3,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,rHm,رحم,3,1,0,1,2.0,0.0,2.0,3.0,0.0
4,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,Hmd,حمد,4,0,0,0,0.0,2.0,2.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78578,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,Sdr,صدر,78244,0,0,0,0.0,0.0,0.0,0.0,0.0
78579,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,nws,نوس,78245,1,0,1,0.0,0.0,0.0,0.0,0.0
78580,114,6,1,من,mn,مِنَ,mina,NaN,NaN,78246,1,0,1,0.0,0.0,0.0,0.0,0.0
78581,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,jnn,جنن,78247,0,1,1,0.0,0.0,0.0,0.0,0.0
78582,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,nws,نوس,78248,0,0,0,0.0,0.0,0.0,0.0,0.0

In [109]:
df_first_200_threegram = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/7-Deployment/Arabic_First_200_Threegram_Loc_With_Sent2.xlsx")
df_first_200_threegram = df_first_200_threegram.iloc[:,[0,1,2,5]]
df_first_200_threegram

       num_1  num_2  num_3  first_200_threegram
0          1      1      1                    3
1          1      1      2                    3
2          1      1      3                    3
3          2      1      1                    3
4          2      1      2                    3
...      ...    ...    ...                  ...
10192     26    174      6                    3
10193     26    174      7                    3
10194     26    190      5                    3
10195     26    190      6                    3
10196     26    190      7                    3

[10197 rows x 4 columns]

In [110]:
df_merge_word_ngrams6 = pd.merge(df_merge_word_ngrams5,df_first_200_threegram, how="left", on=["num_1","num_2","num_3"])
df_merge_word_ngrams6.drop_duplicates(inplace=True)
df_merge_word_ngrams6.iloc[:,-1].fillna(0, inplace=True)
df_merge_word_ngrams6

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,root,root_arabic,index,first_100_word,100_200_word,first_200_word,first_100_twogram,100_200_twogram,first_200_twogram,first_100_threegram,100_200_threegram,first_200_threegram
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,smw,سمو,0,1,0,1,2.0,0.0,2.0,3.0,0.0,3.0
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,Alh,اله,1,1,0,1,2.0,0.0,2.0,3.0,0.0,3.0
3,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,rHm,رحم,2,1,0,1,2.0,0.0,2.0,3.0,0.0,3.0
5,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,rHm,رحم,3,1,0,1,2.0,0.0,2.0,3.0,0.0,3.0
6,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,Hmd,حمد,4,0,0,0,0.0,2.0,2.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80858,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,Sdr,صدر,78244,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
80859,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,nws,نوس,78245,1,0,1,0.0,0.0,0.0,0.0,0.0,0.0
80860,114,6,1,من,mn,مِنَ,mina,NaN,NaN,78246,1,0,1,0.0,0.0,0.0,0.0,0.0,0.0
80861,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,jnn,جنن,78247,0,1,1,0.0,0.0,0.0,0.0,0.0,0.0
80862,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,nws,نوس,78248,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [117]:
df_root = df_merge_word_ngrams6[~df_merge_word_ngrams6.root.isna()]
df_root

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,root,root_arabic,index,first_100_word,100_200_word,first_200_word,first_100_twogram,100_200_twogram,first_200_twogram,first_100_threegram,100_200_threegram,first_200_threegram
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,smw,سمو,0,1,0,1,2.0,0.0,2.0,3.0,0.0,3.0
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,Alh,اله,1,1,0,1,2.0,0.0,2.0,3.0,0.0,3.0
3,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,rHm,رحم,2,1,0,1,2.0,0.0,2.0,3.0,0.0,3.0
5,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,rHm,رحم,3,1,0,1,2.0,0.0,2.0,3.0,0.0,3.0
6,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,Hmd,حمد,4,0,0,0,0.0,2.0,2.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80856,114,5,2,يوسوس,ywsws,يُوَسْوِسُ,yuwasowisu,wsws,وسوس,78242,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
80858,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,Sdr,صدر,78244,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
80859,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,nws,نوس,78245,1,0,1,0.0,0.0,0.0,0.0,0.0,0.0
80861,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,jnn,جنن,78247,0,1,1,0.0,0.0,0.0,0.0,0.0,0.0
80862,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,nws,نوس,78248,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [118]:
df_root["root_flag"] = 4

<ipython-input-118-c489985d2787>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_root["root_flag"] = 4

In [120]:
df_root = df_root.iloc[:,[0,1,2,-1]]
df_root

       num_1  num_2  num_3  root_flag
0          1      1      1          4
1          1      1      2          4
3          1      1      3          4
5          1      1      4          4
6          1      2      1          4
...      ...    ...    ...        ...
80856    114      5      2          4
80858    114      5      4          4
80859    114      5      5          4
80861    114      6      2          4
80862    114      6      3          4

[49968 rows x 4 columns]

In [121]:
df_merge_word_ngrams_root_all = pd.merge(df_merge_word_ngrams6,df_root, how="left", on=["num_1","num_2","num_3"])
df_merge_word_ngrams_root_all.drop_duplicates(inplace=True)
df_merge_word_ngrams_root_all.iloc[:,-1].fillna(0, inplace=True)
df_merge_word_ngrams_root_all

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,root,root_arabic,index,first_100_word,100_200_word,first_200_word,first_100_twogram,100_200_twogram,first_200_twogram,first_100_threegram,100_200_threegram,first_200_threegram,root_flag
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,smw,سمو,0,1,0,1,2.0,0.0,2.0,3.0,0.0,3.0,4.0
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,Alh,اله,1,1,0,1,2.0,0.0,2.0,3.0,0.0,3.0,4.0
2,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,rHm,رحم,2,1,0,1,2.0,0.0,2.0,3.0,0.0,3.0,4.0
3,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,rHm,رحم,3,1,0,1,2.0,0.0,2.0,3.0,0.0,3.0,4.0
4,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,Hmd,حمد,4,0,0,0,0.0,2.0,2.0,0.0,0.0,0.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78246,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,Sdr,صدر,78244,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
78247,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,nws,نوس,78245,1,0,1,0.0,0.0,0.0,0.0,0.0,0.0,4.0
78248,114,6,1,من,mn,مِنَ,mina,NaN,NaN,78246,1,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78249,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,jnn,جنن,78247,0,1,1,0.0,0.0,0.0,0.0,0.0,0.0,4.0
78250,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,nws,نوس,78248,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,4.0

In [122]:
#df_merge_word_ngrams_root_all.to_excel("Arabic_Buckwalter_Word_Root_First_100_200_Word_NGram_Root_Color_Flag.xlsx",index=False)