### Deployment Result

In [1]:
import pandas as pd
import numpy as np
import re
from camel_tools.utils.charmap import CharMapper
from lang_trans.arabic import buckwalter
import nltk
from nltk import word_tokenize
from nltk import ngrams
import json
import re

In [2]:
df_word_merge = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/6-Morphology And Tanzil/Arabic_Buckwalter_Clean_Plain_Word_Merge_Tanzil.xlsx")
df_word_merge

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain
0,1,1,1,بسم,bsm,بِسْمِ,bisomi
1,1,1,2,الله,Allh,اللَّهِ,All~ahi
2,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni
3,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi
4,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu
...,...,...,...,...,...,...,...
78243,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri
78244,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi
78245,114,6,1,من,mn,مِنَ,mina
78246,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api
78247,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi

In [ ]:
df_select_word = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/5-Tanzil Analysis/Arabic_Buckwalter_Word_Frequency_Tanzil_Clean.xlsx")
df_select_word

In [23]:
df_select_word = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/5-Tanzil Analysis/Arabic_Buckwalter_Word_Frequency_Tanzil_Clean.xlsx")
df_select_word_100 = df_select_word.iloc[0:100,]
df_select_word_100_200 = df_select_word.iloc[100:200,]
df_select_word_200 = df_select_word.iloc[0:200,]

    arabic_word_tanzil_clean buckwalter_word_tanzil_clean  frequency
0                         من                           mn       2763
1                       الله                         Allh       2265
2                         في                           fy       1185
3                         ما                           mA       1013
4                         إن                           <n        966
..                       ...                          ...        ...
195                 الكافرين                     AlkAfryn         52
196                     غفور                         gfwr         52
197                     أليم                         >lym         52
198                    قبلهم                        qblhm         52
199                      كنت                          knt         51

[200 rows x 3 columns]

#### Adding Color Column

In [24]:
select_word_list_100 = df_select_word_100.iloc[:,0].to_list()
select_word_list_100_200 = df_select_word_100_200.iloc[:,0].to_list()
select_word_list_200 = df_select_word_200.iloc[:,0].to_list()
#select_word_list

In [25]:
select_word_text_100 = " ".join(select_word_list_100)
select_word_text_100_200 = " ".join(select_word_list_100_200)
select_word_text_200 = " ".join(select_word_list_200)

In [26]:
# 1 Way
def compare_word_text(word, word_text):
    if re.search(fr"(?:\s|^){word}(?:\s|$)", word_text):
        return 1
    else:
        return 0

In [27]:
df_word_merge.iloc[:,3].apply(lambda x: compare_word_text(x, select_word_text))

0        1
1        1
2        1
3        1
4        0
        ..
78243    0
78244    1
78245    1
78246    1
78247    0
Name: arabic_word_tanzil_clean, Length: 78248, dtype: int64

In [28]:
## 2 Way
#def compare_word_list(word, word_list):
#    for i in word_list:
#        if re.search(fr"(?:\s|^){i}(?:\s|$)", word):
#            return 1

In [29]:
#df_word_merge.iloc[:,3].apply(lambda x: compare_word_list(x, select_word_list))

In [30]:
#df_word_merge["color"] = df_word_merge.iloc[:,3].apply(lambda x: compare_word_list(x, select_word_list))
#df_word_merge

In [31]:
#df_word_merge.color = df_word_merge.color.fillna(0)
#df_word_merge

In [ ]:
#df_word_merge.color.sum()

In [32]:
df_word_merge["first_200_word"] = df_word_merge.iloc[:,3].apply(lambda x: compare_word_text(x, select_word_text))
df_word_merge

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,first_100_word,100_200_word,first_200_word
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,1,0,1
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,1,0,1
2,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,1,0,1
3,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,1,0,1
4,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,0,0,0
...,...,...,...,...,...,...,...,...,...,...
78243,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,0,0,0
78244,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,1,0,1
78245,114,6,1,من,mn,مِنَ,mina,1,0,1
78246,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,0,1,1
78247,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,0,0,0

In [33]:
df_root = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/2-Morphology Root Analysis/Arabic_Buckwalter_Form_Root_Morphology.xlsx")
df_root

       num_1  num_2  num_3  num_4        form  tag  root root_arabic
0          1      1      1      2        somi    N   smw         سمو
1          1      1      2      1     {ll~ahi   PN   Alh         اله
2          1      1      3      2  r~aHoma`ni  ADJ   rHm         رحم
3          1      1      4      2    r~aHiymi  ADJ   rHm         رحم
4          1      2      1      2      Hamodu    N   Hmd         حمد
...      ...    ...    ...    ...         ...  ...   ...         ...
49963    114      5      2      1  yuwasowisu    V  wsws        وسوس
49964    114      5      4      1     Suduwri    N   Sdr         صدر
49965    114      5      5      2      n~aAsi    N   nws         نوس
49966    114      6      2      2     jin~api    N   jnn         جنن
49967    114      6      3      3      n~aAsi    N   nws         نوس

[49968 rows x 8 columns]

In [35]:
df_word_root_merge = pd.merge(df_word_merge,df_root, how="left", on=["num_1","num_2","num_3"])
df_word_root_merge = df_word_root_merge.iloc[:,[0,1,2,3,4,5,6,11,13,14,12,7,8,9]]
df_word_root_merge

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,form,root,root_arabic,tag,first_100_word,100_200_word,first_200_word
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,somi,smw,سمو,N,1,0,1
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,{ll~ahi,Alh,اله,PN,1,0,1
2,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,r~aHoma`ni,rHm,رحم,ADJ,1,0,1
3,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,r~aHiymi,rHm,رحم,ADJ,1,0,1
4,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,Hamodu,Hmd,حمد,N,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78244,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,Suduwri,Sdr,صدر,N,0,0,0
78245,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,n~aAsi,nws,نوس,N,1,0,1
78246,114,6,1,من,mn,مِنَ,mina,NaN,NaN,NaN,NaN,1,0,1
78247,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,jin~api,jnn,جنن,N,0,1,1
78248,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,n~aAsi,nws,نوس,N,0,0,0

In [36]:
df_word_root_merge.drop_duplicates(inplace=True)

In [37]:
df_word_root_merge

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,form,root,root_arabic,tag,first_100_word,100_200_word,first_200_word
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,somi,smw,سمو,N,1,0,1
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,{ll~ahi,Alh,اله,PN,1,0,1
2,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,r~aHoma`ni,rHm,رحم,ADJ,1,0,1
3,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,r~aHiymi,rHm,رحم,ADJ,1,0,1
4,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,Hamodu,Hmd,حمد,N,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78244,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,Suduwri,Sdr,صدر,N,0,0,0
78245,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,n~aAsi,nws,نوس,N,1,0,1
78246,114,6,1,من,mn,مِنَ,mina,NaN,NaN,NaN,NaN,1,0,1
78247,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,jin~api,jnn,جنن,N,0,1,1
78248,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,n~aAsi,nws,نوس,N,0,0,0

In [ ]:
#a = set(df_word_root_merge.iloc[:,6])
#b = set(df_word_merge.iloc[:,6])
#a.difference(b)

In [ ]:
#df_word_root_merge.to_excel("Arabic_Buckwalter_Word_Root_Color.xlsx",index=False)

#### Adding Juz Surah Name Word Count And Letter Count

In [38]:
df_verse = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Data/Dataset-Verse-by-Verse.xlsx")
df_verse = df_verse.iloc[:,[4,10,1,5,6,14,15]]
df_verse.rename(columns={"SurahNo":"num_1","AyahNo":"num_2"}, inplace=True)
df_verse

,num_1,num_2,Juz,SurahNameArabic,SurahNameEnglish,ArabicWordCount,ArabicLetterCount
0,1,1,1,الفاتحة,Al-Fatiha,4,19
1,1,2,1,الفاتحة,Al-Fatiha,4,18
2,1,3,1,الفاتحة,Al-Fatiha,2,12
3,1,4,1,الفاتحة,Al-Fatiha,3,12
4,1,5,1,الفاتحة,Al-Fatiha,4,19
...,...,...,...,...,...,...,...
6231,114,2,30,الناس,An-Nas,2,8
6232,114,3,30,الناس,An-Nas,2,8
6233,114,4,30,الناس,An-Nas,4,17
6234,114,5,30,الناس,An-Nas,5,20
6235,114,6,30,الناس,An-Nas,3,13

In [39]:
df_verse.ArabicWordCount.sum()

82176

In [40]:
df_word_root_juz_name_merge = pd.merge(df_word_root_merge, df_verse, how="left", on=["num_1","num_2"])
df_word_root_juz_name_merge

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,form,root,root_arabic,tag,first_100_word,100_200_word,first_200_word,Juz,SurahNameArabic,SurahNameEnglish,ArabicWordCount,ArabicLetterCount
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,somi,smw,سمو,N,1,0,1,1,الفاتحة,Al-Fatiha,4,19
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,{ll~ahi,Alh,اله,PN,1,0,1,1,الفاتحة,Al-Fatiha,4,19
2,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,r~aHoma`ni,rHm,رحم,ADJ,1,0,1,1,الفاتحة,Al-Fatiha,4,19
3,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,r~aHiymi,rHm,رحم,ADJ,1,0,1,1,الفاتحة,Al-Fatiha,4,19
4,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,Hamodu,Hmd,حمد,N,0,0,0,1,الفاتحة,Al-Fatiha,4,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78244,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,Suduwri,Sdr,صدر,N,0,0,0,30,الناس,An-Nas,5,20
78245,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,n~aAsi,nws,نوس,N,1,0,1,30,الناس,An-Nas,5,20
78246,114,6,1,من,mn,مِنَ,mina,NaN,NaN,NaN,NaN,1,0,1,30,الناس,An-Nas,3,13
78247,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,jin~api,jnn,جنن,N,0,1,1,30,الناس,An-Nas,3,13
78248,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,n~aAsi,nws,نوس,N,0,0,0,30,الناس,An-Nas,3,13

In [ ]:
#df_word_root_juz_name_merge.to_excel("Arabic_Buckwalter_Word_Root_Color_Juz_Name.xlsx",index=False)

In [ ]:
# # Color Order Func
# for i in range(len(df_word_root_juz_name_merge)):
#     if df_word_root_juz_name_merge.loc[i,"color"] == 1:
#         word = df_word_root_juz_name_merge.loc[i,"arabic_word_tanzil_clean"]
#         freq = df_select_word[df_select_word.buckwalter_word_tanzil_clean.str.contains(fr"(?:\s|^){word}(?:\s|$)", na=True)]["frequency"]
#         if freq >= 2000:
#             df_word_root_juz_name_merge.loc[i,"color"] == 5
#         elif freq >= 1500:
#             df_word_root_juz_name_merge.loc[i,"color"] == 4
#         elif freq >= 1000:
#             df_word_root_juz_name_merge.loc[i,"color"] == 3
#         elif freq >= 500:
#             df_word_root_juz_name_merge.loc[i,"color"] == 2
#         else:
#             df_word_root_juz_name_merge.loc[i,"color"] == 1
#     else:
#         df_word_root_juz_name_merge.loc[i,"color"] == 0

#### Adding Page Number

In [41]:
df_page = pd.read_json("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Data/pages.json")
df_page

,0,1,2
0,"{'surah': 1, 'start': 1, 'end': 7}",None,None
1,"{'surah': 2, 'start': 1, 'end': 5}",None,None
2,"{'surah': 2, 'start': 6, 'end': 16}",None,None
3,"{'surah': 2, 'start': 17, 'end': 24}",None,None
4,"{'surah': 2, 'start': 25, 'end': 29}",None,None
...,...,...,...
599,"{'surah': 100, 'start': 10, 'end': 10}","{'surah': 101, 'start': 1, 'end': 1}","{'surah': 102, 'start': 1, 'end': 1}"
600,"{'surah': 103, 'start': 1, 'end': 1}","{'surah': 104, 'start': 1, 'end': 1}","{'surah': 105, 'start': 1, 'end': 1}"
601,"{'surah': 106, 'start': 1, 'end': 1}","{'surah': 107, 'start': 1, 'end': 1}","{'surah': 108, 'start': 1, 'end': 1}"
602,"{'surah': 109, 'start': 1, 'end': 1}","{'surah': 110, 'start': 1, 'end': 1}","{'surah': 111, 'start': 1, 'end': 1}"
603,"{'surah': 112, 'start': 1, 'end': 1}","{'surah': 113, 'start': 1, 'end': 1}","{'surah': 114, 'start': 1, 'end': 1}"

In [42]:
df_page2 = pd.DataFrame(df_page.iloc[:,0])
df_page2

                                          0
0        {'surah': 1, 'start': 1, 'end': 7}
1        {'surah': 2, 'start': 1, 'end': 5}
2       {'surah': 2, 'start': 6, 'end': 16}
3      {'surah': 2, 'start': 17, 'end': 24}
4      {'surah': 2, 'start': 25, 'end': 29}
..                                      ...
599  {'surah': 100, 'start': 10, 'end': 10}
600    {'surah': 103, 'start': 1, 'end': 1}
601    {'surah': 106, 'start': 1, 'end': 1}
602    {'surah': 109, 'start': 1, 'end': 1}
603    {'surah': 112, 'start': 1, 'end': 1}

[604 rows x 1 columns]

In [43]:
page_list = []
for i in df_page2.iloc[:,0]:
    surah = i["surah"]
    start = i["start"]
    end = i["end"]
    page_list.append((surah,start,end))
#page_list

In [44]:
df_page_new = pd.DataFrame(page_list)
df_page_new.reset_index(inplace=True)
df_page_new.rename(columns={0:"surah",1:"start",2:"end","index":"page"}, inplace=True)
df_page_new = df_page_new.iloc[:,[1,2,3,0]]
df_page_new["page"] = df_page_new["page"].apply(lambda x: x+1)
df_page_new

     surah  start  end  page
0        1      1    7     1
1        2      1    5     2
2        2      6   16     3
3        2     17   24     4
4        2     25   29     5
..     ...    ...  ...   ...
599    100     10   10   600
600    103      1    1   601
601    106      1    1   602
602    109      1    1   603
603    112      1    1   604

[604 rows x 4 columns]

In [45]:
#df_page_new.to_excel("Quran_Page_Num_Loc.xlsx", index=False)

In [46]:
df_word_root_juz_name_merge

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,form,root,root_arabic,tag,first_100_word,100_200_word,first_200_word,Juz,SurahNameArabic,SurahNameEnglish,ArabicWordCount,ArabicLetterCount
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,somi,smw,سمو,N,1,0,1,1,الفاتحة,Al-Fatiha,4,19
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,{ll~ahi,Alh,اله,PN,1,0,1,1,الفاتحة,Al-Fatiha,4,19
2,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,r~aHoma`ni,rHm,رحم,ADJ,1,0,1,1,الفاتحة,Al-Fatiha,4,19
3,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,r~aHiymi,rHm,رحم,ADJ,1,0,1,1,الفاتحة,Al-Fatiha,4,19
4,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,Hamodu,Hmd,حمد,N,0,0,0,1,الفاتحة,Al-Fatiha,4,18
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78244,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,Suduwri,Sdr,صدر,N,0,0,0,30,الناس,An-Nas,5,20
78245,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,n~aAsi,nws,نوس,N,1,0,1,30,الناس,An-Nas,5,20
78246,114,6,1,من,mn,مِنَ,mina,NaN,NaN,NaN,NaN,1,0,1,30,الناس,An-Nas,3,13
78247,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,jin~api,jnn,جنن,N,0,1,1,30,الناس,An-Nas,3,13
78248,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,n~aAsi,nws,نوس,N,0,0,0,30,الناس,An-Nas,3,13

In [47]:
for i in range(len(df_page_new)):
    surah = df_page_new.loc[i,"surah"]
    start = df_page_new.loc[i,"start"]
    end = df_page_new.loc[i,"end"]
    page = df_page_new.loc[i,"page"]
    for j in range(len(df_word_root_juz_name_merge)):
        if (df_word_root_juz_name_merge.loc[j,"num_1"] == surah and df_word_root_juz_name_merge.loc[j,"num_2"] >= start and df_word_root_juz_name_merge.loc[j,"num_2"] <= end):
            df_word_root_juz_name_merge.loc[j,"page"] = page
        else:
            pass

In [48]:
df_word_root_juz_name_merge

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,form,root,root_arabic,tag,first_100_word,100_200_word,first_200_word,Juz,SurahNameArabic,SurahNameEnglish,ArabicWordCount,ArabicLetterCount,page
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,somi,smw,سمو,N,1,0,1,1,الفاتحة,Al-Fatiha,4,19,1.0
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,{ll~ahi,Alh,اله,PN,1,0,1,1,الفاتحة,Al-Fatiha,4,19,1.0
2,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,r~aHoma`ni,rHm,رحم,ADJ,1,0,1,1,الفاتحة,Al-Fatiha,4,19,1.0
3,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,r~aHiymi,rHm,رحم,ADJ,1,0,1,1,الفاتحة,Al-Fatiha,4,19,1.0
4,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,Hamodu,Hmd,حمد,N,0,0,0,1,الفاتحة,Al-Fatiha,4,18,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78244,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,Suduwri,Sdr,صدر,N,0,0,0,30,الناس,An-Nas,5,20,NaN
78245,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,n~aAsi,nws,نوس,N,1,0,1,30,الناس,An-Nas,5,20,NaN
78246,114,6,1,من,mn,مِنَ,mina,NaN,NaN,NaN,NaN,1,0,1,30,الناس,An-Nas,3,13,NaN
78247,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,jin~api,jnn,جنن,N,0,1,1,30,الناس,An-Nas,3,13,NaN
78248,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,n~aAsi,nws,نوس,N,0,0,0,30,الناس,An-Nas,3,13,NaN

In [49]:
df_word_root_juz_name_merge["page"].fillna(method='ffill', inplace=True) # 'ffill'forward filling method as fill with first previous value, 'bfill'backward filling method

In [50]:
df_word_root_juz_name_merge

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,form,root,root_arabic,tag,first_100_word,100_200_word,first_200_word,Juz,SurahNameArabic,SurahNameEnglish,ArabicWordCount,ArabicLetterCount,page
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,somi,smw,سمو,N,1,0,1,1,الفاتحة,Al-Fatiha,4,19,1.0
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,{ll~ahi,Alh,اله,PN,1,0,1,1,الفاتحة,Al-Fatiha,4,19,1.0
2,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,r~aHoma`ni,rHm,رحم,ADJ,1,0,1,1,الفاتحة,Al-Fatiha,4,19,1.0
3,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,r~aHiymi,rHm,رحم,ADJ,1,0,1,1,الفاتحة,Al-Fatiha,4,19,1.0
4,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,Hamodu,Hmd,حمد,N,0,0,0,1,الفاتحة,Al-Fatiha,4,18,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78244,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,Suduwri,Sdr,صدر,N,0,0,0,30,الناس,An-Nas,5,20,604.0
78245,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,n~aAsi,nws,نوس,N,1,0,1,30,الناس,An-Nas,5,20,604.0
78246,114,6,1,من,mn,مِنَ,mina,NaN,NaN,NaN,NaN,1,0,1,30,الناس,An-Nas,3,13,604.0
78247,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,jin~api,jnn,جنن,N,0,1,1,30,الناس,An-Nas,3,13,604.0
78248,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,n~aAsi,nws,نوس,N,0,0,0,30,الناس,An-Nas,3,13,604.0

In [52]:
df_word_root_juz_name_merge["index"] = df_word_root_juz_name_merge.index
df_word_root_juz_name_merge = df_word_root_juz_name_merge.iloc[:,[0,1,2,3,4,5,6,7,8,9,10,14,15,16,17,18,19,20,11,12,13]]
df_word_root_juz_name_merge

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,form,root,root_arabic,...,Juz,SurahNameArabic,SurahNameEnglish,ArabicWordCount,ArabicLetterCount,page,index,first_100_word,100_200_word,first_200_word
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,somi,smw,سمو,...,1,الفاتحة,Al-Fatiha,4,19,1.0,0,1,0,1
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,{ll~ahi,Alh,اله,...,1,الفاتحة,Al-Fatiha,4,19,1.0,1,1,0,1
2,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,r~aHoma`ni,rHm,رحم,...,1,الفاتحة,Al-Fatiha,4,19,1.0,2,1,0,1
3,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,r~aHiymi,rHm,رحم,...,1,الفاتحة,Al-Fatiha,4,19,1.0,3,1,0,1
4,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,Hamodu,Hmd,حمد,...,1,الفاتحة,Al-Fatiha,4,18,1.0,4,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78244,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,Suduwri,Sdr,صدر,...,30,الناس,An-Nas,5,20,604.0,78244,0,0,0
78245,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,n~aAsi,nws,نوس,...,30,الناس,An-Nas,5,20,604.0,78245,1,0,1
78246,114,6,1,من,mn,مِنَ,mina,NaN,NaN,NaN,...,30,الناس,An-Nas,3,13,604.0,78246,1,0,1
78247,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,jin~api,jnn,جنن,...,30,الناس,An-Nas,3,13,604.0,78247,0,1,1
78248,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,n~aAsi,nws,نوس,...,30,الناس,An-Nas,3,13,604.0,78248,0,0,0

In [53]:
#df_word_root_juz_name_merge.to_excel("Arabic_Buckwalter_Word_Root_First_100_200_Word_Juz_Name_Page.xlsx",index=False)

#### Adding N Gram Flag

In [66]:
#n_gram_num = 100
df_twogram = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/4-N Gram/Arabic_Clean_Twogram_Frequency_From_DataFrame_Tanzil.xlsx")
df_twogram = df_twogram.iloc[0:200,]
df_twogram

          twogram buckwalter_twogram  frequency
0         إن الله            <n Allh        205
1     الذين آمنوا        Al*yn |mnwA        184
2        في الأرض           fy Al>rD        176
3         يا أيها            yA >yhA        142
4     الذين كفروا        Al*yn kfrwA        134
..            ...                ...        ...
195   من المؤمنين        mn Alm&mnyn         19
196      والله لا           wAllh lA         19
197    يهدي القوم         yhdy Alqwm         19
198  ملك السماوات       mlk AlsmAwAt         19
199        إنه هو             <nh hw         19

[200 rows x 3 columns]

In [67]:
df_sent = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/5-Tanzil Analysis/Arabic_Buckwalter_Sent_Tanzil_Clean.xlsx")
df_sent

      num_1  num_2  arabic_sent_tanzil_clean buckwalter_sent_tanzil_clean
0         1      1    بسم الله الرحمن الرحيم       bsm Allh AlrHmn AlrHym
1         1      2     الحمد لله رب العالمين        AlHmd llh rb AlEAlmyn
2         1      3             الرحمن الرحيم                AlrHmn AlrHym
3         1      4            مالك يوم الدين               mAlk ywm Aldyn
4         1      5    إياك نعبد وإياك نستعين       <yAk nEbd w<yAk nstEyn
...     ...    ...                       ...                          ...
6231    114      2                 ملك الناس                    mlk AlnAs
6232    114      3                 إله الناس                    <lh AlnAs
6233    114      4      من شر الوسواس الخناس         mn $r AlwswAs AlxnAs
6234    114      5  الذي يوسوس في صدور الناس     Al*y ywsws fy Sdwr AlnAs
6235    114      6           من الجنة والناس              mn Aljnp wAlnAs

[6236 rows x 4 columns]

In [68]:
# Two Gram
df_sent_twogram_result = pd.DataFrame()
for i in df_twogram.iloc[:,0]:
    try:
        sent_in_video = df_sent[df_sent.arabic_sent_tanzil_clean.str.contains(fr"(^|\s){i}(\s|$)", regex=True)]
        #sent_in_video = df_sent[df_sent.arabic_sent_tanzil_clean.str.contains(fr"(^|\s){i}(\s|$)")].sample(10)
    except:
        sent_in_video = df_sent[df_sent.arabic_sent_tanzil_clean.str.contains(fr"(^|\s){i}(\s|$)", regex=True)] 
        #sent_in_video = df_sent[df_sent.arabic_sent_tanzil_clean.str.contains(fr"(^|\s){i}(\s|$)")].head(10) 
    sent_in_video.insert(0,"twogram",i)
    df_sent_twogram_result = pd.concat([df_sent_twogram_result,sent_in_video], axis=0)
df_sent_twogram_result.reset_index(drop=True, inplace=True)
df_sent_twogram_result

<ipython-input-68-40e6f74a9873>:5: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  sent_in_video = df_sent[df_sent.arabic_sent_tanzil_clean.str.contains(fr"(^|\s){i}(\s|$)", regex=True)]

,twogram,num_1,num_2,arabic_sent_tanzil_clean,buckwalter_sent_tanzil_clean
0,إن الله,2,20,يكاد البرق يخطف أبصارهم كلما أضاء لهم مشوا فيه...,ykAd Albrq yxTf >bSArhm klmA >DA' lhm m$wA fyh...
1,إن الله,2,26,إن الله لا يستحيي أن يضرب مثلا ما بعوضة فما فو...,<n Allh lA ystHyy >n yDrb mvlA mA bEwDp fmA fw...
2,إن الله,2,67,وإذ قال موسى لقومه إن الله يأمركم أن تذبحوا بق...,w<* qAl mwsY lqwmh <n Allh y>mrkm >n t*bHwA bq...
3,إن الله,2,109,ود كثير من أهل الكتاب لو يردونكم من بعد إيمانك...,wd kvyr mn >hl AlktAb lw yrdwnkm mn bEd <ymAnk...
4,إن الله,2,110,وأقيموا الصلاة وآتوا الزكاة وما تقدموا لأنفسكم...,w>qymwA AlSlAp w|twA AlzkAp wmA tqdmwA l>nfskm...
...,...,...,...,...,...
7678,إنه هو,44,6,رحمة من ربك إنه هو السميع العليم,rHmp mn rbk <nh hw AlsmyE AlElym
7679,إنه هو,44,42,إلا من رحم الله إنه هو العزيز الرحيم,<lA mn rHm Allh <nh hw AlEzyz AlrHym
7680,إنه هو,51,30,قالوا كذلك قال ربك إنه هو الحكيم العليم,qAlwA k*lk qAl rbk <nh hw AlHkym AlElym
7681,إنه هو,52,28,إنا كنا من قبل ندعوه إنه هو البر الرحيم,<nA knA mn qbl ndEwh <nh hw Albr AlrHym
7682,إنه هو,85,13,إنه هو يبدئ ويعيد,<nh hw ybd} wyEyd

In [69]:
# ngram_loc_list = []
# for i in range(len(df_sent_ngram_result)):
#     num_1 = df_sent_ngram_result.loc[i,"num_1"]
#     num_2 = df_sent_ngram_result.loc[i,"num_2"]
#     sent = df_sent_ngram_result.loc[i,"arabic_sent_tanzil_clean"]
#     ngram = df_sent_ngram_result.loc[i,"ngram"]
#     sent_token = word_tokenize(sent)
#     ngram_token = word_tokenize(ngram)
#     for j in ngram_token:
#         for k in range(len(sent_token)):
#             if j == sent_token[k]:
#                 num_3 = k+1
#                 ngram_loc_list.append((num_1,num_2,num_3,j,sent))
#                 
# df_ngram_loc = pd.DataFrame(ngram_loc_list)
# df_ngram_loc.rename(columns={0:"num_1",1:"num_2",2:"num_3",3:"ngram_word",4:"arabic_sent_tanzil_clean"},inplace=True)
# df_ngram_loc

In [70]:
# Two Gram
twogram_loc_list = []
for i in range(len(df_sent_twogram_result)):
    num_1 = df_sent_twogram_result.loc[i,"num_1"]
    num_2 = df_sent_twogram_result.loc[i,"num_2"]
    sent = df_sent_twogram_result.loc[i,"arabic_sent_tanzil_clean"]
    ngram = df_sent_twogram_result.loc[i,"twogram"]
    sent_token = word_tokenize(sent)
    ngram_token = word_tokenize(ngram)    
    for j in range(len(ngram_token)):        
        for k in range(len(sent_token)):
            if ngram_token[j] == sent_token[k]:
                try:
                    if ngram_token[j+1] == sent_token[k+1]:
                        num_3 = k+1  # +1 because of k begins with 0 
                        twogram_loc_list.append((num_1,num_2,num_3,ngram_token[j],sent))
                        twogram_loc_list.append((num_1,num_2,num_3+1,ngram_token[j+1],sent))
                except:
                    pass
                
df_twogram_loc = pd.DataFrame(twogram_loc_list)
df_twogram_loc.rename(columns={0:"num_1",1:"num_2",2:"num_3",3:"arabic_word_tanzil_clean",4:"arabic_sent_tanzil_clean"},inplace=True)
df_twogram_loc["first_200_twogram"] = 2
df_twogram_loc

,num_1,num_2,num_3,arabic_word_tanzil_clean,arabic_sent_tanzil_clean,first_200_twogram
0,2,20,20,إن,يكاد البرق يخطف أبصارهم كلما أضاء لهم مشوا فيه...,2
1,2,20,21,الله,يكاد البرق يخطف أبصارهم كلما أضاء لهم مشوا فيه...,2
2,2,26,1,إن,إن الله لا يستحيي أن يضرب مثلا ما بعوضة فما فو...,2
3,2,26,2,الله,إن الله لا يستحيي أن يضرب مثلا ما بعوضة فما فو...,2
4,2,67,5,إن,وإذ قال موسى لقومه إن الله يأمركم أن تذبحوا بق...,2
...,...,...,...,...,...,...
15581,51,30,6,هو,قالوا كذلك قال ربك إنه هو الحكيم العليم,2
15582,52,28,6,إنه,إنا كنا من قبل ندعوه إنه هو البر الرحيم,2
15583,52,28,7,هو,إنا كنا من قبل ندعوه إنه هو البر الرحيم,2
15584,85,13,1,إنه,إنه هو يبدئ ويعيد,2
15585,85,13,2,هو,إنه هو يبدئ ويعيد,2

In [71]:
#df_twogram_loc.to_excel("Arabic_First_200_Twogram_Loc_With_Sent.xlsx",index=False)

In [82]:
#n_gram_num = 200
df_threegram = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/4-N Gram/Arabic_Clean_Threegram_Frequency_From_DataFrame_Tanzil.xlsx")
#df_threegram = df_threegram.head(n_gram_num)
df_threegram = df_threegram.iloc[100:200,]
df_threegram

            threegram buckwalter_threegram  frequency
100   إلى يوم القيامة      <lY ywm AlqyAmp         12
101     والله لا يهدي        wAllh lA yhdy         12
102     من أهل الكتاب        mn >hl AlktAb         12
103        من بعد ذلك           mn bEd *lk         12
104  وقال الذين كفروا     wqAl Al*yn kfrwA         12
..                ...                  ...        ...
195    أظلم ممن افترى       >Zlm mmn AftrY          9
196     فإن الله غفور        f<n Allh gfwr          8
197    ربك لهو العزيز       rbk lhw AlEzyz          8
198      لآية وما كان         l|yp wmA kAn          8
199    وما كان أكثرهم       wmA kAn >kvrhm          8

[100 rows x 3 columns]

In [83]:
# Three Gram
df_sent_threegram_result = pd.DataFrame()
for i in df_threegram.iloc[:,0]:
    try:
        sent_in_video = df_sent[df_sent.arabic_sent_tanzil_clean.str.contains(fr"(^|\s){i}(\s|$)", regex=True)]
        #sent_in_video = df_sent[df_sent.arabic_sent_tanzil_clean.str.contains(fr"(^|\s){i}(\s|$)")].sample(10)
    except:
        sent_in_video = df_sent[df_sent.arabic_sent_tanzil_clean.str.contains(fr"(^|\s){i}(\s|$)", regex=True)] 
        #sent_in_video = df_sent[df_sent.arabic_sent_tanzil_clean.str.contains(fr"(^|\s){i}(\s|$)")].head(10) 
    sent_in_video.insert(0,"threegram",i)
    df_sent_threegram_result = pd.concat([df_sent_threegram_result,sent_in_video], axis=0)
df_sent_threegram_result.reset_index(drop=True, inplace=True)
df_sent_threegram_result

<ipython-input-83-4b5e989fca7f>:5: UserWarning: This pattern has match groups. To actually get the groups, use str.extract.
  sent_in_video = df_sent[df_sent.arabic_sent_tanzil_clean.str.contains(fr"(^|\s){i}(\s|$)", regex=True)]

,threegram,num_1,num_2,arabic_sent_tanzil_clean,buckwalter_sent_tanzil_clean
0,إلى يوم القيامة,3,55,إذ قال الله يا عيسى إني متوفيك ورافعك إلي ومطه...,<* qAl Allh yA EysY <ny mtwfyk wrAfEk <ly wmTh...
1,إلى يوم القيامة,4,87,الله لا إله إلا هو ليجمعنكم إلى يوم القيامة لا...,Allh lA <lh <lA hw lyjmEnkm <lY ywm AlqyAmp lA...
2,إلى يوم القيامة,5,14,ومن الذين قالوا إنا نصارى أخذنا ميثاقهم فنسوا ...,wmn Al*yn qAlwA <nA nSArY >x*nA myvAqhm fnswA ...
3,إلى يوم القيامة,5,64,وقالت اليهود يد الله مغلولة غلت أيديهم ولعنوا ...,wqAlt Alyhwd yd Allh mglwlp glt >ydyhm wlEnwA ...
4,إلى يوم القيامة,6,12,قل لمن ما في السماوات والأرض قل لله كتب على نف...,ql lmn mA fy AlsmAwAt wAl>rD ql llh ktb ElY nf...
...,...,...,...,...,...
981,وما كان أكثرهم,26,121,إن في ذلك لآية وما كان أكثرهم مؤمنين,<n fy *lk l|yp wmA kAn >kvrhm m&mnyn
982,وما كان أكثرهم,26,139,فكذبوه فأهلكناهم إن في ذلك لآية وما كان أكثرهم...,fk*bwh f>hlknAhm <n fy *lk l|yp wmA kAn >kvrhm...
983,وما كان أكثرهم,26,158,فأخذهم العذاب إن في ذلك لآية وما كان أكثرهم مؤ...,f>x*hm AlE*Ab <n fy *lk l|yp wmA kAn >kvrhm m&...
984,وما كان أكثرهم,26,174,إن في ذلك لآية وما كان أكثرهم مؤمنين,<n fy *lk l|yp wmA kAn >kvrhm m&mnyn
985,وما كان أكثرهم,26,190,إن في ذلك لآية وما كان أكثرهم مؤمنين,<n fy *lk l|yp wmA kAn >kvrhm m&mnyn

In [84]:
# Three Gram
threegram_loc_list = []
for i in range(len(df_sent_threegram_result)):
    num_1 = df_sent_threegram_result.loc[i,"num_1"]
    num_2 = df_sent_threegram_result.loc[i,"num_2"]
    sent = df_sent_threegram_result.loc[i,"arabic_sent_tanzil_clean"]
    ngram = df_sent_threegram_result.loc[i,"threegram"]
    sent_token = word_tokenize(sent)
    ngram_token = word_tokenize(ngram)    
    for j in range(len(ngram_token)):        
        for k in range(len(sent_token)):
            if ngram_token[j] == sent_token[k]:
                try:
                    if ngram_token[j+1] == sent_token[k+1]:
                        if ngram_token[j+2] == sent_token[k+2]:
                            num_3 = k+1
                            threegram_loc_list.append((num_1,num_2,num_3,ngram_token[j],sent))
                            threegram_loc_list.append((num_1,num_2,num_3+1,ngram_token[j+1],sent))
                            threegram_loc_list.append((num_1,num_2,num_3+2,ngram_token[j+2],sent))
                except:
                    pass
                
df_threegram_loc = pd.DataFrame(threegram_loc_list)
df_threegram_loc.rename(columns={0:"num_1",1:"num_2",2:"num_3",3:"arabic_word_tanzil_clean",4:"arabic_sent_tanzil_clean"},inplace=True)
df_threegram_loc["100_200_threegram"] = 3
df_threegram_loc

,num_1,num_2,num_3,arabic_word_tanzil_clean,arabic_sent_tanzil_clean,100_200_threegram
0,3,55,20,إلى,إذ قال الله يا عيسى إني متوفيك ورافعك إلي ومطه...,3
1,3,55,21,يوم,إذ قال الله يا عيسى إني متوفيك ورافعك إلي ومطه...,3
2,3,55,22,القيامة,إذ قال الله يا عيسى إني متوفيك ورافعك إلي ومطه...,3
3,4,87,7,إلى,الله لا إله إلا هو ليجمعنكم إلى يوم القيامة لا...,3
4,4,87,8,يوم,الله لا إله إلا هو ليجمعنكم إلى يوم القيامة لا...,3
...,...,...,...,...,...,...
2962,26,174,6,كان,إن في ذلك لآية وما كان أكثرهم مؤمنين,3
2963,26,174,7,أكثرهم,إن في ذلك لآية وما كان أكثرهم مؤمنين,3
2964,26,190,5,وما,إن في ذلك لآية وما كان أكثرهم مؤمنين,3
2965,26,190,6,كان,إن في ذلك لآية وما كان أكثرهم مؤمنين,3
2966,26,190,7,أكثرهم,إن في ذلك لآية وما كان أكثرهم مؤمنين,3

In [85]:
#df_threegram_loc.to_excel("Arabic_100_200_Threegram_Loc_With_Sent.xlsx",index=False)

#### Merge Word NGram Root Flags

In [124]:
df_first_word = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/7-Deployment/Arabic_Buckwalter_Word_Root_First_100_200_Word_Juz_Name_Page.xlsx")
df_first_word = df_first_word.iloc[:,[0,1,2,3,4,5,6,8,9,17,18,19,20]]
df_first_word

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,root,root_arabic,index,first_100_word,100_200_word,first_200_word
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,smw,سمو,0,1,0,1
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,Alh,اله,1,1,0,1
2,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,rHm,رحم,2,1,0,1
3,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,rHm,رحم,3,1,0,1
4,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,Hmd,حمد,4,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
78244,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,Sdr,صدر,78244,0,0,0
78245,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,nws,نوس,78245,1,0,1
78246,114,6,1,من,mn,مِنَ,mina,NaN,NaN,78246,1,0,1
78247,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,jnn,جنن,78247,0,1,1
78248,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,nws,نوس,78248,0,0,0

In [96]:
df_first_100_twogram = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/7-Deployment/Arabic_First_100_Twogram_Loc_With_Sent.xlsx")
df_first_100_twogram = df_first_100_twogram.iloc[:,[0,1,2,5]]
df_first_100_twogram

       num_1  num_2  num_3  first_100_twogram
0          2     20     20                  2
1          2     20     21                  2
2          2     26      1                  2
3          2     26      2                  2
4          2     67      5                  2
...      ...    ...    ...                ...
11033     56     61      8                  2
11034     61      2      7                  2
11035     61      2      8                  2
11036     61      3      7                  2
11037     61      3      8                  2

[11038 rows x 4 columns]

In [100]:
df_merge_word_ngrams = pd.merge(df_first_word,df_first_100_twogram, how="left", on=["num_1","num_2","num_3"])
df_merge_word_ngrams.drop_duplicates(inplace=True)
df_merge_word_ngrams.iloc[:,-1].fillna(0, inplace=True)
df_merge_word_ngrams

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,root,root_arabic,index,first_100_word,100_200_word,first_200_word,first_100_twogram
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,smw,سمو,0,1,0,1,2.0
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,Alh,اله,1,1,0,1,2.0
3,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,rHm,رحم,2,1,0,1,2.0
5,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,rHm,رحم,3,1,0,1,2.0
6,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,Hmd,حمد,4,0,0,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79824,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,Sdr,صدر,78244,0,0,0,0.0
79825,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,nws,نوس,78245,1,0,1,0.0
79826,114,6,1,من,mn,مِنَ,mina,NaN,NaN,78246,1,0,1,0.0
79827,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,jnn,جنن,78247,0,1,1,0.0
79828,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,nws,نوس,78248,0,0,0,0.0

In [101]:
df_100_200_twogram = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/7-Deployment/Arabic_100_200_Twogram_Loc_With_Sent.xlsx")
df_100_200_twogram = df_100_200_twogram.iloc[:,[0,1,2,5]]
df_100_200_twogram

      num_1  num_2  num_3  100_200_twogram
0         2    255     17                2
1         2    255     18                2
2         2    284      5                2
3         2    284      6                2
4         3     29     15                2
...     ...    ...    ...              ...
4543     51     30      6                2
4544     52     28      6                2
4545     52     28      7                2
4546     85     13      1                2
4547     85     13      2                2

[4548 rows x 4 columns]

In [102]:
df_merge_word_ngrams2 = pd.merge(df_merge_word_ngrams,df_100_200_twogram, how="left", on=["num_1","num_2","num_3"])
df_merge_word_ngrams2.drop_duplicates(inplace=True)
df_merge_word_ngrams2.iloc[:,-1].fillna(0, inplace=True)
df_merge_word_ngrams2

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,root,root_arabic,index,first_100_word,100_200_word,first_200_word,first_100_twogram,100_200_twogram
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,smw,سمو,0,1,0,1,2.0,0.0
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,Alh,اله,1,1,0,1,2.0,0.0
2,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,rHm,رحم,2,1,0,1,2.0,0.0
3,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,rHm,رحم,3,1,0,1,2.0,0.0
4,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,Hmd,حمد,4,0,0,0,0.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78433,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,Sdr,صدر,78244,0,0,0,0.0,0.0
78434,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,nws,نوس,78245,1,0,1,0.0,0.0
78435,114,6,1,من,mn,مِنَ,mina,NaN,NaN,78246,1,0,1,0.0,0.0
78436,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,jnn,جنن,78247,0,1,1,0.0,0.0
78437,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,nws,نوس,78248,0,0,0,0.0,0.0

In [103]:
df_first_200_twogram = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/7-Deployment/Arabic_First_200_Twogram_Loc_With_Sent.xlsx")
df_first_200_twogram = df_first_200_twogram.iloc[:,[0,1,2,5]]
df_first_200_twogram

       num_1  num_2  num_3  first_200_twogram
0          2     20     20                  2
1          2     20     21                  2
2          2     26      1                  2
3          2     26      2                  2
4          2     67      5                  2
...      ...    ...    ...                ...
15581     51     30      6                  2
15582     52     28      6                  2
15583     52     28      7                  2
15584     85     13      1                  2
15585     85     13      2                  2

[15586 rows x 4 columns]

In [104]:
df_merge_word_ngrams3 = pd.merge(df_merge_word_ngrams2,df_first_200_twogram, how="left", on=["num_1","num_2","num_3"])
df_merge_word_ngrams3.drop_duplicates(inplace=True)
df_merge_word_ngrams3.iloc[:,-1].fillna(0, inplace=True)
df_merge_word_ngrams3

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,root,root_arabic,index,first_100_word,100_200_word,first_200_word,first_100_twogram,100_200_twogram,first_200_twogram
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,smw,سمو,0,1,0,1,2.0,0.0,2.0
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,Alh,اله,1,1,0,1,2.0,0.0,2.0
3,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,rHm,رحم,2,1,0,1,2.0,0.0,2.0
5,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,rHm,رحم,3,1,0,1,2.0,0.0,2.0
6,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,Hmd,حمد,4,0,0,0,0.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80805,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,Sdr,صدر,78244,0,0,0,0.0,0.0,0.0
80806,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,nws,نوس,78245,1,0,1,0.0,0.0,0.0
80807,114,6,1,من,mn,مِنَ,mina,NaN,NaN,78246,1,0,1,0.0,0.0,0.0
80808,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,jnn,جنن,78247,0,1,1,0.0,0.0,0.0
80809,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,nws,نوس,78248,0,0,0,0.0,0.0,0.0

In [105]:
df_first_100_threegram = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/7-Deployment/Arabic_First_100_Threegram_Loc_With_Sent.xlsx")
df_first_100_threegram = df_first_100_threegram.iloc[:,[0,1,2,5]]
df_first_100_threegram

      num_1  num_2  num_3  first_100_threegram
0         1      1      1                    3
1         1      1      2                    3
2         1      1      3                    3
3         2      1      1                    3
4         2      1      2                    3
...     ...    ...    ...                  ...
7225     58     14      3                    3
7226     58     14      4                    3
7227     59     11      2                    3
7228     59     11      3                    3
7229     59     11      4                    3

[7230 rows x 4 columns]

In [106]:
df_merge_word_ngrams4 = pd.merge(df_merge_word_ngrams3,df_first_100_threegram, how="left", on=["num_1","num_2","num_3"])
df_merge_word_ngrams4.drop_duplicates(inplace=True)
df_merge_word_ngrams4.iloc[:,-1].fillna(0, inplace=True)
df_merge_word_ngrams4

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,root,root_arabic,index,first_100_word,100_200_word,first_200_word,first_100_twogram,100_200_twogram,first_200_twogram,first_100_threegram
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,smw,سمو,0,1,0,1,2.0,0.0,2.0,3.0
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,Alh,اله,1,1,0,1,2.0,0.0,2.0,3.0
3,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,rHm,رحم,2,1,0,1,2.0,0.0,2.0,3.0
5,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,rHm,رحم,3,1,0,1,2.0,0.0,2.0,3.0
6,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,Hmd,حمد,4,0,0,0,0.0,2.0,2.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
79862,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,Sdr,صدر,78244,0,0,0,0.0,0.0,0.0,0.0
79863,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,nws,نوس,78245,1,0,1,0.0,0.0,0.0,0.0
79864,114,6,1,من,mn,مِنَ,mina,NaN,NaN,78246,1,0,1,0.0,0.0,0.0,0.0
79865,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,jnn,جنن,78247,0,1,1,0.0,0.0,0.0,0.0
79866,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,nws,نوس,78248,0,0,0,0.0,0.0,0.0,0.0

In [107]:
df_100_200_threegram = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/7-Deployment/Arabic_100_200_Threegram_Loc_With_Sent.xlsx")
df_100_200_threegram = df_100_200_threegram.iloc[:,[0,1,2,5]]
df_100_200_threegram

      num_1  num_2  num_3  100_200_threegram
0         3     55     20                  3
1         3     55     21                  3
2         3     55     22                  3
3         4     87      7                  3
4         4     87      8                  3
...     ...    ...    ...                ...
2962     26    174      6                  3
2963     26    174      7                  3
2964     26    190      5                  3
2965     26    190      6                  3
2966     26    190      7                  3

[2967 rows x 4 columns]

In [108]:
df_merge_word_ngrams5 = pd.merge(df_merge_word_ngrams4,df_100_200_threegram, how="left", on=["num_1","num_2","num_3"])
df_merge_word_ngrams5.drop_duplicates(inplace=True)
df_merge_word_ngrams5.iloc[:,-1].fillna(0, inplace=True)
df_merge_word_ngrams5

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,root,root_arabic,index,first_100_word,100_200_word,first_200_word,first_100_twogram,100_200_twogram,first_200_twogram,first_100_threegram,100_200_threegram
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,smw,سمو,0,1,0,1,2.0,0.0,2.0,3.0,0.0
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,Alh,اله,1,1,0,1,2.0,0.0,2.0,3.0,0.0
2,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,rHm,رحم,2,1,0,1,2.0,0.0,2.0,3.0,0.0
3,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,rHm,رحم,3,1,0,1,2.0,0.0,2.0,3.0,0.0
4,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,Hmd,حمد,4,0,0,0,0.0,2.0,2.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78578,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,Sdr,صدر,78244,0,0,0,0.0,0.0,0.0,0.0,0.0
78579,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,nws,نوس,78245,1,0,1,0.0,0.0,0.0,0.0,0.0
78580,114,6,1,من,mn,مِنَ,mina,NaN,NaN,78246,1,0,1,0.0,0.0,0.0,0.0,0.0
78581,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,jnn,جنن,78247,0,1,1,0.0,0.0,0.0,0.0,0.0
78582,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,nws,نوس,78248,0,0,0,0.0,0.0,0.0,0.0,0.0

In [109]:
df_first_200_threegram = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/7-Deployment/Arabic_First_200_Threegram_Loc_With_Sent.xlsx")
df_first_200_threegram = df_first_200_threegram.iloc[:,[0,1,2,5]]
df_first_200_threegram

       num_1  num_2  num_3  first_200_threegram
0          1      1      1                    3
1          1      1      2                    3
2          1      1      3                    3
3          2      1      1                    3
4          2      1      2                    3
...      ...    ...    ...                  ...
10192     26    174      6                    3
10193     26    174      7                    3
10194     26    190      5                    3
10195     26    190      6                    3
10196     26    190      7                    3

[10197 rows x 4 columns]

In [110]:
df_merge_word_ngrams6 = pd.merge(df_merge_word_ngrams5,df_first_200_threegram, how="left", on=["num_1","num_2","num_3"])
df_merge_word_ngrams6.drop_duplicates(inplace=True)
df_merge_word_ngrams6.iloc[:,-1].fillna(0, inplace=True)
df_merge_word_ngrams6

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,root,root_arabic,index,first_100_word,100_200_word,first_200_word,first_100_twogram,100_200_twogram,first_200_twogram,first_100_threegram,100_200_threegram,first_200_threegram
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,smw,سمو,0,1,0,1,2.0,0.0,2.0,3.0,0.0,3.0
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,Alh,اله,1,1,0,1,2.0,0.0,2.0,3.0,0.0,3.0
3,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,rHm,رحم,2,1,0,1,2.0,0.0,2.0,3.0,0.0,3.0
5,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,rHm,رحم,3,1,0,1,2.0,0.0,2.0,3.0,0.0,3.0
6,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,Hmd,حمد,4,0,0,0,0.0,2.0,2.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80858,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,Sdr,صدر,78244,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
80859,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,nws,نوس,78245,1,0,1,0.0,0.0,0.0,0.0,0.0,0.0
80860,114,6,1,من,mn,مِنَ,mina,NaN,NaN,78246,1,0,1,0.0,0.0,0.0,0.0,0.0,0.0
80861,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,jnn,جنن,78247,0,1,1,0.0,0.0,0.0,0.0,0.0,0.0
80862,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,nws,نوس,78248,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [117]:
df_root = df_merge_word_ngrams6[~df_merge_word_ngrams6.root.isna()]
df_root

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,root,root_arabic,index,first_100_word,100_200_word,first_200_word,first_100_twogram,100_200_twogram,first_200_twogram,first_100_threegram,100_200_threegram,first_200_threegram
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,smw,سمو,0,1,0,1,2.0,0.0,2.0,3.0,0.0,3.0
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,Alh,اله,1,1,0,1,2.0,0.0,2.0,3.0,0.0,3.0
3,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,rHm,رحم,2,1,0,1,2.0,0.0,2.0,3.0,0.0,3.0
5,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,rHm,رحم,3,1,0,1,2.0,0.0,2.0,3.0,0.0,3.0
6,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,Hmd,حمد,4,0,0,0,0.0,2.0,2.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
80856,114,5,2,يوسوس,ywsws,يُوَسْوِسُ,yuwasowisu,wsws,وسوس,78242,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
80858,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,Sdr,صدر,78244,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0
80859,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,nws,نوس,78245,1,0,1,0.0,0.0,0.0,0.0,0.0,0.0
80861,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,jnn,جنن,78247,0,1,1,0.0,0.0,0.0,0.0,0.0,0.0
80862,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,nws,نوس,78248,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0

In [118]:
df_root["root_flag"] = 4

<ipython-input-118-c489985d2787>:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_root["root_flag"] = 4

In [120]:
df_root = df_root.iloc[:,[0,1,2,-1]]
df_root

       num_1  num_2  num_3  root_flag
0          1      1      1          4
1          1      1      2          4
3          1      1      3          4
5          1      1      4          4
6          1      2      1          4
...      ...    ...    ...        ...
80856    114      5      2          4
80858    114      5      4          4
80859    114      5      5          4
80861    114      6      2          4
80862    114      6      3          4

[49968 rows x 4 columns]

In [121]:
df_merge_word_ngrams_root_all = pd.merge(df_merge_word_ngrams6,df_root, how="left", on=["num_1","num_2","num_3"])
df_merge_word_ngrams_root_all.drop_duplicates(inplace=True)
df_merge_word_ngrams_root_all.iloc[:,-1].fillna(0, inplace=True)
df_merge_word_ngrams_root_all

,num_1,num_2,num_3,arabic_word_tanzil_clean,buckwalter_word_tanzil_clean,arabic_word_tanzil_plain,buckwalter_word_tanzil_plain,root,root_arabic,index,first_100_word,100_200_word,first_200_word,first_100_twogram,100_200_twogram,first_200_twogram,first_100_threegram,100_200_threegram,first_200_threegram,root_flag
0,1,1,1,بسم,bsm,بِسْمِ,bisomi,smw,سمو,0,1,0,1,2.0,0.0,2.0,3.0,0.0,3.0,4.0
1,1,1,2,الله,Allh,اللَّهِ,All~ahi,Alh,اله,1,1,0,1,2.0,0.0,2.0,3.0,0.0,3.0,4.0
2,1,1,3,الرحمن,AlrHmn,الرَّحْمَٰنِ,Alr~aHoma`ni,rHm,رحم,2,1,0,1,2.0,0.0,2.0,3.0,0.0,3.0,4.0
3,1,1,4,الرحيم,AlrHym,الرَّحِيمِ,Alr~aHiymi,rHm,رحم,3,1,0,1,2.0,0.0,2.0,3.0,0.0,3.0,4.0
4,1,2,1,الحمد,AlHmd,الْحَمْدُ,AloHamodu,Hmd,حمد,4,0,0,0,0.0,2.0,2.0,0.0,0.0,0.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78246,114,5,4,صدور,Sdwr,صُدُورِ,Suduwri,Sdr,صدر,78244,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,4.0
78247,114,5,5,الناس,AlnAs,النَّاسِ,Aln~aAsi,nws,نوس,78245,1,0,1,0.0,0.0,0.0,0.0,0.0,0.0,4.0
78248,114,6,1,من,mn,مِنَ,mina,NaN,NaN,78246,1,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
78249,114,6,2,الجنة,Aljnp,الْجِنَّةِ,Alojin~api,jnn,جنن,78247,0,1,1,0.0,0.0,0.0,0.0,0.0,0.0,4.0
78250,114,6,3,والناس,wAlnAs,وَالنَّاسِ,waAln~aAsi,nws,نوس,78248,0,0,0,0.0,0.0,0.0,0.0,0.0,0.0,4.0

In [122]:
#df_merge_word_ngrams_root_all.to_excel("Arabic_Buckwalter_Word_Root_First_100_200_Word_NGram_Root_Color_Flag.xlsx",index=False)