### Web Scrapping Data Combinate To Master

In [1]:
import pandas as pd
import numpy as np
import re
import glob

In [2]:
df_master_all = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/8-Compare Color Flags/Arabic_Buckwalter_All_Relocation_Edit_Counts_Audio_Time_Root_Master.xlsx")
df_master_all

,surah,ayah,word rank,juz,page,surah arabic,surah latin,word count ayah,letter count ayah,tanzil_clean,...,level 1,level 2,level 3,level 4,2gram,3gram,start_time,end_time,repeat flag,index
0,1,1,1,1,1,الفاتحة,Al-Fatiha,4,19,بسم,...,1,2,3,4,2,3,50.0,510.0,NaN,0
1,1,1,2,1,1,الفاتحة,Al-Fatiha,4,19,الله,...,1,2,3,4,2,3,520.0,1180.0,NaN,1
2,1,1,3,1,1,الفاتحة,Al-Fatiha,4,19,الرحمن,...,1,2,3,4,2,3,1190.0,2340.0,NaN,2
3,1,1,4,1,1,الفاتحة,Al-Fatiha,4,19,الرحيم,...,1,2,3,4,2,3,2350.0,4480.0,NaN,3
4,1,2,1,1,1,الفاتحة,Al-Fatiha,4,18,الحمد,...,0,0,2,4,2,0,700.0,1410.0,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78244,114,5,4,30,604,الناس,An-Nas,5,20,صدور,...,0,0,0,0,0,0,5080.0,6760.0,NaN,78244
78245,114,5,5,30,604,الناس,An-Nas,5,20,الناس,...,1,1,1,4,0,0,6770.0,10010.0,NaN,78245
78246,114,6,1,30,604,الناس,An-Nas,3,13,من,...,1,1,1,0,0,0,650.0,1160.0,NaN,78246
78247,114,6,2,30,604,الناس,An-Nas,3,13,الجنة,...,0,1,1,4,0,0,1170.0,3740.0,NaN,78247
78248,114,6,3,30,604,الناس,An-Nas,3,13,والناس,...,0,0,0,4,0,0,3750.0,7530.0,NaN,78248

In [3]:
df_info = pd.DataFrame(df_master_all.groupby(["surah","surah latin"])["index"].min())
df_info.reset_index(inplace=True)
df_info

     surah surah latin  index
0        1   Al-Fatiha      0
1        2   Al-Baqara     29
2        3    Al Imran   6174
3        4    An-Nisa'   9679
4        5   Al-Ma'ida  13446
..     ...         ...    ...
109    110     An-Nasr  78129
110    111    Al-Masad  78152
111    112   Al-Ikhlas  78179
112    113    Al-Falaq  78198
113    114      An-Nas  78225

[114 rows x 3 columns]

In [4]:
df_info["index"] = df_info["index"].apply(lambda x: x+4)
df_info

     surah surah latin  index
0        1   Al-Fatiha      4
1        2   Al-Baqara     33
2        3    Al Imran   6178
3        4    An-Nisa'   9683
4        5   Al-Ma'ida  13450
..     ...         ...    ...
109    110     An-Nasr  78133
110    111    Al-Masad  78156
111    112   Al-Ikhlas  78183
112    113    Al-Falaq  78202
113    114      An-Nas  78229

[114 rows x 3 columns]

In [5]:
#df_info.to_excel("Adding_Info_File.xlsx", index=False)

#### Read Adding Info File

In [2]:
df_info_file = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/10-Web Scrapping Data To Master/Adding_Info_File.xlsx") # Added scrapping name to previous file manually 
df_info_file

     surah surah latin  index    scrap_name
0        1   Al-Fatiha      0    Al Faatiha
1        2   Al-Baqara     33     Al Baqara
2        3    Al Imran   6178  AAl I Imraan
3        4    An-Nisa'   9683      An Nisaa
4        5   Al-Ma'ida  13450     Al Maaida
..     ...         ...    ...           ...
109    110     An-Nasr  78133       An Nasr
110    111    Al-Masad  78156      Al Masad
111    112   Al-Ikhlas  78183    Al Ikhlaas
112    113    Al-Falaq  78202      Al Falaq
113    114      An-Nas  78229       An Naas

[114 rows x 4 columns]

In [58]:
#df_info_file = df_info_file.head(5)

In [3]:
def add_info(df,surah_name, surah_num, index):
    for i in range(len(df)):
        df["surah latin"] = surah_name
        df["surah"] = surah_num
        df.loc[i,"index"] = i+index
    return df

In [4]:
df_list = []
for i in range(len(df_info_file)):
    surah_num = df_info_file.loc[i,"surah"]
    surah_name = df_info_file.loc[i,"surah latin"]
    index = df_info_file.loc[i,"index"]
    surah = df_info_file.loc[i,"scrap_name"]
    file = glob.glob(f"/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Web Scrapping/Result/*/{surah.lower().capitalize()}_Arabic_Transliterate_Translate_Words_Languages_Concat.xlsx")
    df = pd.read_excel(file[0])
    df_added_info = add_info(df,surah_name, surah_num, index)
    df_added_info = df_added_info.iloc[:,[10,9,0,1,2,3,4,5,6,7,8,11]]
    df_list.append(df_added_info)

In [5]:
df_translate_merge_all = pd.DataFrame()
for i in df_list:
    df_translate_merge_all = pd.concat([df_translate_merge_all,i], axis=0)
df_translate_merge_all.reset_index(drop=True, inplace=True)
df_translate_merge_all

,surah,surah latin,arabic,transliterate,translate_english,translate_urdu,translate_hindi,translate_indonesian,translate_bangla,translate_turkish,translate_russian,index
0,1,Al-Fatiha,بِسۡمِ,bis'mi,In (the) name,ساتھ نام,साथ नाम,dengan nama,নামে,adıyla,С именем,0.0
1,1,Al-Fatiha,ٱللَّهِ,al-lahi,(of) Allah,اللہ کے,अल्लाह के,Allah,আল্লাহ (র),Allah'ın,"Аллаха,",1.0
2,1,Al-Fatiha,ٱلرَّحۡمَٰنِ,al-rahmani,the Most Gracious,جو بے حد مہربان ہے,जो बहुत मेहरबान,Maha Pengasih,পরম করুণাময়,Rahman,"Милостивого,",2.0
3,1,Al-Fatiha,ٱلرَّحِيمِ,al-rahimi,the Most Merciful,بار بار رحم فرمانے والا ہے,निहायत रहम करने वाला है,Maha Penyayang,অসীম দয়ালু,Rahim,Милосердного!,3.0
4,1,Al-Fatiha,ٱلۡحَمۡدُ,al-hamdu,All praises and thanks,سب تعریف,सब तारीफ़,pujian,সকল প্রশংসা,hamdolsun,Хвала,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...
77424,114,An-Nas,صُدُورِ,suduri,(the) breasts,سینوں,सीनों में,dada,অন্তরসমূহের,*,грудях,78244.0
77425,114,An-Nas,ٱلنَّاسِ,al-nasi,(of) mankind,انسانوں کے,लोगों के,manusia,মানুষের,insanların,"людей,",78245.0
77426,114,An-Nas,مِنَ,mina,From,سے,*,dari,মধ্য হতে,cinlerden,(будучи) из (числа),78246.0
77427,114,An-Nas,ٱلۡجِنَّةِ,al-jinati,the jinn,جنوں میں,जिन्नों में से,jin,জিনের,*,джиннов,78247.0
77428,114,An-Nas,وَٱلنَّاسِ,wal-nasi,and men,اور انسانوں میں,और इन्सानों में से,dan manusia,ও মানুষের,ve insanlar(dan);,и людей».,78248.0

In [6]:
#df_translate_merge_all.to_excel("All_Surah_Translate_File_Concat.xlsx", index=False)

#### Translate And Master Merge

In [2]:
df_master_all = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/8-Compare Color Flags/Arabic_Buckwalter_All_Relocation_Edit_Counts_Audio_Time_Root_Master.xlsx")
df_master_all

,surah,ayah,word rank,juz,page,surah arabic,surah latin,word count ayah,letter count ayah,tanzil_clean,...,level 1,level 2,level 3,level 4,2gram,3gram,start_time,end_time,repeat flag,index
0,1,1,1,1,1,الفاتحة,Al-Fatiha,4,19,بسم,...,1,2,3,4,2,3,50.0,510.0,NaN,0
1,1,1,2,1,1,الفاتحة,Al-Fatiha,4,19,الله,...,1,2,3,4,2,3,520.0,1180.0,NaN,1
2,1,1,3,1,1,الفاتحة,Al-Fatiha,4,19,الرحمن,...,1,2,3,4,2,3,1190.0,2340.0,NaN,2
3,1,1,4,1,1,الفاتحة,Al-Fatiha,4,19,الرحيم,...,1,2,3,4,2,3,2350.0,4480.0,NaN,3
4,1,2,1,1,1,الفاتحة,Al-Fatiha,4,18,الحمد,...,0,0,2,4,2,0,700.0,1410.0,NaN,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78244,114,5,4,30,604,الناس,An-Nas,5,20,صدور,...,0,0,0,0,0,0,5080.0,6760.0,NaN,78244
78245,114,5,5,30,604,الناس,An-Nas,5,20,الناس,...,1,1,1,4,0,0,6770.0,10010.0,NaN,78245
78246,114,6,1,30,604,الناس,An-Nas,3,13,من,...,1,1,1,0,0,0,650.0,1160.0,NaN,78246
78247,114,6,2,30,604,الناس,An-Nas,3,13,الجنة,...,0,1,1,4,0,0,1170.0,3740.0,NaN,78247
78248,114,6,3,30,604,الناس,An-Nas,3,13,والناس,...,0,0,0,4,0,0,3750.0,7530.0,NaN,78248

In [3]:
df_translate_merge_all = pd.read_excel("/media/kurubal/SSD/Data Scientist/Work/Modern Ways/Project/Arabic/Quaran/Text/Result/10-Web Scrapping Data To Master/All_Surah_Translate_File_Concat.xlsx")
df_translate_merge_all

,surah,surah latin,arabic,transliterate,translate_english,translate_urdu,translate_hindi,translate_indonesian,translate_bangla,translate_turkish,translate_russian,index
0,1,Al-Fatiha,بِسۡمِ,bis'mi,In (the) name,ساتھ نام,साथ नाम,dengan nama,নামে,adıyla,С именем,0
1,1,Al-Fatiha,ٱللَّهِ,al-lahi,(of) Allah,اللہ کے,अल्लाह के,Allah,আল্লাহ (র),Allah'ın,"Аллаха,",1
2,1,Al-Fatiha,ٱلرَّحۡمَٰنِ,al-rahmani,the Most Gracious,جو بے حد مہربان ہے,जो बहुत मेहरबान,Maha Pengasih,পরম করুণাময়,Rahman,"Милостивого,",2
3,1,Al-Fatiha,ٱلرَّحِيمِ,al-rahimi,the Most Merciful,بار بار رحم فرمانے والا ہے,निहायत रहम करने वाला है,Maha Penyayang,অসীম দয়ালু,Rahim,Милосердного!,3
4,1,Al-Fatiha,ٱلۡحَمۡدُ,al-hamdu,All praises and thanks,سب تعریف,सब तारीफ़,pujian,সকল প্রশংসা,hamdolsun,Хвала,4
...,...,...,...,...,...,...,...,...,...,...,...,...
77424,114,An-Nas,صُدُورِ,suduri,(the) breasts,سینوں,सीनों में,dada,অন্তরসমূহের,*,грудях,78244
77425,114,An-Nas,ٱلنَّاسِ,al-nasi,(of) mankind,انسانوں کے,लोगों के,manusia,মানুষের,insanların,"людей,",78245
77426,114,An-Nas,مِنَ,mina,From,سے,*,dari,মধ্য হতে,cinlerden,(будучи) из (числа),78246
77427,114,An-Nas,ٱلۡجِنَّةِ,al-jinati,the jinn,جنوں میں,जिन्नों में से,jin,জিনের,*,джиннов,78247
77428,114,An-Nas,وَٱلنَّاسِ,wal-nasi,and men,اور انسانوں میں,और इन्सानों में से,dan manusia,ও মানুষের,ve insanlar(dan);,и людей».,78248

In [4]:
df_translate_merge_select = df_translate_merge_all.iloc[:,[0,1,2,4,5,6,7,8,9,10,11]]
df_translate_merge_select

,surah,surah latin,arabic,translate_english,translate_urdu,translate_hindi,translate_indonesian,translate_bangla,translate_turkish,translate_russian,index
0,1,Al-Fatiha,بِسۡمِ,In (the) name,ساتھ نام,साथ नाम,dengan nama,নামে,adıyla,С именем,0
1,1,Al-Fatiha,ٱللَّهِ,(of) Allah,اللہ کے,अल्लाह के,Allah,আল্লাহ (র),Allah'ın,"Аллаха,",1
2,1,Al-Fatiha,ٱلرَّحۡمَٰنِ,the Most Gracious,جو بے حد مہربان ہے,जो बहुत मेहरबान,Maha Pengasih,পরম করুণাময়,Rahman,"Милостивого,",2
3,1,Al-Fatiha,ٱلرَّحِيمِ,the Most Merciful,بار بار رحم فرمانے والا ہے,निहायत रहम करने वाला है,Maha Penyayang,অসীম দয়ালু,Rahim,Милосердного!,3
4,1,Al-Fatiha,ٱلۡحَمۡدُ,All praises and thanks,سب تعریف,सब तारीफ़,pujian,সকল প্রশংসা,hamdolsun,Хвала,4
...,...,...,...,...,...,...,...,...,...,...,...
77424,114,An-Nas,صُدُورِ,(the) breasts,سینوں,सीनों में,dada,অন্তরসমূহের,*,грудях,78244
77425,114,An-Nas,ٱلنَّاسِ,(of) mankind,انسانوں کے,लोगों के,manusia,মানুষের,insanların,"людей,",78245
77426,114,An-Nas,مِنَ,From,سے,*,dari,মধ্য হতে,cinlerden,(будучи) из (числа),78246
77427,114,An-Nas,ٱلۡجِنَّةِ,the jinn,جنوں میں,जिन्नों में से,jin,জিনের,*,джиннов,78247
77428,114,An-Nas,وَٱلنَّاسِ,and men,اور انسانوں میں,और इन्सानों में से,dan manusia,ও মানুষের,ve insanlar(dan);,и людей».,78248

In [6]:
df_master_translate_merge = pd.merge(df_master_all,df_translate_merge_select, how="left", on=["surah","surah latin","index"])
df_master_translate_merge

,surah,ayah,word rank,juz,page,surah arabic,surah latin,word count ayah,letter count ayah,tanzil_clean,...,repeat flag,index,arabic,translate_english,translate_urdu,translate_hindi,translate_indonesian,translate_bangla,translate_turkish,translate_russian
0,1,1,1,1,1,الفاتحة,Al-Fatiha,4,19,بسم,...,NaN,0,بِسۡمِ,In (the) name,ساتھ نام,साथ नाम,dengan nama,নামে,adıyla,С именем
1,1,1,2,1,1,الفاتحة,Al-Fatiha,4,19,الله,...,NaN,1,ٱللَّهِ,(of) Allah,اللہ کے,अल्लाह के,Allah,আল্লাহ (র),Allah'ın,"Аллаха,"
2,1,1,3,1,1,الفاتحة,Al-Fatiha,4,19,الرحمن,...,NaN,2,ٱلرَّحۡمَٰنِ,the Most Gracious,جو بے حد مہربان ہے,जो बहुत मेहरबान,Maha Pengasih,পরম করুণাময়,Rahman,"Милостивого,"
3,1,1,4,1,1,الفاتحة,Al-Fatiha,4,19,الرحيم,...,NaN,3,ٱلرَّحِيمِ,the Most Merciful,بار بار رحم فرمانے والا ہے,निहायत रहम करने वाला है,Maha Penyayang,অসীম দয়ালু,Rahim,Милосердного!
4,1,2,1,1,1,الفاتحة,Al-Fatiha,4,18,الحمد,...,NaN,4,ٱلۡحَمۡدُ,All praises and thanks,سب تعریف,सब तारीफ़,pujian,সকল প্রশংসা,hamdolsun,Хвала
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
78244,114,5,4,30,604,الناس,An-Nas,5,20,صدور,...,NaN,78244,صُدُورِ,(the) breasts,سینوں,सीनों में,dada,অন্তরসমূহের,*,грудях
78245,114,5,5,30,604,الناس,An-Nas,5,20,الناس,...,NaN,78245,ٱلنَّاسِ,(of) mankind,انسانوں کے,लोगों के,manusia,মানুষের,insanların,"людей,"
78246,114,6,1,30,604,الناس,An-Nas,3,13,من,...,NaN,78246,مِنَ,From,سے,*,dari,মধ্য হতে,cinlerden,(будучи) из (числа)
78247,114,6,2,30,604,الناس,An-Nas,3,13,الجنة,...,NaN,78247,ٱلۡجِنَّةِ,the jinn,جنوں میں,जिन्नों में से,jin,জিনের,*,джиннов
78248,114,6,3,30,604,الناس,An-Nas,3,13,والناس,...,NaN,78248,وَٱلنَّاسِ,and men,اور انسانوں میں,और इन्सानों में से,dan manusia,ও মানুষের,ve insanlar(dan);,и людей».

In [7]:
df_master_translate_merge.to_excel("Quran_Master_And_Translate_Merge.xlsx", index=False)

#### Filling Asterisk Value

In [ ]:
def asterisk_find_fill(df_master, column_name, fill_loc_num=0):  # fill_loc_num is an intergers as 0,1,-1 . 0 is same value, 1 is next value, -1 is previous value
    prev_same_next_list = []
    for i in range(len(df_master)): 
        if df_master.loc[i,f"{column_name}"] == "*":
            df_master.loc[i,f"{column_name}"] == df_master.loc[i+(fill_loc_num),f"{column_name}"]
        else:
            pass

    return df_master